= SN Stack overview

The SN Stack is an umbrella term for the technological stack required to run a Starknet instance. At its core, this stack includes four layers:

* Sequencing: Producing blocks of transactions
* Proving: Generating STARK proofs of blocks validity
* Verifying: Verifying STARK proofs onchain
* Settling: Storing and managing state onchain

StarkWare's implementation of the SN stack, which has been used by StarkWare to successfully power Starknet for over 4 years, uses Apollo for sequencing, SHARP for proving and verifying, and Core contract for settling.

However, alongside https://www.starknet.io/blog/decentralized-starknet-2025/[Starknet becoming the most decentralized L2^], the SN Stack has also achieved organic decentralization, with https://www.starknet.io/sn-stack/[multiple teams offering their own flavors of the stack^]. This decentralization makes the SN Stack more secure, transparent and customizable, with no single point of failure and plenty of room for innovation.

.Additional resources

* https://www.starknet.io/blog/sn-stack-announcement/[_SN Stack Is Now Publicly Available_] on the Starknet blog