= Becoming a Starknet validator guide overview

Welcome to the official guide for becoming Starknet validator! ✅

While Starknet is currently still centralized, it is gradually moving towards employing a staking protocol, handing over the responsibilities of producing, attesting, and proving blocks to validators.

[TIP]
====
To learn more about Starknet's staking protocol, see xref:architecture-and-concepts:staking.adoc[_Protocol_].
====

This guide will walk you though all the steps necessary to for becoming a Starknet validator, including:

* xref:staking-on-starknet/stake.adoc[]
* xref:staking-on-starknet/pathfinder.adoc[]
* xref:staking-on-starknet/block-attestation.adoc[]
* xref:staking-on-starknet/next-steps.adoc[]

Before proceeding further, however, make sure you meet the following prerequisites:

* Docker is installed
+
[TIP]
====
Visit https://docs.docker.com/get-started/get-docker/[docs.docker.com/get-started/get-docker^] to install Docker for your OS.
====

* Either a Sepolia or Mainnet Ethereum websocket RPC URL is exported using:
+
[source,terminal]
----
export ETHEREUM_URL=<YOUR_URL>
----
+
[TIP]
====
You can get your free Ethereum websocket RPC URL by creating an account with https://www.alchemy.com/[Alchemy^], https://www.infura.io/[Infura^], or https://www.quicknode.com/[Quicknode^].
====

* Three `sncast` accounts are deployed on either Sepolia or Mainnet:
+
[TIP]
====
For deploying and funding an `sncast` account on Sepolia, see xref:quick-start:sepolia.adoc#deploying_a_new_sepolia_account[Deploying a new Sepolia account].
====

** An account named `staker` holding at least xref:architecture-and-concepts:staking.adoc#protocol[the minimum required amount of STRK tokens] with its address exported using:
+
[source,terminal]
----
export STAKING_ADDRESS=<YOUR_STAKER_ACCOUNT_ADDRESS>
----

** An account named `rewardee` with its address exported using:
+
[source,terminal]
----
export REWARDS_ADDRESS=<YOUR_REWARDEE_ACCOUNT_ADDRESS>
----

** An account named `operator` with its address exported using:
+
[source,terminal]
----
export OPERATIONAL_ADDRESS=<YOUR_OPERATOR_ADDRESS>
----

Ready? Let's go! 🏁