= Setting up your environment

== Overview

Welcome to the first installment of the _Becoming a Starknet validator_ guide! ✅

Following this guide requires Docker, an exported Ethereum URL and three exported Starknet account. This installment of the guide will therefore walk you through xref:installing_docker[installing Docker] and exporting xref:exporting_an_ethereum URL[an Ethereum URL] and xref:exporting_accounts[the required accounts].

== Installing docker

The easiest option to run a Starknet full node is using Docker. To install Docker, simply visit https://docs.docker.com/get-started/get-docker/[docs.docker.com/get-started/get-docker^] and choose whatever OS you're using.

== Exporting an Ethereum URL

Running a Starknet full node requires an Ethereum websocket RPC URL. You can get your free Ethereum websocket RPC URL by creating an account with https://www.alchemy.com/[Alchemy^], https://www.infura.io/[Infura^], or https://www.quicknode.com/[Quicknode^]. Afterwhich, you can export it by running:

[source,terminal]
----
export ETHEREUM_URL=<YOUR_URL>
----

== Exporting accounts

Becoming a Starknet validator requires three accounts deployed on either Sepolia or Mainnet. To follow this guide, these account should be configured as follows:

[NOTE]
====
To understand the role of the each address, see xref:architecture-and-concepts:staking.adoc#addresses[_Protocol_].
====

* An account with its address exported using:
+
[source,terminal]
----
export OPERATIONAL_ADDRESS=<YOUR_OPERATOR_ADDRESS>
----

* An account with its address exported using:
+
[source,terminal]
----
export REWARDS_ADDRESS=<YOUR_REWARDEE_ACCOUNT_ADDRESS>
----

* An `sncast` account named `staker` holding at least xref:architecture-and-concepts:staking.adoc#protocol[the minimum required amount of STRK tokens] with its address exported using:
+
[source,terminal]
----
export STAKING_ADDRESS=<YOUR_STAKER_ACCOUNT_ADDRESS>
----
+
[TIP]
====
For deploying and funding an `sncast` account on Sepolia, see xref:quickstart/sepolia.adoc#deploying_a_new_sepolia_account[Deploying a new Sepolia account].
====





