= Staking STRK

== Introduction

Welcome to the first installment of the _Becoming a Starknet validator_ guide! ✅

To become a validator, you must stake least the minimum required amount of STRK tokens by locking them into Starknet's Staking contract, subsequentially earning rewards based on your participation. This installment of the series will therefore walk you through staking your STRK tokens by interacting with the STRK token and Staking contracts.

== Approving STRK transfer 

To lock STRK token into the Staking contract, you first need to approve the transfer of STRK tokens from your staking address to the Staking contract. To do so, use your staking address to invoke the STRK token contract's `approve` function with the following parameters:

. The Staking contract's address
. The number of STRK tokens to stake
+
[NOTE]
====
This number needs to be greater than or equal to the minimum stake for validators.
====

For example, the following can be used to approve the transfer of 1 STRK to the Staking contract on Sepolia: 

[source,terminal]
----
sncast --account=staker invoke \
    --contract-address=0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d \ <1>
    --function=approve \
    --arguments=0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1,1000000000000000000 \ <2>
    --network=sepolia
----
<1> The STRK contract's address on Sepolia
<2> The Staking contract's address on Sepolia and 1 STRK (STRK has 18 decimals)

== Locking STRK

Once the transfer is approved, you can lock your STRK tokens into the Staking contract by using your staking address to invoke the Staking contract's `stake` function with the following parameters:

. The address to set as your rewards address
. The address to set as your operational address
. The number of STRK tokens to stake
+
[NOTE]
====
This number must match the number specified in the `approve` function.
====

. `true` to enable delegation pooling and `false` otherwise
. The commission rate to set for your delegation pool (if enabled), as a percentage with precision where 10,000 represents 100%

For example, the following can be used to stake 1 STRK with delegation pooling enabled and 1% commission on Sepolia:

[source,terminal]
----
sncast --account=staker invoke \
    --contract-address=0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    --function=stake \
    --arguments=$REWARDS_ADDRESS,$OPERATIONAL_ADDRESS,1000000000000000000,true,100 \ <2>
    --network=sepolia 
----
<1> The Staking contract's address on Sepolia
<2> 1 STRK (STRK has 18 decimals), enabled delegation pooling, and 100/10,000 = 1% commission

The `stake` function does the following:

. Records your details in the staking contract
. Locks the specified amount of STRK tokens into the staking contract
. Deploys a new delegation pool contract associated with you (if pooling is enabled)
. Begins accumalating your rewards