= Setting up your validator

== Introduction

To set up your validator, you need to lock stake into the Starknet's staking contract, and:

. In the first phase of the staking protocol (on Mainnet and Sepolia): run a full node
. In the second phase of the staking protocol (soon on Sepolia): be able attest to blocks

// == Spinning up your first validator 

// Ready to launch your first validator? Let’s do this! 

// Running a validator means using your local machine’s storage to maintain a full database of the blockchain, starting from the genesis block. This ensures the availability and integrity of blockchain data.

// Before beginning the installation process, check to see if your system meets the required hardware specifications. We have listed the specifications for the different node clients that we will be covering. 


// *Juno (minimal requirements)*

// * CPU: At least 2 cores
// * RAM: 4GB or more
// * Storage: 400GB or more (SSD recommended, storage grows over time) 

// https://juno.nethermind.io/hardware-requirements[Source^]

// *Pathfinder*

// * CPU: 4 cores
// * RAM: 8 GB
// * Storage: 250GB SSD

// https://eqlabs.github.io/pathfinder/getting-started/hardware-requirements[Source^]

// [NOTE] 
// ====
// It is very important that you consider allocating more than the required amount of storage to anticipate future chain growth and compute for attestation. 
// ====

// Feel free to pick your client of choice and proceed to either of the section to get started. 

// * xref:staking-on-starknet/juno.adoc[]
// * xref:staking-on-starknet/pathfinder.adoc[]

== Registering as validator

To register as validator, you first need to approve the transfer of STRK tokens from the address you wish to set as your staking address to the staking contract. To do so, use your staker profile to approve the transfer of 1 STRK to the staking contract on Sepolia:

// . The staking contract's address
// . The number of STRK tokens to stake
// +
// [NOTE]
// ====
// This number needs to be greater than or equal to the minimum stake for validators.
// ====

// For example, the following can be used to approve the transfer of 1 STRK to the staking contract on Sepolia: 

[source,terminal]
----
starkli invoke \
    0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d \ <1>
    approve \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <2>
    u256:1000000000000000000 \ <3>
    --network=sepolia
----
<1> The STRK contract's address on Sepolia
<2> The staking contract's address on Sepolia
<3> 1*10^18^ = 1 STRK (STRK has 18 decimals) serialized as `u256`

Once the transfer is approved, use your staker profile to stake 1 STRK with delegation pooling enabled and 1% commission on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    stake \
    <rewards address> \
    <operational address> \
    1000000000000000000 \ <2>
    1 \ <3>
    100 \ <4>
    --network=sepolia 
----
<1> The staking contract's address on Sepolia
<2> 1*10^18^ = 1 STRK (STRK has 18 decimals) seriallized to `u256`
<3> Enables delegation pooling
<4> 100/10,000 = 1% commission

[WARNING]
====
The address that you use to invoke the `stake` function is the address that will be set as your staking address, which cannot be changed.
====

== Running a full node

Starknet has xref:ecosystem:fullnodes-rpc-providers.adoc#full_nodes[multiple full node implementations] available for running. For the sake of simplicity, this guide will walk you though running your own Pathfinder node, a Rust implementation developed by https://equilibrium.co/[Equilibrium^].

=== Downloading the database snapshot

Running a full node involves using your local machine's storage to maintain a full database of the blockchain, all the way from the genesis block.

Database snapshots let you quickly start your node without having to download all blocks from the very beginning, and instead use a pre-made version of the database that's already in sync up to a certain block.

To download Pathfinder's snapshot, you first need to download the https://rclone.org/[rclone^] file manager by running:

[source,terminal]
----
sudo -v ; curl https://rclone.org/install.sh | sudo bash
----

[NOTE]
====
This installation script can be used to install rclone on Linux/macOS/BSD systems. For other installation methods, see https://rclone.org/install/[rclone.org/install^].
====

Once rclone is downloaded, create a new rclone configuration file: 

[source,terminal]
----
touch $HOME/.config/rclone/rclone.conf
----

and add the following content:

[source,terminal]
----
[pathfinder-snapshots]
type = s3
provider = Cloudflare
env_auth = false
access_key_id = 7635ce5752c94f802d97a28186e0c96d
secret_access_key = 529f8db483aae4df4e2a781b9db0c8a3a7c75c82ff70787ba2620310791c7821
endpoint = https://cbf011119e7864a873158d83f3304e27.r2.cloudflarestorage.com
acl = private
----

Next, create a new `$HOME/pathfinder` directory, navigate into it, and use rclone to copy https://rpc.pathfinder.equilibrium.co/snapshots/latest[Pathfinder's latest database snapshot^] to your local directory by running:

[source,terminal]
----
mkdir $HOME/pathfinder
cd $HOME/pathfinder
rclone copy -P pathfinder-snapshots:pathfinder-snapshots/<FILENAME> . 
----

Once the database snapshot is downloaded, compare the file's checksum value with the one shown at https://rpc.pathfinder.equilibrium.co/snapshots/latest[rpc.pathfinder.equilibrium.co/snapshots/latest^] by running:

[source,terminal]
----
sha256sum <FILENAME> 
----

If the checksum values match, extract the downloaded database snapshot by running:

[source,terminal]
----
zstd -T0 -d EXACT_FILE_NAME -o testnet-sepolia.sqlite
----

=== Running the node

Now that the database snapshot is extracted, you can start your node by running:

[source,terminal]
----
docker run \
  --name pathfinder \
  --restart unless-stopped \
  --detach \
  -p 9545:9545 \
  --user "$(id -u):$(id -g)" \
  -e RUST_LOG=info \
  -e <ETHEREUM_ENDPOINT> \
  -v $HOME/pathfinder:/usr/share/pathfinder/data \
  eqlabs/pathfinder
----

Once the docker container is up and running, you can check the docker image's logs by running: 

[source,terminal]
---- 
docker logs -f pathfinder
---- 

If successful, the result should resemble the following:

[source,terminal]
---- 
...
2025-05-12T18:30:36  INFO Updated Starknet state with block 766534
2025-05-12T18:31:07  INFO Updated Starknet state with block 766535
2025-05-12T18:31:35  INFO Updated Starknet state with block 766536
...
---- 

[NOTE]
====
To stop the node's execution, run:

[source,terminal]
----
docker stop pathfinder
----
====

// == Next step

// Congratulations, you are now running your own Starknet Sepolia node! However, your node is not a validator yet. We will get there eventually. 

// Next, we will be interacting with the staking contract to stake our STRK tokens and assigning our operation and reward addresses. Let's jump in! 


== Attesting to blocks

Starting from its second phase, the staking protocol requires validators to prove they are actively preserving the history of the network by submitting attestations to randomly assigned blocks in each epoch.

[TIP]
====
To learn more about Starknet's staking protocol, see xref:architecture-and-concepts:staking.adoc[_Protocol_].
====

Luckily, running https://github.com/eqlabs/starknet-validator-attestation/tree/main[Pathfinder's attestation service^] is as easy as running:

[source,terminal]
----
docker run -it --rm --network host \
  -e $VALIDATOR_ATTESTATION_OPERATIONAL_PRIVATE_KEY \
  ghcr.io/eqlabs/starknet-validator-attestation \
  --staking-contract-address 0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \
  --attestation-contract-address 0x03f32e152b9637c31bfcf73e434f78591067a01ba070505ff6ee195642c9acfb \
  --staker-operational-address VALIDATOR_ATTESTATION_OPERATIONAL_ADDRESS \
  --node-url http://localhost:9545/rpc/v0_8 \
  --local-signer
----

// === Checking the status of your block attestor service

// If the service is running successfully, it should have the following output where you can see information like your `staker_address`, `operational_address`, `stake`, `epoch_id`, `epoch_start`, `epoch_length`, `attestation_window`:

// [source,terminal]
// ----
// Current attestation info staker_address=0x48f8ddc0bc864f33d4c47b79a1f0e1460e0777d0b0224d8c291f1039523306e operational_address=0x48f8ddc0bc864f33d4c47b79a1f0e1460e0777d0b0224d8c291f1039523306e stake=100000000000000000000 epoch_id=1201 epoch_start=712773 epoch_length=40 attestation_window=16
// ----

// And on the next upcoming epochs, your block attestor service should start submitting attestations. 

// [source,terminal]
// ----
// 2025-04-22T11:04:22.716449Z  INFO starknet_validator_attestation::state: New epoch started staker_address=0x48f8ddc0bc864f33d4c47b79a1f0e1460e0777d0b0224d8c291f1039523306e operational_address=0x48f8ddc0bc864f33d4c47b79a1f0e1460e0777d0b0224d8c291f1039523306e stake=100000000000000000000 epoch_id=1205 epoch_start=712933 epoch_length=40 attestation_window=16
// 2025-04-22T11:11:00.263344Z  INFO starknet_validator_attestation::state: Attestation transaction sent transaction_hash=0x79f9f5ec8dbfca48a132e8d23caad15455c6e0dc98ec517a7013c374d7d5501
// 2025-04-22T11:11:03.017827Z  INFO starknet_validator_attestation::state: Attestation confirmed staker_address=0x48f8ddc0bc864f33d4c47b79a1f0e1460e0777d0b0224d8c291f1039523306e epoch_id=1205
// ----

// === Claiming your staking rewards
// After submitting few attestations, you can check to see if you have accumulated any rewards by calling `claim_reward` from the staking contract by passing the reward address! 

// You can view this https://sepolia.voyager.online/tx/0x25002ba1dc0ddf8bdb79f62eb5fe07eb24befb392da54b04c4983ed4ee2a463[example transaction^] that has successfully claimed 0.33 STRK to their reward wallet address. 


// Now, you are successfully running your own validator and block attestor service on Sepolia testnet! This means that you will start earning rewards for every successful attestation while preserving the state of Starknet blockchain. 


