[id="transaction_structure"]
= Transaction structure

Starknet supports the following types of transactions:

* _invoke_ transaction
* _declare_ transaction

This topic describes the available fields for these transaction types and how each transaction hash is calculated.

[IMPORTANT]
====
The deploy transaction has now been removed in the current release of Starknet. To deploy new contract instances, you can use the `deploy` syscall.
====

[id="transaction_versioning"]
== Transaction versioning

Starknet supports the transaction versions described here.

When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.

Do not submit a transaction that uses an unsupported transaction type, because it cannot be included in a proof, and so cannot become part of a Starknet block.

[id="deploy_transaction"]

=== Calculating the hash of a deploy transaction

In order to calculate the transaction hash, we first need to obtain the deployed contract address. The Deploy transaction's hash is calculated as follows:

[stem]
++++
\begin{aligned}
\text{deploy_tx_hash} = h( & \text{"deploy"}, \text{version}, \text{ contract_address}, \text{sn_keccak}(\text{"constructor"}), \\
& h(\text{constructor_calldata}), 0, \text{chain_id})
\end{aligned}
++++

Where:

* The placeholder zero is used to align the hash computation for the different types of transactions.
* “deploy” and “constructor” are constant strings encoded in ASCII.
* stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash and stem:[$sn\_keccak$] is xref:../Hashing/hash-functions.adoc#starknet-keccak[Starknet Keccak]
* `chain_id` is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* `contract_address` is calculated as described xref:../Contracts/contract-address.adoc[here].

== Invoke Transaction

The invoke transaction is the main transaction type used to invoke contract functions in Starknet.

[IMPORTANT]
====
Transaction version 0 is deprecated and will be removed in a future release of Starknet.
====

=== Invoke transaction version 1

.Transaction fields

[%autowidth]
|===
| Name | Type | Description

| `sender_address` | `FieldElement` | The address of the sender of this transaction.
| `calldata` | `List<FieldElement>` | The arguments that are passed to the `validate` and `execute` functions.
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. The value is 1. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.
|===

=== Invoke transaction version 0

.Transaction fields
[%autowidth]
|===
| Name | Type | Description

| `contract_address` | `FieldElement` | The address of the contract invoked by this transaction.
| `entry_point_selector` | `FieldElement` | The encoding of the selector for the function invoked (the entry point in the contract)
| `calldata` | `List<FieldElement>` | The arguments that are passed to the invoked function
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction
| `version` | `FieldElement` | The transaction's version. The value is 0. +
Transaction version 0 is deprecated and will be removed in a future version of Starknet. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.
|===

=== Calculating the hash of a v1 invoke transaction

The invoke transaction hash is calculated as a hash over the given transaction elements, specifically:

[stem]
++++
\begin{aligned}
\text{invoke_v1_tx_hash} = h( & \text{"invoke"}, \text{version}, \text{sender_address}, 0, h(\text{calldata}), \\
& \text{max_fee}, \text{chain_id}, \text{nonce})
\end{aligned}
++++

Where:

* stem:[\text{invoke}] is a constant prefix string, encoded in ASCII.
* The placeholder zero is used to align the hash computation for the different types of transactions.
* stem:[\text{chain_id}] is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash

=== Calculating the hash of a v0 invoke transaction

The hash of a v0 invoke transaction is computed as follows:

[stem]
++++
\begin{aligned}
\text{invoke_v0_tx_hash} = h( & \text{"invoke"}, \text{version}, \text{contract_address}, \text{entry_point_selector}, \\
& h(\text{calldata}), \text{max_fee}, \text{chain_id})
\end{aligned}
++++

Where:

* stem:[\text{invoke}] is a constant prefix string, encoded in (ASCII).
* stem:[\text{chain_id}] is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash

== Declare transaction

The declare transaction is used to introduce new classes into the state of Starknet, enabling other contracts to deploy instances of those classes or using them in a library call. For more information, see xref:../Contracts/contract-classes.adoc[contract classes].

A declare transaction has the following fields:

[%autowidth]
|===
| Name | Type | Description

| `contract_class` | `ContractClass` | The class object.
| `sender_address` | `FieldElement` | The address of the account initiating the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction.
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. Possible values are 1 or 0. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases. Transaction version 0 is deprecated and will be removed in a future version of Starknet.
|===

=== Calculating the hash of a v1 declare transaction

The hash of a v1 declare transaction is computed as follows:

[stem]
++++
\begin{aligned}
\text{declare_v1_tx_hash} = h( & \text{"declare"}, \text{version}, \text{sender_address}, 0, \text{class_hash}, \text{max_fee}, \text{chain_id}, \text{nonce})
\end{aligned}
++++

Where:

* stem:[\text{declare}] is a constant prefix string, encoded in ASCII.
* stem:[\text{class_hash}] is the hash of the xref:../Contracts/contract-classes.adoc[contract class]. See xref:../Contracts/contract-hash.adoc[Contract Hash] for details about how the hash is computed.
* The placeholder zero is used to align the hash computation for the different types of transactions.
* stem:[\text{chain_id}] is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash

=== Calculating the hash of a v0 declare transaction

The hash of a v0 declare transaction is computed as follows:

[stem]
++++
\begin{aligned}
\text{declare_v0_tx_hash} = h( & \text{"declare"}, \text{version}, \text{sender_address}, 0, 0, \text{max_fee}, \text{chain_id}, \text{class_hash})
\end{aligned}
++++

Where:

* stem:[\text{declare}] is a constant prefix string, encoded in ASCII.
* The placeholder zeros are used to align the hash computation for the different types of transactions.
* stem:[\text{class_hash}] is the hash of the xref:../Contracts/contract-classes.adoc[contract class]. See xref:../Contracts/contract-hash.adoc[Contract Hash] for details about how the hash is computed.
* stem:[\text{chain_id}] is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash

== Signature

While Starknet does not have a specific signature scheme built into the protocol, the Cairo language, in which smart contracts are written, does have an efficient implementation for ECDSA signature with respect to a xref:../Hashing/hash-functions.adoc#stark-curve[STARK-friendly curve].

The generator used in the ECDSA algorithm is stem:[G=\left(g_x, g_y\right)] where:

stem:[g_x=874739451078007766457464989774322083649278607533249481151382481072868806602] stem:[g_y=152666792071518830868575557812948353041420400780739481342941381225525861407]

[id="chain-id"]
== Chain-Id

Starknet currently supports three chain IDs. Chain IDs are given as numbers, representing the ASCII encoding of specific constant strings, as illustrated by the following Python snippet:

[source,python]
----
chain_id = int.from_bytes(value, byteorder="big", signed=False)
----
Three constants are currently used:

* `SN_MAIN` for Starknet's main network.
* `SN_GOERLI` for Starknet's public testnet.
* `SN_GOERLI2` for Starknet developers.