[id="compiled_class_hash"]
= Compiled class hash


Compiled class hash

Compiled class hash is the hash of the compiled class generated by the Sierra→Casm compiler that is used in Starknet.

The compiled class hash identifies the output of a specific Casm compilation as unique.

Cairo classes that are part of the state commitment are defined with Sierra, an intermediate representation between Cairo and Cairo assembly (Casm). However, the prover only works with Casm.

So in order to prevent needing to compile from Sierra to Casm in every block in which the class is used, the state commitment must have some information about the corresponding Cairo assembly. The compiled class hash provides this information.

For more information, see xref:architecture_and_concepts:Smart_Contracts/cairo-and-sierra.adoc[Cairo and Sierra].

The party that declares the contract signs the compiled class hash, which they obtain using an SDK, as part of the xref:Network_Architecture/transactions.adoc#declare_v2[`DECLARE`] transaction. If the transaction is included in a block, then the compiled class hash becomes part of the state commitment.

In the future, when Sierra-to-Casm compilation becomes part of the Starknet OS, this value might be updated via a proof of the Sierra-to-Casm compiler execution, showing that compiling the same class with a newer compiler version results in some new compiled class hash.
