[id="contract_classes"]
= Contract classes

As in object-oriented programming, Starknet distinguishes between a contract and its implementation by separating contracts into classes and instances.

A _contract class_ is the definition of the contract: Cairo byte code, hint information, entry point names, and everything that defines its semantics unambiguously.

Each class is identified by its class hash, which is analogous to a class name in an object-oriented programming language. 

A _contract instance_ is a deployed contract corresponding to a class. Only contract instances behave as contracts, in that they have their own storage and can be called by transactions or other contracts. 

A contract class does not necessarily have a deployed instance in Starknet.

[id="using_classes"]
== Using Classes

To add new classes to the state of Starknet, use the `DECLARE` transaction.

To deploy new instances of a previously declared class, use the `deploy` system call.

To use the functionality of a declared class, without deploying an instance of that class, you can use the `library_call` system call. 
This system call is an analogue of Ethereum's low-level `delegatecall` function in the world of classes. The `library_call` system call enables you to use class code directly, instead of having a placeholder contract deployed, which is used only for its code.

== Additional resources

* xref:architecture_and_concepts:Smart_Contracts/class-hash.adoc[Class hash]
* xref:architecture_and_concepts:Network_Architecture/transactions.adoc#declare-transaction[`DECLARE` transaction]
* xref:architecture_and_concepts:Smart_Contracts/system-calls-cairo1.adoc#deploy[`deploy` system call]
* xref:architecture_and_concepts:Smart_Contracts/system-calls-cairo1.adoc#library_call[`library_call` system call]
