[id="contract_classes"]
= Contract classes

As in object-oriented programming, Starknet distinguishes between a contract and its implementation by separating contracts into classes and instances.

== Contract Classes

A _contract class_ is the definition of a contract. It includes Cairo byte code, hint information, entry point names, and everything that defines its semantics.

Each class is uniquely identified by its _class hash_, comparable to a class name in traditional object-oriented programming languages.

== Contract Instances

A _contract instance_ is a deployed contract that corresponds to a class. Only contract instances act as true contracts, in that they have their own storage and can be called by transactions or other contracts.

A contract class does not necessarily have a deployed instance in Starknet.

[IMPORTANT]
====
A contract class does not necessarily require a deployed instance in Starknet.
====

== Working with Classes

[horizontal,labelwidth=20,role="stripes-odd"]
Adding new classes:: To introduce new classes to Starknet's state, use the `DECLARE` transaction.

Deploying instances:: To deploy a new instance of a previously declared class, use the `deploy` system call.

Using class functionality:: To use the functionality of a declared class without deploying an instance, use the `library_call` system call. Analogous to Ethereum's `delegatecall`, it enables you to use code in an existing class without deploying a contract instance.

== Additional Resources

* xref:architecture_and_concepts:Smart_Contracts/class-hash.adoc[Class hash]
* xref:architecture_and_concepts:Network_Architecture/transactions.adoc#declare-transaction[`DECLARE` transaction]
* xref:architecture_and_concepts:Smart_Contracts/system-calls-cairo1.adoc#deploy[`deploy` system call]
* xref:architecture_and_concepts:Smart_Contracts/system-calls-cairo1.adoc#library_call[`library_call` system call]

