[id="contract_address"]
= Contract address

The contract address is a unique identifier of the contract on Starknet. It is a chain hash of the following information:

* `prefix` - The ASCII encoding of the constant string `STARKNET_CONTRACT_ADDRESS`.
* `deployer_address` - The deployer address, unless `deploy_from_zero` is `true`, in which case it is `0`.
* `salt` - The salt passed by the contract calling the syscall, provided by the transaction sender.
* `class_hash` - See xref:./class-hash.adoc#computing_the_cairo_1_class_hash[the class hash documentation].
* `constructor_calldata_hash` - xref:Cryptography/hash-functions.adoc#pedersen_array_hash[Array hash] of the inputs to the constructor.

The address is computed as follows:

[source,js]
----
contract_address := pedersen(
    “STARKNET_CONTRACT_ADDRESS”,
    deployer_address,
    salt,
    class_hash,
    constructor_calldata_hash)
----

[NOTE]
====
A random `salt` ensures unique addresses for smart contract deployments, preventing conflicts when deploying identical contract classes.

It also thwarts replay attacks by influencing the transaction hash with a unique sender address.
====

You can find more details of the address computation in the https://github.com/starkware-libs/cairo-lang/blob/ed6cf8d6cec50a6ad95fa36d1eb4a7f48538019e/src/starkware/starknet/services/api/gateway/contract_address.py#L12[Cairo code repository].


