:deploy-syscall: xref:./system-calls-cairo1.adoc#deploy[deploy syscall]

[id="universal_deployer"]
= Universal Deployer Contract

The Universal Deployer Contract (UDC) is a singleton smart contract that wraps the {deploy-syscall} to expose it to any contract that doesn’t implement it, such as account contracts. You can think of it as a standardized generic factory for Starknet contracts.

And since Starknet has no deployment transaction type, it offers a canonical way to deploy smart contracts by following the https://community.starknet.io/t/snip-deployer-contract-interface/2772[standard deployer interface] and emitting a `ContractDeployed` event. For more details on thought process and decision making, refer to the https://community.starknet.io/t/universal-deployer-contract-proposal/1864[Universal Deployer Contract Proposal].

NOTE: The UDC address is `0x041a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf` in mainnet, testnets, and starknet-devnet. This address may change in the future as it gets migrated to Cairo 1+.

== Interface

[,js]
----
trait IUniversalDeployer {
    fn deployContract(
        class_hash: ClassHash,
        salt: felt252,
        unique: bool,
        calldata: Span<felt252>
    ) -> ContractAddress;
}
----

== Usage

To deploy a contract first you need to make sure it's been xref:Network_Architecture/transactions.adoc#declare-transaction[declared] and then send a `deployContract` transaction to the Universal Deployer Contract.
Here's an example implementation in Cairo:

[,js]
----
use openzeppelin::utils::universal_deployer::IUniversalDeployerDispatcher;

const UDC_ADDRESS = 0x041a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf;
let udc = IUniversalDeployerDispatcher { contract_address: UDC_ADDRESS }

let class_hash = 0x5c478ee27f2112411f86f207605b2e2c58cdb647bac0df27f660ef2252359c6;
let salt = 1234567879;
let unique = false;
let mut calldata = ArrayTrait::<felt252>::new();

let deployed_addr = udc.deployContract(class_hash, salt, unique, calldata.span());
----

=== Deployment types

The Universal Deployer Contract offers two types of addresses to deploy: origin dependent and origin independent.
As the names suggest, the origin-dependent type includes the deployer's address in the address calculation;
whereas, the origin-independent type does not.
The `unique` boolean parameter ultimately determines the type of deployment.

CAUTION: When deploying a contract that uses `get_caller_address` in the constructor calldata, remember that the UDC (and not the account) deploys that contract.
Therefore, querying `get_caller_address` in a contract's constructor will return the UDC's address and *not* the account's address.

==== Origin dependent

Making deployments dependent of the origin address, users can "reserve" themselves a whole address space from squatting by someone else.
Only that origin can deploy to those addresses.

Achieving this type of deployment necessitates that the origin sets `unique` to `true` in the `deployContract` call.
Under the hood, the function call leverages the origin's address and creates a hashchain by hashing the origin's address with the given salt.

To deploy a unique contract address pass:

[,js]
----
let deployed_addr = udc.deployContract(class_hash, salt, true, calldata.span());
----


==== Origin independent

Origin-independent contract deployments create contract addresses independent of the deployer and the UDC instance.
Instead only the class hash, salt, and constructor arguments determine the address.
This type of deployment enables redeployments of accounts and known systems across multiple networks.
To deploy a reproducible deployment, set `unique` to `false`.

[,js]
----
let deployed_addr = udc.deployContract(class_hash, salt, false, calldata.span());
----

== Deploying the UDC

NOTE: The Universal Deployer Contract has already been deployed on most networks and development environments.
The standard requires the UDC to be deployed passing `deploy_from_zero=true` to the {deploy-syscall}. This results in a deterministic and predictable address across all instances of Starknet, facilitating SDK integration and reproducibility of deployments.

== API specification

=== Methods

==== `deployContract`

Deploy a contract through the Universal Deploy Contract.

[,js]
----
fn deploy_contract(
    class_hash: ClassHash,
    salt: felt252,
    unique: bool,
    _calldata: Span<felt252>
) -> ContractAddress 
----

=== Events

==== `ContractDeployed`

Emitted when `deployer` deploys a contract through the Universal Deployer Contract.

[,js]
----
#[event]
fn ContractDeployed(
    address: ContractAddress,
    deployer: ContractAddress,
    unique: bool,
    class_hash: ClassHash,
    _calldata: Span<felt252>,
    salt: felt252,
) {}
----
