[id="introduction"]
= Introduction

StarkEx leverages STARK technology to power scalable, self-custodial trading and payment transactions for applications such as DeFi and gaming. StarkEx enables an application to scale significantly and improve transaction speed while also reducing transaction costs. Implementation requires minimal change to existing setups.

StarkEx currently supports ETH, synthetic assets, and the following tokens:

* ERC-20
* ERC-721
* ERC-1155

StarkEx can also support tokens on other EVM-compatible blockchains.

StarkEx is a mature platform that has been deployed on Ethereum Mainnet since June 2020. Before its Mainnet deployment, over 50M StarkEx transactions were settled on both public and private Ethereum testnets.

Many applications are currently using StarkEx, including:

|===
| Client | Launch Date | Current StarkEx Version

| https://rhino.fi[rhino.fi] (Previously DeversiFi)
| June 2020
| spot Trading V4

| https://www.immutable.com[Immutable]
| Apr 2021
| spot Trading V3

| https://dydx.exchange[dYdX]
| Apr 2021
| perpetual trading V1

| https://sorare.com[Sorare]
| June 2021
| spot Trading V4
|===

The concrete smart contract deployments are listed xref:deployments-addresses.adoc[here].

[id="starkex_for_spot_trading_and_starkex_for_perpetual_trading"]
== StarkEx for Spot Trading and StarkEx for Perpetual Trading

This documentation describes two similar, but separate, systems:

* *StarkEx for Spot Trading*
* *StarkEx for Perpetual Trading*

Content that refers only to Spot Trading or Perpetual Trading clearly states so.
