[id="readme"]
= Read Me
:toc:
:toclevels: 1


The Starknet docs website, https://docs.starknet.io, is built using link:https://antora.org/[Antora], a static website generator for AsciiDoc.

== Previewing the website on your local machine

You don't need to install Antora to preview the website. This repo includes an embedded Antora installation, which is referred to in the Antora documentation as a _local installation_.

=== Prerequisites

You must have an active Node.js LTS release on your machine. See the _Antora documentation_ for your OS:

* https://docs.antora.org/antora/latest/install/linux-requirements/#node[Linux]
* https://docs.antora.org/antora/latest/install/windows-requirements/#node[Windows]
* https://docs.antora.org/antora/latest/install/macos-requirements/#node[macOS]

[id="http_server"]
[TIP]
====
Install the optional link:https://docs.antora.org/antora/latest/preview-site/#run-a-local-server-optional[http server Antora provides] so you can view the output in a local web server
====

== Git-related info

* Clone this repo to your local machine. Using a fork is optional.
* When naming a branch, if you do not use a fork, use the following format: `<name>/<short_description>`
* When creating a new PR, tag one or more of the following as reviewers: `stoobie`, `JameStark`

== Tips on authoring

For information on writing in AsciiDoc, see:

* link:https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc Language Documentation]
* link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

[NOTE]
====
There are multiple ways of coding ids, source code blocks, cross references, and links. In general we use the most explicit coding conventions for coding in order to prioritize code readability. Most of these coding conventions are listed in link:https://redhat-documentation.github.io/asciidoc-markup-conventions/[AsciiDoc Mark-up Quick Reference for Red Hat Documentation]
====

== Building and previewing content locally

After writing or editing content, to preview your changes:

. Build the content by running the `build_local_site.sh` build script:
+
[source,bash]
----
$ ./build_local_site
----
+
This command generates the website in the directory `public_html`.
. Open the website by doing one of the following:
+
* Open the start page: `<repo_root>/public_html/index.html`.
* Run the xref:http_server[http server] packaged with Antora:
+
[source,bash]
----
$ http-server public_html -c-1
----
+
The server runs, and gives you one or more local URLs that you can use to view the website. For example:
+
[source,bash,subs="+quotes,+macros"]
----
Starting up http-server, serving *public_html*

...

Available on:
  \http://127.0.0.1:8080
  \http://192.168.68.111:8080
  \http://192.168.14.3:8080
  \http://10.14.0.2:8080
Hit CTRL-C to stop the server

----

== Releasing Starknet docs on Github
_The high-level process for releasing documentation changes in this repository._

During the course of content development, writers merge branches with changes into `dev`, where these changes wait until we are ready to release them—that is, post them to link:https://docs.starknet.io[docs.starknet.io].

Github actions create Git tags and releases that appear at the repo’s link:https://github.com/starknet-community-libs/starknet-docs/releases[Releases] and link:https://github.com/starknet-community-libs/starknet-docs/tags[Tags] pages.

When the `dev` branch is merged into the `master` branch, a github action creates a tag and release, and updates `CHANGELOG.md`.

[NOTE]
====
Previously, this repo used Pre-release tags in addition to Release tags. This functionality is useful for application development, which requires validating multiple release candidates. This usage model does not typically apply to documentation.
====

=== Procedure

. Checkout the `master` branch.
. Fetch the latest changes from the main repo, `origin`. If your origin is a fork of the main repo, update this command appropriately:
+
[source,bash]
----
starknet-docs (master) $ git fetch origin
----
. Merge `dev` into `master` on your local starknet-docs repo:
//. Rebase `dev` into `master` on your local starknet-docs repo:
+
[source,bash]
----
starknet-docs (master) $ git merge dev
----

+
Your local version of `master` now includes all the changes from `dev`.
. Push the local version of `master` to Github:
+
[source,bash]
----
starknet-docs (master) $ git push -f origin master
----
+
Github increments the version numbers in `package.json` and `package-lock.json`, and updates `CHANGELOG.md` with the descriptions of each PR that was just merged into `master`.
. Update your local `dev` branch from the remote `master` branch:
+
[source,bash]
----
starknet-docs (master) $ git checkout dev
starknet-docs (dev) $ git fetch origin
starknet-docs (dev) $ git rebase origin/master
----

