[id="readme"]

= Starknet Docs repository

Welcome to the https://docs.starknet.io[Starknet Docs^] repository, written in https://asciidoc.org/[AsciiDoc^] and built using https://antora.org/[Antora^].

[NOTE]
====
This repository only contains the content of the Starknet Docs. For the UI, see the Starknet Docs can be found in the https://github.com/starknet-io/starknet-docs-ui/tree/main[Starknet Docs UI repository^].
====

To build and preview content locally, first:

. Install `yarn` if it's not already installed.
. Install `npx` if it's not already installed.
. Clone this repo, either from a fork or directly from `starknet-io/starknet-docs` (if you are an official collaborator).
. Nativgate into the `starknet-docs` directory and run the `yarn` command to prepare the environment:
+
----
cd starknet-docs && yarn
----

Then:

. Build the content with Antora:
+
[source,bash]
----
npx antora playbook.yml
----
+
generating the website in the `public_html` directory.

. Run the http server packaged with Antora:
+
[source,bash]
----
npx http-server public_html -c-1
----
+
giving you one or more local URLs that you can use to view the website, e.g.:
+
[source,bash,subs="+quotes,+macros"]
----
Starting up http-server, serving *public_html*

...

Available on:
  \http://127.0.0.1:8080
  \http://192.168.68.111:8080
  \http://192.168.14.3:8080
  \http://10.14.0.2:8080
Hit CTRL-C to stop the server
----

After writing or editing content, rebuild it to preview your changes (rerunning the server is not necessary).
