= Read Me

This website is built using link:https://antora.org/[Antora], a static website generator.

You don't need to install Antora to build the webiste. This repo includes an embedded Antora installation, which is referred to in the Antora documentaton as a _local installation_.

== Prerequisites

You’ve installed an active Node.js LTS release on your https://docs.antora.org/antora/latest/install/linux-requirements/#node[Linux], https://docs.antora.org/antora/latest/install/windows-requirements/#node[Windows], or https://docs.antora.org/antora/latest/install/macos-requirements/#node[macOS] machine.

[id="http_server"]
[TIP]
====
Install the optional link:https://docs.antora.org/antora/latest/preview-site/#run-a-local-server-optional[http server Antora provides] so you can view the output in a local web server
====

.Additional resources

* link:https://docs.antora.org/antora/latest/antora-container/[Run Antora in a Container]
* link:https://docs.antora.org/antora/latest/install/install-antora/#install-antora-globally[Install Antora globally].

== Git-related info

* Clone this repo to your local machine. Using a fork is optional.
* When naming a branch, if you do not use a fork, use the following format: `<name>/<short_description>`
* When creating a new PR, tag one or more of the following as reviewers: `stoobie`, `JameStark`

== Authoring

For information on writing in AsciiDoc, see:

* link:https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc Language Documentation]
* link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

[NOTE]
====
There are multiple ways of coding ids, source code blocks, cross references, and links. In general we use the most explicit coding conventions for coding in order to prioritize code readability. Most of these coding conventions are listed in link:https://redhat-documentation.github.io/asciidoc-markup-conventions/[AsciiDoc Mark-up Quick Reference for Red Hat Documentation]
====

== Building and previewing content locally

After writing or editing content, to preview your changes:

. Build the content by running the `build_local_site.sh` build script:
+
[source,bash]
----
$ ./build_local_site
----
+
This command generates the website in the directory `public_html`.
. Open the website by doing one of the following:
+
* Open the start page: `<repo_root>/public_html/index.html`.
* Run the xref:http_server[http server] packaged with Antora:
+
[source,bash]
----
$ http-server public_html -c-1
----
+
The server runs, and gives you one or more local URLs that you can use to view the website. For example:
+
[source,bash,subs="+quotes,+macros"]
----
Starting up http-server, serving *public_html*

...

Available on:
  \http://127.0.0.1:8080
  \http://192.168.68.111:8080
  \http://192.168.14.3:8080
  \http://10.14.0.2:8080
Hit CTRL-C to stop the server

----
