[id="validator_guide_prerequisite"]
= Setting up your environment

== Introduction

Welcome to the first chapter on running your first node on Starknet! You are one step closer to having your own Starknet validator and making Starknet more decentralized. Treat this chapter as a compiled prerequisite for upcoming chapters. Feel free to come back to this chapter in case you accidentally skipped over a step. 

There are four prerequisites before proceeding to next steps.

* Docker = cloud platform that provides us with an isolated environment for our node client. Many node client providers utilize docker as their go to installation method. Please go to this link to download https://docs.docker.com/desktop/[docker desktop^] for your OS. 

* Wallet Accounts = We need up to two wallet accounts that will be needed in xref:stake.adoc[] and xref:block-attestation.adoc[] sections. 

* Make sure both Accounts have some STRK tokens. You can visit the https://starknet-faucet.vercel.app/[faucet page^] to request STRK.  

* We need ETH sepolia websocket RPC to allow communication between our validator and sepolia testnet. You can create an account with Alchemy, infura or quicknode to get your free RPC. 

With these steps complete, you're now ready to launch your first validator!

== Spinning up your first validator 

Ready to launch your first validator? Let’s do this! 

Running a validator means using your local machine’s storage to maintain a full database of the blockchain, starting from the genesis block. This ensures the availability and integrity of blockchain data.

Before beginning the installation process, check to see if your system meets the required hardware specifications. We have listed the specifications for the different node clients that we will be covering. 


*Juno (minimal requirements)*

* CPU: At least 2 cores
* RAM: 4GB or more
* Storage: 400GB or more (SSD recommended, storage grows over time) 

https://juno.nethermind.io/hardware-requirements[Source^]

*Pathfinder*

* CPU: 4 cores
* RAM: 8 GB
* Storage: 250GB SSD

https://eqlabs.github.io/pathfinder/getting-started/hardware-requirements[Source^]

[NOTE] 
====
It is very important that you consider allocating more than the required amount of storage to anticipate future blocks being processed. 
====

Feel free to pick your client of choice and proceed to either of the section to get started. 

* xref:juno.adoc[]
* xref:pathfinder.adoc[]
