[id="validator_guide_prerequisite"]
= Setting up your environment

== Introduction

Welcome to the first chapter on running your first node on Starknet! You are one step closer to having your own Starknet validator and making Starknet more decentralized. Treat this chapter as a compiled prerequisite for upcoming chapters. Feel free to come back to this chapter in case you accidentally skipped over a step. 

There are four prerequisites before proceeding to next steps.

* Docker = cloud platform that provides us with an isolated environment for our node client. Many node client providers utilize docker as their go to installation method. Please go to this link to download https://docs.docker.com/desktop/[docker desktop^] for your OS. 

* Wallet Accounts = We need up to two wallet accounts for later steps on Staking your STRK tokens and Running your block attestation service. 

* Make sure both Accounts have some STRK tokens. You can visit the https://starknet-faucet.vercel.app/[faucet page^] to request STRK.  

* We need ETH sepolia websocket RPC to allow communication between our validator and sepolia testnet. You can create an account with Alchemy, infura or quicknode to get your free RPC. 

Once you have these steps completed, you are now ready to launch yourfirst validator! 
