[id="validator_guide_stake"]
= Staking your STRK tokens

In this chapter, we will provide a step by step guide on how to stake your STRK tokens using Starknet blockchain explorer (https://voyager.online/[Voyager^] or https://starkscan.co/[Starkscan^]). We will also utilize the two wallet accounts from the xref:prerequisite.adoc[prerequisite] section to assign reward and operation addresses. 

== Role of reward and operation addresses

Reward address = address that receives rewards from staking.

[NOTE]
====
You can only receive rewards if you are running the block attestation service. 
====

Operation address = address that is used to pay transactions for submitting attestation and any future operation needs such as block proposing which will be rolled out in later phases. 

[NOTE]
====
While the staking function provides two separate address parameters to enhance security, you have the option of using two separate addresses or a single address.  
====

== Accessing the staking contract

Once you have your wallet addresses ready, let’s access the staking contract. We can refer to the https://docs.starknet.io/resources/chain-info/#staking[important addresses page^]  and copy the staking contract under the Sepolia section.

We will paste the address on our blockchain explorer then, we will click *Write Contract* to list all the state changing functions. We will be calling the `stake` function that will have the following parameters 

[source,terminal]
----
reward_address = YOUR_REWARD_ADDRESS
operational_address = YOUR OPERATIONAL ADDRESS
amount = NUMBER_OF_STRK_TOKENS_TO_STAKE
pool_enabled = ENABLE_OR_DISABLE_DELEGATORS
commission = FEES_IN_PERCENTAGE
----


Let’s briefly go over the `amount`, `pool_enabled` and `commission` parameters as they can be confusing. 

`amount` = the STRK token amount is required to be written in 18 decimal places. Therefore, it would be your `amount * 10^18`. 

`pool_enabled` = Set this to 1 if you want to enable delegation for your validator, or 0 if you don’t.

`commission` = If you enabled delegation for your validator then it’s time to set your fee amount. This is done in percentages where the input can range from `0` to `10000`. As an example, `10` would equal to *0.1%* and `100` would equal to *1%*. 

[NOTE]
====
The minimum required amount to stake on sepolia is 1 STRK. 
====

Once the transaction is executed and the amount in STRK is withdrawn, you have now successfully staked your STRK and your reward/operation addresses are now discoverable by the block attestor service. 

