[id="validate_and_execute_functions"]
== `validate` and `execute` functions

A StarkNet account contract must include the following two functions:

* validate
* execute

These serve distinct purposes to ensure that only the account owner can initiate transactions and that fair fees are charged for the resources they use.

[id="starknet_account_structure"]
= StarkNet account structure

Starknet's account type is inspired by Ethereum's EIP-4337, where instead of EOAs, users now use smart contract accounts with arbitrary verification logic. 

Through the use of smart contracts, you are provided with complete flexibility within your account implementation.

[id="examples"]
== Examples of customizing account functionality

Two examples of how you might program an account to function using account abstraction are:

Social recovery:: A process where if you lose your wallet, you are able to retrieve it via a selected social network, vastly improving the typical experience of wallet recovery.

Operating your account via facial recognition:: With signature abstraction, you can use your phone's native hardware to sign transactions, making it practically impossible to take control of another user's account (even in the case of the phone itself being stolen).

[id="replay_protection"]
== Replay Protection

The StarkNet OS enforces transaction uniqueness via a nonce. A nonce is a notion in programming that refers to an integer that is unique within the system.

Within StarkNet the nonce provides an important mechanism for protecting against a replay attack. 

The transaction uniqueness that results from the use of a nonce means that a sequencer will never include the same transaction twice. 

While not mandatory at the protocol level, a richer standard interface for accounts was developed by the community. This standard was developed by OpenZeppelin, in a close collaboration with wallet teams and other Core StarkNet developers. You can see the IAccount interface https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/account/IAccount.cairo[here].
