[id="starknet_account_structure"]
= StarkNet account structure

Starknet's account type is based on Ethereum's EIP-4337, where instead of EOAs, the account type uses smart contracts and is almost entirely implementation-agnostic. 

Through the use of smart contracts, you are provided with complete flexibility within your account implementation.

This method of account implementation is more broadly known as account abstraction.

[id="examples"]
== Examples of customizing account functionality

Two examples of how you might program an account to function using account abstraction are:

Social recovery:: A process where if you lose your wallet, you are able to retrieve it via a selected social network, vastly improving the typical experience of wallet recovery.

Operating your account via facial recognition:: With signature abstraction, you can use your phone's native hardware to sign transactions, making it practically impossible to take control of another user's account (even in the case of the phone itself being stolen).

[id="starknets_approach_to_account_management"]
== StarkNet's approach to account management

StarkNet has its own account smart contract that all new account contracts should build upon. The StarkNet account contract combined with the underlying operating system provides three important features that create a basic account structure:

* `validate` and `execute` functions
* A Nonce
* A Payment Mechanism

[id="validate_and_execute_functions"]
== `validate` and `execute` functions

Starknet's account contract has two important functions that provide you with an interface:

* `validate`
* `execute`

These serve distinct purposes to ensure honest behavior and to provide a mechanism for sequencers to charge fair fees for the resources they use. 

[id="a_nonce_for_uniqueness"]
== A nonce for uniqueness

The StarkNet OS enforces transaction uniqueness via a nonce. A nonce is a notion in programming that refers to an integer that is unique within the system.

Within StarkNet the nonce provides an important mechanism for protecting against a replay attack. 

Without enforcement of a nonce for each transaction, an attacker could steal funds or carry out a Denial of Service (DoS) attack.

The transaction uniqueness that results from the use of a nonce means that a sequencer will never include the same transaction twice. 

[id="a_payment_mechanism"]
== A payment mechanism

The underlying Starknet OS run by the sequencer offers a payment mechanism for moving funds and charging fees. 

The sequencer receives fees in ETH in return for including transactions in a block.