[id="starknet_account_structure"]
== StarkNet account interface

A StarkNet account contract must include the following two functions:

* `&lowbar;&lowbar;validate&lowbar;&lowbar;`
* `&lowbar;&lowbar;execute&lowbar;&lowbar;`

These serve distinct purposes to ensure that only the account owner can initiate transactions and that fees can be charged for the resources you use.

Starknet's account type is inspired by Ethereum's EIP-4337, where instead of EOAs, you now use smart contract accounts with arbitrary verification logic. 

Through the use of smart contracts, you are provided with complete flexibility within your account implementation.

[id="examples"]
== Examples of customizing account functionality

Two examples of how you might program an account to function using account abstraction are:

Social recovery:: A process where if you lose your wallet, you are able to retrieve it via a selected social network, vastly improving the typical experience of wallet recovery.

Operating your account via facial recognition:: With signature abstraction, you can use your phone's native hardware to sign transactions, making it practically impossible to take control of another user's account (even in the case of the phone itself being stolen).

[id="replay_protection"]
== Replay protection

In StarkNet, similar to Ethereum, every contract has a nonce. This nonce is sequential; when a transaction is sent from an account, its nonce must match the account's nonce and it's incremented after the transaction is executed (whether or not it was reverted). 

Note that, similar to Ethereum, only the nonce of account contracts (that is, those adhering to the above structure) can be non-zero.

A nonce serves two important roles:

*   It guarantees transaction hash uniqueness (this is important for good UX)
*   It provides replay protection to the account (since the signature refers to a particular nonce, the transaction can't be replayed by a malicious party)

As seen above, StarkNet currently determines the nonce structure (sequential) at the protocol level. In the future, StarkNet consider a more flexible design, extending account abstraction to nonce management (previously referred to as "nonce abstraction").