[id="validate_and_execute"]
= `validate` and `execute`

As previously stated, StarkNet's account structure is not completely arbitrary, but must include the following two functions, which account transactions call: 

* `_validate`
* `_execute`

Separating the `validate` and `execute` functions guarantees payment to sequencers for work completed, and protects them from Denial of Service (DoS) attacks.

[id="the_validate_function"]
== The `validate` function

The `validate` function:

*   Ensures that any transaction submitted was indeed initiated by the account owner and therefore will not take up unjustified resources during the execution process.

Without this mechanism, a forged transaction can result in the sequencer stealing the user's funds.
In short, `validate` ensures that the sequencer may only include transactions that were approved by the account owner.


[id="invalid_transactions"]
== Invalid transactions

When the `validate` function fails, no fee will be taken from the account in question.

[id="the_execute_function"]
== The `execute` function

The purpose of the `execute` function is to abstract away the remaining actions performed by a transaction. 

In Ethereum, a transaction is necessary a call to a specific function in a smart contract. With the execute abstraction, the account designer controls the flow of the transaction. For example, multicalls can be natively supported in your account, saving the need to send multiple transactions (in practice, this is even harder to manage without multicalls due to nonces).

[id="reverted_transactions"]
== Reverted transactions

A transaction is considered reverted when the __execute__ function failed. Today, reverted transactions are not included in blocks, but in the future, they will be, and the sequencer will be eligible to charge a fee for the work done up to the point of failure, similarly to Ethereum.

The sequencer charges only for successful transactions that result from the successful completion of the `execute` function.
