[id="validate_and_execute"]
= `&lowbar;&lowbar;validate&lowbar;&lowbar;` and `&lowbar;&lowbar;execute&lowbar;&lowbar;`

As previously stated, StarkNet's account structure is not completely arbitrary, but must include the following two functions, which account transactions call: 

* `&lowbar;&lowbar;validate&lowbar;&lowbar;`
* `&lowbar;&lowbar;execute&lowbar;&lowbar;`

Separating the `&lowbar;&lowbar;validate&lowbar;&lowbar;` and `&lowbar;&lowbar;execute&lowbar;&lowbar;` functions guarantees payment to sequencers for work completed and protects them from Denial of Service (DoS) attacks.

[id="the_validate_function"]
== The `&lowbar;&lowbar;validate&lowbar;&lowbar;` function

The `&lowbar;&lowbar;validate&lowbar;&lowbar;` function ensures that any transaction submitted was indeed initiated by the account owner and therefore will not take up unjustified resources during the execution process.

Without this mechanism, a forged transaction can result in the sequencer stealing the user's funds.
In short, `&lowbar;&lowbar;validate&lowbar;&lowbar;` ensures that the sequencer may only include transactions that were approved by the account owner.

The arbitrary logic allowed in the `&lowbar;&lowbar;validate&lowbar;&lowbar;` function gives the account's designer the ability to determine what it means to him for a transaction to be valid. This gives rise to the usage of different signature schemes and other xref:approach.adoc#examples[exotic accounts].

[id="invalid_transactions"]
== Invalid transactions

When the `&lowbar;&lowbar;validate&lowbar;&lowbar;` function fails, no fee will be taken from the account in question.

[id="the_execute_function"]
== The `&lowbar;&lowbar;execute&lowbar;&lowbar;` function

The purpose of the `&lowbar;&lowbar;execute&lowbar;&lowbar;` function is to abstract away the remaining actions performed by a transaction. 

In Ethereum, a transaction is a necessary call to a specific function in a smart contract. With the `&lowbar;&lowbar;execute&lowbar;&lowbar;` abstraction, the account designer controls the flow of the transaction. For example, multicalls can be natively supported in your account, saving the need to send multiple transactions (in practice, this is even harder to manage without multicalls due to nonces).

[id="reverted_transactions"]
== Reverted transactions

A transaction is considered reverted when the `&lowbar;&lowbar;execute&lowbar;&lowbar;` function failed. Today, reverted transactions are not included in blocks, but in the future, they will be and the sequencer will be eligible to charge a fee for the work done up to the point of failure, similar to Ethereum.

The sequencer charges only for successful transactions that result from the successful completion of the `&lowbar;&lowbar;execute&lowbar;&lowbar;` function.
