[id="hash_functions"]
= Hash functions
:stem: latexmath

[id="domain_and_range"]
== domain and range

All hashes outputs are eventually mapped to elements in stem:[$\mathbb{F}_p$] with stem:[$p=2^{251}+17\cdot 2^{192}+1$].

There are two hash functions used throughout Starknet's specifications:

* stem:[$sn\_keccak: \{0,1\}^* \rightarrow \mathbb{F}_p$]
* stem:[$pedersen: \mathbb{F}_p\times\mathbb{F}_p\rightarrow\mathbb{F}_p$]

[id="starknet_keccak"]
== Starknet Keccak

Starknet keccak, usually denoted by stem:[$sn\_keccak$], is defined as the first 250 bits of the Keccak256 hash (this is just Keccak256 augmented
in order to fit into a field element).

[id="pedersen_hash"]
== Pedersen hash

[id="stark_curve"]
=== STARK curve

Pedersen hash makes use of the following STARK friendly elliptic curve over stem:[$\mathbb{F}_p^2$]:

[stem]
++++
y^2=x^3+\alpha x +\beta
++++

where

* stem:[$\alpha=1$]
* stem:[$\beta = 3141592653589793238462643383279502884197169399375105820974944592307816406665$]

[id="definition"]
=== Definition

Given an input stem:[$(a,b)\in\mathbb{F}_p^2$], we begin by breaking it into stem:[$a_{low}, a_{high}, b_{low}, b_{high}$],
where the low part consists of the low 248 bits of the element and the high part consists of the high 4 bits of the element. Our Pedersen hash is then defined by:

[stem]
++++
h(a,b) = \left[shift\_point + a_{low} \cdot P_0 + a_{high} \cdot P1 + b_{low} \cdot P2  + b_{high} \cdot P3\right]_x
++++

where the values of the constants stem:[$shift\_point, P_0, P_1, P_2, P_3$] can be found in link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/crypto/signature/fast_pedersen_hash.py[fast_pedersen_hash.py^], and stem:[$[P\]_x$] denotes the stem:[$x$] coordinate of the point stem:[$P$].

[id="array_hashing"]
=== Array hashing

Let stem:[$h$] denote the pedersen hash function, then given an array stem:[$a_1,...,a_n$] of stem:[$n$] field elements
we define stem:[$h(a_1,...,a_n)$] to be:

[stem]
++++
h(...h(h(0, a_1),a_2),...,a_n),n)
++++
