[#declare-the-contract-on-the-starknet-testnet]
[id="declare-the-contract-on-the-starknet-testnet"]
== Declare the contract on the Starknet testnet

In order to instruct the CLI to work with the Starknet testnet you
should either pass `--network=alpha-goerli` on every use, or set the
`STARKNET_NETWORK` environment variable as follows:

[#starknet_env]
[source,bash]
----
export STARKNET_NETWORK=alpha-goerli
----

Unlike Ethereum, Starknet distinguishes between a contract class and a
contract instance. A contract class represents the code of a contract
(but with no state), while a contract instance represents a specific
instance of the class, with its own state.

Run the following command to declare your contract class on the Starknet
testnet:

[#starknet_declare]
[source,bash]
----
starknet declare --contract contract_compiled.json
----

The output should look like:

[#starknet_declare_output]
[source,bash]
----
Declare transaction was sent.
Contract class hash: 0x1e2208b571b2cb68908f37a196ed5e391c8933a6db23bb3939acedee40d9b8a
Transaction hash: 0x762e166dd3326b2e263eb5bcfdccd225dc88e067fdf7c92cf8ce5e4ea01f9f1
----

You can see here the class hash of your new contract. You’ll need this
class hash in order to deploy an instance of the contract using the
xref:deploying_from_contracts.adoc[deploy
system call].
