
[#deploy-the-contract-on-the-starknet-testnet]
== Deploy the contract on the Starknet testnet

🚧

[IMPORTANT]
====
The alpha release is an experimental release. Newer
versions may require a reset of the network’s state (resulting in the
removal of the deployed contracts).
====

Run the following command to deploy your contract on the Starknet
testnet (replace `$CLASS_HASH` with the class hash you got from
`starknet declare`):

[#starknet_deploy]
[source,bash]
----
starknet deploy --class_hash $CLASS_HASH
----

The output should look like:

[#starknet_deploy_output]
[source,bash]
----
Invoke transaction for contract deployment was sent.
Contract address: 0x039564c4f6d9f45a963a6dc8cf32737f0d51a08e446304626173fd838bd70e1c
Transaction hash: 0x125e4bc5251af8ee2664ea0d1495b36c593f25f78f1a78f637a3f7aafa9e22
----

You can see here the address of your new contract. You’ll need this
address to interact with the contract.

Set the following environment variable:

[#intro_contract_address]
[source,bash]
----
# The deployment address of the previous contract.
export CONTRACT_ADDRESS="<address of the previous contract>"
----

[#interact-with-the-contract]
== Interact with the contract

Run the following command to invoke the `increase_balance()`:

[#starknet_invoke]
[source,bash]
----
starknet invoke \
    --address ${CONTRACT_ADDRESS} \
    --abi contract_abi.json \
    --function increase_balance \
    --inputs 1234
----

The result should look like:

[#starknet_invoke_output]
[source,bash]
----
Invoke transaction was sent.
Contract address: 0x039564c4f6d9f45a963a6dc8cf32737f0d51a08e446304626173fd838bd70e1c
Transaction hash: 0x69d743891f69d758928e163eff1e3d7256752f549f134974d4aa8d26d5d7da8
----

[NOTE]
====
Due to the use of fees in Starknet, every interaction with a
contract through a function invocation must be done using an account. To
set up an account, see
xref:account_setup.adoc[Setting up a
Starknet account].
====

The following command allows you to query the transaction status based
on the transaction hash that you got (here you’ll have to replace
`TRANSACTION_HASH` with the transaction hash printed by
`starknet invoke`):

[#tx-status]
[#starknet_tx_status]
[source,bash]
----
starknet tx_status --hash TRANSACTION_HASH
----

The result should look like:

[#starknet_tx_status_output]
[source,json]
----
{
    "block_hash": "0x0",
    "tx_status": "ACCEPTED_ON_L2"
}
----

The possible statuses are:

* `NOT_RECEIVED`: The transaction has not been received yet (i.e., not
written to storage).
* `RECEIVED`: The transaction was received by the sequencer.
* `PENDING`: The transaction passed the validation and entered the
pending block.
* `REJECTED`: The transaction failed validation and thus was skipped.
* `ACCEPTED_ON_L2`: The transaction passed the validation and entered
an actual created block.
* `ACCEPTED_ON_L1`: The transaction was accepted on-chain.

[#query-the-balance]
== Query the balance

Use the following command to query the current balance:
[#starknet_call]
[source,bash]
----
starknet call \
    --address ${CONTRACT_ADDRESS} \
    --abi contract_abi.json \
    --function get_balance
----

The result should be:

[#starknet_call_output]
[source,bash]
----
1234
----

[NOTE]
====
To see the up-to-date balance you should wait until the
`increase_balance` transaction status is at least `ACCEPTED_ON_L2`
(that is, `ACCEPTED_ON_L2` or `ACCEPTED_ON_L1`). Otherwise, you’ll
see the balance before the execution of the `increase_balance`
transaction (that is, 0).
====

In the next section we will describe other CLI functions for querying
Starknet’s state. Note that while `deploy` and `invoke` affect
Starknet’s state, all other functions are read-only. In particular,
using `call` instead of `invoke` on a function that may change the
state, such as `increase_balance`, will return the result of the
function without actually applying it to the current state, allowing the
user to dry-run before committing to a state update.

