[id="block_structure"]
= Block structure

A Starknet block is a list of transactions and a block header that contains the following fields:

[%autowidth]
|===
| Name | Type | Description

|`block_number` | `u64` | The number of this block (i.e., its height)

| `parent_block_hash` | `felt252` | The xref:#block_hash[hash of the block's parent]

| `global_state_root` | `felt252` | A xref:../network-architecture/starknet-state.adoc#state_commitment[commitment to the new state]

|`sequencer_address` | `ContractAddress` | The Starknet address of the sequencer that created the block

| `block_timestamp` | `Timestamp` | The time at which the sequencer began building the block, in seconds since the Unix epoch

|`transaction_count` | `u32` | The number of transactions in the block

|`events_count` | `u32` | The number of events in the block.

|`state_diff_length`| `u32` | The total amount of storage diffs, nonce updates, deployed contracts, and declared classes

|`state_diff_commitment`| `felt252` | A xref:#state_diff_hash[commitment to the state diff of the block]

| `transactions_commitment` | `felt252` | A xref:#transactions_events_receipts_commitments[commitment to the transactions included in the block]

| `events_commitment` | `felt252` | A xref:#transactions_events_receipts_commitments[commitment to the events included in the block]

| `receipts_commitment`| `felt252` | A xref:#transactions_events_receipts_commitments[commitment to the recepits of the transactions included in the block]

| `l1_gas_price` | `(u128, u128)` | The price of L1 gas that was used while constructing the block, where the first value is the price in wei and the second is the price in fri (see xref:./fee-mechanism.adoc[] for more details)

| `l1_data_gas_price` | `(u128, u128)` | The price of L1 blob gas that was used while constructing the block, where the first value is the price in wei and the second is the price in fri (see xref:./fee-mechanism.adoc[] for more details)

| `l1_da_mode` | `String` | `CALLDATA` or `BLOB`, depending on how Starknet state diffs are sent to L1

| `protocol_version` | `String` | The version of the Starknet protocol used when creating the block

|===

[#block_hash]
== Block hash

A block hash is defined by:

[,,subs="quotes"]
----
h(
    "STARKNET_BLOCK_HASH0",
    block_number,
    global_state_root,
    sequencer_address,
    block_timestamp,
    transaction_count || event_count || state_diff_length || l1_da_mode,
    state_diff_commitment,
    transactions_commitment
    events_commitment,
    l1_gas_price_in_wei,
    l1_gas_price_in_fri,
    l1_data_gas_price_in_wei,
    l1_data_gas_price_in_fri
    receipts_commitment
    0,
    parent_block_hash
)
----

Where:

- `h` is the xref:../../cryptography/hash-functions.adoc#poseidon-hash[Poseidon hash function]
- `transaction_count || event_count || state_diff_length || l1_da_mode` is the concatenation of the 64-bit representations of `transaction_count`, `event_count`, and `state_diff_length` with 0 if `l1_da_mode` is `CALLDATA` and 1 if `l1_da_mode` is `BLOB`

[TIP]
====
For a reference implementation, see link:https://github.com/starkware-libs/sequencer/blob/bb361ec67396660d5468fd088171913e11482708/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L68[ `block_hash_calculator.rs`] in the Starknet sequencer's GitHub repository
====

[#state_diff_hash]
== State diff commitment

The state diff commitment is defined by:

[,,subs="quotes"]
----
h(
    "STARKNET_STATE_DIFF0",
    s + r,
    deployed_address~1~, deployed_class_hash~1~, ... , deployed_address~s~, deployed_class_hash~s~,
    replaced_contract_address~1~, new_class_hash~1~, ... , replaced_contract_address~r~, new_class_hash~r~,
    d,
    declared_class_hash~1~, declared_compiled_class_hash~1~, ... , declared_class_hash~d~, declared_compiled_class_hash~d~,
    1,
    0,
    n,
    c~1~, k~1,1~, v~1,1~, ... ,k~1,m^1^~, v~1,m^1^~, ... ,c~n~, k~n,1~, v~n,1~, ... ,k~n,m^n^~, v~n,m^n^~,
    k,
    account~1~, new_nonce~1~, ... ,account~k~, new_nonce~k~
)
----

Where:

- `h` is the  Poseidon hash function
- `1` and `0` are placeholders that may be used in the future
- `c~i~,k~i,1~, v~i,1~, ... , k~i,m^i^~,v~i,m^i^~` are `m^i^` updates `(k~i,1~, v~i,1~), ... ,(k~i,m^i^~, v~i,m^i^~)` to contract addresses `c~i~`

[#transactions_events_receipts_commitments]
== Transactions, events, and receipts commitments
The commitment to transactions, the commitment to events and the commitment to receipts are all roots of height-64 binary Merkle Patricia tries where the leaf at index `i` corresponds to:

* For transactions: `h(transaction_hash, signature)` for the ``i``'th transaction included in the block, where `h` is the xref:../../cryptography/hash-functions.adoc#poseidon-hash[Poseidon hash function]
* For events: The xref:#event_hash[event hash] of the ``i``'th emitted evet included in the block
* For receipts: The xref:#receipt_hash[receipt hash] of the ``i``'th transaction receipt included in the block

[#event_hash]
=== Event hash

The hash of an xref:../smart-contracts/starknet-events.adoc[event] emitted by a contract whose address is `emitter_address` and a transaction whose hash is `tx_hash` is defined by:

[,,subs="quotes"]
----
h(
    emitter_address,
    tx_hash,
    h(keys),
    h(data)
)
----

Where `h` is the xref:../../cryptography/hash-functions.adoc#poseidon-hash[Poseidon hash function].

[#receipt_hash]
=== Receipt hash

The hash of a xref:./transaction-life-cycle.adoc#transaction-receipt[transaction receipt] is defined by:

[,,subs="quotes"]
----
h(
    transaction_hash,
    actual_fee,
    h(messages),
    sn_keccak(revert_reason),
    h(l2_gas_consumed, l1_gas_consumed, l1_data_gas_consumed)
)
----

Where:

- `h` is the xref:../../cryptography/hash-functions.adoc#poseidon-hash[Poseidon hash function]
- `h(messages)` for `messages = (from~1~, to~1~, payload~1~), ... , (from~n~, to~n~, payload~n~)` where each payload is length-prefixed is defined by:

[,,subs="quotes"]
----
h(
    n,
    from~1~, to~1~, h(payload~1~), ... , from~n~, to~n~, h(payload~n~)
)
----