[id="data_availability"]
= Data availability

[id="introduction"]
== Introduction

Starknet is a Validity Rollup, which means that after consolidating and proving a set of changes to Starknet's state, it updates the latest proven state on Ethereum. Alongside the proof, it sends the difference between the previous and new states, also known as _state diff_, allowing anyone monitoring Ethereum to use this data and reconstruct Starknet's current state.

== State diff format

=== Pre-v0.11.0

Before Starknet version 0.11.0, the state diffs contained information on every contract whose storage was updated, along with additional information on contract deployments. Those differences were sent as part of the calldata of the transaction that registered the proof on Ethereum, in a `uint256[]` array that included:

* The number of contracts that were deployed 
* The address and class hash of each deployed contract
* The number of contracts whose storage was updated
* For each contract whose storage was updated:
** Its address 
** A `uint256` value that encodes both the number of its storage updates and its updated nonce, defined as follows:
+
[stem]
++++
\underbrace{0\cdots0}_{\text{128 bits}} | \underbrace{\text{new nonce}}_{\text{64 bits}} |
{\underbrace{\text{# of storage updates}}_{\text{64 bits}}}_{\text{LSB}}
++++
+
** The key and new value for each storage update

See xref:#pre_v0_11_0_example[] to review an example of this format.

=== Changes in v0.11.0

In Starknet version 0.11.0, the state diffs changed to contain information on every contract whose storage was updated and additional information on contract deployments. This information was still sent as part of the calldata of the transaction that registered the proof on Ethereum, in a `uint256[]` array that included:

* The number of contracts whose storage was updated 
* For contract whose storage was updated:
** Its contract address
** A single 32-byte word that includes its updated nonce and meta information about the storage updates, defined as follows:
+
[stem]
++++
\underbrace{0\cdots0}_{\text{127 bits}}|
\underbrace{\text{class information flag}}_{\text{1 bit}}|
\underbrace{\text{new nonce}}_{\text{64 bits}}|{
\underbrace{\text{# of storage updates}}_{\text{64 bits}}}_{\text{LSB}}
++++
+
where the class information flag's value is `1` if the contract was deployed or replaced and `0` otherwise (i.e., there were only storage updates). When set to `1`, the new class hash occupies the next entry in the array
** The key and new value for each storage update
* The number of classes that were declared
* The class hash and compiled class hash of each declared class

See xref:#post_v0_11_0_example[] to review an example of this format.

=== Change in v0.13.1

In Starknet version 0.13.1, sending the state diffs to Ethereum changed from using calldata to using either calldata or blobs. Under normal conditions, using blobs is default method, but in extreme situations where blob prices significantly exceed those of calldata, the Starknet sequencer can switch to use calldata instead.

[TIP]
====
See https://community.starknet.io/t/data-availability-with-eip4844/[Data availability with EIP-4844^] on the Starknet Community Forum or review https://etherscan.io/tx/0x8a227491bc78424c2cac1b203c95cdd99ede5112d41f0e7eab26f3c8aa9c658d/[an example blob published on Ethereum by the Starknet sequencer^] for more details.
====

The format for state diffs remains the same as in version 0.11.0, but the data sent to Ethereum changed to a Fast Fourier Transform (FFT) of the original data. To recover Starknet's state diff based on blobs or calldata published onchain, an Inverse Fast Fourier Transform (IFFT) on the data must first be performed, afterwhich decoding can procede as usual.

=== Changes in v0.13.3

#WIP#

=== Examples

====  Pre v0.11.0 example

[source,json]
----
[
  2, <1>
  2472939307328371039455977650994226407024607754063562993856224077254594995194, <2>
  1336043477925910602175429627555369551262229712266217887481529642650907574765, <3>
  1, <4>
  2019172390095051323869047481075102003731246132997057518965927979101413600827, <5>
  18446744073709551617, <6>
  5, <7>
  102, <8>
]
----

<1> The number of deployed contracts
<2> The address of the first, and only, contract whose state changed
<3> The class hash of the first, and only, contract whose state changed
<4> The number of contracts whose storage was updated
<5> The address of the first, and only, contract whose storage was updated
<6> The `uint256` value that encodes the number of storage updates and updated nonce of the first, and only, contract whose storage was updated, which equals stem:[$2^{64}+1 = 0^{128}|0^{63}1|0^{63}1$] and therefore:
* One storage cell was updated
* The updated nonce is `1`
<7> The key of the first, and only, storage update of the first, and only, contract whose storage was updated
<8> The new value of the first, and only, storage update of the first, and only, contract whose storage was updated

==== Post v0.11.0 example

[source,json]
----
[
  1, <1>
  2019172390095051323869047481075102003731246132997057518965927979101413600827, <2>
  18446744073709551617, <3>
  100, <4>
  200, <5>
  1, <6>
  1351148242645005540004162531550805076995747746087542030095186557536641755046, <7>
  558404273560404778508455254030458021013656352466216690688595011803280448032 <8>
]
----
<1> The number of contracts whose storage was updated
<2> The address of the first, and only, contract whose storage changed
<3> The 32-byte word that encodes the updated nonce and meta information about the storage updates of the first, and only, contract whose storage was updated, which equals stem:[$2^{64}+1 = 0^{127}|0|0^{63}1|0^{63}1$] and therefore:
* One storage cell was update
* The new nonce is `1`
* The class information flag is `0`, which means that the contract was not deployed or replaced and therefore the next word shouldn't be treated as the class hash
<4> The key of the first, and only, storage update of the first, and only, contract whose storage was updated
<5> The new value of the first, and only, storage update of the first, and only, contract whose storage was updated 
These two elements, `100` and `200`, encode the storage update, where the value of key `100` is set to `200`.
<6> The number of classes that were declared
<7> The class hash of the first, and only, declared class
<8> The compiled class hash of the first, and only, declared class

== Data extraction

The data described above is sent across several Ethereum transactions, each holding a part of this array as calldata. Both https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs[Rust^] and https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/resources/fact_retrieval.py[Python] versions of the code for extracting this data from Ethereum can be found in Pathfinder's (the first Starknet full node implementation) codebase.
