[id="contract_hash"]
= Class hash
:stem: latexmath

The class hash is a hash chain of the definition of the class.

[id="cairo1_class"]
== Definition of a (Cairo 1) class

Classes that were written in Cairo 1 are defined by their Sierra code (
resulting from the compilation of the Cairo code into Sierra, see xref:../Cairo_on_Starknet/cairo-1-and-sierra.adoc[here] for more details).

The elements that define a class are:

[horizontal,labelwidth=35]
contract_class_version:: The version of the contract class object. Currently, the Starknet OS
supports version 0.1.0
Array of external functions entry points:: An entry point is a pair `(_selector_, _function_idx_)`, where `_function_idx_` is the index of the function inside the Sierra program.
+
[NOTE]
====
The selector is an identifier through which the function is callable in transactions or in other classes. The selector is the xref:../Hashing/hash-functions.adoc#starknet_keccak[starknet_keccak] hash of the function name, encoded in ASCII.
====
Array of xref:documentation:architecture_and_concepts:L1-L2_Communication/messaging-mechanism.adoc#l1-l2_message_fees[L1 handlers] entry points :: -
Array of constructors entry points:: Currently, the compiler allows only one constructor.
ABI:: A string representing the ABI of the class. The ABI hash (which affects the class hash) is given by:
+
[source,python]
----
starknet_keccak(bytes(ABI, "UTF-8"))
----
+
[NOTE]
====
This string is supplied by the user declaring the class (and is signed on as part of the `DECLARE` transaction), and is not enforced to be the true ABI of the associated class.
Without seeing the underlying source code (i.e. the Cairo code generating the class's Sierra), this ABI should be treated as the "intended" ABI by the declaring party, which may be incorrect (intentionally or otherwise).
The "honest" string would be the json serialization of the contract's ABI as produced by the Cairo 1 compiler.
====
Sierra program:: An array of field elements representing the Sierra instructions.

=== Computing the (Cairo 1) class hash

The hash of the class is the chain hash of its components, computed as follows:

[stem]
++++
\begin{aligned}
\text{class_hash} = h( & \text{contract_class_version}, \\& \text{external_entry_points}, \\&
\text{l1_handler_entry_points}, \\& \text{constructor_entry_points}, \\ & \text{abi_hash}, \\&\text{sierra_program_hash})
\end{aligned}
++++

Where

* stem:[$h$] is the xref:../Hashing/hash-functions.adoc#poseidon_hash[Poseidon] hash function
* The hash of an entry point array stem:[$(selector,index)_{i=1}^n$] is given by stem:[$h(\text{selector}_1,\text{index}_1,...,\text{selector}_n,\text{index}_n)$]
* The `sierra_program_hash` is the xref:../Hashing/hash-functions.adoc#poseidon_hash[Poseidon] hash of the bytecode array

[NOTE]
====
The Starknet OS currently supports contract class version 0.1.0, which is represented in the above hash computation as the ASCII encoding of the string `CONTRACT_CLASS_V0.1.0` (hashing the version in this manner gives us domain separation between
the hashes of classes and other objects).
====

For more details, see the https://github.com/starkware-libs/cairo-lang/blob/7712b21fc3b1cb02321a58d0c0579f5370147a8b/src/starkware/starknet/core/os/contracts.cairo#L47[Cairo implementation].

== Definition of a (Cairo 0) class

[IMPORTANT]
====
Cairo 0 classes are deprecated, and will no longer be supported after regenesis.
====

The elements that define a class are:

[horizontal,labelwidth=35]
API version:: The version of the class, currently always 0.
Array of external functions entry points:: An entry point is a pair `(_selector_, _offset_)`, where `_offset_` is the offset of the instruction that should be called inside the class's bytecode.
+
[NOTE]
====
The selector is an identifier through which the function is callable in transactions or in other classes. The selector is the xref:../Hashing/hash-functions.adoc#starknet_keccak[starknet_keccak] hash of the function name, encoded in ASCII.
====
Array of xref:documentation:architecture_and_concepts:L1-L2_Communication/messaging-mechanism.adoc#l1-l2_messages[L1 handlers] entry points :: -
Array of constructors entry points:: Currently, the compiler allows only one constructor.
Array of used builtin names:: An ASCII-encode array, ordered by declaration.
Program hash:: The xref:../Hashing/hash-functions.adoc#starknet_keccak[starknet_keccak] of the class's program. The class's program is the abi and program part of the `.json` file that the Starknet compiler outputs when you run the following command:
+
[source,shell]
----
$ starknet-compile --no_debug_info
----
+
The compiler outputs the abi, entrypoint selectors, and program. For the program hash, only the `starknet_keccak` of the abi and program needs to be calculated. To see the exact computation of this field, see https://github.com/starkware-libs/cairo-lang/blob/7712b21fc3b1cb02321a58d0c0579f5370147a8b/src/starkware/starknet/core/os/contract_hash.py#L116[contract_hash.py^].
Bytecode:: Represented by an array of field elements.

=== Computing the (Cairo 0) class hash

The hash of the class is the chain hash of its components, computed as follows:

[stem]
++++
\begin{aligned}
\text{class_hash} = h( & \text{api_version}, \\& \text{external_entry_points}, \\&
\text{l1_handler_entry_points}, \\& \text{constructor_entry_points}, \\ & \text{builtin_names}, \\& \text{program_hash}, \\& \text{bytecode_hash})
\end{aligned}
++++

Where

* stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen_hash[Pedersen] hash function
* The hash of an entry point array stem:[$(\text{selector},\text{offset})_{i=1}^n$] is given by stem:[$h(\text{selector}_1,\text{offset}_1,...,\text{selector}_n,\text{offset}_n)$]
* The `program_hash` is the `starknet_keccak` of the json described above
* The `bytecode_hash` is the xref:../Hashing/hash-functions.adoc#pedersen_hash[Pedersen] hash of the bytecode array
