= System Calls

Writing smart contracts requires some operations, such as calling another contract or accessing the contract’s storage, that standalone programs do not require. The Starknet contract language supports these operations by using system calls. System calls enable a contract to require services from the Starknet OS. You can use system calls in a function to get information that depends on the broader state of Starknet, which would otherwise be inaccessible, rather than local variables that appear in the function’s scope.

[id="getters"]
== getters

Below we describe the collection of system calls that can be used to get information regarding the block, transaction, or execution context during runtime (e.g. block number, account address, and caller address).

[id="get_block_number"]
=== `get_block_number`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func get_block_number{syscall_ptr : felt*}() -> (__block_number__ : felt)
----

[discrete]
==== Description

Gets the number of the block in which the transaction is executed.

[discrete]
==== Arguments

None.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_block_number_`:: The number of the block in which the transaction is executed.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/common/syscalls.cairo#L161[`syscalls.cairo`^]


[id="get_block_timestamp"]
=== `get_block_timestamp`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func get_block_timestamp{syscall_ptr : felt*}() -> (__block_timestamp__ : felt)
----

[discrete]
==== Description

Gets the timestamp of the block in which the transaction is executed.

[discrete]
==== Arguments

None.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_block_timestamp_`:: The timestamp of the block in which the transaction is executed.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/common/syscalls.cairo#L210[`syscalls.cairo`^]


[id="get_caller_address"]
=== `get_caller_address`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func get_caller_address{syscall_ptr : felt*}() -> (__caller_address__ : felt)
----

[discrete]
==== Description

Returns the address of the calling contract, or 0 if the call was not initiated by another contract.

[discrete]
==== Arguments

None.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`__caller_address__`:: The address of the calling contract, or 0 if the call was not initiated by another contract.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/common/syscalls.cairo#L200[`syscalls.cairo`^]


[id="get_contract_address"]
=== `get_contract_address`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func get_contract_address{syscall_ptr : felt*}() -> (__contract_address__ : felt)
----

[discrete]
==== Description

Gets the address of the contract who raised the system call.

[discrete]
==== Arguments

None.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_contract_address_`:: The address of the contract that raised the system call.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/common/syscalls.cairo#L186[`syscalls.cairo`^]


[id="get_sequencer_address"]
=== `get_sequencer_address`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func get_sequencer_address{syscall_ptr : felt*}() -> (__sequencer_address__ : felt)
----

[discrete]
==== Description

Returns the address of the sequencer that generated the current block.

[discrete]
==== Arguments

None.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_sequencer_address_`:: The address of the sequencer that generated the current block.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/common/syscalls.cairo#L138[`syscalls.cairo`^]


[id="get_transaction_info"]
=== `get_transaction_info`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func get_tx_info{syscall_ptr : felt*}() -> (__tx_info__ : TxInfo*)
----

[discrete]
==== Description

Gets information about the original transaction.

[discrete]
==== Arguments

None.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_tx_info_`:: The following information about the original transaction:
+
* The version of the transaction.
* The address of the account that initiated this transaction.
* The maximum fee that is allowed to be charged for the inclusion of this transaction.
* The signature of the account that initiated this transaction.
* The transaction's hash.
* The intended chain id.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/common/syscalls.cairo#L351[`syscalls.cairo`^]


[id="call_contract"]
== `call_contract`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func call_contract{syscall_ptr : felt*}(
    __contract_address__ : felt, __function_selector__ : felt, __calldata_size__ : felt, __calldata__ : felt*
) -> (__retdata_size__ : felt, __retdata__ : felt*)
----

[discrete]
==== Description

Calls a given contract. This system call expects the address of the called contract, a selector for a function within that contract, and call arguments.

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_contract_address_`:: The address of the contract you want to call.
`_function_selector_`:: A selector for a function within that contract.
`_calldata_size_`:: The size, in number of felts, of the calldata.
`_calldata_`:: The calldata.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_retdata_size_`:: The size, in number of felts, of the return data.
`_retdata_`:: The return data.


[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/common/syscalls.cairo#L42[`syscalls.cairo`^]

[NOTE]
====
This is considered a lower-level syntax for calling contracts.

If the interface of the called contract is available, then you can use a more straightforward syntax.
====


[id="deploy"]
== `deploy`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func deploy{syscall_ptr : felt*}(
    __class_hash__ : felt,
    __contract_address_salt__ : felt,
    __constructor_calldata_size__ : felt,
    __constructor_calldata__ : felt*,
    __deploy_from_zero__: felt,
) -> (__contract_address__ : felt)
----

[discrete]
==== Description

Deploys a new instance of a previously declared class.

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_class_hash_`:: The class hash of the contract to be deployed.
`_contract_address_salt_`:: The salt, an arbitrary value provided by the sender, used in the computation of the xref:Contracts/contract-address.adoc[contract's address].
`_constructor_calldata_size_`:: The number of arguments to pass to the constructor, equal to the number of felts in `_constructor_calldata_`.
`_constructor_calldata_`:: The constructor's calldata. An array of felts.
`__deploy_from_zero__`:: A flag used for the contract address computation. If set, the new contract's deployer address will be `0`. Otherwise, the caller's address will be used.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_contract_address_`:: The address of the deployed contract.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/common/syscalls.cairo#L157[`syscalls.cairo`^]


[id="emit_event"]
== `emit_event`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func emit_event{syscall_ptr : felt*}(__keys_len__ : felt, __keys__ : felt*, __data_len__ : felt, __data__ : felt*)
----

[discrete]
==== Description

Emits an event with a given set of keys and data.

For more information, and for a higher-level syntax for emitting events, see xref:Events/starknet-events.adoc[Starknet events].

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_keys_len_`:: The number of keys in the event. Analogous to Ethereum's event topics, you can use the link:https://github.com/starkware-libs/starknet-specs/blob/c270b8170684bb09741672a7a4ae5003670c3f43/api/starknet_api_openrpc.json#L569RPC[starknet_getEvents] method to filter by these keys.
`_keys_`:: The event's keys.
`_data_len_`:: The number of data elements in the event.
`_data_`:: The event's data.

[discrete]
==== Return values

None.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/common/syscalls.cairo#L301[`syscalls.cairo`^]

[discrete]
==== Example

The following example emits an event with two keys, the https://www.cairo-lang.org/docs/how_cairo_works/consts.html#short-string-literals[strings] `status` and `deposit` and three data elements: `1`, `2`, and `3`.

[source,cairo]
----
let (keys : felt*) = alloc()
assert keys[0] = 'status'
assert keys[1] = 'deposit'
let (data : felt*) = alloc()
assert data[0] = 1
assert data[1] = 2
assert data[2] = 3
emit_event(2, keys, 3, data)
----


[id="library_call"]
== `library_call`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func library_call{syscall_ptr : felt*}(
    __class_hash__ : felt, __function_selector__ : felt, __calldata_size__ : felt, __calldata__ : felt*
) -> (__retdata_size__ : felt, __retdata__ : felt*)
----

[discrete]
==== Description

Calls the requested function in any previously declared class. The class is only used for its logic.

This system call replaces the known delegate call functionality from Ethereum, with the important difference that there is only one contract involved.

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_class_hash_`:: The hash of the class you want to use.
`_function_selector_`:: A selector for a function within that class.
`_calldata_size_`:: The size, in number of felts, of the calldata.
`_calldata_`:: The calldata.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_retdata_size_`:: The size, in number of felts, of the return data.
`_retdata_`:: The return data.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/common/syscalls.cairo#L85[`syscalls.cairo`^]


[id="library_call_l1_handler"]
== `library_call_l1_handler`

[WARNING]
====
This system call is not currently not supported in Cairo 1.0.
In practice, this was only used for proxy contracts, which in Cairo 1.0 can be implemented instead via the `replace_class` system call, making `library_call_l1_handler` redundant.
====

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func library_call_l1_handler{syscall_ptr : felt*}(
    __class_hash__ : felt, __function_selector__ : felt, __calldata_size__ : felt, __calldata__ : felt*
) -> (__retdata_size__ : felt, __retdata__ : felt*)
----

[discrete]
==== Description

Calls the requested L1 handler in any previously declared class.

Same as the `library_call` system call, but also enables you to call an L1 handler that cannot otherwise be called directly. For more information, see Starknet's xref:L1-L2_Communication/messaging-mechanism.adoc#l1-l2_messages[messaging mechanism] (note that when you invoke an L1 handler with this system call, the sequencer does not consume an L1->L2 message).

[TIP]
====
It is recommended to raise this system call only inside an L1 handler in order to use the logic inside an L1 handler of a different class.
====

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_class_hash_`:: The hash of the class you want to use.
`_function_selector_`:: A selector for an L1 handler function within that class.
`_calldata_size_`:: The size, in number of felts, of the calldata.
`_calldata_`:: The calldata.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_retdata_size_`:: The size, in number of felts, of the return data.
`_retdata_`:: The return data.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/common/syscalls.cairo#L107[`syscalls.cairo`^]


[id="send_message_to_L1"]
== `send_message_to_L1`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func send_message_to_l1{syscall_ptr : felt*}(
    __to_address__ : felt, __payload_size__ : felt, __payload__ : felt*
)
----

[discrete]
==== Description

Sends a message to L1.

This system call includes the message parameters as part of the proof's output and exposes these parameters to the Starknet Core contract on L1 once the state update, including the transaction, is received.

For more information, see Starknet's xref:L1-L2_Communication/messaging-mechanism.adoc[messaging mechanism].

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_to_address_`:: The recipient's L1 address.
`_payload_size_`:: The size of the message payload.
`_payload_`:: A pointer to an array containing the contents of the message.

[discrete]
==== Return values

None.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/common/messages.cairo[`messages.cairo`^]

[discrete]
==== Example

The following example sends a message whose content is `(1,2)` to the L1 contract whose address is `3423542542364363`.

[source,cairo,subs="+quotes,+macros"]
----
let payload = alloc()
payload[0] = 1
payload[1] = 2
send_message_to_l1(3423542542364363,2,payload)
----


[id="replace_class"]
== `replace_class`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
replace_class(class_hash: felt)
----

[discrete]
==== Description
Once `replace_class` is called, the class of the calling contract (i.e. the contract whose address is returned by `get_contract_address` at the time the syscall is called) will be replaced
by the class whose hash is given by the class_hash argument.

[NOTE]
====
After calling `replace_class`, the code currently executing from the old class will finish running.


The new class will be used from the next transaction onwards or if the contract is called via
the call_contract syscall in the same transaction (after the replacement).
====

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_class_hash_`:: The hash of the class you want to use as a replacement.

[discrete]
==== Return values

None.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/common/syscalls.cairo#L463[`syscalls.cairo`^]

[id="storage_read"]
== `storage_read`

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func storage_read{syscall_ptr : felt*}(__address__ : felt) -> (__value__ : felt)
----

[discrete]
==== Description

Gets the value of a key in the storage of the calling contract.

This system call provides direct access to any possible key in storage, in contrast with `var.read()`, which enables you to read storage variables that are defined explicitly in the contract.

For information on accessing storage by using the storage variables, see xref:./contract-storage.adoc#storage_variables[storage variables].

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_address_`:: The address of the storage key you want to read.

[discrete]
==== Return values

[horizontal,labelwidth=35]
`_value_`:: The value of the key.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/common/syscalls.cairo#L264[`syscalls.cairo`^]

[discrete]
==== Example

[source,cairo,subs="+quotes,+macros"]
----
let value = storage_read(3534535754756246375475423547453)
----

[id="storage_write"]
== `storage_write`

Sets the value of a key in the storage of the calling contract.

[discrete]
==== Syntax

[source,cairo,subs="+quotes,+macros"]
----
func storage_write{syscall_ptr : felt*}(__address__ : felt, __value__ : felt)
----

[discrete]
==== Description

Sets the value of a key in the storage of the calling contract.

This system call provides direct access to any possible key in storage, in contrast with `var.write()`, which enables you to write to storage variables that are defined explicitly in the contract.

For information on accessing storage by using the storage variables, see xref:./contract-storage.adoc#storage_variables[storage variables].

[discrete]
==== Arguments

[horizontal,labelwidth=35]
`_address_`:: The address of the storage key to which you want to write.
`_value_`:: The value to write to the key.

[discrete]
==== Return values

None.

[discrete]
==== Common library

link:https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/common/syscalls.cairo#L282[`syscalls.cairo`^]

