[id="starknets_approach_to_account_management"]
= Starknet's Approach to Account Management

Starknet has its own account smart contract that all new account contracts should build upon. The StarkNet account contract combined with the underlying operating system provides three important features that create a basic account structure:

* `validate` and `execute` functions
* A Nonce
* A Payment Mechanism

[id="validate_and_execute_functions"]
== `validate` and `execute` Functions

Starknet's account contract has two important functions that provide you with an interface:

* `validate`
* `execute`

These serve distinct purposes to ensure honest behavior and to provide a mechanism for sequencers to charge fair fees for the resources they use. 

[id="a_nonce_for_uniqueness"]
== A nonce for uniqueness

The Starknet OS enforces transaction uniqueness via a nonce. A nonce is a notion in programming that refers to an integer that is unique within the system.

Within StarkNet the nonce provides an important mechanism for protecting against a replay attack. 

Without enforcement of a nonce for each transaction, an attacker could steal funds or carry out a Denial of Service (DoS) attack.

The transaction uniqueness that results from the use of a nonce means that a sequencer will never include the same transaction twice. 

[id="a_payment_mechanism"]
== A payment mechanism

The underlying Starknet OS run by the sequencer offers a payment mechanism for moving funds and charging fees. 

The sequencer receives fees in ETH in return for including transactions in a block.