[id="starknets_approach_to_account_management"]
= Starknet's Approach to Account Management

Starknet has its own account smart contract that all new account contracts should extend from. This contract combined with the underlying operating system provides three important features that create a basic account framework from which you can extend:

* Validate and execute functions
* A Nonce
* A Payment Mechanism

[id="validate_and_execute_functions"]
== Validate and Execute Functions

Starknet's account contract has two important functions that provide you with an interface to extend from:

* validate
* execute

These serve distinct purposes to ensure honest behavior and to provide a mechanism for sequencers to fairly charge fees relative to the resources they use. 

[id="a_nonce_for_uniqueness"]
== A Nonce For Uniqueness

The Starknet OS enforces transaction uniqueness via a nonce. A nonce is a notion in programming that refers to an integer that is unique within the system.

[id="a_payment_mechanism"]
== A Payment Mechanism

The underlying Starknet OS run by the sequencer offers a payment mechanism for moving funds and charging fees. This is deliberately abstracted from the account contract itself to avoid some of the risks to the sequencer executing the transactions.  

Fees are paid to the sequencer in ETH for executing system state changes.