[id="account_abstraction"]
= Introduction to Account Abstraction
Account abstraction moves user account implementation away from the protocol layer and into a smart contract.

Using account abstraction you can now program how an account functions. 

Account abstraction is a significant departure from how accounts are historically implemented on blockchains where they are implemented at a protocol level. This allows for a much higher level of flexibility and extensibility. 

Some examples are:
* Social recovery
* Signature abstraction

Social recovery is a process where if you lose your wallet, you are able to retrieve it via a selected social network, vastly improving the typical experience of wallet recovery.

Signature abstraction allows you to choose the validation scheme per account contract, for example adding secure enclave support for a smartphone.

[id="what_is_an_account"]
== What is an Account?

Broadly speaking, an account is the mechanism by which you manage account balances and account state on the blockchain. 

An account is required in order to exchange value between parties and is a fundamental part of any state based system. 

[id="ethereum_account_structure"]
== Ethereum Account Structure

Within Ethereum, individual user accounts are known as Externally Owned Accounts (EOAs), an implementation where you are directly responsible for the storage of your own private keys. 

EOAs have no direct ability to run code or store application data and can only do so indirectly by invoking smart contracts. 

Although this is theoretically a secure method of account management, in practice it has some drawbacks such as having a large emphasis on seed phrase security and limited flexibility surrounding wallet functionality.  

EIP 4337, a governance proposal for Ethereum outlines account abstraction whereby all accounts are managed via a dedicated Smart Contract on the Ethereum network. This is in the interest of increased flexibility and usability. It allows you to add custom logic on top of the basic account functionality provided. 

[id="starknet_account_structure"]
== StarkNet Account Structure

Starknet's account type is inspired by the approach described in EIP-4337, where instead of EOAs, the account type uses smart contracts and is almost entirely implementation-agnostic. 

Through the use of smart contracts, you are provided with complete flexibility in regard to how your accounts are implemented, opening up a many possibilities for bespoke account functionality.

This method of account implementation is more broadly known as account abstraction.