[id="account_abstraction"]
= Introduction to account abstraction

Account abstraction implements user accounts in a smart contract, as opposed to implementing them in the protocol layer.

Using account abstraction you can now program how an account functions. 


[id="what_is_an_account"]
== What is an account?

An account is the mechanism by which you manage account balances and account state on the blockchain. 

You need an account to exchange value with another party. An account is a fundamental part of any state based system.

[id="ethereum_account_structure"]
== Ethereum account structure

Within Ethereum individual user accounts are known as Externally Owned Accounts (EOAs). You are directly responsible for the storage of your own private keys.

Although this is theoretically a secure method of account management, in practice it has some drawbacks, such a requiring you to keep your seed phrase secure yet accessible to you, and limited flexibility surrounding wallet functionality.

EIP-4337, a governance proposal for Ethereum outlines account abstraction whereby all accounts are managed via a dedicated smart contract on the Ethereum network, as a way to increase flexibility and usability. You can add custom logic on top of the basic account functionality provided. 

[id="starknet_account_structure"]
== StarkNet account structure

Starknet's account type is based on Ethereum's EIP-4337, where instead of EOAs, the account type uses smart contracts and is almost entirely implementation-agnostic. 

Through the use of smart contracts, you are provided with complete flexibility within your account implementation.

This method of account implementation is more broadly known as account abstraction.

[id="exmaples"]
== Examples of customizing account functionality

Two examples of how you might program an account to function using account abstraction are:

Social recovery:: A process where if you lose your wallet, you are able to retrieve it via a selected social network, vastly improving the typical experience of wallet recovery.

Signature abstraction:: You can choose the validation scheme per account contract, such as adding secure enclave support for a smartphone.
