[id="validate_and_execute"]
= Validate and Execute

Internal to Starknet's account smart contract are two distinct functions that account transactions will call: 
* Validate
* Execute

These should be your focus when extending account functionality.

Separating validate and execute ensures that sequencers are guaranteed payment for work completedand are not susceptible to Denial of Dervice (DoS) attacks.

[id="the_validate_function"]
== The Validate Function

The primary purpose of the validate function is to ensure that any transaction submitted is genuine and therefore will not take up unjustified resources during the execution process.

Without this mechanism, a forged transaction could result in the sequencer taking a fee and charging you unfairly. In short, validate ensures that the sequencer can only charge for valid transactions. 

In addition to this, having a separate validate function allows the sequencer to quickly and efficiently select valid transactions from the Starknet mempool. This in turn ensures that sequencers can charge more accurately compared to a system where validate and execute functions are bound together. 

[id="invalid_transactions"]
== Invalid Transactions

If the transaction is not deemed to be genuine by the validate function then it will be returned as invalid and no fee will be taken from the account in question.

[id="the_execute_function"]
== The Execute Function

The purpose of the execute function is to abstract away the remaining actions performed by a transaction. This is the step where the sequencer will process transactions that are to be included in a block. 

[id="reverted_transactions"]
== Reverted Transactions

If the transaction fails for any reason during the execute function then the transaction will be reverted. 

Only successful transactions resulting from the completion of the execute function will be charged a fee by the sequencer. 