= Stwo

== Introduction
Stwo, which stands for STARK two, is Starknet's next-generation prover, designed to deliver high-throughput, low-latency STARK proofs optimized for modern use cases. Stwo represents a major leap forward in zero-knowledge infrastructure, enabling faster proof generation and lower costs for Starknet applications and beyond.

Whether you're curious to xref:learning_about_stwo[learn how Stwo works], or only interested in xref:using_stwo[using it in your application], this page serves as a starting point for exploring the ecosystem of guides, references, and learning materials around the Stwo prover. Most resources are open-source, so don't hesitate to fix a typo, improve an example, or even write an entirely new content while your're reading!

== Learning about Stwo

* https://blog.zksecurity.xyz/posts/circle-starks-1/[blog.zksecurity.xyz/posts/circle-starks-1] and https://blog.zksecurity.xyz/posts/circle-starks-2/[blog.zksecurity.xyz/posts/circle-starks-2]

* https://eprint.iacr.org/2024/278.pdf[eprint.iacr.org/2024/278.pdf^]

== Using Stwo

* https://www.cairo-lang.org/cairovm/[cairo-lang.org/cairovm]

* https://book.cairo-lang.org/ch01-03-proving-a-prime-number.html[book.cairo-lang.org/ch01-03-proving-a-prime-number.html]

* https://github.com/starkware-libs/stwo[github.com/starkware-libs/stwo^]

* https://github.com/starkware-libs/stwo-cairo[github.com/starkware-libs/stwo-cairo]

* https://github.com/nexus-xyz/nexus-zkvm[github.com/nexus-xyz/nexus-zkvm^]
