[id="environment"]

# Setting up the environment

## Overview

Setting up your local development environment to develop on Starknet involves the following steps:

* xref:#_install_the_prerequisites[Install the prerequisites]
* xref:#_install_the_additional_dependencies[Install the additional dependencies]
* xref:#_install_the_cairo_cli[Install the Cairo CLI]
* xref:#_install_the_cairo_compiler[Install the Cairo compiler]


## Install the prerequisites

We recommend using a link:https://docs.python.org/3/library/venv.html[Python virtual environment]
for your development work.

To create and enter the Python virtual environment, you have two options:

* xref:#_option_1__activate_your_cairo_virtual_environment_manually[Activate your Cairo virtual environment manually]
* xref:#_option_2__use_the_python_environment_manager[Use the Python environment manager]


### Option 1 - Activate your Cairo virtual environment manually

Run the following two commands to manually create and activate a Cairo virtual environment:

[,Bash]
----
python3.9 -m venv ~/cairo_venv
source ~/cairo_venv/bin/activate
----

After creating and activating the virtual environment, you should see `(cairo_venv)` in the command line prompt, indicating that the virtual environment is active, for example:

[,Bash]
----
(cairo_venv)
----


### Option 2 - Use the Python environment manager

Alternatively, you can use the Python environment manager to create a virtual environment. Simply run the following commands:

[,Bash]
----
curl https://pyenv.run | bash
----

Now add the following to your `.bashrc` or `.zshrc` file:

[,Bash]
----
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
----

Restart your terminal and run the following commands:

[,Bash]
----
pyenv install 3.9.0
pyenv virtualenv 3.9.0 cairo_venv
pyenv activate cairo_venv
----

you should see `(cairo_venv)` in the command line prompt, indicating that the virtual environment
is active, for example:

[,Bash]
----
(cairo_venv)
----

## Install the additional dependencies

Depending on your operating system, you may need to install the following, additional dependencies:
|===
|Dependency |Description

|`libgmp3-dev`/`gmp`|A software development library package for the GNU Multiple Precision Arithmetic
Library.
|`ECDSA` |(Elliptic Curve Digital Signature Algorithm) is a digital signature algorithm that is based on the mathematics of elliptic curves.
|`FastECDSA`|An open-source software library that provides an implementation of the Elliptic Curve
Digital Signature Algorithm (ECDSA) for use in cryptographic applications. It is designed to be fast, efficient, and easy to use, and is written in the Python programming language.
|`SymPy` |A Python library for symbolic mathematics.
|===


### On Linux Ubuntu
On Ubuntu, you will need to run the following command:

[,Bash]
----
sudo apt install -y libgmp3-dev
----

### On macOS
On macOS, you can use Homebrew:

[,Bash]
----
brew install gmp
----

After that, you need to install the following dependencies (Linux and Mac):

[,Bash]
----
pip install ecdsa fastecdsa sympy
----

## Install the Cairo CLI

The Cairo CLI allows you to interact with Starknet via command line interface. If you had
Cairo installed previously, uninstall it and install the latest version:

### Uninstall the previous version (optional)
[,Bash]
----
pip uninstall cairo-lang
----

### Install the latest version of Cairo

You can use `pip` to install the latest version of Cairo:

[,Bash]
----
pip install cairo-lang
----

Alternatively, you can download a specific version of Cairo using this command:

[,Bash]
----
pip install $HOME/Downloads/cairo-lang-0.11.0.2.zip
----

Once you have installed the Cairo package, make sure to test your installation by running the
following command:

[,Bash]
----
starknet --version
----

You should see an output in your terminal similar to the below:
[,Bash]
----
starknet 0.11.0.2
----

Make sure the version output matches the link:https://github.com/starkware-libs/cairo-lang/releases[latest release].

## Install the Cairo compiler

The Cairo compiler allows you to compile Cairo code into machine executable byte code.

To install the Cairo compiler, run the following commands:

### Step 1 - Clone the repository and set up the Cairo compiler

Go to your $HOME directory

[,Bash]
----
cd ~/
----

Clone the cairo Cairo 1 compiler to a folder called .cairo in your home directory

[,Bash]
----
git clone https://github.com/starkware-libs/cairo/ .cairo
cd .cairo/
git checkout tags/v1.0.0-alpha.6
cargo build --all --release
----

### Step 2 - Add the Cairo executables to your path

After building the Cairo binaries, add them to the PATH environment variable by adding the following line to your `.bashrc` or `.zshrc` file:

[,Bash]
----
export PATH="$HOME/.cairo/target/release:$PATH"
----

Then, open a new shell and check that the following command returns a version number:

[,Bash]
----
cairo-compile --version
----

Your output should look similar to the below:

[,Bash]
----
cairo-lang-compiler 1.0.0-alpha.6
----

You are now able to compile, deploy and interact with smart contracts on Starknet
