[id="getting_started"]
= Getting started

Starknet is a permissionless decentralized ZK-Rollup operating as an L2 network on Ethereum,
where any dApp can achieve unlimited scale for its computation, without compromising Ethereum’s
composability and security.

Currently, Starknet’s first step, Starknet Alpha, is deployed. You can learn more about the
current stable Starknet release on the xref:starknet_versions:version_notes.adoc[Starknet
versions page].

== In this guide

This guide walks you through everything you need to know in order to begin interacting with the Starknet network including
writing and deploying your first smart contract and interacting with existing smart contracts.

Below is a table of contents to help you to understand in more depth what this tutorial covers:

|===
|Title |Description

|xref:getting_started:cairo_1/environment_setup.adoc[Environment setup]|Setting up your local
development environment for Starknet
|xref:cairo_1/writing_first_contract.adoc[Writing smart contracts]|Writing a Starknet smart contract
|xref:cairo_1/deploying_contracts.adoc[Deploying smart contracts]|Deploying
smart contracts to Starknet
|Setting up a Starknet account|Coming soon
|Constructors |Coming soon
|More features|Coming soon
|Calling other contracts|Coming soon
|Deploying a contract by proxy|Coming soon
|Events|Coming soon
|Interacting with L1 contracts|Coming soon
|Default entry points|Coming soon
|Writing unit tests|Coming soon
|Signature verification|Coming soon
|A simple automated market maker example|Coming soon

|===
