[id="getting_started"]
= Getting started

Starknet is a permissionless decentralized ZK-Rollup operating as an L2 network on Ethereum,
where any dApp can achieve unlimited scale for its computation, without compromising Ethereum’s
composability and security.

Currently, Starknet’s first step, Starknet Alpha, is deployed. You can learn more about the
current stable Starknet release on the xref:../../starknet_versions/version_notes.adoc[Starknet
versions page].

This guide walks you through everything you need to know in order to begin interacting with the Starknet network including
writing and deploying your first smart contract and interacting with existing smart contracts.

Below is a table of contents to help you to understand in more depth what this tutorial covers:

|===
|Title |Description

|Environment setup|Description
|Setting up an account, row 3 |Description
|Writing smart contracts|Description
|Constructors |Description
|More features|Description
|Calling other contracts|Description
|Deploying a contract by proxy|Description
|Events|Description
|Interacting with L1 contracts|Description
|Default entry points|Description
|Writing unit tests|Description
|Signature verification|Description
|A simple automated market maker example|Description

|===
