[id="contract_hash"]
= Class hash
:stem: latexmath

The class hash is a hash chain of the definition of the class.

== Definition of a class

The elements that define a class are:

[frame=none,grid=none,cols="1,2",stripes=none]
|===
|API version
| The version of the class, currently always `0`.

|Array of external functions entry points
a| An entry point is a pair `(_selector_, _offset_)`, where `_offset_` is the offset of the instruction that should be called inside the class's bytecode.

[NOTE]
====
The selector is an identifier through which the function is callable in transactions or in other classes. The selector is the xref:../Hashing/hash-functions.adoc#starknet-keccak[starknet_keccak] hash of the function name, encoded in ASCII.
====
|Array of entry points for https://www.cairo-lang.org/docs/hello_starknet/l1l2.html#receiving-a-message-from-l1[L1 handlers]
|

|Array of entry points for constructors
| Currently, the compiler allows only one constructor.

|Array of used built-in names
| An ASCII-encoded array, ordered by declaration.

|Program hash a| The xref:../Hashing/hash-functions.adoc#starknet-keccak[starknet_keccak], of the class's program. The class's program is the `.json` file that the StarkNet compiler outputs when you run the following command:

[source,shell]
----
$ starknet-compile --no_debug_info
----

To see the exact computation of this field, see link:https://github.com/starkware-libs/cairo-lang/blob/7712b21fc3b1cb02321a58d0c0579f5370147a8b/src/starkware/starknet/core/os/contract_hash.py#L116[contract_hash.py^].

|Bytecode
|Represented by an array of field elements.
|===

== How the class hash is computed

The hash of the class is the chain hash, that is, the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen hash], of the above, computed as follows:

. Start with stem:[$h(0,\text{api_version})$].
. For every line in the above, excluding the first, compute stem:[$h(h(previous\_line), new\_line)$], where the hash of an array is defined as xref:../Hashing/hash-functions.adoc#starknet-keccak[starknet_keccak].
. Let stem:[$c$] denote the cumulative hash that results from applying the above process; the class's hash is then stem:[$h(c, \textrm{number_of_lines})$], where stem:[$\text{number_of_lines}$] is 7.

For more details, see the https://github.com/starkware-libs/cairo-lang/blob/7712b21fc3b1cb02321a58d0c0579f5370147a8b/src/starkware/starknet/core/os/contracts.cairo#L47[Cairo implementation].
