[id="eol"]
= Deprecated, unsupported, and removed features

The features on this page are deprecated, unsupported, or removed from Starknet.

// [cols="1,3"]
// |===
// |Status|Definition
//
// |Deprecated| Feature or capability that is still supported, but support will be removed in a future release of Starknet.
// Future fixes or enhancements are unlikely. If necessary, an alternative is available.
// |Unsupported or removed|Feature or capability that is no longer supported, and might have been removed from Starknet.
// |===

[horizontal,labelwidth="15"]
Deprecated:: Refers to a feature or capability that is still supported, but support will be removed in a future release of Starknet.
Future fixes or enhancements are unlikely. If necessary, an alternative is available.
Unsupported:: Refers to a feature or capability that is no longer supported.
Removed:: Refers to a feature or capability that has been entirely removed.

== Deprecated features

[cols="1,3",]
|===
|Name|Description

| Goerli testnet
a| Goerli testnet is deprecated and is being replaced by Sepolia testnet. Starknet started migrating to Sepolia testnet on November 15th, 2023. Goerli testnet support will be removed in the upcoming months. You should migrate to Sepolia testnet as soon as possible. For more information on the Goerli deprecation, see https://ethereum.org/nb/developers/docs/networks/#ethereum-testnets[the deprecation announcement on Ethereum's site].

Full nodes, API services, SDKs, and other Starknet developer tools have started their migration to Sepolia as well. Builders are urged to migrate to Sepolia as soon as possible.

[NOTE]
====
Sepolia's state and history are relatively small. Sepolia xref:version_notes.adoc[supports declaring classes of Cairo v0 and Cairo v2.0.0 and higher].
====

|Starknet CLI | The Starknet CLI is deprecated. Instead use xref:cli:starkli.adoc[Starkli].

Support for Starknet CLI will be removed in Starknet v0.13.0.
|Cairo 0 | xref:starknet_versions:version_notes.adoc#version0.11.0[Starknet v0.11.0] introduces Cairo 1.0 smart contracts.
|===

== Unsupported and removed features

[cols="1,3"]
|===
|Name|Description

| Starknet feeder gateway a| The Starknet feeder gateway, a temporary solution for querying the sequencer’s state, is being replaced by Starknet full nodes (Pathfinder, Juno, Deoxys, Papyrus) and RPC services. For more information, see xref:tools:api-services.adoc[Full nodes and API services].

Support for the feeder gateway queries that are not required for full nodes to synchronize on the state of Starknet will stop according to the following schedule:

[%autowidth.stretch]
!===
!Environment !Date

!Integration
!1 November 2023
!Testnet
!15 November 2023
!Mainnet
!19 December 2023
!===

Queries that are required for full nodes to synchronize on the state of Starknet are still supported.

For more information, see the Community Forum post link:https://community.starknet.io/t/feeder-gateway-deprecation/100233[_Feeder Gateway Deprecation_].
| Goerli testnet 2 | Goerli testnet 2 is removed. Use Goerli testnet.
|Free L1-> L2 messaging |Previously, sending a message from L1 to L2 had an optional fee associated.

From xref:starknet_versions:version_notes.adoc#version0.11.0[Starknet v0.11.0], the fee mechanism is enforced and the ability to send L1->L2 messages without the corresponding L2 fee has been removed.

See xref:architecture_and_concepts:Network_Architecture/messaging-mechanism.adoc#l1-l2-message-fees[here] for more details.

|`invoke` transaction v0 |`invoke` transaction v0 has been removed since xref:starknet_versions:version_notes.adoc#version0.11.0[Starknet v0.11.0].
|`declare` transaction v0 |`declare` transaction v0 has been removed since xref:starknet_versions:version_notes.adoc#version0.11.0[Starknet v0.11.0].

|`deploy` transaction|The `deploy` transaction has been removed since xref:documentation:starknet_versions:version_notes.adoc#version0.10.3[Starknet v0.10.3].

To deploy new contract instances, you can use the xref:architecture_and_concepts:Smart_Contracts/system-calls-cairo1.adoc#deploy[`deploy` system call].
|===
