[id="upcoming_versions"]
# StarkNet v0.11.0

StarkNet Alpha 0.11.0 introduces Cairo 1.0 smart contracts. Until regenesis, old and new contracts will co-exist and will be able to interact with each other. On the regenesis, classes (and contracts that are instances of those classes) written in older Cairo versions will no longer be supported.

In StarkNet v0.11.0, you can declare, deploy and run Cairo 1.0 smart contracts. We also introduce a new system call that allows a smooth transitioning of existing contracts to a Cairo 1.0 implementation.

So far, contract classes have been defined in terms of Cairo assembly, or Casm for short (the class definition also included more information needed for execution, e.g., hint data). The novelty of Cairo 1.0 is the introduction of Sierra (Safe Intermediate Representation), an intermediate layer between Cairo 1.0 and Casm.

The role of Sierra is to guarantee that every contract execution can be proven. With Cairo 0, one may write contracts that fail ungracefully, e.g., via an `assert` instruction, which will result in unprovable transactions.

In such cases, it is impossible to trustlessly charge a fee for the failed transaction, which creates a potential DOS vector on StarkNet sequencers. On the other hander, Sierra is guaranteed to compile to “safe Casm,” i.e., a subset of Casm that cannot fail (the simplest example that illustrates the restrictions of safe Casm is the usage of if/else instructions rather than asserts).

To guarantee that all classes in the system originated from Sierra, users will send a new contract class structure (one that corresponds to Sierra), and the StarkNet sequencer will compile it to Casm.

In the future, this compilation step will be proven inside the StarkNet OS. In the meantime, users have to perform this compilation and produce the Casm hash locally in order to sign it in the `DECLARE` transaction. Note that the user’s approval here is vital; if the compilation to Casm is not verified, nothing enforces the generated Casm to correspond to the (Sierra) contract class.

[NOTE]
====
💡 Note that essentially, Cairo is only required for proving. In order to prove the validity of blocks, we need to be able to represent every contract execution in Cairo.

For sequencers, who are responsible for block production, proving may be out of scope. Thus, the compilation of the contract class to Casm may not be important for them. In the future, one can imagine a Sierra VM or compilation from Sierra to different CPU architectures, e.g., x86).

However, for the time being, different components in the ecosystem (the sequencer, full nodes, etc.) will keep using the generated Casm for contract execution.
====

The introduction of Cairo 1.0 and Sierra has several effects on the system. Below we list the effects on each component; of particular note are:

- A new version of the `DECLARE` transaction, which allows sending the new class structure
- The state commitment will now include contract classes
- Changes to the on-chain data format
- New system call - `replace_class`
- StarkNet API (feeder gateway/gateway) and JSON-RPC updates

## Declare v2

### Transaction structure

The following is an example of the new version of the `DECLARE` transaction:

```json
{
	"version": "0x2",
	"max_fee": "0xf99ee42792c",
	"signature": [
		"0x1e3207935d3ab611b30bf486915b3d2f7ddb5eaa00c1fca2ec73343babbe434",
		"0x418a33a22ccba3c743d0a097bd61d749527f4d460bd3317e904762d91eebc05"
	],
	"nonce": "0x1",
	"contract_class": {
		...
	},
	"compiled_class_hash": "0x418a33a22ccba3c743d0a097bd61d749527f4d460bd3317e904762d91eebc05"
	"sender_address": "0x706064eb9da21c692ef9a6b9f19d671b718e3bea99926ba6b6ad938c049fcbe",
	"type": "DECLARE"
}
```

### Transaction flow

Upon receiving a `DECLARE v2` transaction, the sequencer will compile the contract class to Casm and ensure that the resulting compiled class hash equals the given `compiled_class_hash`; otherwise, the transaction is dropped.

The sequencer then proceeds to run `__validate_declare___` (similarly to version 1), and in case the transaction is found valid, it stores the given class in its DB and updates the state commitment with the `(class_hash, compiled_class_hash)` pair.

### Deploy and library_call

After the class was declared, it can be used either in deploying new instances or via library calls. Note that to specify the class (either for deploy or library_call), one has to send `class_hash` and **NOT** `compiled_class_hash`. The sequencer and full nodes may internally maintain a mapping between the two, but a reference to a declared class has to be via its class hash.

## Version 0 Removal

`INVOKE` and `DECLARE` transactions of version 0 will no longer be supported in StarkNet Alpha v0.11.0


## State Commitment

New classes declared by v2 Declare transactions will be included in the state commitment. To this end, we change the state commitment from `global_tree_root` to `h(global_tree_root, classes_root)`, where `classes_root` is a height 251 Patricia tree constructed from the key-value pairs `(class_hash, compiled_class_hash)`.

## Replace Class Syscall

We add a new system call that allows changing a contract’s class to a Cairo 1.0 class:

`replace_class(class_hash: felt)`

## On-Chain Data

The data published on L1 should allow everyone to construct the StarkNet state locally. The introduction of the `replace_class` system call and the separation between classes (Sierra) and compiled classes (Casm) induces some changes to our on chain data format:

- The deployment info section is removed
- The first word will be the number of contracts affected by the block (this includes storage updates, nonce updates, class updates, or deployments).
- For each affected contract, the first word will encode the new nonce and number of storage updates. Additionally, it will use one bit to determine whether or not the contract was deployed or if its class was updated.

The specific encoding is given by:


|===
|flag|new nonce|n_updates

| 1 bit | 64 bits   | 64 bits   |
|===

- If the above flag is turned on, then the next word is the new contract class (whether it was just deployed or replaced). Otherwise, you can skip to the next bullet.
- For each storage update, we send to L1 the key and the new value (this part remains unchanged)

## API Changes

### Feeder Gateway

- New endpoint: **`get_compiled_class`.** The purpose of this endpoint is to return the Cairo assembly associated with the Class. This is the data needed for contract execution.
- `**get_class_by_hash**` - the structure of the returned class will depend on whether or not it is a new type of class, compiled from Cairo 1.0.
- `**get_full_contract**` - same as above
- `**get_state_update`**
- added `replaced_classes` section
- `declared_contracts` is split into `old_declared_contracts` and `declared_contracts`
- `old_declared_contracts` is a list of class hashes
- `declared_classes` is a dictionary that maps `class_hash` to `compiled_class_hash`
- `**get_block**`
- the `transactions` field is subject to the same changes in `get_transaction`
- `state_root` is renamed to `state_commitment`
- `**get_transaciton**`
- `contract_address` is changed to `sender_address` in invoke transactions
- Declare v2 transaction may be returned

### Gateway

- `**add_transaction**`
- can now take a Declare v2 transaction
- `contract_address` is changed to `sender_address` in Invoke transactions