[id="upcoming_versions"]

# Upcoming Starknet versions

## Starknet Alpha v0.12.0

### What to expect
Starknet’s https://medium.com/starkware/starknet-goals-and-roadmap-for-2023-fe7b89eead3b[roadmap
for 2023] is focussed on performance and user experience.

The upcoming version 0.12.0 of Starknet is focused on enhancing the network's throughput to improve scale and transaction latency.
To achieve this, a new Rust implementation has been introduced for the sequencer.
The sequencer contains more efficient local storage and critical path logic implemented, aimed at significantly reducing wait times for transaction confirmations and addressing network congestion issues.

### Notable changes
While there are minimum changes at the protocol level, the upcoming version introduces significant
improvements to the sequencer.

Here are some notable changes to expect:

#### Sequencer performance
The new sequencer's performance will benefit from the following three enhancements:

* https://github.com/lambdaclass/cairo-rs[Cairo-rs]: Cairo VM in Rust
* The https://github.com/starkware-libs/blockifier[blockifier]: a transaction execution framework
 available on GitHub under the Apache 2.0
license.
* Local state management of the sequencer will use https://github.com/starkware-libs/papyrus[Papyrus] storage.

#### Removal of pending status
The `PENDING` transaction status will be removed in v0.12.0.

* In Starknet, the pending block is a valid block that was executed by the sequencer but is not
yet full and more transactions might be added to it.
* In v0.12.0, the status for transactions in the pending block will be changed from `PENDING` to
`ACCEPTED_ON_L2` to reflect their finality status.

#### Block hash syscall
In v0.12.0, a new syscall will be added that will allow contracts to fetch
the block hashes of older blocks (similar to https://docs.soliditylang.org/en/v0.8.11/units-and-global-variables.html#block-and-transaction-properties[blockhash] in Solidity).

* The syscall will allow access to past blocks in the range (`current block-10, current block -
1024`).
* In v0.12.0, the Starknet OS will not prove the correctness of those block hash returned by the
syscall. This is temporary and will be proven in the final version of the Starknet OS.

#### Smart contract syntax improvements
In Starknet version 0.12.0, we are introducing significant improvements to the smart contract syntax. The new syntax focuses on:

- Contract safety.
- Laying the foundations for extensibility.

Safety in this context means being more explicit about the external-facing components of the contract (interface/storage/events). This provides developers with a better understanding of what to expect when interacting with the contract.

Extensibility, which will be finalized in a later version, allows contracts to utilize components from external libraries. This is a key feature of any smart contract language and addresses a significant issue in the Starknet development community.

For an in-depth look at the motivation behind these changes, see this link:https://community.starknet.io/t/cairo-1-contract-syntax-is-evolving/94794[community forum post].

[NOTE]
====
While the link:https://github.com/starkware-libs/cairo/releases/tag/v2.0.0-rc0[new compiler
version] includes breaking changes, *_you can continue using the older
compiler version (v1.1.0) and deploy the resulting contracts on Starknet_*.

Starting from version 0.12.0, Starknet will support multiple compiler versions. This means that the
sequencer will continue to accept contracts compiled with the older version for at least six months after the introduction of a breaking change.
====
