[id="upcoming_versions"]

# Upcoming Starknet versions

## Starknet Alpha v0.12.3

[id="what_to_expect"]
### What to expect
The focus of Starknet v0.12.3 is to deprecate the Starknet feeder gateway.

The Starknet feeder gateway serves as a gateway for querying the centralized sequencer on the state of Starknet. It was meant to be used as a temporary solution until full nodes that support Starknet’s JSON-RPC mature and are able to meet the needs of the community.

Starknet now has three different full node implementations in production (xref:pathfinder_versions.adoc[Pathfinder], xref:juno_versions.adoc[Juno], and Papyrus). Consequently, it is time to deprecate the feeder gateway and migrate to RPC providers.

#### Key dates

The feeder gateway will stop supporting most queries on the following dates:

[%autowidth.stretch]
|===
|Environment |Date

|Integration
|1st November 2023

|Testnets
|15th November 2023

|Mainnet
|18th December 2023
|===

[NOTE]
====
The feeder gateway will continue to support queries required for full nodes to synchronize on the state of Starknet.
====
