[id="upcoming_versions"]

= Upcoming Starknet versions

[id="what_to_expect"]
== Starknet Alpha v0.13.0


This version introduces the following changes:

* In addition to ETH, users will be able to pay transaction fees in STRK using v3 transactions.
* v3 transactions are structured to support several upcoming features detailed below.

=== v3 transactions

[IMPORTANT]
====
While v3 transactions will support the following features, not all the features that they will support will be available in Starknet v0.13.0.
====

* A *fee market*, starting with Starknet v0.14.0, to enable users to optimize their transaction process by the network during periods of congestion.
* A *paymaster* mechanism, to enable entities other than the transaction sender to pay transaction fees.
* Account deployment will take place with an account’s initial Invoke or Declare transaction.
* *Volition mode*, for reducing data availability costs.
* *Nonce generalization*, enabling users to send multiple transactions simultaneously by specifying different channels for different transactions.

For more information, see the following:

* link:https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-8.md[SNIP 8: Transaction V3 Structure]
* link:https://github.com/ob1337/SNIPs/blob/snip-10/SNIPS/snip-10.md[SNIP 10: STRK fee token]


