[id="upcoming"]
= Starknet release notes

The following release notes cover the ongoing version changes to Starknet. You can subscribe to get the latest version updates delivered to your inbox at  link:https://www.starknet.io/en/roadmap[Starknet Roadmap & version updates].

== Starknet environments

Within Starknet's deployment pipeline there are separate and distinct networks that operate independently of each other for testing before deployment.


include::ROOT:partial$snippet_important_goerli2_removed.adoc[]

.Current versions supported in each environment
[%autowidth.stretch]
|===
|Environment |Starknet version|Sierra version|Cairo version

|Mainnet|0.12.2|1.3.0|2.0.0 - 2.3.1
|Goerli Testnet|0.13.0|1.3.0|2.0.0 - 2.3.4
|Sepolia Testnet|0.13.0|1.3.0|2.0.0 - 2.3.4
|===



[id="version0.13.0"]
== Starknet v0.13.0 (December 13, 2023)

Starknet v0.13.0 is live on testnet.

This version introduces the following changes:

* In addition to ETH, users can pay transaction fees in STRK using v3 transactions.
* v3 transactions are structured to support several upcoming features detailed below.

=== v3 transactions

[IMPORTANT]
====
While v3 transactions will support the following features, not all the features that they will support will be available in Starknet v0.13.0.
====

* A *fee market*, starting with Starknet v0.14.0, to enable users to optimize their transaction process by the network during periods of congestion.
* A *paymaster* mechanism, to enable entities other than the transaction sender to pay transaction fees.
* Account deployment will take place with an account’s initial Invoke or Declare transaction.
* *Volition mode*, for reducing data availability costs.
* *Nonce generalization*, enabling users to send multiple transactions simultaneously by specifying different channels for different transactions.

For more information, see the following:

* link:https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-8.md[SNIP 8: Transaction V3 Structure]
* link:https://github.com/ob1337/SNIPs/blob/snip-10/SNIPS/snip-10.md[SNIP 10: STRK fee token]

[id="version0.12.3"]
== Starknet v0.12.3 (November 19th 23)

// Starknet v0.12.3 is live on testnet.

This release partially removes support for the Starknet feeder gateway. For details, see link:https://community.starknet.io/t/feeder-gateway-deprecation/100233/1[Feeder Gateway Deprecation] in Development Proposals on the Starknet comunity forum.

Additionally, this version includes the following changes:

* Performance optimizations in the gateway, the computation of the Patricia storage root, and block hash
* Support for `secp256r1` syscalls in the Starknet OS.
* Restriction for `+__validate__+` and the constructor of `DeployAccount` transactions:
** Restrict access to `sequencer_address` in the `get_execution_info` syscall by returning ``0``'s for the address.
** Restrict access to the following syscalls:
*** Cairo contracts: `get_block_hash`
*** Cairo 0 contracts: `get_sequencer_address`

This version is available on both Goerli and Sepolia testnets.

[discrete]
=== Cairo 0

Move structs that are common to `secp256k1` and `secp256r1` to a separate file.


[id="version0.12.2"]
== Starknet v0.12.2 (September 4th 23)

Starknet v0.12.2 is live on Mainnet.

This version includes the following changes:

* Enabling P2P Authentication: An additional endpoint in the sequencer gateway to provide a signature on the state diff commitment and block hash.
* Resolving Mismatches in Queries: An extension to the `get_state_update` endpoint in the sequencer gateway that returns both the pending state diff and the pending block together.
* Increased maximum Cairo steps per transaction from 1 million to 3 million.

[id="version0.12.1"]
== Starknet v0.12.1 (August 21st 23)

Starknet v0.12.1 is live on Mainnet.

This version includes the following changes:

* Mempool Validation.
* Inclusion of Failed Transactions.
* Keccak builtin.

[id="version0.12.0"]
== Starknet v0.12.0 (July 12th, 23)

Starknet v0.12.0 is live on Mainnet.

This version contains the following changes:

* Use the link:https://github.com/starkware-libs/blockifier[rust blockifier] and link:https://github.com/lambdaclass/cairo-vm[LambdaClass's Cairo VM] to accelerate the sequencer's time to handle transactions.
* Support link:https://github.com/starkware-libs/cairo/releases/tag/v2.0.0[version 2.0.0] of the Cairo compiler.
* Replace the `PENDING` status of transactions to `ACCEPTED_ON_L2` - once a transaction is in that status it means that it will be included in a block, this applies to transactions - blocks still have the `PENDING` status.
* Add an experimental `get_block_hash` syscall.
* Change HTTP error code from 500 to 400 on API errors.

[id="version0.11.2"]
== Starknet v0.11.2 (May 31, 23)

Starknet v0.11.2 is live on Mainnet.

This version contains the following changes:

* Upgrade Cairo 1.0 version to v1.0.0-rc0 (Cairo 1.0 activated on Starknet!)

[id="version0.11.1"]
== Starknet v0.11.1 (May 23, 23)

Starknet v0.11.1 is live on Mainnet.

This version contains the following changes:

* Upgrade Cairo 1.0 version to v1.0.0-rc0.

* Charged transaction fee is now based on an average Ethereum gas price instead of a single sample
(estimation API is unaffected).

* API changes:
** Remove the state root in `get_state_update` for pending blocks to allow faster responses
in future versions.

* Testing framework:
** Allow declaring (and interacting with) Cairo 1.0 contracts.
*** Currently, the Cairo 1.0 ABI is not supported yet, so a Cairo 0 ABI should be supplied to
`declare()` manually.
** Split `deploy()` to two phases declare and deploy: `deprecated_declare()` (for Cairo 0 contract) or
`declare()` (for Cairo 1.0 contracts) and `deploy()` (for both).
* Add current block hash to the Starknet Core contract (currently not verified by the Starknet OS):
** Breaking change: The `LogStateUpdate` event's data is changed to include blockHash.

[id="version0.11.0"]
== Starknet v0.11.0 (Mar 29, 23)

Starknet v0.11.0 is live on Mainnet.


[NOTE]
====
`invoke` and `declare` transactions of version 0 are no longer supported on this version.
====

In Starknet v0.11.0, you can declare, deploy and run Cairo 1.0 smart contracts. We also introduce a new system call that allows a smooth transitioning of existing contracts to a Cairo 1.0 implementation.

Historically, contract classes have been defined in terms of Cairo assembly, or Casm for short (the class definition also included more information needed for execution, e.g., hint data). The novelty of Cairo 1.0 is the introduction of Sierra (Safe Intermediate Representation), an intermediate layer between Cairo 1.0 and Casm.

The introduction of Cairo 1.0 and Sierra has several effects on the system. Below we list the effects on each component; of particular note are:

* A new version of the `declare` transaction, which allows sending the new class structure
* The state commitment will now include contract classes
* Changes to the onchain data format
* New system call - `replace_class`


[id="version0.10.3"]
== Starknet v0.10.3 (Dec 12, 22)

[NOTE]
====
The `deploy` transaction is no longer supported on this version.
====

This version contains the following changes:

Starknet

*   Performance - Separate the state commitment computation from the execution of the transactions
*   Add `starknet-class-hash` command to compute the class hash of a compiled Starknet contract

Cairo:

*   Autoformatter: Automatically break lines inside expressions


[id="version0.10.2"]
== Starknet v0.10.2 (Nov 29, 22)

- This version introduces sequencer parallelization! This is the first step in our roadmap of performance upgrades. Details about the specific mechanism of parallelization and the roadmap in general are described in https://medium.com/starkware/starknet-performance-roadmap-bb7aae14c7de[this medium post]. 

- A new endpoint, `estimate_fee_bulk`, is added to the feeder gateway. This will allow estimating the fee of several transactions at once, where each transaction is executed relative to the resulting state from applying the previous one.

*   Sequencing performance improvements
*   Builtin ratio changes, which affects builtin costs
*   Add `estimate_fee_bulk` API that computes the fee of multiple transactions that will be executed consecutively

As part of this version, we will also increase the finality of transactions in the pending block, by fixing the timestamp at the time of the block creation. This will solve the issue of transactions moving from pending to rejected on account of too old timestamp

[id="version0.10.1"]
== Starknet v0.10.1 (Oct 25, 22)

This version contains the following changes:

Starknet:

*   Add `DeployAccount` transaction (which will replace the Deploy transaction for deploying account contracts). To use it, you should first add enough funds to your account address to pay the transaction fee, and then you can invoke DeployAccount
*   Split the `starknet deploy_account` CLI command into `starknet new_account` and `starknet deploy_account`
*   Account contracts that are expected to be deployed this way should implement the`__validate_deploy__()` entry point, which should check the signature of the `DeployAccount` transaction
*   Improve L1 fee computation: the fee is computed according to the diff of the storage state
*   API: Remove `entry_point_type` field from transaction information

Cairo:

*   Add `uint256_mul_div_mod` to `uint256.cairo`


[id="version0.10.0"]
== Starknet v0.10.0 (Sept 05, 22)

This version introduces the next step in Starknet's account abstraction design, specifically the validate/execute separation. See https://www.notion.so/starkware/Starknet-0-10-0-4ac978234c384a30a195ce4070461257[here] for more information.

This version contains the following changes:

Starknet:

*   Contract (breaking changes):
**   @external and @view functions should be imported directly by the main compiled file. Otherwise, they will not be usable as external functions
**   Forbid using the same storage variable name in two modules
*   New transaction version (version 1) for `invoke` and `declare` transactions:
**   Transactions of version 0 are deprecated and will not be supported in Starknet from the next version (v0.11.0). Please update your systems to use the new version

[NOTE]
====
In order to use transactions of version 1 you will need to upgrade your account contracts
====

**   Add nonce field to the transactions. Nonce validation is now part of the Starknet protocol and is enforced to be executed sequentially
**   `Invoke`:
***   Split `__execute__` to two functions:` __validate__` (only validates the transaction) and `__execute__` (only executes the transaction)
***   Remove the selector (which is now always `__execute__`) field, following the above change.
**   Declare:
***   `declare` transaction should now be sent from an account (and is validated using `__validate_declare__` in the account contract)
*   Support fee for sending L1 messages. At this point, it's not mandatory and messages with no fee will still be handled. Starting from the next version it will become mandatory.

Cairo:

Syntax changes in Cairo (to make it more similar to rust and C++):

*   You can use the cairo-migrate script to convert old code to the new syntax. Use the `-i` flag to apply the changes to the files
*   End statements with `;`

[NOTE]
====
New lines are still part of the language at this point, and you cannot put more than one instruction per line. This will change in Cairo1.0.
====

*   Use `{ … }` for code blocks (instead of `:` and `end`)
*   Add `()` around the condition of if statements
*   Remove the member keyword in structs
*   Change comment to use `//` instead of `#`
*   Use `..., ap++` instead of `...; ap++` in low level Cairo code
*   Support return types that are not tuples. For example, `func foo() -> felt` (instead of `func foo() -> (r: felt)`)
As a result, it's now mandatory to specify return types. `func foo() -> (res)` should be replaced by `func foo() -> (res: felt)`. The cairo-migrate tool does that automatically.
*   Return statement accepts expressions, rather than only tuples. For example, you can write `let x = (5,); return x;`
*   A few standard library functions were changed to return felt. The cairo-migrate script also fixes calls to those functions
*   Support using functions as expressions
*   This only applies to functions with -> felt signature`, whose ap change is known at compile-time (e.g., recursive functions cannot be used this way)
*   Fix a bug in the secp signature verification code that allowed a malicious prover to ignore the value of `v` (this does not let the prover fake a signature, but allows it to claim that a valid signature is invalid).
*   Add Cairo code for the recursive STARK verifier

Technical changes:
*   Move from python3.7 to python3.9


[id="version0.9.1"]
== Starknet v0.9.1 (July 20, 22)

This version contains the following changes:

Starknet:

API changes:

*   Add `get_block_traces` API - returns all the transaction traces of a given block
*   Add a list of declared contracts in `get_state_update`
*   Add a 0x prefix for class hash in the API
*   Add `starknet_version` field for blocks (only applies to new blocks)

Starknet CLI:

*   Change the default block number to pending
*   Using a wallet is the default, `--no_wallet` must be specified explicitly to override this
*   Deploying contracts:
**  Add `deploy_contract` function to the account contract created by `starknet deploy_account`
**  Use this function to deploy contract (unless using `--no_wallet`). In particular, `deploy` should be used after declaring the contract (it expects the contract class hash)
*   Support `--dry_run` to get the transaction information without signing or sending it
*   Support `deploy_from_zero` in the `deploy` syscall to deploy a contract to an address that does not depend on the deployer

Cairo:
*   Support and in if statements (`if x == y and z == w`). 

[NOTE]
====
At the moment other boolean combinations are not supported
====

[id="version0.9.0"]
== Starknet v0.9.0 (June 06, 22)

This version introduces the contract class/instance paradigm into Starknet. See https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/contract-classes/[here] for more information.

This version contains the following changes:

Starknet:

*   Enforce fees - `max_fee` must not be set to zero, and selector must be `__execute__`
*   Split the concepts of contract class and contract instance. 
*   Add `declare` transaction type
*   New API and CLI commands:
*   `declare` - Declares a contract class
*   `get_class_by_hash` - Returns the contract class given its hash
*   `get_class_hash_at` - Returns the class hash for a given contract instance address
*   Rename `delegate_call` to `library_call`, and change the contract address argument to class hash. 
*   Add a `deploy` system call.
*   Rename `ContractDefinition` to `ContractClass`
*   Reduce the compiled contract file's size by removing unnecessary identifiers (this optimization can be disabled using `--dont_filter_identifiers`)

Cairo:

*   Initial support for the `EC-op` builtin (scalar multiplication over the STARK curve). Not supported in Starknet yet.
*   Add additional helper methods to `blake2s.cairo`, including big-endian support

Technical changes:
*   Change function's `return` type from a struct to a named tuple. In particular, `foo.Return.SIZE` is no longer supported.
