= Developer integrations

From infrastructure services such as full nodes and oracles to user-oriented applications such as wallets and onramps, the Starknet's dynamic and rapidly growing network of projects, developers, and contributors reflects the collaborative and innovative spirit of its developer ecosystem.

The following are key ecosystem projects that developers can integrate with:

[IMPORTANT]
====
The list of projects in this section is dynamic and continuously updated. If a project you are using is missing, please consider opening an issue or editing the page by yourself.
====

* Full nodes:
https://www.nethermind.io/juno[Juno^],
https://github.com/madara-alliance/madara[Madara^],
and https://equilibrium.co/projects/pathfinder[Pathfinder^]


* RPC providers:
http://www.alchemy.com/starknet[Alchemy],
https://www.allthatnode.com/starknet.dsrv[All That Node^],
http://blastapi.io/public-api/starknet[Blast^],
http://blockpi.io/starknet[BlockPI^],
https://chainstack.com/build-better-with-starknet/[Chainstack^],
https://drpc.org/chainlist/starknet[dRPC^],
https://www.dwellir.com/[Dwellir^],
https://getblock.io/nodes/strk/[GetBlock^],
https://www.infura.io/networks/ethereum/starknet[Infura^],
https://www.lavanet.xyz/[Lava^],
https://nownodes.io/starknet[NOWNodes^],
https://omniatech.io/[OMNIA^],
https://onfinality.io/networks/starknet[OnFinality^],
https://www.quicknode.com/chains/strk[QuickNode^],
https://spectrumnodes.com/[Spectrum^],
and https://zan.top/home/node-service[Zan^] 
+
[NOTE]
====
OnFinality also provides a WSS open endpoint, and Blast, dRPC, and Lava also provide open endpoints to Sepolia.

For version support:

* In Dwellir, GetBlock, Lava, and Zan, use the `/rpc/vX_Y` suffix (e.g., use `/rpc/v0_6` for v0.6.0)
* In Alchemy, see https://docs.alchemy.com/reference/starknet-api-faq#what-versions-of-starknet-api-are-supported[docs.alchemy.com/reference/starknet-api-faq^]
* In Blast, see https://blastapi.io/public-api/starknet[blastapi.io/public-api/starknet^]
* In Chainstack, see https://docs.chainstack.com/reference/getting-started-starknet#starknet-json-rpc-version-endpoints[docs.chainstack.com/reference/getting-started-starknet^]
* In QuickNode, see https://www.quicknode.com/docs/starknet#supporting-multiple-versions[quicknode.com/docs/starknet^]

For complete information on the Starknet JSON-RPC API, see https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json[`starknet_api_openrpc.json`^].
====

* Sepolia Faucet: https://faucet.starknet.io/[Starknet Foundation^]

* Block explorers:
https://explorer.cartridge.gg/[Cartridge^],
https://www.oklink.com/starknet[OKLink^],
https://starkscan.co[Starkscan^],
https://viewblock.io/starknet[ViewBlock^],
and https://voyager.online[Voyager^]
+
[NOTE]
====
https://sepolia.starkscan.co/[Starkscan] and https://sepolia.voyager.online[Voyager^] also provide explorers for Sepolia.
====

* Monitoring tools:
https://www.starknet-monitor.com/[Starknet Monitor^]
and https://status.starknet.io/[Starknet Status^]

* Indexers:
https://www.apibara.com/[Apibara^],
https://checkpoint.box/[Checkpoint^],
https://dipdup.io/[DipDup^],
https://www.footprint.network/[Footprint Analytics^],
https://goldsky.com/[Goldsky^],
https://subquery.network/[SubQuery^],
https://thegraph.com/[The Graph^],
and https://tokenflow.live/[Token Flow^]

* Enhanced APIs:
https://docs.alchemy.com/reference/starknet-api-endpoints#nft-api[Alchemy^],
https://www.arkproject.dev/products/nft-api[ArkProject^],
https://docs.blastapi.io/blast-documentation/apis-documentation/builder-api/starknet[Blast^],
and https://starkscan.co/api-info[Starkscan^]

* Bridges:
https://bridge.arkproject.dev/[ArkProject^] (NFT bridge),
https://layerswap.io/app[Layerswap^],
https://minibridge.chaineye.tools/?src=ethereum&dst=starknet[Mini Bridge^],
https://www.orbiter.finance/en?src_chain=1&tgt_chain=SN_MAIN&src_token=ETH[Orbiter Finance^], 
https://owlto.finance/[Owlto Finance^],
https://app.rango.exchange/bridge?fromBlockchain=ARBITRUM&fromToken=ETH&toBlockchain=STARKNET&toToken=ETH--0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7[Rango^],
https://app.rhino.fi/bridge?token=ETH&chainOut=STARKNET&chain=ETHEREUM[Rhino.fi^],
https://app.retrobridge.io/?tokenFrom=ETH[RetroBridge^],
and https://starkgate.starknet.io/bridge/deposit[StarkGate^]

* Oracles:
https://docs.chain.link/data-feeds/starknet/[Chainlink^],
https://docs.pragma.build/starknet/[Pragma^],
and https://docs.pyth.network/price-feeds/use-real-time-data/starknet/[Pyth^]

* Wallets:
https://braavos.app/[Braavos^],
https://www.keplr.app/[Keplr^],
https://www.ledger.com/[Ledger^],
https://snaps.consensys.io/starknet[MetaMask^],
and https://www.ready.co/ready-wallet[Ready^]

* On-ramps:
https://banxa.com/[Banxa^],
https://changelly.com/[Changelly^],
https://fun.xyz/[Checkout^],
https://www.moonpay.com/[Moonpay^],
https://onramp.money/[Onramp Money^],
https://ramp.network/[Ramp^],
https://transak.com/[Transak^],
and https://www.crypto.unlimit.com/[Unlimit Crypto^]

* Auditors:
https://www.abdk.consulting/[ABDK^],
https://beosin.com/[Beosin^],
https://beyondaudit.github.io/[Beyond^],
https://cairosecurityclan.com/[Cairo Security Clan^],
https://chainsecurity.com/[ChainSecurity^],
https://codespect.net/[CODESPECT^],
http://consensys.net/diligence[ConsenSys^],
https://thesis.co/defense[Defense^],
https://www.extropy.io/[Extropy^],
https://fuzzinglabs.com/[FuzzingLabs^],
https://gingersec.xyz/[Ginger Security^],
https://hashlock.com/[Hashlock^],
https://www.nethermind.io/smart-contract-audits[Nethermind Security^],
https://www.oaksecurity.io/[Oak Security^],
https://www.openzeppelin.com/[Open Zeppelin^],
https://osec.io/[OtterSec^],
https://peckshield.com/[PeckShield^],
http://www.trailofbits.com/[Trail of Bits^],
and https://www.zellic.io/[Zellic^]

* Security platforms:
https://www.hypernative.io/[Hypernative^]
and https://trustblock.run/[Trustblock^]

// * Bug bounty programs: https://immunefi.com/bug-bounty/starknet/information/[Immunefi^]

