= Declaring a smart contract


== Prerequisites

=== Ensure Starkli and Scarb are installed correctly
Ensure that the below commands are working properly on your system.

[source, bash]
----
starkli --version
scarb --version
snforge --version
----

If either of the above commands fails, see xref:environment-setup.adoc[Setting up your environment].

== Introduction

Deploying a smart contract in Starknet requires two steps:

* Declaring the class of your contract, i.e. sending your contract's code to the network.
* Deploying a contract, i.e. creating an instance of the code you previously declared.


== Compiling a smart contract

Scarb is the preferred tool to create a new Starknet smart contract project and compile it.

To create a new Starknet smart contract project with Scarb, run `scarb new <project_name>`, and select the default `Starknet Foundry` as a test runner. Alternatively,  run `scarb init` in an empty directory to achieve the same result.

Navigate into the newly created directory:
[source,bash]
----
cd <project_name>
----

The `Scarb.toml` file should look similar to this (versions might vary):
[source,toml]
----
[package]
name = "my_project"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.32.0" }
assert_macros = "2.8.4"

[[target.starknet-contract]]
sierra = true
----



[NOTE]
====
Building a Starknet Foundry project with Scarb requires that a Rust toolchain is installed. You can install the Rust toolchain by running the following command: `curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh`.
See more details on the Rust installation process at link:https://doc.rust-lang.org/beta/book/ch01-01-installation.html[Rust installation].
====

Run the following command:

[source,bash]
----
scarb build
----

The compiled contract will be saved in the `target/dev/` directory.

The contract is now compiled and ready to be declared.

[NOTE]
====
The first time the project is built, some components of Scarb are compiled locally with the Rust toolchain. This process may take a few minutes. This will not happen in subsequent builds.
====

== Setting an RPC provider

To interact with the Starknet network, you need to set an RPC endpoint for Starkli, as an environment variable or the flag `--rpc`. 

The following are the RPC providers available for Starknet: xref:tools:api-services.adoc[API providers].

For interactions with Starknet Sepolia and Starknet mainnet, Starkli supports default RPC providers when using the `--network=sepolia` or `--network=mainnet` flags (limitations to these may apply).

== Declaring a smart contract

A contract can be declared on Starknet using the following command:

[source,bash]
----
starkli declare target/dev/<NAME>.json --network=sepolia
----

[NOTE]
====
Starkli will do its best to identify the compiler version of the declare class. In case it fails, the `--compiler-version` flag can be used to specify the version of the compiler. 
====


You can find the compiler version supported by Starkli by running:

[source,bash]
----
starkli declare --help 
----

In the `--compiler-version` flag you will see possible versions of the compiler:

[source,bash]
----
--compiler-version <COMPILER_VERSION>
          Statically-linked Sierra compiler version [possible values: ...]
----

To see the current Scarb version in use, run:

[source,bash]
----
scarb --version
----

In this case you need to use a different compiler version, switching to a different Scarb version is easy with `asdf.`

First install the desired Scarb version:

[source,bash]
----
asdf install scarb <VERSION>
----

Then select it as the local version for the project:

[source,bash]
----
asdf local scarb <VERSION>
----


== Expected result

[source,bash]
----
starkli declare target/dev/<NAME>.json --network=sepolia
----

The result of the declaration command is a contract class hash:
[source,bash]
----
Class hash declared: <CLASS_HASH>
----

This hash is the identifier of the contract class in Starknet. You can think of it as the address of the contract class. You can use a block explorer like https://sepolia.starkscan.co/class/0x00e68b4b07aeecc72f768b1c086d9b0aadce131a40a1067ffb92d0b480cf325d[StarkScan] to see the contract class hash in the blockchain.

If the contract you are declaring has previously been declared by someone else, you will get an output like this:

[source,bash]
----
Not declaring class as its already declared. Class hash: <CLASS_HASH>
----

An example of declaring a contract with a specific compiler version, and an RPC provider:

[source,bash]
----
starkli declare target/dev/contracts_Ownable.sierra.json \
    --rpc=https://starknet-sepolia.infura.io/v3/<API_KEY> \
    --compiler-version=2.6.0
----