= Deploying and interacting with `HelloStarknet` on Starknet Sepolia

== Introduction

Welcome to the fifth installment of the "Hello, Starknet!" quickstart series, the official tutorial for starting your journey as a Starknet developer! 🚀

Deploying a smart contract involves creating an instance of a previously declared code on Starknet. Once a contract is deployed, it can be interacted with via its various functions. This installment of the series will therefore walk you through the steps necessary to use Starkli for deploying the `HelloStarknet` contract on Starknet Sepolia and interacting with it.

== Deploying `HelloStarknet`

Starkli's deployment command requires the contract's class hash and any arguments expected by its constructor. For our example, if the constructor expects two integers, the deployment command would resemble the following: 

[source,console]
----
$ starkli deploy \
    <CONTRACT_CLASS_HASH> \
    4 \
    2 \
    --network=sepolia --strk
----

However, since `HelloStarknet` doesn't implement a construct, it implicitly uses the Starknet's default constructor, which take no arguments. Therefore, `HelloStarknet` can be deployed on Starknet Sepolia by simply running:

[source,console]
----
$ starkli deploy \
    0x0785c92bf4aa7a89fb62371802aef2f58e2333d8df7e2aadf938efa83735431c \
    --network=sepolia --strk
----

[IMPORTANT]
====
Note that this is indeed the same class hash as in xref:declare-a-smart-contract.adoc[Declaring `HelloStarknet`].
====

The output of a successful deployment command should resemble the following:

[source,console]
----
Deploying class 0x0785c92bf4aa7a89fb62371802aef2f58e2333d8df7e2aadf938efa83735431c with salt 0x024094fe319e0d44752392a9f487633a4cbd37a678f10cec7cc39444565dd2ce...
The contract will be deployed at address 0x055adcccc3de77a9d23cd8250965b388179e1ebd6d6be32f5bc6a08a34805e5e
Contract deployment transaction: 0x01c59c66ad52f3c0e4c23735a61914ddb6d422ef4f93bd6dad418bec74fc94b8
Contract deployed: 0x055adcccc3de77a9d23cd8250965b388179e1ebd6d6be32f5bc6a08a34805e5e
----

and you should be able to see the deployed contract on one of xref:tools:ref-block-explorers.adoc[Starknet Sepolia's block explorers] by searching for its address.

== Interacting with `HelloStarknet`

Now that your contract has been deployed, you (and everyone else) are able to interact with it. Starkli enables interaction with smart contracts via two primary methods:

* `call` for read functions that don't modify Starknet's state.

* `invoke` for write functions that modify Starknet's state.

=== Calling `get_balance`

The `call` command allows querying a smart contract function without sending a transaction. For example, you can call `HelloStarknet` 's `get_balance` function which doesn't expect any arguments and returns the contract's balance by running:

[source,console]
----
$ starkli call \
    0x055adcccc3de77a9d23cd8250965b388179e1ebd6d6be32f5bc6a08a34805e5e \
    get_balance \
    --network=sepolia
----

where `0x055adcccc3de77a9d23cd8250965b388179e1ebd6d6be32f5bc6a08a34805e5e` is the contract's deployed address. If called before invoking the `increase_balance` function, the result should resemble the following (since the contract's initial balance is preset to `0`):
[source,console]
----
[
    "0x0000000000000000000000000000000000000000000000000000000000000000"
]
----

=== Invoking `increase_balance`

Unlike the `call` command, the `invoke` command modifies the state of the smart contract by submitting a transaction to the network. For example, you can invoke `HelloStarknet` 's `increase_balance` function, which expect an integer as argument, by running:

[source,console]
----
$ starkli invoke \
    0x055adcccc3de77a9d23cd8250965b388179e1ebd6d6be32f5bc6a08a34805e5e \
    increase_balance \
    42 \
    --network=sepolia
----

If the invocation was successful, Starkli's output should resemble the following:

[source,console]
----
Invoke transaction: 0x0146cfed26a0d62bff0e6c27490204690a5e144266b274b1c84cb32ee7ba6200
----

and you should be able to see the transaction on one of xref:tools:ref-block-explorers.adoc[Starknet Sepolia's block explorers] by searching for its hash.


After the transaction's status is changed to "Accepted on L2", you can confirm that Starknet's state indeed changed by calling the `get_balance` function again:

[source,console]
----
$ starkli call \
    0x055adcccc3de77a9d23cd8250965b388179e1ebd6d6be32f5bc6a08a34805e5e \
    get_balance \
    --network=sepolia --strk
----

If this was the first time the `increase_balance` was invoked, the result should resemble the following (`42~10~ = 2a~16~`):

[source,console]
----
[
    "0x000000000000000000000000000000000000000000000000000000000000002a"
]
----

