= Deploying and interacting with a smart contract

== Introduction

Welcome to the fourth installment of Starknet 101!

Now that your contract is declared, it can finally be deployed. This installment of the series will therefore guide you through the steps necessary to deploy your contract on Starknet Sepolia and interact with it.

== Deploying a smart contract

Deploying a smart contract involves creating an instance of a previously declared code on Starknet. The deployment command requires the contract's class hash and any arguments expected by its constructor. For our example, if the constructor expects an integer, the deployment command would resemble the following: 

[source,console]
----
$ starkli deploy \
    0x00e68b4b07aeecc72f768b1c086d9b0aadce131a40a1067ffb92d0b480cf325d \
    42 \
    --network=sepolia
----

After running the command and adding your password, the output should resemble the following:

[source,bash]
----
Deploying class 0x00e68b4b07aeecc72f768b1c086d9b0aadce131a40a1067ffb92d0b480cf325d with salt 0x04bc3fc2284c8e41fb3d2a37bb0354fd0506131cc77a8c91e4e67ce3aed1d19e...
The contract will be deployed at address 0x014825acb37c36563d3b96c450afe363d2fdfa3cfbd618b323f95b68b55ebf7e
Contract deployment transaction: 0x0086972e7463d5673d8b553ae521ec2df974a97c2ce6aafc1d1c20d22c6b96c6
Contract deployed: 0x014825acb37c36563d3b96c450afe363d2fdfa3cfbd618b323f95b68b55ebf7e
----

== Interacting with a smart contract

Now that your contract has been deployed, you (and everyone else) are able to interact with it. Starkli enables interaction with smart contracts via two primary methods:

* `call for` read-only functions.

* `invoke` for write functions that modify Starknet's state.

=== Calling a function

The `call` command allows querying a smart contract function without sending a transaction. As an example you can use the `get_owner` function which doesn't expect any arguments and returns the address of the current owner:

[source,bash]
----
starkli call \
    0x014825acb37c36563d3b96c450afe363d2fdfa3cfbd618b323f95b68b55ebf7e \
    get_owner --network=sepolia
----

This will return the address that we passed to the constructor during deployment:

[source,bash]
----
[
    "0x02cdab749380950e7a7c0deff5ea8edd716feb3a2952add4e5659655077b8510"
]
----

=== Invoking a function

To modify the state of the smart contract, use the `invoke` command. Unlike the `call` command, `invoke` submits a transaction to the network.

In this example, we'll invoke the `transfer_ownership` function to transfer the ownership from our deployer address to a different smart wallet address:

[source,bash]
----
starkli invoke \
    0x014825acb37c36563d3b96c450afe363d2fdfa3cfbd618b323f95b68b55ebf7e \
    transfer_ownership \
    0x011088d3cbe4289bc6750ee3a9cf35e52f4fa4e0ac9f42fb0b62e983139e135a \
    --network=sepolia
----

After the transaction is accepted on L2, you can confirm the state transition by calling the `get_owner` function again:

[source,bash]
----
starkli call \
    0x014825acb37c36563d3b96c450afe363d2fdfa3cfbd618b323f95b68b55ebf7e \
    get_owner \
    --network=sepolia
----

The `get_owner` function now returns the new owner address, confirming the successful ownership transfer.

