= Deploying a smart contract

== Introduction

Welcome to the fourth installment of Starknet 101!

Now that your contract is declared, it can finally be deployed. This installment of the series will therefore guide you through the steps necessary to deploy your contract on Starknet Sepolia and interact with it.

== Deploying a smart contract

Deploying a smart contract involves creating an instance of a previously declared code on Starknet. The deployment command requires the contract's class hash and any arguments expected by its constructor.

For our example, the constructor expects an address to assign as the owner:

[source,bash]
----
starkli deploy \
    <CLASS_HASH> \
    <CONSTRUCTOR_INPUTS> \
    --network=sepolia
----

With the class hash and constructor inputs, the command looks like this:

[source,bash]
----
starkli deploy \
    0x00e68b4b07aeecc72f768b1c086d9b0aadce131a40a1067ffb92d0b480cf325d \
    0x02cdAb749380950e7a7c0deFf5ea8eDD716fEb3a2952aDd4E5659655077B8510 \
    --network=sepolia
----

== Expected result

After running the command and adding your password, you will see an output similar to this:

[source,bash]
----
Deploying class 0x00e68b4b07aeecc72f768b1c086d9b0aadce131a40a1067ffb92d0b480cf325d with salt 0x04bc3fc2284c8e41fb3d2a37bb0354fd0506131cc77a8c91e4e67ce3aed1d19e...
The contract will be deployed at address 0x014825acb37c36563d3b96c450afe363d2fdfa3cfbd618b323f95b68b55ebf7e
Contract deployment transaction: 0x0086972e7463d5673d8b553ae521ec2df974a97c2ce6aafc1d1c20d22c6b96c6
Contract deployed: 0x014825acb37c36563d3b96c450afe363d2fdfa3cfbd618b323f95b68b55ebf7e
----

The smart contract has now been deployed to Starknet.
