[id="setup"]
= Setting up your Starknet development environment

== Introduction

Welcome to the first installment of the "Hello, Starknet!" quickstart series, the official tutorial for starting your journey as a Starknet developer! 🚀

As a popular phrase (often attributed to Abraham Lincoln) says, "Give me six hours to chop down a tree, and I will spend the first four sharpening the axe". The first installment of the series will therefore guide you through setting up your development environment, which will include the four most recommended tools to begin developing on Starknet:

* _Scarb_, a build toolchain and package manager for Cairo and Starknet ecosystems

* _Starknet Foundry_, the go-to framework for building and testing Starknet Smart Contracts

* _Starknet Devnet_, a Rust implementation of a local Starknet node

* _Starkli_, a command-line interface that allows you to interact with Starknet


[TIP]
====
To review these tools in more detail, as well as all other Starknet developer tools, check out the xref:tools:devtools/overview.adoc[Tooling section].
====

[#installing-rust]
== Installing Rust

Installing Scarb, Starknet Foundry, Starkent Devnet, and Starkli require https://www.rust-lang.org/[Rust] to be installed. You can verify that Rust is installed and up-to-date by running:

    rustc --version

or install the latest Rust version by following the instructions in the https://doc.rust-lang.org/beta/book/ch01-01-installation.html[Rust documentation].

[#installing-scarb-and-snfoundry]
== Installing Scarb, Starknet Foundry, and Starknet Devnet

=== MacOS and Linux

You can install Scarb and Starknet Foundry via the link:https://github.com/software-mansion/starkup[Starkup]. Starkup uses the link:https://asdf-vm.com/[`asdf` version manager] under the hood to install these tools, which makes easy to switch between different versions—both globally and on a per-project basis (see full details in the link:https://asdf-vm.com/manage/commands.html[`asdf` documentation] or by running `asdf --help`). 

While Starkup automatically installs `asdf`, you may need to update it manually later. If you prefer to install `asdf` on your own, follow the instructions in the link:https://asdf-vm.com/guide/getting-started.html[`asdf` documentation].

Starkup installs the following tools:

* _Scarb_, the Cairo package manager
* _Starknet Foundry_, the Cairo and Starknet testing framework
* _Universal Sierra Compiler_, compiler for any ever-existing Sierra version
* _Cairo Profiler_, profiler for Cairo programming language & Starknet
* _Cairo Coverage_, utility for coverage reports generation for code written in Cairo programming language
* _CairoLS_, vscode extension

Note that Starkup does not install Starknet Devnet, so you will need to install it separately using `asdf`.

.Procedure

. Install Scarb and Starknet Foundry via Starkup:
+
[source,terminal]
----
curl --proto '=https' --tlsv1.2 -sSf https://sh.starkup.dev | sh
----
+
Follow the instructions displayed on the screen.

. Verify that Scarb and Starknet Foundry are installed correctly:
+
[source,terminal]
----
scarb --version
snforge --version && sncast --version
----

. Install the Starknet Devnet plugin via `asdf`:
+
[source,terminal]
----
asdf plugin add starknet-devnet
----

. Install the latest versions of Starknet Devnet:
+
[source,terminal]
----
asdf install starknet-devnet latest
----
or
+
[source,terminal]
----
asdf install starknet-devnet
----

. Verify that Starknet Devnet is installed correctly:
+
[source,terminal]
----
starknet-devnet --version
----


=== Windows

Both Scarb's, Starknet Foundry's, and Starknet Devnet's installations on Windows requires manual setup.

.Procedure

. Follow the instructions in the link:https://docs.swmansion.com/scarb/download.html#windows[Scarb documentation^], https://foundry-rs.github.io/starknet-foundry/getting-started/installation.html#installation-on-windows[Starknet Foundry documentation^], and https://0xspaceshard.github.io/starknet-devnet/docs/intro/#windows-installation[Starknet Devnet documentation^].

. Restart the terminal and verify that Scarb, Starknet Foundry, and Starknet Devnet are installed correctly:
+
[source,terminal]
----
scarb --version
snforge --version && sncast --version
starknet-devnet --version
----

[#installing-starkli]
== Installing Starkli

=== MacOS and Linux

It is highly recommended to install Starkli on MacOS and Linux using the link:https://get.starkli.sh[`starkliup` portable script]. `starkliup` manages shell configuration for you, and using any other installation method requires to link:https://book.starkli.rs/shell-completions[manually set up shell completions].

.Procedure

. Download `starkliup`:
+
[source,terminal]
----
curl https://get.starkli.sh | sh
----

. Restart the terminal and install Starkli:
+
[source,terminal]
----
starkliup
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,terminal]
----
starkli --version
----

=== Windows

Starknet Foundry's installation on Windows requires manually setting up shell completions.

.Procedure

. Install Starkli:
+
[source,terminal]
----
cargo install --locked --git https://github.com/xJonathanLEI/starkli
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,terminal]
----
starkli --version
----
+

. Set up Starkli's shell completions by following the instructions in the link:https://book.starkli.rs/shell-completions[Starkli documentation].
