[id="setup"]
= Setting up your Starknet development environment

include::partial$snippet-important-troubleshooting.adoc[]

== Introduction

Welcome to the first installment of the "Hello, Starknet!" quickstart series, the official tutorial for starting your journey as a Starknet developer! 🚀

As a popular phrase (often attributed to Abraham Lincoln) says, "Give me six hours to chop down a tree, and I will spend the first four sharpening the axe". The first installment of the series will therefore guide you through setting up your development environment, which will include the four most recommended tools to begin developing on Starknet:

* _Scarb_, a build toolchain and package manager for Cairo and Starknet ecosystems

* _Starknet Foundry_, the go-to framework for building and testing Starknet Smart Contracts

* _Starknet Devnet_, a Rust implementation of a local Starknet node

[TIP]
====
To review these tools in more detail, as well as all other Starknet developer tools, check out the xref:tools:overview.adoc[Tooling section].
====

[#installing-scarb-and-snfoundry]
== Installing Scarb and Starknet Foundry

=== MacOS and Linux

On MacOS and Linux, Scarb and Starknet Foundry can be easily installed using the https://github.com/software-mansion/starkup[Starkup installer^] by running:

[source,terminal]
----
curl --proto '=https' --tlsv1.2 -sSf https://sh.starkup.sh | sh
----

and following the onscreen instructions. You can verify that Scarb and Starknet Foundry are installed correctly by running:

[source,terminal]
----
scarb --version
snforge --version && sncast --version
----

[NOTE]
====
Starkup installs Scarb and Starknet Foundry Devnet on MacOS and Linux via the https://asdf-vm.com/[`asdf` version manager^], which allows to easily switch between their different versions, both globally and per project (see full details in the https://asdf-vm.com/manage/commands.html[`asdf` documentation^] or by running `asdf --help`). Alongside Scarb and Starknet Foundry, Starkup uses `asdf` to install additional useful tools, including the https://github.com/software-mansion/universal-sierra-compiler[Universal Sierra Compiler^], https://github.com/software-mansion/cairo-profiler[Cairo Profiler^], https://github.com/software-mansion/cairo-coverage[Cairo Coverage^], and https://github.com/software-mansion/cairols[CairoLS^].

If you encounter any issues while using it or have any requests, please help by https://github.com/software-mansion/starkup/issues/new[submitting an issue^].
====

=== Windows

Both Scarb's and Starknet Foundry's installations on Windows requires manual setup. To do so, follow the instructions in the https://docs.swmansion.com/scarb/download.html#windows[Scarb documentation^] and https://foundry-rs.github.io/starknet-foundry/getting-started/installation.html#installation-on-windows[Starknet Foundry documentation^]. When complete, restart the terminal and verify that Scarb and Starknet Foundry are installed correctly by running:

[source,terminal]
----
scarb --version
snforge --version && sncast --version
----

[#installing-devnet]
== Installing Starknet Devnet

=== MacOS and Linux

xref:#installing-scarb-and-snfoundry[Similar to Scarb and Starknet Foundry], it is highly recommended to install Starknet Devnet on MacOS and Linux via the `asdf` version manager. Luckily, if you installed Scarb and Starknet Foundry using the Starkup installer, you should already have `asdf` installed. To install Starknet Devnet using `asdf`:

. Verify that `asdf` is installed:
+
[source,terminal]
----
asdf --version
----
+
or install it by following the instructions in the link:https://asdf-vm.com/guide/getting-started.html[`asdf` documentation].

. Install the `asdf` Starknet Devnet plugin:
+
[source,terminal]
----
asdf plugin add starknet-devnet
----

. Install the latest version of Starknet Devnet:
+
[source,terminal]
----
asdf install starknet-devnet latest
----

. Set global version for Starknet Devnet:
+
[source,terminal]
----
asdf set -u starknet-devnet latest
----

. Restart the terminal and verify that Starknet Devnet is installed correctly:
+
[source,terminal]
----
starknet-devnet --version
----

=== Windows

Starknet Devnet's installation on Windows requires manual setup. To do so, follow the instructions in the https://0xspaceshard.github.io/starknet-devnet/docs/intro/#windows-installation[Starknet Devnet documentation^]. When complete, restart the terminal and verify that Starknet Devnet is installed correctly by running:

[source,terminal]
----
starknet-devnet --version
----