[id="setup"]
= Setting up your environment

== Introduction

Welcome to the first installment of Starknet 101, the official guide for starting your journey as a Starknet developer!

As a popular phrase (often attributed to Abraham Lincoln) says, "Give me six hours to chop down a tree, and I will spend the first four sharpening the axe". The first installment of the series will therefore guide you through installing the three most recommended tools to begin developing on Starknet:

* _Scarb_, a build toolchain and package manager for Cairo and Starknet ecosystems.

* _Starknet Foundry_, the go-to framework for building and testing Starknet Smart Contracts

* _Starkli_, a command-line interface that allows you to interact with Starknet.

[TIP]
====
To review these tools in more detail, as well as all other Starknet developer tools, check out the xref:tools:devtools/overview.adoc[Tooling section].
====

[#installing-scarb-and-snfoundry]
== Installing Scarb and Starknet Foundry

=== MacOS and Linux

on MacOS and Linux, it is highly recommended to install both Scarb and Starknet Foundry via the link:https://asdf-vm.com/[`asdf` version manager]. Installing Scarb and Starknet Foundry with `asdf` allows to easily switch between their different versions, both globally and per project (see full details in the link:https://asdf-vm.com/manage/commands.html[`asdf` documentation] or by running `asdf --help`).

.Procedure

. Verify that `asdf` is installed:
+
[source,console]
----
$ asdf --version
----
+
or install it by following the instructions in the link:https://asdf-vm.com/guide/getting-started.html[`asdf` documentation].

. Install the `asdf` Scarb and Starknet Foundry plugins:
+
[source,console]
----
$ asdf plugin add scarb
$ asdf plugin add starknet-foundry
----

. Install the latest versions of Scarb and Starknet Foundry:
+
[source,console]
----
$ asdf install scarb latest
$ asdf install starknet-foundry latest
----

. Set global versions for Scarb and Starknet Foundry (need for using `scarb init`):
+
[source,console]
----
$ asdf global scarb latest
$ asdf global starknet-foundry latest
----

. Restart the terminal and verify that Scarb and Starknet Foundry are installed correctly:
+
[source,console]
----
$ scarb --version
$ snforge --version
$ sncast --version
----

=== Windows

Both Scarb's and Starknet Foundry's installation on Windows requires manual setup.

.Procedure

. Follow the instructions in the link:https://docs.swmansion.com/scarb/download.html#windows[Scarb documentation] and https://foundry-rs.github.io/starknet-foundry/getting-started/installation.html#installation-on-windows[Starknet Foundry documentation]

. Restart the terminal and verify that Scarb is installed correctly:
+
[source,console]
----
$ scarb --version
$ snforge --version
$ sncast --version
----

[#installing-starkli]
== Installing Starkli

=== MacOS and Linux

It is highly recommended to install Starkli on MacOS and Linux using the link:https://get.starkli.sh[`starkliup` portable script]. `starkliup` manages shell configuration for you, and using any other installation method requires to link:https://book.starkli.rs/shell-completions[manually set up shell completions].

.Procedure

. Download `starkliup`:
+
[source,console]
----
$ curl https://get.starkli.sh | sh
----

. Restart the terminal and install Starkli:
+
[source,console]
----
$ starkliup
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,console]
----
$ starkli --version
----

=== Windows

Starknet Foundry's installation on Windows requires manually setting up shell completions.

.Procedure

. Install Starkli:
+
[source,console]
----
$ cargo install --locked --git https://github.com/xJonathanLEI/starkli
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,console]
----
$ starkli --version
----
+

. Set up Starkli's shell completions by following the instructions in the link:https://book.starkli.rs/shell-completions[Starkli documentation].
