[id="setup"]
= Setting up your Starknet development environment

include::partial$snippet-important-troubleshooting.adoc[]

== Introduction

Welcome to the first installment of the "Hello, Starknet!" quickstart series, the official tutorial for starting your journey as a Starknet developer! 🚀

As a popular phrase (often attributed to Abraham Lincoln) says, "Give me six hours to chop down a tree, and I will spend the first four sharpening the axe". The first installment of the series will therefore guide you through setting up your development environment, which will include the four most recommended tools to begin developing on Starknet:

* _Scarb_, a build toolchain and package manager for Cairo and Starknet ecosystems

* _Starknet Foundry_, the go-to framework for building and testing Starknet Smart Contracts

* _Starknet Devnet_, a Rust implementation of a local Starknet node

* _Starkli_, a command-line interface that allows you to interact with Starknet


[TIP]
====
To review these tools in more detail, as well as all other Starknet developer tools, check out the xref:tools:devtools/overview.adoc[Tooling section].
====

[#installing-rust]
== Installing Rust

Installing Scarb, Starknet Foundry, Starkent Devnet, and Starkli require https://www.rust-lang.org/[Rust] to be installed. You can verify that Rust is installed and up-to-date by running:

[source,terminal]
----
rustc --version
----

or install the latest Rust version by following the instructions in the https://doc.rust-lang.org/beta/book/ch01-01-installation.html[Rust documentation].

[#installing-scarb-and-snfoundry]
== Installing Scarb and Starknet Foundry

=== MacOS and Linux

On MacOS and Linux, Scarb and Starknet Foundry can be easily installed using the https://github.com/software-mansion/starkup[Starkup installer^] by running:

[source,terminal]
----
curl --proto '=https' --tlsv1.2 -sSf https://sh.starkup.sh | sh
----

and following the onscreen instructions. You can verify that Scarb and Starknet Foundry are installed correctly by running:

[source,terminal]
----
scarb --version
snforge --version && sncast --version
----

[NOTE]
====
The Starkup installer installs Starknet Devnet on MacOS and Linux via the https://asdf-vm.com/[`asdf` version manager^], which allows to easily switch between their different versions, both globally and per project (see full details in the https://asdf-vm.com/manage/commands.html[`asdf` documentation^] or by running `asdf --help`)

If you encounter any issues while using it or have any requests, please help by https://github.com/software-mansion/starkup/issues/new[submitting an issue^].
====

=== Windows

Both Scarb's and Starknet Foundry's installations on Windows requires manual setup. To do so, follow the instructions in the https://docs.swmansion.com/scarb/download.html#windows[Scarb documentation^] and https://foundry-rs.github.io/starknet-foundry/getting-started/installation.html#installation-on-windows[Starknet Foundry documentation^]. When complete, restart the terminal and verify that Scarb and Starknet Foundry are installed correctly by running:

[source,terminal]
----
scarb --version
snforge --version && sncast --version
----

[#installing-devnet]
== Installing Starknet Devnet

=== MacOS and Linux

It is highly recommended to install Starknet Devnet on MacOS and Linux via the https://asdf-vm.com/[`asdf` version manager^], as it allows to easily switch between their different versions, both globally and per project (see full details in the https://asdf-vm.com/manage/commands.html[`asdf` documentation^] or by running `asdf --help`). Luckily, if you xref:#installing-scarb-and-snfoundry[installed Scarb and Starknet Foundry using the Starkup installer], `asdf` should already be installed in your machine. To install Starknet Devnet using `asdf`:

. Verify that `asdf` is installed:
+
[source,terminal]
----
asdf --version
----
+
or install it by following the instructions in the link:https://asdf-vm.com/guide/getting-started.html[`asdf` documentation].

. Install the `asdf` Starknet Devnet plugin:
+
[source,terminal]
----
asdf plugin add starknet-devnet
----

. Install the latest version of Starknet Devnet:
+
[source,terminal]
----
asdf install starknet-devnet latest
----

. Set global version for Starknet Devnet:
+
[source,terminal]
----
asdf global starknet-devnet latest
----

. Restart the terminal and verify that Starknet Devnet is installed correctly:
+
[source,terminal]
----
starknet-devnet --version
----

=== Windows

Starknet Devnet's installation on Windows requires manual setup. To do so, follow the instructions in the https://0xspaceshard.github.io/starknet-devnet/docs/intro/#windows-installation[Starknet Devnet documentation^]. When complete, restart the terminal and verify that Starknet Devnet is installed correctly by running:

[source,terminal]
----
starknet-devnet --version
----

[#installing-starkli]
== Installing Starkli

=== MacOS and Linux

It is highly recommended to install Starkli on MacOS and Linux using the https://get.starkli.sh[`starkliup` portable script^]. `starkliup` manages shell configuration for you, and using any other installation method requires to https://book.starkli.rs/shell-completions[manually set up shell completions^]. To install Starkli using `starkliup`:

. Download `starkliup`:
+
[source,terminal]
----
curl https://get.starkli.sh | sh
----

. Restart the terminal and install Starkli:
+
[source,terminal]
----
starkliup
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,terminal]
----
starkli --version
----

=== Windows

Starknet Foundry's installation on Windows requires manually setting up shell completions. To do so:

. Install Starkli:
+
[source,terminal]
----
cargo install --locked --git https://github.com/xJonathanLEI/starkli
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,terminal]
----
starkli --version
----
+

. Set up Starkli's shell completions by following the instructions in the link:https://book.starkli.rs/shell-completions[Starkli documentation].
