[id="setup"]
= Setting up your Starknet development environment

include::partial$snippet-important-troubleshooting.adoc[]

== Introduction

Welcome to the first installment of the "Hello, Starknet!" quickstart series, the official tutorial for starting your journey as a Starknet developer! 🚀

As a popular phrase (often attributed to Abraham Lincoln) says, "Give me six hours to chop down a tree, and I will spend the first four sharpening the axe". The first installment of the series will therefore guide you through setting up your development environment, which will include the four most recommended tools to begin developing on Starknet:

* _Scarb_, a build toolchain and package manager for Cairo and Starknet ecosystems

* _Starknet Foundry_, the go-to framework for building and testing Starknet Smart Contracts

* _Starknet Devnet_, a Rust implementation of a local Starknet node

* _Starkli_, a command-line interface that allows you to interact with Starknet


[TIP]
====
To review these tools in more detail, as well as all other Starknet developer tools, check out the xref:tools:overview.adoc[Tooling section].
====

[#installing-scarb-and-snfoundry]
== Installing Scarb and Starknet Foundry

=== MacOS and Linux

On MacOS and Linux, Scarb and Starknet Foundry can be easily installed using the https://github.com/software-mansion/starkup[Starkup installer^] by running:

[source,terminal]
----
curl --proto '=https' --tlsv1.2 -sSf https://sh.starkup.sh | sh
----

and following the onscreen instructions. You can verify that Scarb and Starknet Foundry are installed correctly by running:

[source,terminal]
----
scarb --version
snforge --version && sncast --version
----

[NOTE]
====
Starkup installs Scarb and Starknet Foundry Devnet on MacOS and Linux via the https://asdf-vm.com/[`asdf` version manager^], which allows to easily switch between their different versions, both globally and per project (see full details in the https://asdf-vm.com/manage/commands.html[`asdf` documentation^] or by running `asdf --help`). Alongside Scarb and Starknet Foundry, Starkup uses `asdf` to install additional useful tools, including the https://github.com/software-mansion/universal-sierra-compiler[Universal Sierra Compiler^], https://github.com/software-mansion/cairo-profiler[Cairo Profiler^], https://github.com/software-mansion/cairo-coverage[Cairo Coverage^], and https://github.com/software-mansion/cairols[CairoLS^].

If you encounter any issues while using it or have any requests, please help by https://github.com/software-mansion/starkup/issues/new[submitting an issue^].
====

[#installing-devnet]
== Installing Starknet Devnet

=== MacOS and Linux

xref:#installing-scarb-and-snfoundry[Similar to Scarb and Starknet Foundry], it is highly recommended to install Starknet Devnet on MacOS and Linux via the `asdf` version manager. Luckily, if you installed Scarb and Starknet Foundry using the Starkup installer, you should already have `asdf` installed. To install Starknet Devnet using `asdf`:

. Verify that `asdf` is installed:
+
[source,terminal]
----
asdf --version
----
+
or install it by following the instructions in the link:https://asdf-vm.com/guide/getting-started.html[`asdf` documentation].

. Install the `asdf` Starknet Devnet plugin:
+
[source,terminal]
----
asdf plugin add starknet-devnet
----

. Install the latest version of Starknet Devnet:
+
[source,terminal]
----
asdf install starknet-devnet latest
----

. Set global version for Starknet Devnet:
+
[source,terminal]
----
asdf set -u starknet-devnet latest
----

. Restart the terminal and verify that Starknet Devnet is installed correctly:
+
[source,terminal]
----
starknet-devnet --version
----

[#installing-starkli]
== Installing Starkli

=== MacOS and Linux

It is highly recommended to install Starkli on MacOS and Linux using the https://get.starkli.sh[`starkliup` portable script^]. `starkliup` manages shell configuration for you, and using any other installation method requires to https://book.starkli.rs/shell-completions[manually set up shell completions^]. To install Starkli using `starkliup`:

. Download `starkliup`:
+
[source,terminal]
----
curl https://get.starkli.sh | sh
----

. Restart the terminal and install Starkli:
+
[source,terminal]
----
starkliup
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,terminal]
----
starkli --version
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,terminal]
----
starkli --version
----
+

. Set up Starkli's shell completions by following the instructions in the link:https://book.starkli.rs/shell-completions[Starkli documentation].

[#Dev-env-windows]
== Setting up dev environment on Windows

Setting up Scarb and Starknet Foundry on Windows requires configuring the Windows Subsystem for Linux (WSL) and installing the tools inside a Linux distribution such as Ubuntu. Follow the steps below to complete the installation.

=== Install WSL and Ubuntu

. Open *PowerShell as Administrator* and run:
+
[source,terminal]
----
wsl --install
----
+
This command installs WSL along with the default Ubuntu distribution. If WSL or virtualization is not yet enabled, reboot and re-run the command as needed.

. Restart your computer when prompted.

. After reboot, launch *Ubuntu* from the Start menu. On the first launch, create a UNIX username and password when prompted.

[TIP]
====
If `wsl --install` does not work, enable WSL manually with:

[source,terminal]
----
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
----

Then install Ubuntu from the Microsoft Store: https://aka.ms/wslstore
====

=== Install Prerequisites in Ubuntu

. Open the Ubuntu terminal and run:
+
[source,terminal]
----
sudo apt update
sudo apt install -y curl git build-essential
----

=== Install Homebrew (Linuxbrew)

. Run the Homebrew install script:
+
[source,terminal]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
----

. Add Homebrew to your shell environment:
+
[source,terminal]
----
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
source ~/.profile
----

. Verify the installation:
+
[source,terminal]
----
brew --version
----

=== Install ASDF (Version Manager)

. Install ASDF using Homebrew:
+
[source,terminal]
----
brew install asdf
----

. Add ASDF to your shell:
+
[source,terminal]
----
echo '. "$(brew --prefix asdf)/libexec/asdf.sh"' >> ~/.bashrc
source ~/.bashrc
----

. Verify ASDF is working:
+
[source,terminal]
----
asdf --version
----

=== Install Scarb and Starknet Foundry via ASDF

. Add the Scarb plugin:
+
[source,terminal]
----
asdf plugin add scarb
----

. Install the latest Scarb version:
+
[source,terminal]
----
asdf install scarb latest
asdf global scarb latest
----

. Add the Starknet Foundry plugin:
+
[source,terminal]
----
asdf plugin add starknet-foundry
----

. Install the latest Starknet Foundry version:
+
[source,terminal]
----
asdf install starknet-foundry latest
asdf global starknet-foundry latest
----

. Restart your terminal and verify installation:
+
[source,terminal]
----
scarb --version
snforge --version && sncast --version
----

[NOTE]
====
Using `asdf` allows you to easily switch between versions of Scarb and Starknet Foundry globally or per project. If commands like `scarb` or `snforge` are not recognized, try running `source ~/.bashrc` or restarting your terminal.
====