[id="setup"]
= Setting up your Starknet development environment

== Introduction

Welcome to the first installment of the "Hello, Starknet!" quickstart series, the official tutorial for starting your journey as a Starknet developer! 🚀

As a popular phrase (often attributed to Abraham Lincoln) says, "Give me six hours to chop down a tree, and I will spend the first four sharpening the axe". The first installment of the series will therefore guide you through setting up your development environment, which will include the four most recommended tools to begin developing on Starknet:

* _Scarb_, a build toolchain and package manager for Cairo and Starknet ecosystems

* _Starknet Foundry_, the go-to framework for building and testing Starknet Smart Contracts

* _Starknet Devnet_, a Rust implementation of a local Starknet node

* _Starkli_, a command-line interface that allows you to interact with Starknet


[TIP]
====
To review these tools in more detail, as well as all other Starknet developer tools, check out the xref:tools:devtools/overview.adoc[Tooling section].
====

[#installing-rust]
== Installing Rust

Installing Scarb, Starknet Foundry, Starkent Devnet, and Starkli require https://www.rust-lang.org/[Rust] to be installed. You can verify that Rust is installed and up-to-date by running:

    rustc --version

or install the latest Rust version by following the instructions in the https://doc.rust-lang.org/beta/book/ch01-01-installation.html[Rust documentation].

[#installing-scarb-and-snfoundry]
== Installing Scarb, Starknet Foundry, and Starknet Devnet

=== MacOS and Linux

It is highly recommended to install Scarb, Starknet Foundry, and Starknet Devnet on MacOS and Linux via the link:https://asdf-vm.com/[`asdf` version manager], as it allows to easily switch between their different versions, both globally and per project (see full details in the link:https://asdf-vm.com/manage/commands.html[`asdf` documentation] or by running `asdf --help`).

.Procedure

. Verify that `asdf` is installed:
+
[source,terminal]
----
asdf --version
----
+
or install it by following the instructions in the link:https://asdf-vm.com/guide/getting-started.html[`asdf` documentation].

. Install the `asdf` Scarb, Starknet Foundry, and Starknet Devnet plugins:
+
[source,terminal]
----
asdf plugin add scarb
asdf plugin add starknet-foundry
asdf plugin add starknet-devnet
----

. Install the latest versions of Scarb, Starknet Foundry, and Starknet Devnet:
+
[source,terminal]
----
asdf install scarb latest
asdf install starknet-foundry latest
asdf install starknet-devnet latest
----

. Set global versions for Scarb, Starknet Foundry, and Starknet Devnet:
+
[source,terminal]
----
asdf set -u scarb latest
asdf set -u starknet-foundry latest
asdf set -u starknet-devnet latest

# For asdf versions older than 0.16.0:
asdf global scarb latest
asdf global starknet-foundry latest
asdf global starknet-devnet latest
----

. Restart the terminal and verify that Scarb, Starknet Foundry, and Starknet Devnet are installed correctly:
+
[source,terminal]
----
scarb --version
snforge --version && sncast --version
starknet-devnet --version
----

=== Windows

Both Scarb's, Starknet Foundry's, and Starknet Devnet's installations on Windows requires manual setup.

.Procedure

. Follow the instructions in the link:https://docs.swmansion.com/scarb/download.html#windows[Scarb documentation^], https://foundry-rs.github.io/starknet-foundry/getting-started/installation.html#installation-on-windows[Starknet Foundry documentation^], and https://0xspaceshard.github.io/starknet-devnet/docs/intro/#windows-installation[Starknet Devnet documentation^].

. Restart the terminal and verify that Scarb, Starknet Foundry, and Starknet Devnet are installed correctly:
+
[source,terminal]
----
scarb --version
snforge --version && sncast --version
starknet-devnet --version
----

[#installing-starkli]
== Installing Starkli

=== MacOS and Linux

It is highly recommended to install Starkli on MacOS and Linux using the link:https://get.starkli.sh[`starkliup` portable script]. `starkliup` manages shell configuration for you, and using any other installation method requires to link:https://book.starkli.rs/shell-completions[manually set up shell completions].

.Procedure

. Download `starkliup`:
+
[source,terminal]
----
curl https://get.starkli.sh | sh
----

. Restart the terminal and install Starkli:
+
[source,terminal]
----
starkliup
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,terminal]
----
starkli --version
----

=== Windows

Starknet Foundry's installation on Windows requires manually setting up shell completions.

.Procedure

. Install Starkli:
+
[source,terminal]
----
cargo install --locked --git https://github.com/xJonathanLEI/starkli
----

. Restart the terminal and verify that Starkli is installed correctly:
+
[source,terminal]
----
starkli --version
----
+

. Set up Starkli's shell completions by following the instructions in the link:https://book.starkli.rs/shell-completions[Starkli documentation].
