[id="setup"]
= Setting up your environment

== Overview

In order to use Starknet, you need to install several tools. This section will walk you through installing the three most recommended tools to begin developing on Starknet:

* xref:tools:devtools/clis.adoc#starkli[Starkli], a command-line interface that allows you to interact with Starknet.

* xref:tools:devtools/smart-contract-tools.adoc#scarb[Scarb], a build toolchain and package manager for Cairo and Starknet ecosystems.

* xref:tools:devtools/smart-contract-tools.adoc#starknet_foundry[Starknet Foundry], the go-to framework for building and testing Starknet Smart Contracts

To review all Starknet developer tools, check out the xref:tools:devtools/overview.adoc[tools and resources section].

[#installing_starkli]
== Setting up Starkli

=== MacOS and Linux installation

It is highly recommended to install Starkli on MacOS and Linux using the link:https://get.starkli.sh[`starkliup` portable script]. `starkliup` manages shell configuration for you, and using any other installation method requires to link:https://book.starkli.rs/shell-completions[manually set up shell completions].

.Procedure

. Download `starkliup`:
+
[source,shell]
----
curl https://get.starkli.sh | sh
----

. Restart the terminal and install Starkli:
+
[source,shell]
----
starkliup
----

. Restart the terminal and verify that Starkli is installated correctly:
+
[source,shell]
----
starkli --version
----

=== Windows installation

Starknet Foundry's installation on Windows requires manually setting up shell completions.

.Procedure

. Install Starkli:
+
[source,shell]
----
cargo install --locked --git https://github.com/xJonathanLEI/starkli
----

. Restart the terminal and verify that Starkli is installated correctly:
+
[source,shell]
----
starkli --version
----
+

. Set up Starkli's shell completions by following the instructions in the link:https://book.starkli.rs/shell-completions[Starkli documentation].

[#setting_environment_variables_for_starkli]
=== Environment variables setup

For the majority of flags available on Starkli you can set environment variables to make the commands shorter and easier to manage.

Setting environment variables for Starkli significantly simplifies command execution and management, thereby enhancing efficiency, readability, and control when using Starkli.

The two primary environment variables that are vital for effective usage of Starkli's CLI are:

[horizontal,labelwidth="25"]
`STARKNET_ACCOUNT`:: The location of the xref:set-up-an-account.adoc#creating_an_account_descriptor[Account Descriptor] file.
`STARKNET_KEYSTORE`:: The location of the keystore file for the xref:set-up-an-account.adoc#creating_a_signer[Signer].

The following sections assume these environment variables are set as follows:

[source,bash]
----
export STARKNET_ACCOUNT=~/.starkli-wallets/deployer/account.json
export STARKNET_KEYSTORE=~/.starkli-wallets/deployer/keystore.json
----

[#installing_scarb]
== Setting up Scarb

=== MacOS and Linux installation

It is highly recommended to install Scarb on MacOS and Linux via the link:https://asdf-vm.com/[`asdf` version manager]. Installing Scarb with `asdf` seamlessly integrates with the Cairo xref:tools:devtools/vscode.adoc[Cairo VSCode extension], and allows to easily switch between different versions of Scarb, both globally and per project (see full details in the link:https://asdf-vm.com/manage/commands.html[`asdf` documentation] or by running `asdf --help`).

.Procedure

. Verify that `asdf` is installed:
+
[source, bash]
----
asdf --version
----
+
or install it by following the instructions in the link:https://asdf-vm.com/guide/getting-started.html[`asdf` documentation].

. Install the `asdf` Scarb plugin:
+
[source, bash]
----
asdf plugin add scarb
----

. Install the latest version of Scarb:
+
[source, bash]
----
asdf install scarb latest
----

. Verify that Scarb is installed correctly:
+
[source, bash]
----
scarb --version
----

. Set a global version for Scarb (need for using `scarb init`):
+
[source, bash]
----
asdf global scarb latest
----

=== Windows installation

Scarb's installation on Windows requires manual setup.

.Procedure

. Follow the instructions in the link:https://docs.swmansion.com/scarb/download.html#windows[Scarb documentation].

. Restart the terminal and verify that Scarb is installed correctly:
+
[source, bash]
----
scarb --version
----

[#starknet_foundry_setup]
== Setting up Starknet Foundry

=== MacOS and Linux installation

It is highly recommended to install Starknet Foundry on MacOS and Linux using the link:https://asdf-vm.com/[`asdf` version manager]. Installing Starknet Foundry with `asdf` allows to easily switch between different versions of Starknet Foundry, both globally and per project (see full details in the link:https://asdf-vm.com/manage/commands.html[`asdf` documentation] or by running `asdf --help`).

.Procedure

. Verify that `asdf` is installed, or install it by following the instructions on the link:https://asdf-vm.com/guide/getting-started.html[`asdf` documentation].

. Install the `asdf` Starknet Foundry plugin:
+
[source, bash]
----
asdf plugin add starknet-foundry
----

. Install the latest version of Starknet Foundry:
+
[source, bash]
----
asdf install starknet-foundry latest
----

. Set a global version for Starknet Foundry using `asdf` (need for using `scarb init`):
+
[source, bash]
----
asdf global starknet-foundry latest
----

. Restart the terminal and verify that Starknet Foundry is installed correctly:
+
[source, bash]
----
snforge --version
sncast --version
----

=== Windows installation

Starknet Foundry's installation on Windows requires manual setup.

.Procedure

. Follow the instructions in the link:https://foundry-rs.github.io/starknet-foundry/getting-started/installation.html#installation-on-windows[Starknet Foundry documentation].
. Restart the terminal and verify that Starknet Foundry is installed correctly:
+
[source, bash]
----
snforge --version
sncast --version
----
