[id="next-steps]

= Recommended next steps on your Starknet journey

Welcome to the fifth and final installment of the "Hello, Starknet!" quickstart series, the official tutorial for starting your journey as a Starknet developer! 🚀

By now you've successfully declared, deployed, and interacted with the `HelloStarknet`, both on Starknet Sepolia and locally (way to go!). This last installment of the series will therefore list the various next steps you can take on your Starknet journey:

* Learn more about Starknet's xref:architecture-and-concepts:accounts/introduction.adoc[architecture], xref:tools:devtools/overview.adoc[tooling], or xref:tools:fullnodes-rpc-providers.adoc[ecosystem]
* Watch the latest https://starknet.notion.site/Starknet-Basecamp-Hub-1541b3c1f49f439da872d3d71647d834[Starknet Basecamp^], or join an upcoming one
* Complete the https://starklings.app/[Starklings^] and https://speedrunstark.com/[Speedrun Stark^] coding challenges
* Apply for a https://www.starknet.io/grants/[seed or growth grant^] 
// * Grow your app through a https://www.starknet.io/grants/growth-grants/[growth grant^]

Good luck! We can't wait to see the new and innovative things you'll bring to Starknet 🌟
