= Setting up an account

== Introduction

Interactions with Starknet such as declaring, deploying, and interacting with Starknet smart contracts require a deployed account.
Starkli supports both importing an already deployed account (e.g., created by Argent or Braavos) as well as creating and deploying new account from scratch. 

In this tutorial, we will use Starkli to create and deploy a new account on Starknet Sepolia.

== Prerequisites

Ensure that the following command shows the version information for Starkli:
[source, bash]
----
starkli --version
----
If this command fails, see xref:environment-setup.adoc[Setting up your environment].

== Creating a signer

Creating a Starkli account requires first creating a Starkli signer, which Starkli uses to sign transactions.
Theoratically, a signer can be anything that can provide valid signatures for transactions.

In this tutorial, we will use an encrypted keystores signer.
Encrypted keystores are JSON files that follow the Web3 secret storage definition.
A password must be supplied to create a keystore, and is required for subsequently using the keystore.
The main advantage of this approach is that it prevents storing the private key as plain text on your computer.

To create a new encrypted keystore signer, run:

[source,terminal]
----
starkli signer keystore new keystore.json
----

and enter a password that will be used to encrypt your private key. The result should be similar to the following:

[source,terminal]
----
Created new encrypted keystore file: ~/.starkli-accounts/my-first-account/keystore.json
Public key: 0x03dfdb739fbd3ddab0f851bf1131079e31ca266c7af94f05cef4d9481f837509
----

Although not mandory, exporting the keystore path is highly recommended as it prevents specifying `--keystore` in every command. To export the keystore path, run:

[source,terminal]
----
export STARKNET_KEYSTORE=$(pwd)/keystore.json
----

== Creating an account

Now that you have a Starkli signer, a new account can be created by running:

[source,terminal]
----
starkli account oz init account.json
----

[NOTE]
====
`oz` stand for OpenZeppelin, which, along with Argent and Braavos, are the accounts variants supported by Starkli.
====

The result should be similar to the following:

[source,terminal]
----
Created new account config file: ~/.starkli-accounts/my-first-account/account.json

Once deployed, this account will be available at:
    0x01cf4d57ba01109f018dec3ea079a38fc08b789e03de4df937ddb9e8a0ff853a

Deploy this account by running:
    starkli account deploy account.json
----

Similar to the keystore, exporting the account path is highly recommended as it prevents specifying `--account` in every command. To export the account path, run:

[source,terminal]
----
export STARKNET_ACCOUNT=$(pwd)/account.json
----

== Deploying an account

Finally, to deploy your account run:

[source,terminal]
----
starkli account deploy account.json
----

This command sends a `DEPLOY_ACCOUNT` transaction, which requires the account to contain enough ETH to pay for the transaction fee. 
When run, the command shows instructions on how to fund the account before proceeding.
You can fund your wallet using one of the https://www.starknet.io/en/ecosystem/bridges-and-onramps[Starknet Sepolia faucets^].

[NOTE]
====
To sends the `DEPLOY_ACCOUNT` transaction with STRK as fee token, use:
[source,terminal]
----
starkli account deploy account.json --strk
----
====

The following is an example output for a successful account deployment:

[source,terminal]
----
The estimated account deployment fee is 0.000011483579723913 ETH. However, to avoid failure, fund at least:
    0.000017225369585869 ETH
to the following address:
    0x01cf4d57ba01109f018dec3ea079a38fc08b789e03de4df937ddb9e8a0ff853a
Press [ENTER] once you've funded the address.
Waiting for transaction 0x06a9a08208084ac376f10657c745a3020362fa65e7730b13e08ec03d0cd7e59d to confirm.
If this process is interrupted, you will need to run `starkli account fetch` to update the account file.
Transaction not confirmed yet...
Transaction 0x06a9a08208084ac376f10657c745a3020362fa65e7730b13e08ec03d0cd7e59d confirmed
----