= Declare, deploy, and interact with a smart contract using Staknet Foundry

This tutorial guides you through deploying a Cairo smart contract onto Starknet Devnet.

== Prerequisites

The following tools are installed:

* Starknet Foundry
* Scarb
* Starknet Devnet

== Create a new project

Create a new project using the `snforge` command. Let's name it `hello_starknet`.

[source, bash]
----
snforge init hello_starknet
----

You will get a `Scarb.toml` similar to the one below.

[source, toml]
----
[package]
name = "hello_starknet"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.5.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.25.0" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
----

Then you can check the `lib.cairo` file.

[source, cairo]
----
#[starknet::interface]
pub trait IHelloStarknet<TContractState> {
    fn increase_balance(ref self: TContractState, amount: felt252);
    fn get_balance(self: @TContractState) -> felt252;
}

#[starknet::contract]
mod HelloStarknet {
    #[storage]
    struct Storage {
        balance: felt252, 
    }

    #[abi(embed_v0)]
    impl HelloStarknetImpl of super::IHelloStarknet<ContractState> {
        fn increase_balance(ref self: ContractState, amount: felt252) {
            assert(amount != 0, 'Amount cannot be 0');
            self.balance.write(self.balance.read() + amount);
        }

        fn get_balance(self: @ContractState) -> felt252 {
            self.balance.read()
        }
    }
}
----

== Compile contract and import an account

Compile your contract using scarb.

[source, bash]
----
scarb build
----

Having compiled the smart contract, it's time to import a prefunded account from Starknet Devnet.

== Create profile and import account

Launch https://0xspaceshard.github.io/starknet-devnet-rs/[Starknet Devnet].

[source, bash]
----
starknet-devnet --seed 42
----

After starting Starknet Devnet, a list of accounts is automatically generated and deployed. We use the `--seed` flag to keep the same pre-configured accounts each time we initiate Starknet Devnet.

We look at the first generated account.

[source, bash]
----
| Account address |  0x34ba56f92265f0868c57d3fe72ecab144fc96f97954bbbc4252cef8e8a979ba
| Private key     |  0xb137668388dbe9acdfa3bc734cc2c469
| Public key      |  0x5a5e37c60e77a0318643b111f88413a76af6233c891a0cfb2804106372006d4
----

With this information, we have to import that account and create our profile to interact with Starknet Foundry. Execute:

[source, bash]
----
sncast --url http://127.0.0.1:5050 account add --name my_devnet_account \ 
--address 0x34ba56f92265f0868c57d3fe72ecab144fc96f97954bbbc4252cef8e8a979ba \
--private-key 0xb137668388dbe9acdfa3bc734cc2c469 --type oz --add-profile my_profile
----

Upon successful command execution, you'll obtain a `snfoundry.toml` with your profile information.

== Declare contract

To declare your contract, execute:

[source, bash]
----
sncast --profile my_profile declare --contract-name HelloStarknet
----

Upon successful command execution, you'll obtain a contract class hash. This unique hash serves as the identifier for your contract class within Starknet.

[source, bash]
----
class_hash: 0x49b56635f966772662a4af0c9be97e739d43a3d8c0d5384a6471f515cfafa78
transaction_hash: 0x960268ca9750455902bd74ef6195d4721bc6c3813dd895105fb66ce8bcdcc1
----

== Deploy contract

[source, bash]
----
sncast --profile <profile> deploy <class_hash_of_the_contract_to_be_deployed> --constructor-calldata <constructor_calldata>...
----

For this contract, we did not specify a `constructor` function, so we don't need to pass any constructor arguments.

[source, bash]
----
sncast --profile my_profile deploy --class-hash 0x183cc71fac33a2823d5afb59ed7679e2e872b305acff9c57ebe0e70fea59ef3
----


After running, expect an output similar to:

[source, bash]
----
contract_address: 0x45c66e339f547ebce72ec16de4bd2597037c155b9a069a77847f20c6d279be7
transaction_hash: 0x1fcf59d8524e2a9773457952fd35b097f94fca31ecbb1d07cd9c40f4abf3091
----

== Call contract

The first parameter is your profile, the second parameter is the contract address, the third parameter is the function to be called.

[source, bash]
----
sncast --profile my_profile call --contract-address 0x39a9a0f739ad27293656951fb65f715d3d1bf45947b45da92554969e1d41f10 --function get_balance
----

After running, expect an output similar to:

[source, bash]
----
command: call
response: [0x0]
----

It means the value of `balance` is zero.

== Invoke contract

The first parameter is your profile, the second parameter is the contract address, the third parameter is the function to be invoked, and the fourth parameter is the function parameter.
Let's set the value of `balance` to 6.

[source, bash]
----
sncast --profile my_profile invoke --contract-address 0x39a9a0f739ad27293656951fb65f715d3d1bf45947b45da92554969e1d41f10 --function increase_balance --calldata 6
----

Let's retrieve the new value of `balance`

[source, bash]
----
sncast --profile my_profile call --contract-address 0x39a9a0f739ad27293656951fb65f715d3d1bf45947b45da92554969e1d41f10 --function get_balance
----

After running, expect an output similar to:

[source, bash]
----
command: call
response: [0x6]
----

Awesome! You deployed and interacted with a Cairo smart contract using Starknet Devnet and Starknet Foundry!
You can now build more complex smart contracts and interact with them using the same process.
