= "Hello, Starknet!" quickstart tutorial troubleshooting

== Setting up your environment

=== Starkli unable to detect shell

.Procedure 

. Detect whether your shell is `zsh` or `bash`:
+
[source,terminal]
----
echo $SHELL
----

. Add:
+
[source,terminal]
----
. /Users/<NAME>/.starkli/env
----
+
to either `~/.zshrc` or `~/.bashrc`.

. Restart the terminal, and run either:
+
[source,terminal]
----
source ~/.zshrc
----
+
or:
+
[source,terminal]
----
source ~/.bashrc
----

== Declaring, deploying, and interacting with HelloStarknet locally

=== `scarb build` fails to run version command for Rust

Starting from Scarb version 2.10 and Starknet Foundry version 0.37.0, Rust is longer required for projects with the following line in the `Scarb.toml` file:

[source,cairo]
----
[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
----

If you don't have all three rules met, and you don't have Rust installed, you will get a compilation error when running `scarb build` (and `scarb test`). To resolve this, simply update Scarb, Starknet Foundry, and your `Scarb.toml` file according to the aforementioned conditions. If you wish to continue using older version of Scarb and Starknet Foundry, you can https://www.rust-lang.org/tools/install[install Rust^] instead. 

=== `starkli declare` unable to identify compiler version

When using `starkli declare`, Starkli will do its best to identify the compiler version of the declared class. In case it fails, the `--compiler-version` flag can be used to specify the version of the compiler.

.Procedure 

. Find the compiler versions supported by Starkli by running:
+
[source,terminal]
----
starkli declare --help 
----
+
and looking for the possible values of the `--compiler-version` flag.

. Find the current Scarb version in use:
+
[source,terminal]
----
scarb --version
----

. In case a different compiler version is required, switch to a different Scarb version using `asdf`:

.. Install the desired Scarb version:
+
[source,terminal]
----
asdf install scarb <VERSION>
----

.. Select the desired Scarb version as the local version for the project:
+
[source,terminal]
----
asdf local scarb <VERSION>
----

== Deploying and interacting with HelloStarknet on Sepolia

[#fetching-a-predeployed-sepolia-account]
=== Fetching a predeployed Sepolia account

.Procedure 

. Export the private key from your wallet by:
* For Argent wallets: navigating to `Settings` -> `<YOUR_ACCOUNT>` -> `Export Private Key`.
* For Braavos wallets: navigating to `Settings` -> `Privacy and Security` -> `Export Private Key`.
. Create a keystore file by running:
+
[source,terminal]
----
starkli signer keystore from-key keystore.json
----
+
and entering the private key of your smart wallet, along with a password that will be used to encrypt it.
. Fetch the account by running:
+
[source,terminal]
----
starkli account fetch \
    <SMART_WALLET_ADDRESS> \
    --output account.json \
    --network=sepolia
----