= Using the `HelloStarknet` contract

== Introduction

Welcome to the third installment of the "Hello, Starknet!" quickstart series, the official tutorial for starting your journey as a Starknet developer! 🚀

Starknet smart contracts are a special subset of Cairo programs that, once deployed, can have access to Starknet's state. The third installment of the series will therefore walk you though generating and understanding Scarb's default `HelloStarknet` contract.

[TIP]
====
For more details on Starknet smart contracts, see the xref:architecture-and-concepts:smart-contracts/contract-classes.adoc[Contracts section].
====

== Generating `HelloStarknet`

Scarb's default `HelloStarknet` contract can be generated by simply running:

[source,console]
----
$ scarb new hello_starknet
----

and select the default Starknet Foundry as a test runner.

[NOTE]
====
Generating `HelloStarknet` with Scarb requires https://www.rust-lang.org/[Rust] to be installed. You can verify that Rust is installed and up-to-date by running:

    rustc --version

or install the latest Rust version by following the instructions in the https://doc.rust-lang.org/beta/book/ch01-01-installation.html[Rust documentation].
====

For the purpose of this tutorial, you can ignore all files in the `hello_starknet` directory other than `hello_starknet/src/lib.cairo`, which holds the contract's code.

== Understanding `HelloStarknet`

Looking at `HelloStarknet` 's code:

[#example-cairo-contract]
[source,cairo]
----
/// Interface representing `HelloContract`.
/// This interface allows modification and retrieval of the contract balance.
#[starknet::interface]
pub trait IHelloStarknet<TContractState> {
    /// Increase contract balance.
    fn increase_balance(ref self: TContractState, amount: felt252);
    /// Retrieve contract balance.
    fn get_balance(self: @TContractState) -> felt252;
}

/// Simple contract for managing balance.
#[starknet::contract]
mod HelloStarknet {
    use core::starknet::storage::{StoragePointerReadAccess, StoragePointerWriteAccess};

    #[storage]
    struct Storage {
        balance: felt252,
    }

    #[abi(embed_v0)]
    impl HelloStarknetImpl of super::IHelloStarknet<ContractState> {
        fn increase_balance(ref self: ContractState, amount: felt252) {
            assert(amount != 0, 'Amount cannot be 0');
            self.balance.write(self.balance.read() + amount);
        }

        fn get_balance(self: @ContractState) -> felt252 {
            self.balance.read()
        }
    }
}
----

it's clear that this is a simple contract with two basic functions:

* `increase_balance`, which get `amount` as input, increases the contract's balance by `amount`, and write the new balance to its storage.
* `get_balance`, which read the contract's current balance.
