[id="starknet-compiler-options"]
= Legacy compiler CLI reference

When the Starknet compiler is installed, you can view this command-line help in a terminal by entering the following command:

[source,bash]
----
starknet-compile --help
----

== Usage

[source,bash,subs="+quotes,+macros"]
----
starknet-compile [-h] [--abi _ABI_] [--disable_hint_validation]
                      [--account_contract] [--dont_filter_identifiers] [-v]
                      [--prime __PRIME__] [--cairo_path CAIRO_PATH]
                      [--preprocess] [--output __OUTPUT__] [--no_debug_info]
                      [--debug_info_with_source]
                      [--cairo_dependencies __CAIRO_DEPENDENCIES__]
                      [--no_opt_unused_functions]
                      file [__file__ ...]
----

== Example

The following example compiles the file `contract.cairo`. It generates two files:

[horizontal]
contract_compiled.json:: The contract class. This file contains the bytecode and all other information necessary to execute a contract. For information on contract classes, see xref:architecture:smart-contracts/contract-classes.adoc[].
contract_abi.json:: The contract's ABI.

[source,shell]
----
starknet-compile contract.cairo \
    --output contract_compiled.json \
    --abi contract_abi.json
----




== Description

A tool to compile Starknet contracts.

== Positional arguments


=== file

File names.

== Optional arguments


=== `-h`, `--help`

Show this help message and exit.

=== `--abi _ABI_`

Output the contract's ABI.

=== `--disable_hint_validation`

Disable the hint validation.

=== `--account_contract`

Compile as account contract.

=== `--dont_filter_identifiers`

Disable the filter-identifiers-optimization.If True, all the identifiers will be kept, instead of just the ones mentioned in hints or 'with_attr' statements.

=== `-v`, `--version`

show program's version number and exit

=== `--prime _PRIME_`

The size of the finite field.

=== `--cairo_path _CAIRO_PATH_`

A list of directories, separated by ":" to resolve import paths. The full list will consist of directories defined by this argument, followed by the environment variable CAIRO_PATH, the working directory and the standard library path.

=== `--preprocess`

Stop after the preprocessor step and output the preprocessed program.

=== `--output _OUTPUT_`

The output file name (default: `stdout`).

=== `--no_debug_info`

Don't include debug information in the compiled file.

=== `--debug_info_with_source`

Include debug information with a copy of the source code.

=== `--cairo_dependencies _CAIRO_DEPENDENCIES_`

Output a list of the Cairo source files used during the compilation as a CMake file.

=== `--no_opt_unused_functions`

Disables unused function optimization.