[id="upcoming"]
= Release notes

[TIP]
====
You can get the latest version updates delivered to your inbox by subscribing to the link:https://www.starknet.io/starknet-devs-newsletter/[Starknet Devs Newsletter].
====

[id="version0.13.3"]
== Starknet v0.13.3 (November 20, 24)

[discrete]
=== New features and enhancements
* State diff compression: Starknet submits compressed state diffs to L1
* Squashing discount factor: Users pay for the expected marginal contribution of their transaction to the blobs sent to L1

[discrete]
=== DA format
* The uncompressed encoding of contract diff headers changes to:
+
[stem]
++++
\underbrace{\text{new_nonce (if changed)}}_{\text{64 bits}} |
\underbrace{\text{n_updates}}_{\text{8 or 64 bits}} | \underbrace{\text{n_updates_len}}_{\text{1 bit}} | \underbrace{\text{flag}}_{\text{1 bit}}
++++
+
where:

** The semantics of `flag` is unchanged (i.e., it indicates whether or not the class was replaced)
** `n_updates_len` is 0 if the number of updates is less than 256 (and therefore can fit in 8 bits), and 1 otherwise
** `n_updates` can spread over 8 or 64 bits, depending on `n_updates_len`
** If the nonce of the contract is unchanged, the value of `new_nonce` is zero (and not the unchanged nonce)

[discrete]
=== Additional resources

Community Forum Posts:

* link:https://community.starknet.io/t/fall-roadmap-updates/115001[Fall roadmap updates]

[id="version0.13.2"]
== Starknet v0.13.2 (August 28, 24)

[discrete]
=== New features and enhancements

* Optimistic parallelization in the sequencer.
* Applicative recursion ("blockpacking"): pack a contiguous sequence of blocks into a single L1 state update, instead of just one block. This change also affects the Starknet core contract on L1 and the structure of data availability:
** The contract will store also the hash of the "aggregator" program, alongside the hash of the Starknet OS.
** The link:https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/starknet/solidity/Starknet.sol#L36[LogStateUpdate] event will be emitted once for every sequence of blocks in an applicative tree, rather than for every block.
** The data posted on L1 is now the output of the aggregator, instead of the OS. The link:https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/starknet/core/os/output.cairo#L25[OsOutputHeader] struct will contain four new fields: `prev_block_number`, `prev_block_hash`, `os_program_hash`, `full_output`.
* New block hash definition: see the reference implementation link:https://github.com/starkware-libs/sequencer/blob/b6955bbd59635d37a12f9070a3f0b8a8db74f7c1/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L67[here].



[discrete]
=== API changes

==== Feeder gateway

* All objects containing the block hash will use the new block hash computation.
* Receipts will contain a new property `total_gas_consumed`, only for transactions after v0.13.2.
* Three new builtins can appear in the `builtin_instance_counter` property of `execution_resources` in the transaction receipts: `add_mod`, `mul_mod` and `range_check96`.
* End support for the endpoints `get_block_traces` and `get_transaction_trace`.

==== JSON RPC

No changes in v0.13.2. The new JSON RPC version v0.8.0 will be released alongside Starknet v0.13.3.



[discrete]
=== Cairo

A new compiler version will be released for v0.13.2, Cairo v2.7.0. This includes a Sierra upgrade to v1.6.0, i.e. contracts compiled with the new compiler will only be accepted on Starknet v0.13.2 onwards.

The Starknet-related features that will be added in this Cairo version include:

* sha256 syscall - syscall for computing sha256 on an arbitrary length input:
** link:https://github.com/starkware-libs/cairo/blob/f5ac2d1d24ae0a626e9925db0c564bd0c4fea433/corelib/src/sha256.cairo#L24[High level code] for using sha256/
** link:https://github.com/starkware-libs/blockifier/blob/b22fb076a7db5e0fcdd2048a6fb579b0b1d25561/crates/blockifier/resources/versioned_constants.json#L284[Syscall cost] - the dominant part of the syscall is ~1.1k bitwise builtin applications which today costs ~180 L1 gas (the 2k steps are negligible in comparison). The syscall is applied once for ~14 `u32`.
* Circuit builtin - the new compiler version will introduce a way to define ad-hoc algebraic circuits in Cairo. Circuits use the new `mul_mod` and `add_mod` builtins under the hood.
** Example usage can be found in link:https://github.com/starkware-libs/cairo/blob/39095a2a717b5bf3a76c813186f0a9cd0e087948/corelib/src/test/circuit_test.cairo#L24[circuit_test.cairo].


[discrete]
=== Others

Errors prettifying: execution errors are becoming more link:https://github.com/starkware-libs/blockifier/blob/8417325e6990af64e93253b1f76cb70611516cd2/crates/blockifier/src/execution/syscalls/hint_processor.rs#L69[structured], which will be the basis for better error handling in the next JSON RPC version, resulting in nice error displays by wallets.

[discrete]
=== Additional resources

Community Forum Posts:

* link:https://community.starknet.io/t/starknet-v0-13-2-pre-release-notes/114223[Starknet v0.13.2 pre-release notes]
* link:https://community.starknet.io/t/optimistic-parallelization-revived/114121[Optimistic parallelization revived]
* link:https://community.starknet.io/t/upcoming-feature-starknet-applicative-recursion/113868[Upcoming Feature: Starknet Applicative Recursion]
* link:https://community.starknet.io/t/cairo-v2-7-0-is-coming/114362[Cairo v2.7.0 is coming!]


[id="version0.13.1.1"]
== Starknet v0.13.1.1 (April 15, 24)

In response to community feedback, Starknet 0.13.1.1 reduces class declaration fees and increases the calldata limit:

|===
| Resource | Gas cost (0.13.1) | Gas cost (0.13.1.1)

| CASM bytecode | 28 gas/felt | 1 gas/felt
| Sierra bytecode | 28 gas/felt | 1 gas/felt
| ABI | 0.875 gas/character | 0.032 gas/character
|===

|===
|Entity | Limit (0.13.1) | Limit (0.13.1.1)

| Calldata length (felts) | 4,000 | 5,000
|===

[id="version0.13.1"]
== Starknet v0.13.1 (March 13, 24)

[discrete]
=== New features and enhancements

* *Cheaper data availability (DA):* Starknet uses link:https://eips.ethereum.org/EIPS/eip-4844[EIP-4844]. State diffs are now blobs, rather than calldata, requiring the addition of `data_gas` to the Starknet block header.
* Time-related syscalls when called from an account contract's `+__validate__+`, `+__validate_deploy__+`, `+__validate_declare__+`, or `constructor` function:
** `block_timestamp` returns the hour, rounded down.
** `block_number` returns the block number, rounded down to the nearest multiple of 100.
* *Optimization:* Load into memory only the functions in a contract that are actually used when generating the proof.

[discrete]
=== Block header updates
The block header includes the following new fields:

* `l1_da_mode`: A string enum that takes the value `CALLDATA` or `BLOB`, and indicates whether EIP-4844 is the data availability solution that is used for the block. Also appears in pending block.
* `l1_data_gas_price`: Contains `price_in_wei` and `price_in_fri`, where 1 fri is 10^-18^ STRK. Also appears in pending block.
* `l1_gas_price`: Replaces `eth_l1_gas_price` and `strk_l1_gas_price`. Contains the data gas price (EIP-4844) in addition to the regular gas price.

[discrete]
=== API: JSON RPC

[discrete]
==== Starknet API JSON RPC 0.6.0

Starknet 0.13.1 is backward compatible with `starknet_api_openrpc.json` v0.6.0. Responses from 0.13.1 can be mapped naturally into v0.6.0 objects.

[discrete]
==== Starknet API JSON RPC 0.7.0

A new version of `starknet_api_openrpc.json`, 0.7.0, accommodates the changes introduced by Starknet using EIP-4844.

.`BLOCK_HEADER` includes two new fields to support EIP-4844:

* `l1_data_gas_price`: contains `price_in_wei` and `price_in_fri` (10^-18^ denominations, similar to https://github.com/starkware-libs/starknet-specs/blob/49665932a97f8fdef7ac5869755d2858c5e3a687/api/starknet_api_openrpc.json#L3766[v0.6.0]).
* `l1_da_mode`: An enum that indicates whether this block will use calldata or blobdata and can take the following values:
** `CALLDATA`
** `BLOB`

.`FEE_ESTIMATE`

* Includes two new fields:
** `data_gas_consumed`
** `data_gas_price`
* `overall_fee` is now: +
`gas_consumed` × `gas_price` + `data_gas_consumed` × `data_gas_price`
* Fee estimates will change depending on the data availability solution used by current Starknet blocks. For example, if you estimate the fee against the pending block, and it’s currently using `CALLDATA`, then nodes are expected to return `data_gas_consumed=0` and compute the fee similarly to today, that is, get higher estimates.

.Receipts and traces now include data availability resources

* `COMMON_RECEIPT_PROPERTIES`, the main receipt object, now includes a new entry: execution_resources.
* The `EXECUTION_RESOURCES` object now includes the field `data_availability`. Note that the resources of internal calls will remain the same/
* For more information, see the https://github.com/starkware-libs/starknet-specs/pull/187/files[PR for the API JSON RPC specs]

.`EXECUTION_RESOURCES`

* Computation resources are separated from data availability resources. This is done by introducing the `data_availability` property, which includes `l1_gas` and `l1_data_gas`, which were consumed due to DA requirements. One of these will always be zero, depending on whether or not the block uses calldata or blobs, as specified by the `l1_da_mode` field in the block header.
* Syscall costs are now included in the execution resources of traces and receipts. These are costs that are already being paid for but were not reported so far.

[discrete]
=== Pricing changes

[discrete]
==== Computation

* A Cairo step now costs 0.0025 gas/step, a 50% reduction.
* All builtins costs are accordingly reduced by 50%.

[discrete]
==== Calldata and signatures

Each felt in the calldata and signature arrays of all transaction types now costs 0.128 gas/felt.

[discrete]
==== Class declaration
* Each felt of a sierra_program in the contract class and of bytecode in the compiled contract class now costs 28 gas/felt.
+
[NOTE]
====
v1 `DECLARE` transactions only include bytecode.
====
* Each character in the ABI costs 0.875 gas.

[discrete]
==== Events

* An additional felt to the data array of an event now costs 0.128 gas/felt, similar to calldata.
* An additional felt to the keys array now costs 0.256 gas/felt.

[discrete]
=== Infrastructure updates

Starknet now supports multiple L1 providers.

[discrete]
=== Additional resources

Community Forum Posts:

* link:https://community.starknet.io/t/starknet-v0-13-1-eip4844-support-more-fee-reductions-stability-quality-of-life/112951[Starknet v0.13.1: EIP4844 Support, More Fee Reductions, Stability, Quality of Life]
* link:https://community.starknet.io/t/starknet-v0-13-1-fee-reduction/113552[Starknet v0.13.1: Fee Reduction]
* link:https://community.starknet.io/t/data-availability-with-eip4844/113065[Data availability with EIP4844]
* link:https://community.starknet.io/t/starknet-v0-13-1-pre-release-notes/113664[Starknet v0.13.1 pre-release notes]


[id="version0.13.0"]
== Starknet v0.13.0 (Jan 10, 24)

Starknet v0.13.0 is live on Mainnet.

Starknet 0.13.0 includes the following changes:

* v3 transactions, including:
** Fee payment in STRK
** Reserved fields for future features, such as Volition and payment master
* `get_block` API: The `gas_price` field is replaced by the `eth_l1_gas_price` and `strk_l1_gas_price` fields. This change applies also to existing blocks. For more information on the new fields, see the link:https://github.com/starkware-libs/starknet-specs/releases/tag/v0.6.0[JSON RPC API Spec on GitHub]
* Sierra v1.4.0. This new version of Sierra is part of Crate v2.4.0, in the Cairo 2.4.0 package. For more information, see link:https://community.starknet.io/t/cairo-v2-4-0-is-out/109275[Cairo v2.4.0 is out!] on the Community forum.
* Improved performance of `secp256k1_mul` and `secp256r1_mul` syscalls
* Computation cost is reduced by approximately 50% as a result of reduced Cairo steps and increased use of builtins. L1 data availability cost is reduced by approximately 10%-25%. For an ERC-20 transfer, the DA fee reduction is 25%.


[id="version0.12.3"]
== Starknet v0.12.3 (Nov 19, 23)

Starknet v0.12.3 is live on Mainnet.

This release partially removes support for the Starknet feeder gateway. For details, see link:https://community.starknet.io/t/feeder-gateway-deprecation/100233/1[Feeder Gateway Deprecation] in Development Proposals on the Starknet community forum.

Additionally, this version includes the following changes:

* Performance optimizations in the gateway, the computation of the Patricia storage root, and block hash
* Support for `secp256r1` syscalls in the Starknet OS.
* Restriction for `+__validate__+` and the constructor of `DeployAccount` transactions:
** Restrict access to `sequencer_address` in the `get_execution_info` syscall by returning ``0``'s for the address.
** Restrict access to the following syscalls:
*** Cairo contracts: `get_block_hash`
*** Cairo 0 contracts: `get_sequencer_address`

This version is available on both Goerli and Sepolia testnets.

[discrete]
=== Cairo 0

Move structs that are common to `secp256k1` and `secp256r1` to a separate file.


[id="version0.12.2"]
== Starknet v0.12.2 (Sep 04, 23)

Starknet v0.12.2 is live on Mainnet.

This version includes the following changes:

* Enabling P2P Authentication: An additional endpoint in the sequencer gateway to provide a signature on the state diff commitment and block hash.
* Resolving Mismatches in Queries: An extension to the `get_state_update` endpoint in the sequencer gateway that returns both the pending state diff and the pending block together.
* Increased maximum Cairo steps per transaction from 1 million to 3 million.

[id="version0.12.1"]
== Starknet v0.12.1 (Aug 21, 23)

Starknet v0.12.1 is live on Mainnet.

This version includes the following changes:

* Mempool Validation.
* Inclusion of Failed Transactions.
* Keccak builtin.

[id="version0.12.0"]
== Starknet v0.12.0 (July 12, 23)

Starknet v0.12.0 is live on Mainnet.

This version contains the following changes:

* Use the link:https://github.com/starkware-libs/blockifier[rust blockifier] and link:https://github.com/lambdaclass/cairo-vm[LambdaClass's Cairo VM] to accelerate the sequencer's time to handle transactions.
* Support link:https://github.com/starkware-libs/cairo/releases/tag/v2.0.0[version 2.0.0] of the Cairo compiler.
* Replace the `PENDING` status of transactions to `ACCEPTED_ON_L2` - once a transaction is in that status it means that it will be included in a block, this applies to transactions - blocks still have the `PENDING` status.
* Add an experimental `get_block_hash` syscall.
* Change HTTP error code from 500 to 400 on API errors.

[id="version0.11.2"]
== Starknet v0.11.2 (May 31, 23)

Starknet v0.11.2 is live on Mainnet.

This version contains the following changes:

* Upgrade Cairo 1.0 version to v1.0.0-rc0 (Cairo 1.0 activated on Starknet!)

[id="version0.11.1"]
== Starknet v0.11.1 (May 23, 23)

Starknet v0.11.1 is live on Mainnet.

This version contains the following changes:

* Upgrade Cairo 1.0 version to v1.0.0-rc0.

* Charged transaction fee is now based on an average Ethereum gas price instead of a single sample
(estimation API is unaffected).

* API changes:
** Remove the state root in `get_state_update` for pending blocks to allow faster responses
in future versions.

* Testing framework:
** Allow declaring (and interacting with) Cairo 1.0 contracts.
*** Currently, the Cairo 1.0 ABI is not supported yet, so a Cairo 0 ABI should be supplied to
`declare()` manually.
** Split `deploy()` to two phases declare and deploy: `deprecated_declare()` (for Cairo 0 contract) or
`declare()` (for Cairo 1.0 contracts) and `deploy()` (for both).
* Add current block hash to the Starknet Core Contract (currently not verified by the Starknet OS):
** Breaking change: The `LogStateUpdate` event's data is changed to include blockHash.

[id="version0.11.0"]
== Starknet v0.11.0 (Mar 29, 23)

Starknet v0.11.0 is live on Mainnet.


[NOTE]
====
`invoke` and `declare` transactions of version 0 are no longer supported on this version.
====

In Starknet v0.11.0, you can declare, deploy and run Cairo 1.0 smart contracts. We also introduce a new system call that allows a smooth transitioning of existing contracts to a Cairo 1.0 implementation.

Historically, contract classes have been defined in terms of Cairo assembly, or Casm for short (the class definition also included more information needed for execution, e.g., hint data). The novelty of Cairo 1.0 is the introduction of Sierra (Safe Intermediate Representation), an intermediate layer between Cairo 1.0 and Casm.

The introduction of Cairo 1.0 and Sierra has several effects on the system. Below we list the effects on each component; of particular note are:

* A new version of the `declare` transaction, which allows sending the new class structure
* The state commitment will now include contract classes
* Changes to the onchain data format
* New system call - `replace_class`


[id="version0.10.3"]
== Starknet v0.10.3 (Dec 12, 22)

[NOTE]
====
The `deploy` transaction is no longer supported on this version.
====

This version contains the following changes:

Starknet

*   Performance - Separate the state commitment computation from the execution of the transactions
*   Add `starknet-class-hash` command to compute the class hash of a compiled Starknet contract

Cairo:

*   Autoformatter: Automatically break lines inside expressions


[id="version0.10.2"]
== Starknet v0.10.2 (Nov 29, 22)

- This version introduces sequencer parallelization! This is the first step in our roadmap of performance upgrades. Details about the specific mechanism of parallelization and the roadmap in general are described in https://medium.com/starkware/starknet-performance-roadmap-bb7aae14c7de[this medium post]. 

- A new endpoint, `estimate_fee_bulk`, is added to the feeder gateway. This will allow estimating the fee of several transactions at once, where each transaction is executed relative to the resulting state from applying the previous one.

*   Sequencing performance improvements
*   Builtin ratio changes, which affects builtin costs
*   Add `estimate_fee_bulk` API that computes the fee of multiple transactions that will be executed consecutively

As part of this version, we will also increase the finality of transactions in the pending block, by fixing the timestamp at the time of the block creation. This will solve the issue of transactions moving from pending to rejected on account of too old timestamp

[id="version0.10.1"]
== Starknet v0.10.1 (Oct 25, 22)

This version contains the following changes:

Starknet:

*   Add `DeployAccount` transaction (which will replace the Deploy transaction for deploying account contracts). To use it, you should first add enough funds to your account address to pay the transaction fee, and then you can invoke DeployAccount
*   Split the `starknet deploy_account` CLI command into `starknet new_account` and `starknet deploy_account`
*   Account contracts that are expected to be deployed this way should implement the`__validate_deploy__()` entry point, which should check the signature of the `DeployAccount` transaction
*   Improve L1 fee computation: the fee is computed according to the diff of the storage state
*   API: Remove `entry_point_type` field from transaction information

Cairo:

*   Add `uint256_mul_div_mod` to `uint256.cairo`


[id="version0.10.0"]
== Starknet v0.10.0 (Sept 05, 22)

This version introduces the next step in Starknet's account abstraction design, specifically the validate/execute separation. See https://www.notion.so/starkware/Starknet-0-10-0-4ac978234c384a30a195ce4070461257[here] for more information.

This version contains the following changes:

Starknet:

*   Contract (breaking changes):
**   @external and @view functions should be imported directly by the main compiled file. Otherwise, they will not be usable as external functions
**   Forbid using the same storage variable name in two modules
*   New transaction version (version 1) for `invoke` and `declare` transactions:
**   Transactions of version 0 are deprecated and will not be supported in Starknet from the next version (v0.11.0). Please update your systems to use the new version

[NOTE]
====
In order to use transactions of version 1 you will need to upgrade your account contracts
====

**   Add nonce field to the transactions. Nonce validation is now part of the Starknet protocol and is enforced to be executed sequentially
**   `Invoke`:
***   Split `__execute__` to two functions:` __validate__` (only validates the transaction) and `__execute__` (only executes the transaction)
***   Remove the selector (which is now always `__execute__`) field, following the above change.
**   Declare:
***   `declare` transaction should now be sent from an account (and is validated using `__validate_declare__` in the account contract)
*   Support fee for sending L1 messages. At this point, it's not mandatory and messages with no fee will still be handled. Starting from the next version it will become mandatory.

Cairo:

Syntax changes in Cairo (to make it more similar to rust and C++):

*   You can use the cairo-migrate script to convert old code to the new syntax. Use the `-i` flag to apply the changes to the files
*   End statements with `;`

[NOTE]
====
New lines are still part of the language at this point, and you cannot put more than one instruction per line. This will change in Cairo1.0.
====

*   Use `{ … }` for code blocks (instead of `:` and `end`)
*   Add `()` around the condition of if statements
*   Remove the member keyword in structs
*   Change comment to use `//` instead of `#`
*   Use `..., ap++` instead of `...; ap++` in low level Cairo code
*   Support return types that are not tuples. For example, `func foo() -> felt` (instead of `func foo() -> (r: felt)`)
As a result, it's now mandatory to specify return types. `func foo() -> (res)` should be replaced by `func foo() -> (res: felt)`. The cairo-migrate tool does that automatically.
*   Return statement accepts expressions, rather than only tuples. For example, you can write `let x = (5,); return x;`
*   A few standard library functions were changed to return felt. The cairo-migrate script also fixes calls to those functions
*   Support using functions as expressions
*   This only applies to functions with -> felt signature`, whose ap change is known at compile-time (e.g., recursive functions cannot be used this way)
*   Fix a bug in the secp signature verification code that allowed a malicious prover to ignore the value of `v` (this does not let the prover fake a signature, but allows it to claim that a valid signature is invalid).
*   Add Cairo code for the recursive STARK verifier

Technical changes:
*   Move from python3.7 to python3.9


[id="version0.9.1"]
== Starknet v0.9.1 (July 20, 22)
This version contains the following changes:

Starknet:

API changes:

*   Add `get_block_traces` API - returns all the transaction traces of a given block
*   Add a list of declared contracts in `get_state_update`
*   Add a 0x prefix for class hash in the API
*   Add `starknet_version` field for blocks (only applies to new blocks)

Starknet CLI:

*   Change the default block number to pending
*   Using a wallet is the default, `--no_wallet` must be specified explicitly to override this
*   Deploying contracts:
**  Add `deploy_contract` function to the account contract created by `starknet deploy_account`
**  Use this function to deploy contract (unless using `--no_wallet`). In particular, `deploy` should be used after declaring the contract (it expects the contract class hash)
*   Support `--dry_run` to get the transaction information without signing or sending it
*   Support `deploy_from_zero` in the `deploy` syscall to deploy a contract to an address that does not depend on the deployer

Cairo:
*   Support and in if statements (`if x == y and z == w`). 

[NOTE]
====
At the moment other boolean combinations are not supported
====

[id="version0.9.0"]
== Starknet v0.9.0 (June 06, 22)

This version introduces the contract class/instance paradigm into Starknet. See https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/contract-classes/[here] for more information.

This version contains the following changes:

Starknet:

*   Enforce fees - `max_fee` must not be set to zero, and selector must be `__execute__`
*   Split the concepts of contract class and contract instance. 
*   Add `declare` transaction type
*   New API and CLI commands:
*   `declare` - Declares a contract class
*   `get_class_by_hash` - Returns the contract class given its hash
*   `get_class_hash_at` - Returns the class hash for a given contract instance address
*   Rename `delegate_call` to `library_call`, and change the contract address argument to class hash. 
*   Add a `deploy` system call.
*   Rename `ContractDefinition` to `ContractClass`
*   Reduce the compiled contract file's size by removing unnecessary identifiers (this optimization can be disabled using `--dont_filter_identifiers`)

Cairo:

*   Initial support for the `EC-op` builtin (scalar multiplication over the STARK curve). Not supported in Starknet yet.
*   Add additional helper methods to `blake2s.cairo`, including big-endian support

Technical changes:
*   Change function's `return` type from a struct to a named tuple. In particular, `foo.Return.SIZE` is no longer supported.
