[id="hash_functions"]
= Hash functions
:stem: latexmath

[id="domain_and_range"]
== Domain and range

All hashes outputs are eventually mapped to elements in stem:[$\mathbb{F}_p$] with stem:[$p=2^{251}+17\cdot 2^{192}+1$].

There are three hash functions used throughout Starknet's specifications:

* stem:[$sn\_keccak: \{0,1\}^* \rightarrow \mathbb{F}_p$]
* stem:[$pedersen: \mathbb{F}_p^2\rightarrow\mathbb{F}_p$]
* stem:[$poseidon: \mathbb{F}_p^*\rightarrow \mathbb{F}_p$]

[id="starknet_keccak"]
== Starknet Keccak

Starknet keccak, usually denoted by stem:[$sn\_keccak$], is defined as the first 250 bits of the Keccak256 hash (this is just Keccak256 augmented
in order to fit into a field element).

[id="pedersen_hash"]
== Pedersen hash



[id="poseidon_hash"]
== Poseidon hash

link:https://www.poseidon-hash.info/[Poseidon] is a family of hash functions designed to be very efficient as algebraic circuits. As such, they may be very useful in ZK proving systems such as STARKs and others.

Poseidon is a sponge construction based on the Hades permutation. Starknet's version of Poseidon is based on a three element state permutation (see exact parameters below).

We define the Poseidon hash of up to 2 elements below, see xref:#poseidon_array_hash[below] the arbitrary number of inputs version.

[stem]
++++
poseidon_1(x) := \left[\text{hades_permutation}(x,0,1)\right]_0
++++


[stem]
++++
poseidon_2(x,y) := \left[\text{hades_permutation}(x,y,2)\right]_0
++++

Where latexmath:[[\cdot\]_j] denotes taking the j'th coordinate of a tuple

Useful resources:

* The exact link:https://github.com/starkware-industries/poseidon/blob/main/poseidon3.txt[parameters] defining the permutation used in Starknet
* A link:https://github.com/CryptoExperts/poseidon[reference implementation] (in c and assembly) of the above by CryptoExperts


[id="array_hashing"]
== Array hashing

[id="pedersen_array_hash"]
=== Pedersen

Let stem:[$h$] denote the pedersen hash function, then given an array stem:[$a_1,...,a_n$] of stem:[$n$] field elements
we define stem:[$h(a_1,...,a_n)$] to be:

[stem]
++++
h(...h(h(0, a_1),a_2),...,a_n),n)
++++

[id="poseidon_array_hash"]
=== Poseidon

Let stem:[$\text{hades}:\mathbb{F}_p^3\rightarrow\mathbb{F}_p^3$] denote the Hades permutation (with Starknet's parameters), then given an array stem:[$a_1,...,a_n$] of stem:[$n$] field elements
we define stem:[$poseidon(a_1,...,a_n)$] to be the first coordinate of stem:[$H(a_1,...,a_n;0,0,0)$], where:

[stem]
++++
H(a_1,...,a_n;s_1,s_2,s_3)=\begin{cases}
H\big(a_3,...,a_n;\text{hades}(s_1+a_1, s_2+a_2, s_3)\big), & \text{if  } n\ge 2 \\
\text{hades}(s_1+a_1,s_2+1,s_3), & \text{if  } n=1 \\
\text{hades}(s_1+1,s_2,s_3), & \text{if  } n=0 \\
\end{cases}
++++

You can find an implementation of the above in Python link:https://github.com/starkware-libs/cairo-lang/blob/12ca9e91bbdc8a423c63280949c7e34382792067/src/starkware/cairo/common/poseidon_hash.py#L46[here],
and an equivalent Cairo implementation link:https://github.com/starkware-libs/cairo-lang/blob/12ca9e91bbdc8a423c63280949c7e34382792067/src/starkware/cairo/common/builtin_poseidon/poseidon.cairo#L28[here].
