[id="chain-info"]

= Chain information

[TIP]
====
You can get the latest updates delivered to your inbox by subscribing to the https://www.starknet.io/starknet-devs-newsletter/[Starknet Devs Newsletter^].
====

== Current versions

[%autowidth.stretch]
|===
|Environment |Starknet version|Sierra version|Cairo version

|Mainnet|0.13.5|1.7.0|2.0.0 - 2.11.0
|Sepolia|0.13.5|1.7.0|2.0.0 - 2.11.0
|===

== Current limits

[IMPORTANT]
====
The following limits are subject to revisions and change on a regular basis
====

[NOTE]
====
Starting from v0.13.0, blockifier-related constants and limits are defined for each Starknet version in a JSON file called `versioned_constants` in the https://github.com/starkware-libs/sequencer/tree/main/crates/blockifier/resources[blockifier's resources directory^].
====

[%autowidth.stretch]
|===
| Entity | Description | Sepolia | Mainnet

| Block time
| The maximum amount of time within which a pending block is closed, if no other limit is met.
| 30 seconds
| 30 seconds

| Block limit (Cairo steps)
| The maximum number of Cairo steps that can be completed
within each block to ensure block production times remain consistent and predictable.
| 40,000,000
| 40,000,000

| Block limit (gas)
| Certain Starknet operations, such as sending messages between L1 and L2, consume Ethereum gas. The current L1 state update
mechanism involves an Ethereum transaction for each Starknet block.

The gas limit for Starknet blocks is therefore inherited from the gas limit for Ethereum blocks.
| 5,000,000
| 5,000,000

| Max transaction size (Cairo steps)
| The maximum number of computational steps, measured in Cairo steps, that a transaction can contain when processed on the Starknet network.
This limit is important for ensuring the efficient execution of transactions and preventing potential congestion.
| 10,000,000
| 10,000,000

| Max state updates per transaction
| The maximum number of storage updates that a single transaction can generate. This limit helps maintain network stability and predictable performance.
| 2,000
| 2,000

| Max number of events per transaction
| The maximum number of events that a transaction can emit during its execution.
| 1,000
|  1,000

| Max number of data felts per event
| The maximum number of felts that an event can contain in its `data` array.
| 300
|  300

| Max number of key felts per event
| The maximum number of felts that an event can contain in its `keys` array.
| 50
| 50

| Max Cairo steps for `validate`
| The maximum number of computational steps, measured in Cairo steps, for a `validate` function.
| 1,000,000
| 1,000,000

| Max contract bytecode size
| The maximum size of the bytecode or program that a smart contract can have on Starknet.

Bytecode is the low-level code that comprises smart contracts. Limiting this size helps manage the complexity of contracts and the overall efficiency of the network.
| 81,290
|  81,290
| Max contract class size
| The maximum size for a contract class within Starknet.

Contract classes are a fundamental building block for smart contracts, and limiting their size can have implications for the network's scalability and security.
| 4,089,446 bytes
| 4,089,446 bytes

| IP address limits
| In order to reduce network spam, Starknet limits the amount of contract reads and writes that a single IP
address can make.
| 200 per min per IP address
| 200 per min per IP address

| Signature length (felts)
| The maximum length of a signature
| 4,000 
| 4,000

| Calldata length (felts)
| The maximum length of a transaction calldata
| 5,000
| 5,000
|===


== Deprecated features

[NOTE]
====
A deprecated feature is a feature that is still supported, but support will be removed in a future release of Starknet.
====

[%autowidth]
|===
| Name | Description

| Cairo 0
| xref:resources:version-notes.adoc#version0.11.0[Starknet v0.11.0] introduces Cairo 1.0 smart contracts.

| `v1` and `v2` transactions
| `v1` and `v2` transactions were removed from RPC version 0.8, used in Starknet 0.13.5. In future Starknet upgrades, Starknet will stop accepting `v1` and `v2` transactions altogether, and only accept `v3` transactions.
|===

== Unsupported and removed features

[NOTE]
====
An unsupported feature is a feature that is no longer supported.

A removed feature is a feature that has been entirely removed.
====

[cols="1,3"]
|===
| Name | Description

| Starknet CLI
| Support for the Starknet CLI has been removed. Instead use xref:tools:interacting-with-starknet.adoc[Starkli or Starknet Foundry's `sncast`].

| Goerli testnet
a| Goerli testnet support was removed April 2, 2024. Sepolia testnet replaces Goerli testnet.

Starknet started migrating to Sepolia testnet on November 15th, 2023.  For more information on the Goerli deprecation, see https://ethereum.org/nb/developers/docs/networks/#ethereum-testnets[the deprecation announcement on Ethereum's site].

Full nodes, API services, SDKs, and other Starknet developer tools have migrated to Sepolia as well.

[NOTE]
====
Sepolia's state and history are relatively small. Sepolia xref:resources:version-notes.adoc[supports declaring classes of CairoZero and Cairo v2.0.0 and higher].
====

| Starknet feeder gateway
a| The Starknet feeder gateway, a temporary solution for querying the sequencer's state, is being replaced by Starknet full nodes (Pathfinder, Juno, Deoxys, Papyrus) and RPC services. For more information, see xref:ecosystem:fullnodes-rpc-providers.adoc[Full nodes and API services].

Support for the feeder gateway queries that are not required for full nodes to synchronize on the state of Starknet will stop according to the following schedule:

[%autowidth.stretch]
!===
!Environment !Date

!Integration
!1 November 2023
!Testnet
!15 November 2023
!Mainnet
!19 December 2023
!===

Queries that are required for full nodes to synchronize on the state of Starknet are still supported.

For more information, see the Community Forum post https://community.starknet.io/t/feeder-gateway-deprecation/100233[_Feeder Gateway Deprecation_^].

| Free L1-> L2 messaging
| Previously, sending a message from L1 to L2 had an optional fee associated.

From xref:resources:version-notes.adoc#version0.11.0[Starknet v0.11.0], the fee mechanism is enforced and the ability to send L1->L2 messages without the corresponding L2 fee has been removed.

See xref:architecture-and-concepts:network-architecture/messaging-mechanism.adoc#l1-l2-message-fees[here] for more details.

| `invoke` transaction v0
| `invoke` transaction v0 has been removed since xref:resources:version-notes.adoc#version0.11.0[Starknet v0.11.0].
| `declare` transaction v0 |`declare` transaction v0 has been removed since xref:resources:version-notes.adoc#version0.11.0[Starknet v0.11.0].

| `deploy` transaction
| The `deploy` transaction has been removed since xref:resources:version-notes.adoc#version0.10.3[Starknet v0.10.3].

To deploy new contract instances, you can use the xref:architecture-and-concepts:smart-contracts/system-calls-cairo1.adoc#deploy[`deploy` system call].
|===

== Important addresses

=== General

==== Mainnet
[horizontal, labelwidth="30"]
Sequencer base URL:: alpha-mainnet.starknet.io
Core contract:: 0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4
SHARP verifier contract:: 0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60

==== Sepolia
[horizontal, labelwidth="30"]
Sequencer base URL:: alpha-sepolia.starknet.io
Core contract:: 0xE2Bb56ee936fd6433DC0F6e7e3b8365C906AA057
SHARP verifier contract:: 0x07ec0D28e50322Eb0C159B9090ecF3aeA8346DFe

=== Tokens

==== Mainnet
[horizontal, labelwidth="30"]
STRK contract:: 0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d
ETH contract:: 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
vSTRK contract:: 0x0782f0ddca11d9950bc3220e35ac82cf868778edb67a5e58b39838544bc4cd0f

==== Sepolia
[horizontal, labelwidth="30"]
STRK contract:: 0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d
ETH contract:: 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
vSTRK contract:: 0x035c332b8de00874e702b4831c84b22281fb3246f714475496d74e644f35d492

=== StarkGate

==== Mainnet
[horizontal, labelwidth="30"]
StarkgateManager contract:: 0x0c5aE94f8939182F2D06097025324D1E537d5B60
StarkgateRegistry contract:: 0x1268cc171c54F2000402DfF20E93E60DF4c96812
L1 StarknetTokenBridge contract:: 0xF5b6Ee2CAEb6769659f6C091D209DfdCaF3F69Eb
L2 StarknetTokenBridge contract:: 0x0616757a151c21f9be8775098d591c2807316d992bbc3bb1a5c1821630589256
Bridged tokens:: starkgate.starknet.io/static/tokens.json

==== Sepolia
[horizontal, labelwidth="30"]
Bridged tokens:: sepolia.starkgate.starknet.io/static/tokens.json

=== Staking

==== Mainnet
[horizontal, labelwidth="30"]
Staking contract:: 0x00ca1702e64c81d9a07b86bd2c540188d92a2c73cf5cc0e508d949015e7e84a7
Reward supplier contract:: 0xCa1406D57eD09947E68DE121316C87113fBE9ff5
Mint manager contract:: 0xCa14076A3cec95448BaD179cc19B351A4204B88B
Reward supplier contract:: 0x009035556d1ee136e7722ae4e78f92828553a45eed3bc9b2aba90788ec2ca112
Minting curve contract:: 0x00ca1705e74233131dbcdee7f1b8d2926bf262168c7df339004b3f46015b6984

==== Sepolia
[horizontal, labelwidth="30"]
Staking contract:: 0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1
Reward supplier contract:: 0xE58d25681B9d290D60e4d7f379a05d5BFD973fFB
Mint manager contract:: 0x648D1B35a932F5189e7ff97b2F795E03734DE4ce
Reward supplier contract:: 0x02ebbebb8ceb2e07f30a5088f5849afd4f908f04f3f9c97c694e5d83d2a7cc61
Minting curve contract:: 0x0351c67dc2d4653cbe457be59a035f80ff1e6f6939118dad1b7a94317a51a454
Attestation contract:: 0x3f32e152b9637c31bfcf73e434f78591067a01ba070505ff6ee195642c9acfb