= Starknet compatibility tables

[IMPORTANT]
====
This page is currently being manually updated. Contributions with more up-to-date information are more than welcome. 
====

== Starknet versions

[NOTE]
====
For the RPC, Cairo, and Sierra versions, the version specified is the latest version supported by the respective Starknet version.

For the Pathfinder and Juno versions, the version specified is the recommended version for running a full node with the respective Starknet version.
====

[%header, cols="~,^~,^~,^~"]
|===
| | Starknet 0.13.5 | Starknet 0.13.3 | Starknet 0.13.2
| RPC | 0.8 | 0.7 | 0.7
| Cairo | 2.11.0 | 2.9.0 | 2.8.0
| Sierra | 1.7.0 | 1.6.0 | 1.6.0
| Pathfinder | 0.16.2 | 0.15.1 | 0.14.1
| Juno | 0.14.2 | 0.12.4 | 0.12.0
|===

== Starknet RPC versions

[NOTE]
====
For the latest Starknet RPC API version, the version specified is the recommended version for working with the respective API version. If a newer version exist, the newest version should be used instead.

For older versions, the version specified is the last recommended version of the tool that worked with the respective API version.
====

[%header, cols="~,^~,^~,^~"]
|===
| | RPC 0.8 | RPC 0.7 | RPC 0.6
| Pathfinder | 0.16.2 | 0.11.0 | 0.10.2
| Juno | 0.14.2 | 0.11.0 | 0.8.0
| Starknet Foundry |  0.39.0 | 0.27.0 | 0.20.0
| Starknet Devnet | 0.3.0 | 0.1.2 | 0.0.2
| Starkli | 0.4.0 | 0.3.0 | 0.2.0
| starknet.js | 7.0.1 | 6.11.0 | 5.14.0
| starknet.py | 0.26.0 | 0.21.0 | 0.20.0
| starknet-rs | 0.14.0 | 0.11.0 | 0.10.0
| starknet.go | 0.8.0 | 0.7.0 | 0.6.1 
| starknet-jvm | 0.14.0 | 0.11.0 | 0.10.0
| starknet.swift | N/A | 0.9.0 | 0.8.0
|===

== Cairo

[NOTE]
====
For Starknet Foundry, the version specified is the version that can compile, declare, and deploy contracts written in the respective Cairo version.

For Starknet Devnet, the version specified is the version that contracts written in the respective Cairo version can be declared and deployed on.

For Starkli, the version specified is the version that can declare and deploy contracts written in the respective Cairo version.

====

[%header, , cols="~,^~,^~,^~"]
|===
| | Cairo 2.11.x | Cairo 2.10.x | Cairo 2.9.x
| Starknet Foundry | 0.38.3 | 0.38.3 | 0.30.0
| Starknet Devnet | 0.3.0 | 0.3.0-rc.1 | 0.2.0
| Starkli | 0.3.8 | 0.3.8 | 0.3.4
|===