[id="useful_info"]
= Useful info

==  Starknet Alpha on Mainnet

The Starknet core contract:: link:https://etherscan.io/address/0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4[`0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4`^]
Verifier address::  link:https://etherscan.io/address/0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60[`0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60`^]
Sequencer base URL for API routing:: \https://alpha-mainnet.starknet.io

== Starknet Alpha version on Goerli testnet 1

The Starknet core contract:: link:https://goerli.etherscan.io/address/0xde29d060D45901Fb19ED6C6e959EB22d8626708e[`0xde29d060D45901Fb19ED6C6e959EB22d8626708e`^]
Verifier address::  link:https://goerli.etherscan.io/address/0xAB43bA48c9edF4C2C4bB01237348D1D7B28ef168[`0xAB43bA48c9edF4C2C4bB01237348D1D7B28ef168`^]
Sequencer base URL for API routing:: \https://alpha4.starknet.io

== Starknet Alpha version on Goerli testnet 2

The Starknet core contract:: link:https://goerli.etherscan.io/address/0xa4eD3aD27c294565cB0DCc993BDdCC75432D498c[`0xa4eD3aD27c294565cB0DCc993BDdCC75432D498c`^]
Verifier address::  link:https://goerli.etherscan.io/address/0xAB43bA48c9edF4C2C4bB01237348D1D7B28ef168[`0xAB43bA48c9edF4C2C4bB01237348D1D7B28ef168`^]
Sequencer base URL for API routing:: \https://alpha4-2.starknet.io

== Bridged Tokens

The tokens that are currently bridged to Starknet are listed in the following `.json` files:

link:https://github.com/starknet-community-libs/starknet-addresses/blob/master/bridged_tokens/mainnet.json[`mainnet.json`^]:: The addresses of the tokens currently bridged to Starknet Mainnet.
https://github.com/starknet-community-libs/starknet-addresses/blob/master/bridged_tokens/goerli.json[`goerli.json`^]:: The addresses of the tokens currently bridged to Starknet testnet.
https://github.com/starknet-community-libs/starknet-addresses/blob/master/bridged_tokens/goerli2.json[`goerli2.json`^]:: The addresses of the tokens currently bridged to Starknet testnet2.

Each token has the following parameters:

Name:: token name
Symbol:: token symbol
Decimals:: number of decimal places used to get the user representation
l1_token_address:: address of the L1 ERC-20 contract
l2_token_address:: address of the L2 ERC-20 contract
l1_bridge_address:: address of the L1 bridge contract
l2_bridge_address:: address of the L2 bridge contract

== `P` value

The field element type in Starknet is based on the field in the underlying Cairo VM. In other words, a value stem:[$$x$$] of a field element type is an integer in the range of stem:[$$0≤x<P$$].

stem:[$$P$$] is currently defined as stem:[$$2^{251} + 17*2^{192} + 1$$]