[id="upcoming"]
= Upcoming versions

*   Text here

[id="versions"]
= Version Notes

The following release notes cover the ongoing version changes to the StarkNet system.

[id="version0.10.2"]
== StarkNet Alpha v0.10.2

- This version introduces sequencer parallelization! This is the first step in our roadmap of performance upgrades. Details about the specific mechanism of parallelization and the roadmap in general will be released in a post next week.
- A new endpoint, estimate_fee_bulk, is added to the feeder gateway. This will allow estimating the fee of several transactions at once, where each transaction is executed relative to the resulting state from applying the previous one.

Summary

*   Sequencing performance improvements
*   Builtin ratio changes, which affects builtin costs
*   Add estimate_fee_bulk API that computes the fee of multiple transactions that will be executed consecutively

As part of this version, we will also increase the finality of transactions in the pending block, by fixing the timestamp at the time of the block creation. This will solve the issue of transactions moving from pending to rejected on account of too old timestamp

[id="version0.10.1"]
== StarkNet Alpha v0.10.1

StarkNet:

*   Add DeployAccount transaction (which will replace the Deploy transaction for deploying account contracts). To use it, you should first add enough funds to your account address to pay the transaction fee, and then you can invoke DeployAccount
*   Split the starknet deploy_account CLI command into starknet new_account and starknet deploy_account
*   Account contracts that are expected to be deployed this way should implement the __validate_deploy__() entry point, which should check the signature of the DeployAccount transaction
*   Improve L1 fee computation: the fee is computed according to the diff of the storage state
*   API: Remove entry_point_type field from transaction information

Cairo:

*   Add uint256_mul_div_mod to uint256.cairo


[id="version0.10.0"]
== StarkNet Alpha v0.10.0
StarkNet:

*   Contract (breaking changes):
**   @external and @view functions should be imported directly by the main compiled file. Otherwise, they will not be usable as external functions
**   Forbid using the same storage variable name in two modules
*   New transaction version (version 1) for invoke and declare transactions:
**   Transactions of version 0 are deprecated and will not be supported in StarkNet from the next version (v0.11.0). Please update your systems to use the new version
**   Note that to use transactions of version 1 you will need to upgrade your account contracts
**   Add nonce field to the transactions. Nonce validation is now part of the StarkNet protocol and is enforced to be executed sequentially
**   Invoke:
***   Split __execute__ to two functions: __validate__ (only validates the transaction) and __execute__ (only executes the transaction)
***   Remove the selector (which is now always __execute__) field, following the above change.
**   Declare:
***   declare transaction should now be sent from an account (and is validated using __validate_declare__ in the account contract)
*   Support fee for sending L1 messages. At this point, it's not mandatory and messages with no fee will still be handled. Starting from the next version it will become mandatory.

Cairo:

Syntax changes in Cairo (to make it more similar to rust and C++):

*   You can use the cairo-migrate script to convert old code to the new syntax. Use the -i flag to apply the changes to the files
*   End statements with ;
Note that new lines are still part of the language at this point, and you cannot put more than one instruction per line. This will change in Cairo1.0.

*   Use { … } for code blocks (instead of : and end)
*   Add () around the condition of if statements
*   Remove the member keyword in structs
*   Change comment to use // instead of #
*   Use ..., ap++ instead of ...; ap++ in low level Cairo code
*   Support return types that are not tuples. For example, func foo() -> felt (instead of func foo() -> (r: felt))
As a result, it's now mandatory to specify return types. func foo() -> (res) should be replaced by func foo() -> (res: felt). The cairo-migrate tool does that automatically.
*   Return statement accepts expressions, rather than only tuples. For example, you can write let x = (5,); return x;
*   A few standard library functions were changed to return felt. The cairo-migrate script also fixes calls to those functions
*   Support using functions as expressions
*   This only applies to functions with -> felt signature, whose ap change is known at compile-time (e.g., recursive functions cannot be used this way)
*   Fix a bug in the secp signature verification code that allowed a malicious prover to ignore the value of v (this does not let the prover fake a signature, but allows it to claim that a valid signature is invalid).
*   Add Cairo code for the recursive STARK verifier

Technical changes:
*   Move from python3.7 to python3.9


[id="version0.9.1"]
== StarkNet Alpha v0.9.1

StarkNet:

API changes:

*   Add get_block_traces API - returns all the transaction traces of a given block
*   Add a list of declared contracts in get_state_update
*   Add a 0x prefix for class hash in the API
*   Add starknet_version field for blocks (only applies to new blocks)

StarkNet CLI:

*   Change the default block number to pending
*   Using a wallet is the default, --no_wallet must be specified explicitly to override this
*   Deploying contracts:
**  Add deploy_contract function to the account contract created by starknet deploy_account
**  Use this function to deploy contract (unless using --no_wallet). In particular, deploy should be used after declaring the contract (it expects the contract class hash)
*   Support --dry_run to get the transaction information without signing or sending it
*   Support deploy_from_zero in the deploy syscall to deploy a contract to an address that does not depend on the deployer

Cairo:
*   Support and in if statements (if x == y and z == w). Note that at the moment other boolean combinations are not supported



[id="version0.9.0"]
== StarkNet Alpha v0.9.0

StarkNet:

*   Enforce fees - max_fee must not be set to zero, and selector must be __execute__
*   Split the concepts of contract class and contract instance. See here
*   Add declare transaction type
*   New API and CLI commands:
*   declare - Declares a contract class
*   get_class_by_hash - Returns the contract class given its hash
*   get_class_hash_at - Returns the class hash for a given contract instance address
*   ename delegate_call to library_call, and change the contract address argument to class hash. See here
*   Add a deploy system call. See here
*   Rename ContractDefinition to ContractClass
*   Reduce the compiled contract file's size by removing unnecessary identifiers (this optimization can be disabled using --dont_filter_identifiers)

Cairo:

*   Initial support for the "EC-op" builtin (scalar multiplication over the STARK curve). Not supported in StarkNet yet.
*   Add additional helper methods to blake2s.cairo, including big-endian support
*   Technical changes:
*   Change function's return type from a struct to a named tuple. In particular, foo.Return.SIZE is no longer supported.

[id="version0.8.2"]
== StarkNet Alpha v0.8.2

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.8.2[`Release notes`^]

[id="version0.8.1"]
== StarkNet Alpha v0.8.1

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.8.1[`Release notes`^]

[id="version0.8.0"]
== StarkNet Alpha v0.8.0

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.8.0[`Release notes`^]
*   link:https://medium.com/starkware/starknet-alpha-0-8-0-16e046e0f94b[`Blog post`^]

[id="version0.7.1"]
== StarkNet Alpha v0.7.1

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.7.1[`Release notes`^]

[id="version0.7.0"]
== StarkNet Alpha v0.7.0

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.7.0[`Release notes`^]
*   link:https://starkware.medium.com/starknet-alpha-0-7-0-26e04db03509[`Blog post`^]

[id="version0.6.2"]
== StarkNet Alpha v0.6.2

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.6.2[`Release notes`^]
*   link:https://community.starknet.io/t/cairo-v0-6-2-api-change-pending-block/195[`Blog post`^]

[id="version0.6.1"]
== StarkNet Alpha v0.6.1

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.6.1[`Release notes`^]

[id="versionv0.6.0"]
== StarkNet Alpha v0.6.0

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.6.0[`Release notes`^]
*   link:https://medium.com/starkware/starknet-alpha-now-on-mainnet-4cf35efd1669[`Blog post`^]

[id="version0.5.2"]
== StarkNet Alpha v0.5.2

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.5.2[`Release notes`^]

[id="version0.5.1"]
== StarkNet Alpha v0.5.1

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.5.1[`Release notes`^]

[id="version0.5.0"]
== StarkNet Alpha v0.5.0

*   link:https://starknet.io/building-on-starknet/versions-release-notes/#:~:text=Cairo%2Dv0.5.0%C2%A0%20%7C-,Release%20Notes,-Cairo%2Dv0.4.2[`Release notes`^]

[id="version0.4.2"]
== StarkNet Alpha v0.4.2

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.4.2[`Release notes`^]

[id="version0.4.1"]
== StarkNet Alpha v0.4.1

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.4.1[`Release notes`^]

[id="version0.4.0"]
== StarkNet Alpha v0.4.0

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.4.0[`Release notes`^]
*   link:https://medium.com/starkware/starknet-alpha-2-4aa116f0ecfc[`Blog post`^]

[id="version0.3.1"]
== StarkNet Alpha v0.3.1

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.3.1[`Release notes`^]

[id="version0.3.0"]
== StarkNet Alpha v0.3.0

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.3.0[`Release notes`^]
*   link:https://medium.com/starkware/starknet-alpha-1-90c3348cca4f[`Blog post`^]

[id="version0.2.0"]
== StarkNet Alpha v0.2.0

*   link:https://github.com/starkware-libs/cairo-lang/releases/tag/v0.2.0[`Release notes`^]
*   link:https://medium.com/starkware/starknet-planets-alpha-on-ropsten-e7494929cb95[`Blog post`^]



