[id="claiming-rewards"]
= Claiming Rewards (WIP) 🚧

:description: How to claim your staking rewards on Starknet by directly interacting with the staking or delegation pooling contracts.

Staking rewards on Starknet accumulate over time as your staked STRK tokens contribute to network security. To claim these rewards, you need to interact with the staking contract (if you are a validator) or the specific delegation pooling contract associated with the validator you have staked with (if you are a delegator) and execute the appropriate functions.

.Prerequisites

* The validator or delegator address must have an existing stake in the respective contract.
* The caller must be either the validator/delegator or their respective reward address.

.Procedure

. Using a Starknet block explorer, navigate to the appropriate contract:
+ 
* For validators: Navigate to the staking contract.
* For delegators: Navigate to the delegation pooling contract associated with the validator you have staked with.
. In the contract interface, locate and select the `claim_rewards` function.
. Enter the following parameters:
+
* In *`staker_address`* or *`pool_member`*, enter the address of the validator or delegator for whom you are claiming the rewards.
. Submit the transaction to initiate the rewards claim.

[NOTE]
====
Ensure that the address entered is either the validator's or delegator's main address or their respective reward address. If the address is not authorized, the function will fail.
====

Once the transaction is successful, the rewards will be transferred to the designated reward address associated with the staked tokens.