[id="delegating-stake"]
= Delegating Stake (WIP) 🚧

:description: How to delegate your stake to a validator on Starknet by interacting directly with the staking and delegation pooling contracts.

Delegating your stake on Starknet involves adding your stake to a validator's delegation pool managed by the staking contract. This approach offers the advantage of lower capital requirements and relieves you of the need to manage the operational aspects of staking, as the validator handles these responsibilities.

The delegation process includes joining a validator's delegation pool by interacting with the `enter_delegation_pool` function.

.Prerequisites

* A Starknet-compatible block explorer or CLI tool.
* The delegation pooling contract address of an active validator to whom you wish to delegate your stake.
* Pre-approval of the STRK ERC20 contract on Starknet for the transfer of tokens from your address to the delegation pooling contract. _**(TODO: should we elaborate more on how to do that?)**_

.Procedure

. Using a Starknet block explorer, navigate to the delegation pooling contract associated with the validator you want to delegate to.
. In the contract interface, locate and select the `enter_delegation_pool` function.
. Enter the following parameters:
+
* In *`amount`*, enter the number of STRK tokens you want to delegate to the validator.
* In *`reward_address`*, enter the address where you wish to receive your staking rewards.
. Submit the transaction to join the delegation pool.

Upon successful execution, your STRK tokens will be added to the validator's delegation pool, and you will begin earning rewards as part of the pooled staking process.
