[id="entering-staking"]
= Becoming a Validator

:description: How to enter the staking protocol on Starknet by interacting directly with the staking contract.

Using the Starknet staking contract to stake STRK tokens requires interacting with the `stake` function. The `stake` function does the following:

. Locks the specified amount of STRK tokens from the validator’s account into the staking contract.
. Records the validator's details, including reward and operational addresses, in the staking contract.
. If pooling is enabled, deploys a new delegation pool contract associated with the validator.

Subsequently, the validator’s tokens will be locked in the staking contract, and the validator will begin earning rewards based on their stake.

For more information on what happens during the staking process, see xref:architecture.adoc#staking-contract[Staking Contract Architecture].

.Prerequisites

* Validators are required to run full nodes in preparation for the following stages of the protocol. You can use any full node implementation you choose:
** link:https://github.com/NethermindEth/juno[Juno] by Nethermind - link:https://juno.nethermind.io/hardware-requirements/#recommended-requirements[Spec].
** link:https://github.com/eqlabs/pathfinder[Pathfinder] by EQLabs - https://github.com/eqlabs/pathfinder?tab=readme-ov-file#hardware-requirements[Spec].
** link:https://github.com/madara-alliance/madara[Madara] by Madara Alliance - link:https://docs.madara.build/Installation/requirements[Spec].
* A Starknet-compatible block explorer or CLI tool.
* Sufficient STRK token balance in your wallet.

.Procedure

. Pre-approve the STRK ERC20 contract for the transfer of tokens from your address to the staking contract:
+
.. Using a Starknet block explorer, navigate to the STRK ERC20 contract (link:https://starkscan.co/token/0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d[Starkscan], link:https://voyager.online/contract/0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d[Voyager]).
.. In the contract interface, locate and select the `approve` function.
.. Enter the following parameters:
* In *`spender`*, enter the Staking contract address (The contract addresses can be found xref:overview.adoc#contract-addresses[here]).
* In *`amount`*, enter the number of STRK tokens you want to stake. Note: STRK has 18 decimals.
.. Submit the transaction to execute the pre-approval.
. Using a Starknet block explorer, navigate to the Staking contract (The contract addresses can be found xref:overview.adoc#contract-addresses[here]).
. In the contract interface, locate and select the `stake` function.
. Enter the following parameters:
+
* In *`reward_address`*, enter the address where the rewards will be sent.
* In *`operational_address`*, enter the operational address associated with this stake.
* In *`amount`*, enter the number of STRK tokens you want to stake. Note: STRK has 18 decimals.
* In *`pooling_enabled`*, enter `true` if you wish to enable delegation pooling, otherwise enter `false`.
* In *`commission`*, enter the commission rate for any delegated staking. The rate should be entered as a percentage with precision, where 10000 represents 100%. For example, to set a 5% commission, you would enter 500.
. Submit the transaction to execute the staking operation.
. Register your validator on the staking dashboards, by link:https://forms.gle/WJqrRbUwxSyG7M9x7[whitelisting it] and link:https://stakingrewards.typeform.com/to/aZdO6pW7[claiming your staking rewards provider profile].

.Secured hardware wallets:
Ledger hardware wallet is supported through:

* link:https://braavos.app/wallet-features/ledger-on-braavos/[Braavos wallet]

* link:https://www.argent.xyz/blog/how-to-use-your-hardware-wallet-with-argent/[Argent wallet]
