[id="entering-staking"]
= Becoming a Validator

:description: How to enter the staking protocol on Starknet by interacting directly with the staking contract.

Using the Starknet staking contract to stake STRK tokens requires interacting with the `stake` function. The `stake` function does the following:

. Locks the specified amount of STRK tokens from the validator’s account into the staking contract.
. Records the validator's details, including reward and operational addresses, in the staking contract.
. If pooling is enabled, deploys a new delegation pool contract associated with the validator.

Subsequently, the validator’s tokens will be locked in the staking contract, and the validator will begin earning rewards based on their stake.

For more information on what happens during the staking process, see xref:architecture.adoc#staking-contract[Staking Architecture].

.Prerequisites

* Validators are required to run full nodes in preparation for the following stages of the protocol. You can use any full node implementation you choose:
** https://github.com/NethermindEth/juno[Juno] by Nethermind: https://juno.nethermind.io/hardware-requirements[juno.nethermind.io/hardware-requirements]
** https://github.com/eqlabs/pathfinder[Pathfinder] by Equilibrium: https://github.com/eqlabs/pathfinder?tab=readme-ov-file#hardware-requirements[github.com/eqlabs/pathfinder?tab=readme-ov-file#hardware-requirements]
** https://github.com/madara-alliance/madara[Madara] by Madara Alliance: https://docs.madara.build/Installation/requirements[docs.madara.build/Installation/requirements]
* A Starknet-compatible block explorer or CLI tool.
* Sufficient STRK token balance in your wallet.
+
[TIP]
====
For validators who wish to use a secure hardware wallet, the https://www.ledger.com/[Ledger hardware wallet] is supported by both https://www.argent.xyz/blog/ledger-argent-integration/[Argent] and https://braavos.app/wallet-features/ledger-on-braavos/[Braavos] wallets.

====

.Procedure

. Pre-approve the STRK ERC20 contract for the transfer of tokens from your address to the staking contract:
+
.. Using a Starknet block explorer such as https://starkscan.co[Starkscan] or https://voyager.online[Voyager], navigate to the STRK contract by searching for xref:tools:important-addresses.adoc#fee_tokens[its address].
.. In the contract interface, locate and select the `approve` function.
.. Enter the following parameters:
* In *`spender`*, enter the xref:overview.adoc#staking_contract[staking contract's address].
* In *`amount`*, enter the number of STRK tokens you want to stake (note that STRK has 18 decimals).
.. Submit the transaction to execute the pre-approval.
. Using a Starknet block explorer such as https://starkscan.co[Starkscan] or https://voyager.online[Voyager], navigate to the staking contract by searching for xref:overview.adoc#staking_contract[its address].
. In the contract interface, locate and select the `stake` function.
. Enter the following parameters:
+
* In *`reward_address`*, enter the address where the rewards will be sent.
* In *`operational_address`*, enter the operational address associated with this stake.
* In *`amount`*, enter the number of STRK tokens you want to stake (note that STRK has 18 decimals).
* In *`pooling_enabled`*, enter `true` if you wish to enable delegation pooling, otherwise enter `false`.
* In *`commission`*, enter the commission rate for any delegated staking. The rate should be entered as a percentage with precision, where 10000 represents 100%. For example, to set a 5% commission, you would enter 500.
. Submit the transaction to execute the staking operation.
. Register your validator on link:https://forms.gle/BUMEZx9dpd3DcdaT8[Karnot's], link:https://stakingrewards.typeform.com/to/aZdO6pW7[Staking Rewards'], and link:https://forms.gle/WJqrRbUwxSyG7M9x7[Voyager's] dashboards.
