[id="entering-staking"]
= Becoming a Validator (WIP) 🚧

:description: How to enter the staking protocol on Starknet by interacting directly with the staking contract.

Using the Starknet staking contract to stake STRK tokens requires interacting with the `stake` function. The `stake` function does the following:

. Locks the specified amount of STRK tokens from the validator’s account into the staking contract.
. Records the validator's details, including reward and operational addresses, in the staking contract.
. If pooling is enabled, deploys a new delegation pool contract associated with the validator.

Subsequently, the validator’s tokens will be locked in the staking contract, and the validator will begin earning rewards based on their stake.

For more information on what happens during the staking process, see xref:architecture.adoc#staking-contract[Staking Contract Architecture].

.Prerequisites

* A Starknet-compatible block explorer or CLI tool.
* Sufficient STRK token balance in your wallet.
* Pre-approval of the STRK ERC20 contract on Starknet for the transfer of tokens from your address to the staking contract. _**(TODO: should we elaborate more on how to do that?)**_
* The contract address of the staking contract. _**(TODO: Check if this really needs to be mentioned.)**_
* The required details for staking: reward address, operational address, amount, pooling enabled status, and commission rate.

.Procedure

. Using a Starknet block explorer, navigate to the staking contract. 
. In the contract interface, locate and select the `stake` function.
. Enter the following parameters:
+
* In *`reward_address`*, enter the address where the rewards will be sent.
* In *`operational_address`*, enter the operational address associated with this stake.
* In *`amount`*, enter the number of STRK tokens you want to stake.
* In *`pooling_enabled`*, enter `true` if you wish to enable delegation pooling, otherwise enter `false`.
* In *`commission`*, enter the commission rate for any delegated staking. The rate should be entered as a percentage with precision, where 10000 represents 100%. For example, to set a 5% commission, you would enter 500.
. Submit the transaction to execute the staking operation.