[id="entering-staking"]
= Becoming a Validator

include::partial$snippet-important-troubleshooting.adoc[]

:description: How to enter the staking protocol on Starknet by interacting directly with the staking contract.

== Introduction

Using the Starknet staking contract to stake STRK tokens requires interacting with the staking contract's `stake` function. The `stake` function does the following:

. Locks the specified amount of STRK tokens from the validator's account into the staking contract.
. Records the validator's details, including reward and operational addresses, in the staking contract.
. If pooling is enabled, deploys a new delegation pool contract associated with the validator.

Subsequently, the validator's tokens will be locked in the staking contract, and the validator will begin earning rewards based on their level of participation and contribution.

// .Prerequisites

// * Validators are required to run full nodes in preparation for the following stages of the protocol. You can use any full node implementation you choose:
// ** https://github.com/NethermindEth/juno[Juno] by Nethermind: https://juno.nethermind.io/hardware-requirements[juno.nethermind.io/hardware-requirements]
// ** https://github.com/eqlabs/pathfinder[Pathfinder] by Equilibrium: https://github.com/eqlabs/pathfinder?tab=readme-ov-file#hardware-requirements[github.com/eqlabs/pathfinder?tab=readme-ov-file#hardware-requirements]
// ** https://github.com/madara-alliance/madara[Madara] by Madara Alliance: https://docs.madara.build/Installation/requirements[docs.madara.build/Installation/requirements]
// * A Starknet-compatible xref:ecosystem:block-explorers-monitoring-tools.adoc[block explorer] or xref:tools:interacting-with-starknet.adoc[CLI tool].
// * Sufficient STRK token balance in your wallet.
// +
// [NOTE]
// ====
// For validators who wish to use a secure hardware wallet, the https://www.ledger.com/[Ledger hardware wallet] is supported by both https://www.argent.xyz/blog/ledger-argent-integration/[Argent] and https://braavos.app/wallet-features/ledger-on-braavos/[Braavos] wallets.

// ====

== Procedure

// . If you are using a block explorer:
// .. Navigate to the STRK contract by searching for xref:resources:chain-info.adoc#important_addresses[its address]
// .. In the contract interface, locate and select the `approve` function.

First, pre-approve the STRK contract for the transfer of tokens from your address to the staking contract by invoking its `approve` function with the following parameters:

. The xref:resources:chain-info.adoc#staking[staking contract's address]
. The number of STRK tokens to stake (note the xref:overview.adoc#economic_parameters[minimum stake for validators] and that STRK has 18 decimals).

For example, the following uses Starkli to approve the STRK contract to transfer 1 STRK to the staking contract on Sepolia: 

[source,terminal]
----
starkli invoke \
0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d \ <1>
approve \
0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <2>
u256:1000000000000000000 \ <3>
--network=sepolia
----
<1> The STRK contract's address on Sepolia
<2> The staking contract's address on Sepolia
<3> 1^18^ = 1 serialized to `u256`

Next, invoke the staking contract's `stake` function with the following parameters:

. The address that will be used as your rewards address (for more information, see https://docs.starknet.io/architecture-and-concepts/staking/#addresses[rewards address])
. The address that will be used as your operational address (for more information, see https://docs.starknet.io/architecture-and-concepts/staking/#addresses[operational address])
. The number of STRK tokens you want to stake (note the xref:overview.adoc#economic_parameters[minimum stake for validators] and that STRK has 18 decimals)
. `1` if you wish to enable delegation pooling, and `0` otherwise
. The commission rate for delegated staking, as a percentage with precision where 10,000 represents 100%

[NOTE]
====
For validators who wish to use a secure hardware wallet for their operational and/or rewards address, the https://www.ledger.com/[Ledger hardware wallet] is supported by both https://www.argent.xyz/blog/ledger-argent-integration/[Argent] and https://braavos.app/wallet-features/ledger-on-braavos/[Braavos] wallets.
====

For example, the following uses Starkli to stake 1 STRK with delegation pooling enabled and 1% commission on Sepolia:

[source,terminal]
----
starkli invoke \
0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
stake \
<reward_address> \
<operational_address> \
1000000000000000000 \ <2>
1 \
100 \ <3>
--network=sepolia 
----
<1> The staking contract's address on Sepolia
<2> 1^18^ = 1 seriallized to `u256`
<3> 1% commission (100 out of 10,000)

Finally, register your validator on the https://forms.gle/BUMEZx9dpd3DcdaT8[Karnot^], https://providers.stakingrewards.com/[Staking Rewards^], and https://forms.gle/WJqrRbUwxSyG7M9x7[Voyager^] dashboards.
