[id="entering-staking"]
= Entering the Staking Protocol

:description: How to enter the staking protocol on Starknet by interacting directly with the staking contract.

Using the Starknet staking contract to stake STRK tokens requires interacting with the `stake` function. The `stake` function does the following:

. Locks the specified amount of STRK tokens from the staker’s Starknet account into the staking contract.
. Records the staker's details, including reward and operational addresses, in the staking contract.
. If pooling is enabled, deploys a new delegation pool contract associated with the staker.

Subsequently, the staker’s tokens will be locked in the staking contract, and the staker will begin earning rewards based on their stake.

For more information on what happens during the staking process, see xref:architecture.adoc#staking-contract[Staking Contract Architecture].

.Prerequisites

* A Starknet-compatible block explorer or CLI tool.
* Sufficient STRK token balance in your Starknet wallet.
* Pre-approval of the STRK ERC20 contract on Starknet for the transfer of tokens from your address to the staking contract. _**(TODO: should we elaborate more on how to do that?)**_
* The contract address of the Starknet staking contract. _**(TODO: Check if this really needs to be mentioned.)**_
* The required details for staking: reward address, operational address, amount, pooling enabled status, and commission rate.

.Procedure

. Using a Starknet block explorer, navigate to the staking contract. 
. In the contract interface, locate and select the `stake` function.
. Enter the following parameters:
+
* In *`reward_address`*, enter the address where the rewards will be sent.
* In *`operational_address`*, enter the operational address associated with this stake.
* In *`amount`*, enter the number of STRK tokens you want to stake.
* In *`pooling_enabled`*, enter `true` if you wish to enable delegation pooling, otherwise enter `false`.
* In *`commission`*, enter the commission rate (as a percentage) for any delegated staking, if applicable. _**TODO: Specify the format (e.g., 10000 for 100%) depending on implementation.**_
. Submit the transaction to execute the staking operation.

The `stake` function will lock your STRK tokens in the staking contract, and if pooling is enabled, a new delegation pool contract will be deployed and associated with your stake.
