[id="increasing-stake"]
= Increasing Stake

:description: How to increase your stake on Starknet by interacting directly with the staking contract.

The staking contract allows stakers to increase their existing stake through the `increase_stake` function. This function adds the specified amount of STRK tokens to the staker's current stake, recalculates rewards _**(TODO: Should I add here that the rewards recalculation is done before the staked amount is updated?)**_, and updates the total staked amount.

.Prerequisites

* A Starknet-compatible block explorer or CLI tool.
* Sufficient STRK token balance in your Starknet wallet.
* The staker must have pre-approved the staking contract to transfer the specified STRK amount from their account. _**(TODO: should we elaborate more on how to do that?)**_
* The contract address of the Starknet staking contract. _**(TODO: Check if this really needs to be mentioned.)**_
* The staker must not be in an unstake process.
* The caller must be either the staker or the staker's reward address.

.Procedure

. Using a Starknet block explorer, navigate to the staking contract.
. In the contract interface, locate and select the `increase_stake` function.
. Enter the following parameters:
+
* In *`staker_address`*, enter the address of the staker whose stake you want to increase.
* In *`amount`*, enter the number of STRK tokens you want to add to the existing stake.
. Submit the transaction to execute the stake increase.

[NOTE]
====
Ensure that the staker is not in an unstake process before attempting to increase the stake. If the staker is currently unstaking, this function will fail.
====
