[id="staking_overview"]
= Staking on Starknet guide overview

[IMPORTANT]
====
This is a hands-on guide for developers interacting with Starknet's staking protocol. To learn about the staking protocol, go to xref:architecture-and-concepts:staking.adoc[Architecture].
====

Staking on Starknet involves locking STRK tokens in the staking protocol, contributing to network security and performance. Anyone holding STRK in their wallets can stake their tokens on Starknet as either validators or delegatiors and earn rewards based on their level of participation and contribution.

This guide will walk you through the various procedures enabled by the staking protocol, including:

.Validators
* xref:running-full-nodes.adoc[Running a full node]:

* xref:entering-staking.adoc[Becoming a validator]: Locking STRK tokens in the staking contract and deploying a new delegation pool contract if pooling is enabled

* xref:increasing-staking.adoc[Increasing stake as a validator]: 


.Additional resources

* https://www.starknet.io/staking[Staking^] on starknet.io
* https://github.com/starkware-libs/starknet-staking/tree/%40staking/contracts-v0.1.1-dev.356[`starknet-staking`^] on Github (deployed tag)
* Staking dashboards:
** https://dashboard.endur.fi/[Endur]
** https://www.stakingrewards.com/stake-app?input=starknet[Staking Rewards]
** https://voyager.online/staking-dashboard[Voyager]