[id="staking_overview"]
= Staking on Starknet guide overview

[IMPORTANT]
====
This is a hands-on guide for interacting with Starknet's staking protocol. To learn about the protocol itself, go to xref:architecture-and-concepts:staking.adoc[Architecture].
====

Staking on Starknet involves locking STRK tokens in the staking protocol, contributing to network security and performance. Anyone holding STRK in their wallets can stake their tokens on Starknet as either validators or delegators, and earn rewards based on their level of participation and contribution.

This guide will walk you through the processes of staking on Starknet, including:

* xref:staking-as-validators.adoc[]: For developers insterested in earning rewards by incrementally taking over the responsibilities of producing, attesting, and proving blocks
* xref:staking-as-delegators.adoc[]: For developers interested in becoming delegators without using a staking dashboard (or are building one)

For a list of the staking protocol contract addresses, see xref:resources:chain-info.adoc#staking[Resources].

.Additional resources

* xref:resources:chain-info.adoc#staking[The staking protocol's contract addresses]
// * https://www.starknet.io/staking[starknet.io's _Staking_ page^]
// * https://github.com/starkware-libs/starknet-staking/tree/%40staking/contracts-v0.1.1-dev.356[starknet-staking's deployed tag^]
// * https://dashboard.endur.fi/[Endur's staking dashboard^]
// * https://www.stakingrewards.com/stake-app?input=starknet[Staking Rewards' staking dashboard^]
// * https://voyager.online/staking-dashboard[Voyager's staking dashboard^]