[id="staking_overview"]
= Staking Overview

== Introduction
Staking on Starknet involves locking STRK tokens in the staking protocol, contributing to network security and performance. Anyone holding STRK in their wallets can stake their tokens on Starknet either directly or by delegating their tokens to others, with rewards based on their level of participation and contribution.

=== Key terms

* _Stake_: Locking STRK tokens into the staking protocol.
* _Delegate_: Assigning STRK tokens to a validator to participate indirectly.
* _Reward_: Earnings from participating in staking.

[id="important-links"]
=== Important links

* Staking on https://www.starknet.io/[starknet.io] (coming soon)
* link:https://github.com/starkware-libs/starknet-staking[`starknet-staking` GitHub repository]
* Staking dashboards:
** link:https://voyager.online/staking-dashboard[Voyager]
** link:https://www.stakingrewards.com/stake-app?input=starknet[Staking Rewards]
** link:https://dashboard.endur.fi/[Endur]

// [NOTE]
// ====
// STRK tokens never leave the Starknet protocol during these operations.
// ====

== First stage

In the future, validators will be responsible for maintaining and securing the network by producing, attesting, and proving blocks, as part of Starknet's consensus protocol. However, handing over these responsibilities all in one day is neither feasible nor desirable.  Instead, the first stage of staking on Starknet will only require validators to run full nodes and test the protocol's economic incentive structure and some of its key smart contract components.

[IMPORTANT]
====
In the first phase of staking on Starknet, validators are required to run a full node in preparation for future staking phases
====

Over time, validators' responsibilities will gradually increase, with each phase bringing additional tasks until validators fully maintain and secure the network. This incremental approach is necessary, as it allows for the following:

* Gradual implementation: introducing features in small and manageable milestones, ensuring each step is carefully implemented and easily integrated, and allowing to refine the process and address issues as they arise

* Validators preparation: giving validators time to adapt to their new responsibilities and critical roles, maximizing the network's stability during the transition

* Proven reliability: having a proven set of sequencers that reliably produce and attest to blocks by the time validators perform their full responsibilities, cementifying the network's decentralization

== Protocol details

=== Overview

The staking protocol features two main options:

* _Staking_: Users can stake any amount of STRK, with a minimum threshold set at 20,000 STRK. Validators are expected to run full nodes and eventually handle additional responsibilities as the protocol evolves. Validators can choose whether to allow delegation.
* _Stake Delegation_: Users can delegate their STRK to validators without running their own nodes, if the validator allows delegation. Delegators share in the rewards earned by the validators they choose.

Validators and delegators can both unstake their funds, subject to network-defined latencies for security.

[id=minting-curve]
=== Minting curve

The minting curve balances participation and inflation by adjusting rewards based on the total STRK locked in the protocol. It is defined by the formula:

[stem]
++++
M = \frac{C}{10} \times \sqrt{S}
++++

where:

* stem:[S] is the staking rate as a percentage of the total token supply
* stem:[M] is the annual minting rate as a percentage of the total token supply
* stem:[C] is the maximum theoretical inflation percentage

For the first stage, stem:[C] is proposed to be 1.6%.

=== Staking rewards

Rewards are distributed based on the amount staked and the commission policy constant stem:[CP] set by the validator. The yearly reward percentages are calculated using the following formulas:

[stem]
++++
\begin{align}
\text{Validators: } & \; \left[\text{self_stake} + \text{total_stake_delegated} \times CP\right] \times \frac{M}{S} \\
\text{Stake Delegators: } & \; \text{stake_delegated} \times (1 - CP) \times \frac{M}{S}
\end{align}
++++

where stem:[M] and stem:[S] are the same as described in xref:#minting-curve[the minting curve section].

=== Latencies

* Current version: Immediate entry and exit from the staking protocol. However, funds are subject to a 21-day security lockup after signaling unstake intent.
* Future versions: Introduction of epochs to determine entry/exit latencies and continued 21-day lockup after signaling unstake intent.

[NOTE]
====
Stake delegators can switch between validators without waiting for the full lockup period, promoting a competitive delegation market.
====

[id="contract-addresses"]
== Contract addresses

The following are the relevant contract addresses for interacting with the staking protocol:

=== L1 addresses
[horizontal, labelwidth="15"]

==== Reward supplier contract

[horizontal, labelwidth="15"]
Mainnet:: TBD
Sepolia:: 0xE58d25681B9d290D60e4d7f379a05d5BFD973fFB

==== Mint manager contract

[horizontal, labelwidth="15"]
Mainnet:: TBD
Sepolia:: 0x648D1B35a932F5189e7ff97b2F795E03734DE4ce

=== L2 addresses

==== Reward supplier contract

[horizontal, labelwidth="15"]
Mainnet:: TBD
Sepolia:: 0x02ebbebb8ceb2e07f30a5088f5849afd4f908f04f3f9c97c694e5d83d2a7cc61

==== Minting curve contract

[horizontal, labelwidth="15"]
Mainnet:: TBD test
Sepolia:: 0x0351c67dc2d4653cbe457be59a035f80ff1e6f6939118dad1b7a94317a51a454

==== Staking contract

[horizontal, labelwidth="15"]
Mainnet:: TBD
Sepolia:: 0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1

== Economic parameters on Sepolia

The following are the economic parameters used on Starknet Sepolia:

* Minimum STRK for Staking: 1 STRK
* Withdrawal Security Lockup: 5 minutes
* Minting Curve Yearly Inflation Cap (stem:[C]): 1.6

[NOTE]
====
For developers who wish to deep dive, the index update interval parameter is also set to a minimum of 1 minute instead of a minimum of 24-hours which will be used in production.
====
