= Staking for validators

include::partial$snippet-important-troubleshooting.adoc[]

== Introduction

== Prerequisites

* Starkli
* A Starknet account on Sepolia, whose address is exported as follows:
+
[source,terminal]
----
export STAKING_ADDRESS=<address> REWARDS_ADDRESS=<address> OPERATIONAL_ADDRESS=<address>
----

[IMPORTANT]
====
For validators who wish to use a secure hardware wallet for their operational and/or rewards address, the https://www.ledger.com/[Ledger hardware wallet] is supported by both https://www.argent.xyz/blog/ledger-argent-integration/[Argent] and https://braavos.app/wallet-features/ledger-on-braavos/[Braavos] wallets.
====

== Becoming as a validator

Becoming a validator requires interacting with the staking contract's `stake` function, which does the following:

. Locks the specified amount of STRK tokens from the validator's account into the staking contract.
. Records the validator's details, including reward and operational addresses, in the staking contract.
. If pooling is enabled, deploys a new delegation pool contract associated with the validator.

First, we must pre-approve the STRK contract for the transfer of tokens from our address to the staking contract by invoking its `approve` function. To approve the STRK contract to transfer 1 STRK to from our address to the staking contract on Sepolia, run: 

[source,terminal]
----
starkli invoke \
    0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d \ <1>
    approve \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <2>
    u256:1000000000000000000 \ <3>
    --network=sepolia
----
<1> The STRK contract's address on Sepolia
<2> The staking contract's address on Sepolia
<3> 1^18^ = 1 STRK (STRK has 18 decimals) serialized to `u256`

Now we can invoke the staking contract's `stake` function. To stake 1 STRK with delegation pooling disabled and 1% commission on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    stake \
    $REWARD_ADDRESS \
    $OPERATIONAL_ADDRESS \
    1000000000000000000 \ <2>
    0 \ <3>
    --network=sepolia 
----
<1> The staking contract's address on Sepolia
<2> 1^18^ = 1 STRK (STRK has 18 decimals) seriallized to `u256`
<3> Disables delegation

[IMPORTANT]
====
Don't forget to register your validator on the https://forms.gle/BUMEZx9dpd3DcdaT8[Karnot^], https://providers.stakingrewards.com/[Staking Rewards^], and https://forms.gle/WJqrRbUwxSyG7M9x7[Voyager^] dashboards.
====

== Increasing stakes

The staking contract allows validators to increase their existing stake using the staking contract's `increase_stake` function. The `increase_stake` function adds the specified amount of STRK tokens to the current stake, recalculate rewards before the staked amount is updated, and update the total staked amount.

To increase our staked STRK by 1 STRK, run:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    increase_stake \
    $REWARDS_ADDRESS \ <2>
    u256:1000000000000000000 \ <3>
    --network=sepolia
----
<1> The staking contract's address on Sepolia
<2> OPERATIONAL_ADDRESS can also be used
<3> 1^18^ = 1 STRK (STRK has 18 decimals) seriallized to `u256`

== Claiming rewards

Staking rewards on Starknet accumulate over time as your staked STRK tokens contribute to network security. To claim these rewards, you need to interact with the staking contract's `claim_rewards` function.

[WARNING]
====
The caller must be the validator's staking or rewards address.
====

Although we shouldn't have any rewards, let's make sure of it:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    claim_rewards \
    STAKING_ADDRESS \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

== Exiting the protocol

== Managing participation 

=== Opening a delegation pool

If a validator doesn't enable delegation when becoming a validator, they can open one by calling the staking contract's `set_open_for_delegation` function. Once created, the delegation pool will be associated with the validator's staking contract, allowing delegators to delegate their stake to the validator. To open a delegation pool with 1% commission, run:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    set_open_for_delegation \
    u256:1000000000000000000 \ <2>
    --network=sepolia
----
<1> The staking contract's address on Sepolia
<2> 1^18^ = 1 STRK (STRK has 18 decimals) serialized to `uint256`

=== Updating commission rates

Validators can update the commission rate of their delegation pool using the `update_commission` function. The commission is expressed as a percentage with precision, where 10000 represents 100%.

[IMPORTANT]
====
The commission rate can only be decreased or kept the same; it cannot be increased.
====

To update the commission of our delegation pool to 2%, run:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    update_commission \
    u256:2000000000000000000 \ <2>
    --network=sepolia
----
<1> The staking contract's address on Sepolia
<2> 2*10^18^ = 2 STRKS (STRK has 18 decimals) serialized as `u256`