= Staking as validators

== Introduction

To stake as a validator, you are required to:

. In the first phase of the staking protocol (on Mainnet and Sepolia): xref:running_a_full_node[run a full node]
. In the second phase of the staking protocol (soon on Sepolia): be able attest to blocks

You can then xref:registering_as_validator[register as validator] by locking stake into the staking contract, and xref:managing_participation[manage your participation] in the staking protocol, including claiming your rewards, updating your commission rate, and more.

.Relevant contract addresses
[horizontal, labelwidth="25"]
Staking contract on Mainnet:: 0x00ca1702e64c81d9a07b86bd2c540188d92a2c73cf5cc0e508d949015e7e84a7
Staking contract on Sepolia:: 0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1
STRK contract on Mainnet and Sepolia:: 0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d

== Running a full node 

To run a full node, you can follow the integration guide of any of the following full node implementations:

[%autowidth]
|===
| Name | Hardware requirements | Integration guide

| Juno
| https://juno.nethermind.io/hardware-requirements[juno.nethermind.io/hardware-requirements^]
| https://juno.nethermind.io/running-juno[juno.nethermind.io/running-juno^]

| Madara
| https://docs.madara.build/hardware[docs.madara.build/hardware^]
| https://github.com/madara-alliance/madara/blob/main/README.md#%EF%B8%8F-installation[github.com/madara-alliance/madara/README.md^]

| Pathfinder
| https://eqlabs.github.io/pathfinder/getting-started/hardware-requirements[eqlabs.github.io/pathfinder/getting-started/hardware-requirements^]
| https://eqlabs.github.io/pathfinder/getting-started/running-pathfinder[eqlabs.github.io/pathfinder/getting-started/running-pathfinder^]
|===

== Registering as validator

To register as validator, you need lock at least the xref:architecture-and-concepts:staking.adoc#protocol[minimum required amount of STRK tokens] into the staking contract. must first approve the transfer of STRK tokens from the address you wish to set as your xref:architecture-and-concepts:staking.adoc#addresses[staking address] to the staking contract. To do so, use this address to invoke the STRK contract's `approve` function with the following parameters:

. The staking contract's address
. The number of STRK tokens you wish to stake
+
[NOTE]
====
This number needs to be greater than or equal to the xref:architecture-and-concepts:staking.adoc#protocol[minimum stake for validators].
====

For example, you can use the following to approve the transfer of 1 STRK to the staking contract on Sepolia: 

[source,terminal]
----
starkli invoke \
    0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d \ <1>
    approve \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <2>
    u256:1000000000000000000 \ <3>
    --network=sepolia
----
<1> The STRK contract's address on Sepolia
<2> The staking contract's address on Sepolia
<3> 1*10^18^ = 1 STRK (STRK has 18 decimals) serialized as `u256`

Once the transfer is approved, use the same address to invoke the staking contract's `stake` function with the following parameters:

[WARNING]
====
The addressed that you use to invoke the `stake` function is the address that will be set as your staking address, which cannot be changed.
====

. The address you wish to use as your xref:architecture-and-concepts:staking.adoc#addresses[rewards address]
. The address you wish to use as your xref:architecture-and-concepts:staking.adoc#addresses[operational address]
. The number of STRK tokens you wish to stake
+
[NOTE]
====
This number must match the number specified in the `approve` function.
====

. `1` if you wish to enable delegation pooling and `0` otherwise
. The commission rate you wish to set for your delegation pool (if enabled), as a percentage with precision where 10,000 represents 100%

For example, you can use the following to stake 1 STRK with delegation pooling enabled and 1% commission on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    stake \
    <rewards address> \
    <operational address> \
    1000000000000000000 \ <2>
    1 \ <3>
    100 \ <4>
    --network=sepolia 
----
<1> The staking contract's address on Sepolia
<2> 1*10^18^ = 1 STRK (STRK has 18 decimals) seriallized to `u256`
<3> Enables delegation pooling
<4> 100/10,000 = 1% commission

The `stake` function does the following:

. Records your details in the staking contract
. Locks the specified amount of STRK tokens into the staking contract
. Deploys a new delegation pool contract associated with you (if pooling is enabled)
. Begins accumalating your rewards

[TIP]
====
Although not mandatory, it is highly recommended that you also register on the staking dashboards by https://forms.gle/BUMEZx9dpd3DcdaT8[Karnot^], https://providers.stakingrewards.com/[Staking Rewards^], and https://forms.gle/WJqrRbUwxSyG7M9x7[Voyager^].
====

== Managing participation

After locking stake into a the staking contract, you can manage various aspects of your participation in the staking protocol. This section details the various procedures available to you for managing your participation, summarized in the following table:

[cols="2,2,1,1"]
|===
| Procedure | Invoker | Contract | Function

| Claiming rewards
| Your rewards or staking address
| Staking
| `claim_rewards` 

.2+.^| Increasing stake
.2+.^| Your rewards or staking address
| STRK
| `approve`
| Staking
| `increase_stake`

// | Enabling delegation
// | The validator's operational address
// | Staking
// | `set_open_for_delegation`

| Updating commission rate
| Your operational address
| Staking
| `change_rewards_address`

| Changing rewards address
| The validator's staking address
| Staking
| `change_rewards_address`

.2+.^| Changing operational address
| The validator's new operational address
| Staking
| `declare_operational_address`
| The validator's staking address
| Staking
| `change_operational_address`

.2+.^| Exiting the protocol
| The validator's staking address
| Staking
| `unstake_intent`
| Any address
| Staking
| `unstake_action`
|===

=== Claiming rewards

To claim rewards that have been accumulated for you, use your rewards or staking address to invoke the staking contract's `claim_rewards` function with your staking address as parameter. For example, you can use the following to claim rewards on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    claim_rewards \
    <your staking address> \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

=== Increasing stake

To increase your stake, you must first approve the transfer of additional STRK tokens from your staking or rewards address to the staking contract, by using it to invoke the STRK contract's `approve` function with the following parameters:

. Your staking address
. The number of STRK to add to your stake

For an example of approving the transfer of 1 STRK to the staking contract on Sepolia, see xref:#registering_as_validator[]. Once the transfer is approved, use the same address to invoke the staking contract's `increase_stake` function with the following parameters:

. Your staking address
. The number of STRK tokens to add to your stake
+
[NOTE]
====
This number must match the number specified in the `approve` function.
====

For example, you can use the following to increase your stake by 1 STRK:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    increase_stake \
    <your staking address> \
    u256:1000000000000000000 \ <2>
    --network=sepolia
----
<1> The staking contract's address on Sepolia
<2> 1*10^18^ = 1 STRK (STRK has 18 decimals) seriallized to `u256`

The `increase_stake` function does the following:

. Adds the specified amount of STRK tokens to your current stake
. Recalculates rewards
. Updates the total staked amount

// === Enabling delegation

// If you did not enable delegation on initialization, you enable open delegation by using your operational address to invoke the staking contract's `set_open_for_delegation` function with the commission rate for the pool — expressed as a percentage with precision, where 10,000 represents 100% — as parameter. For example, you can use the following to open a delegation pool with 1% commission on Sepolia:

// [source,terminal]
// ----
// starkli invoke \
//     0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
//     set_open_for_delegation \
//     100 \ <2>
//     --network=sepolia
// ----
// <1> The staking contract's address on Sepolia
// <2> 1*10^18^ = 1 STRK (STRK has 18 decimals) serialized to `uint256`

// The `set_open_for_delegation` function creates a delegation pool associated with your staking contract, allowing delegators to delegate their stake to you.

=== Updating commission rate

[IMPORTANT]
====
Currently, commission rates can only be decreased.
====

To update the commission rate of your delegation pool, use your operational address to invoke the staking contract's `update_commission` function with the new commission rate as parameter. The commission rate should be expressed as a percentage with precision, where 10,000 represents 100%. For example, you can use the following to change the commission rate to 1% on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    update_commission \
    u256:1000000000000000000 \ <2>
    --network=sepolia
----
<1> The staking contract's address on Sepolia
<2> 1*10^18^ = 1 STRKS (STRK has 18 decimals) serialized as `u256`

=== Changing rewards address

To change your rewards address, use your staking address to invoke the staking contract's `change_rewards_address` function with the new address as parameter. For example, you can use the following to change rewards addresses on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    change_rewards_address \
    <new rewards address> \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

=== Changing operational address

To change your operational address, you must first declare it by using your new operational address to invoke the staking contract's `declare_operational_address` function with your staking address as parameter. For example, you can use the following to declare a new operational address on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    declare_operational_address \
    <staking address> \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

Once declared, you can use your staking address to invoke the staking contract's `change_operational_address` function with the new operational address as parameter. For example, you can use the following to change operational addresses on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    change_operational_address \
    <new operational address> \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

=== Exiting the protocol

You can signal an unstake intent by invoking the staking contract's `unstake_intent`. For example, you can use the following to signal an unstake intent on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    unstake_intent \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

The `unstake_intent` function does the following:

. Records your unstake intent
. Pauses your rewards collection
. Starts your xref:architecture-and-concepts:staking.adoc#latencies[waiting period]

Once the waiting period has passed, anyone can finalize your unstake intent by invoking the staking contract's `unstake_action` function with the validator's staking address as parameter. For example, you can use the following to finalize an unstake intent on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    unstake_action \
    <staking address> \
    --network=sepolia
----
<1> The staking contract's address on Sepolia