= Staking as delegators

[IMPORTANT]
====
This guide is intended for developers who wish to interact with delegation pools directly. Users who wish to simply delegate their stake to a validator are recommended to visit one of the staking dashboard by https://dashboard.endur.fi/[Endur^], https://www.stakingrewards.com/stake-app?input=starknet[Staking Rewards^], or https://voyager.online/staking-dashboard[Voyager^].
====

== Introduction

Staking on Starknet as delegators involves adding stakes to a validator's delegation pool, which is managed by the staking contract. This approach offers the advantage of lower capital requirements, eliminating the need to manage the operational aspects of staking, as the validator handles these responsibilities.

The following sections describe the procedures available for delegators, summarized in the following table:

[cols="2,2,1,1"]
|===
| Procedure | Invoker | Contract | Function

.2+.^| Delegating stake
.2+.^| Address to be used as the delegator's staking address
| STRK
| `approve`
| Delegation pool
| `enter_delegation_pool`

.2+.^| Claiming rewards
.2+.^| The delegator's rewards address or staking address
| STRK
| `approve`
| Staking
| `claim_rewards` 

.2+.^| Undelegating stakes
| The delegator's staking address
| Delegation pool
| `exit_delegation_pool_intent`
| Any address
| Delegation pool
| `exit_delegation_pool_action`

| Switching delegation pools
| The delegator's staking address
| Source delegation pool
| `switch_delegation_pool`

| Changing the rewards address
| The delegator's staking address
| Delegation pool
| `change_rewards_address`
|===

== Delegating stake

[WARNING]
====
The addressed used for this procedure is the address that will be set as the delegator's xref:architecture-and-concepts:staking.adoc#addresses[staking address].
====

To delegate stake, delegators must first approve the transfer of STRK tokens to the staking contract by invoking the STRK contract's `approve` function with the following parameters:

. The delegation pool contract's address
. The number of STRK tokens to be delegated

For example, the following can be used to approve the transfer of 1 STRK to the staking contract on Sepolia: 

[source,terminal]
----
starkli invoke \
    <delegation pool address> \
    approve \
    u256:1000000000000000000 \ <1>
    --network=sepolia
----
<1> 1*10^18^ = 1 STRK (STRK has 18 decimals) serialized to `u256`

One the transfer is approved, delegators can use the same address to invoke the delegation pool contract's `enter_delegation_pool` function with the following parameters:

. The number of STRK tokens to be delegated
. The address to be used as xref:architecture-and-concepts:staking.adoc#addresses[rewards address]

The `enter_delegation_pool` adds the delegator's STRK tokens to the validator's delegation pool and begins accumalating rewards for the delegator.

== Claiming rewards

Delegators can claim the rewards they have accumulated by using their rewards or staking addresses to invoke a delegation pool contract's `claim_rewards` function with their staking address as parameter. For example, the following can be used to claim rewards on Sepolia:

[source,terminal]
----
starkli invoke \
    <delegation pool contract's address> \
    claim_rewards \
    <delegator's staking address> \
    --network=sepolia
----

== Undelegating stakes

Delegators can signal an undelegate intent by invoking a delegation pool contract's `exit_delegation_pool_intent` with the number of STRK tokens to be undelegated as parameter. For example, the following can be used to signal an undelegate intent on Sepolia:

[source,terminal]
----
starkli invoke \
    <delegation pool address> \
    exit_delegation_pool_intent \
    u256:1000000000000000000 \ <1>
    --network=sepolia
----
<1> 1*10^18^ = 1 STRK (STRK has 18 decimals) serialized to `u256`

The `exit_delegation_pool_intent` function does the following:

. Records the undelegate intent
. Pauses rewards collection
. Starts the xref:architecture-and-concepts:staking.adoc#latencies[waiting period]

Once the waiting period has passed, anyone can finalize the undelegate intent by invoking the same delegation pool contract's `exit_delegation_pool_action` function with the delegator's staking address as parameter. For example, the following can be used to finalize an undelegate intent on Sepolia:

[source,terminal]
----
starkli invoke \
    <delegation pool contract's address> \
    exit_delegation_pool_action \
    <delegator's staking address> \ <1>
    --network=sepolia
----

== Switching delegation pools

Delegators can switch from one validator's delegation pool to another by using their staking address to invoke the source delegation pool contract's `switch_delegation_pool` function with the following parameters:

. The staking address of the target delegation pool's validator
. The target delegation pooling contract's address
. The number of STRK tokens to be transferred from the source delegation pool to the target delegation pool

For example, the following can be used to transfer 1 STRK from one validator's delegation pool to another on Sepolia:

[source,terminal]
----
starkli invoke \
    <source delegation pool contract's address> \
    switch_delegation_pool \
    <target delegation pool contract's address> \
    u256:1000000000000000000 \ <1>
    --network=sepolia
----
<1> 1*10^18^ = 1 STRK (STRK has 18 decimals) serialized to `u256`

== Changing the rewards address

Delegators can change their rewards address by using their staking address to invoke a delegation pool contract's `change_rewards_address` function with the new reward address as parameter. For example, the following can be used to change rewards addresses on Sepolia:

[source,terminal]
----
starkli invoke \
    <delegation pool contract's address> \
    change_rewards_address \
    <delegator's new rewards address> \
    --network=sepolia
----