= Staking as validators

include::partial$snippet-important-troubleshooting.adoc[]

== Introduction

The following sections describe the procedures available for validators, summarized in the following table:

[%autowidth]
|===
| Procedure | Function | Contract | Invoker

.2+.^| Initializing stake
| `approve`
| STRK
.2+.^| Address to be used as the validator's staking address
| `stake`
| Staking

.2+.^| Increasing stake
| `approve`
| STRK
.2+.^| The validator's rewards or staking address
| `increase_stake`
| Staking

.2+.^| Claiming rewards
| `approve`
| STRK
.2+.^| The validator's rewards address or staking address
| `claim_rewards` 
| Staking

.2+.^| Exiting the protocol
| `unstake_intent`
| Staking
| The validator's staking address
| `unstake_action`
| Staking
| Any address
|===

// [IMPORTANT]
// ====
// For validators who wish to use a secure hardware wallet for their operational and/or rewards address, the https://www.ledger.com/[Ledger hardware wallet] is supported by both https://www.argent.xyz/blog/ledger-argent-integration/[Argent] and https://braavos.app/wallet-features/ledger-on-braavos/[Braavos] wallets.
// ====

== Initializing stake

[WARNING]
====
The addressed used for this procedure is the address that will be set as the validator's xref:architecture-and-concepts:staking.adoc#addresses[staking address].
====

[NOTE]
====
The initial stake must greater or equal to the xref:architecture-and-concepts:staking.adoc#protocol[minimum stake required for validators].
====

// [TIP]
// ====
// For validators who wish to use a secure hardware wallet for their staking and/or rewards addresses, the https://www.ledger.com/[Ledger hardware wallet] is supported by both https://www.argent.xyz/blog/ledger-argent-integration/[Argent] and https://braavos.app/wallet-features/ledger-on-braavos/[Braavos] wallets.
// ====

To initialize their stake, validators must first approve the transfer of STRK tokens to the staking contract by invoking the STRK contract's `approve` function with the following parameters:

. The staking contract's address
. The number of STRK tokens to be staked

For example, the following can be used to approve the transfer of 1 STRK to the staking contract on Sepolia: 

[source,terminal]
----
starkli invoke \
    0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d \ <1>
    approve \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <2>
    u256:1000000000000000000 \ <3>
    --network=sepolia
----
<1> The STRK contract's address on Sepolia
<2> The staking contract's address on Sepolia
<3> 1^18^ = 1 STRK (STRK has 18 decimals) serialized to `u256`

One the transfer is approved, validators can use the same address to invoke the staking contract's `stake` function with the following parameters:

. The address to be used as xref:architecture-and-concepts:staking.adoc#addresses[rewards address]
. The address to be used as xref:architecture-and-concepts:staking.adoc#addresses[operational address]
. The number of STRK tokens to be staked
. `1` to enable delegation pooling and `0` otherwise
. The commission rate for delegated staking, as a percentage with precision where 10,000 represents 100%

For example, the following can be used to stake 1 STRK with delegation pooling enabled and 1% commission on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    stake \
    <rewards address> \
    <operation address> \
    1000000000000000000 \ <2>
    1 \ <3>
    100 \ <4>
    --network=sepolia 
----
<1> The staking contract's address on Sepolia
<2> 1^18^ = 1 STRK (STRK has 18 decimals) seriallized to `u256`
<3> Enables delegation pooling
<4> 100/10,000 = 1% commission

The `stake` function does the following:

. Locks the specified amount of STRK tokens from the validator's account into the staking contract
. Records the validator's details in the staking contract
. Deploys a new delegation pool contract associated with the validator (if pooling is enabled)

// [IMPORTANT]
// ====
// Don't forget to register your validator on the https://forms.gle/BUMEZx9dpd3DcdaT8[Karnot^], https://providers.stakingrewards.com/[Staking Rewards^], and https://forms.gle/WJqrRbUwxSyG7M9x7[Voyager^] dashboards.
// ====

== Increasing stake

To increase their existing stake, validators must first approve the transfer of additional STRK tokens from their staking address to the staking contract by invoking the STRK contract's `approve` function with the following parameters:

. The staking contract's address
. The number of STRK tokens to be added

For an example of approving the transfer of 1 STRK to the staking contract on Sepolia, see xref:#initializing_stake[]. Once the transfer is approved, validators can use the same address to invoke the staking contract's `increase_stake` function with the following parameters:

. The validator's rewards or staking address
. The number of STRK tokens to be added

For example, the following can be used to increase an existing stake by 1 STRK:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    increase_stake \
    <rewards or staking address> \ <2>
    u256:1000000000000000000 \ <3>
    --network=sepolia
----
<1> The staking contract's address on Sepolia
<2> STAKING_ADDRESS can also be used
<3> 1^18^ = 1 STRK (STRK has 18 decimals) seriallized to `u256`

The `increase_stake` function does the following:

. Adds the specified amount of STRK tokens to the validator's current stake
. Recalculates rewards
. Updates the total staked amount

== Claiming rewards

Validators can claim the xref:architecture-and-concepts:staking.adoc#rewards[rewards] they have accumulated by using their rewards or staking addresses to invoke the staking contract's `claim_rewards` with their staking address as parameter. For example, the following can be used to claim rewards on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    claim_rewards \
    <staking address> \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

== Exiting the protocol

Validator can signal an unstake intent by invoking the staking contract's `unstake_intent`. For example, the following can be used to signal an unstake intent on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    unstake_intent \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

The `unstake_intent` function does the following:

. Records the unstake intent
. Pauses rewards collection
. Starts the xref:architecture-and-concepts:staking.adoc#latencies[waiting period]

Once the waiting period has passed, anyone can finalize the unstaking intent by invoking the staking contract's `unstake_action` function with the validator's staking address as parameter. For example, the following can be used to finalize an unstake intent on Sepolia:

[source,terminal]
----
starkli invoke \
    0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
    unstake_action \
    <staking address> \
    --network=sepolia
----
<1> The staking contract's address on Sepolia

// == Managing participation 

// === Opening a delegation pool

// If a validator doesn't enable delegation when becoming a validator, they can open one by calling the staking contract's `set_open_for_delegation` function. Once created, the delegation pool will be associated with the validator's staking contract, allowing delegators to delegate their stake to the validator. To open a delegation pool with 1% commission, run:

// [source,terminal]
// ----
// starkli invoke \
//     0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
//     set_open_for_delegation \
//     u256:1000000000000000000 \ <2>
//     --network=sepolia
// ----
// <1> The staking contract's address on Sepolia
// <2> 1^18^ = 1 STRK (STRK has 18 decimals) serialized to `uint256`

// === Updating commission rates

// Validators can update the commission rate of their delegation pool using the `update_commission` function. The commission is expressed as a percentage with precision, where 10000 represents 100%.

// [IMPORTANT]
// ====
// The commission rate can only be decreased or kept the same; it cannot be increased.
// ====

// To update the commission of our delegation pool to 2%, run:

// [source,terminal]
// ----
// starkli invoke \
//     0x03745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1 \ <1>
//     update_commission \
//     u256:2000000000000000000 \ <2>
//     --network=sepolia
// ----
// <1> The staking contract's address on Sepolia
// <2> 2*10^18^ = 2 STRKS (STRK has 18 decimals) serialized as `u256`

// === Changing operational and rewards addresses
