[id="switching-delegation-pools"]
= Switching Delegation Pools

:description: How to switch your delegated stake from one validator's pool to another on Starknet by interacting directly with the delegation pooling contract.

include::partial$snippet-important-staking-architecture.adoc[]

Switching your delegated stake from one validator's delegation pool to another allows you to optimize your staking strategy by moving your funds to a different validator. This process involves interacting with the `switch_delegation_pool` function in the delegation pooling contract, which coordinates with the staking contract to move your stake.

.Prerequisites

* An existing delegation in a validator’s pool with a STRK token balance equal to or greater than the amount you wish to switch.
* The delegator must have initiated an undelegation process before attempting to switch pools.
* The target validator must have an active delegation pool associated with their staking contract.

.Procedure

. Using a Starknet block explorer, navigate to the delegation pooling contract associated with the validator from whose pool you wish to switch.
. In the contract interface, locate and select the `switch_delegation_pool` function.
. Enter the following parameters:
+
* In *`to_staker`*, enter the address of the validator whose pool you want to switch to.
* In *`to_pool`*, enter the address of the target delegation pooling contract associated with the new validator.
* In *`amount`*, enter the number of STRK tokens you want to move to the new delegation pool.
. Submit the transaction to execute the delegation pool switch.

[NOTE]
====
Ensure that you have initiated the undelegation process before attempting to switch pools. If the undelegation intent has not been set, this function will fail.
====

Upon successfully switching pools, any unclaimed rewards from your previous delegation pool will be transferred to your designated reward address. Your subsequent rewards will be based on the performance of the new validator's delegation pool.

For more details on the staking architecture and how delegation pools work, see xref:architecture.adoc#staking-contract[Staking Contract Architecture].
