[#setup]

= Set up your environment

In order to interact with Starknet and compile Cairo code, you need to install several tools.

The following tools are recommended::

* https://github.com/xJonathanLEI/starkli[Starkli]: A command-line interface that allows you to interact with Starknet.

* https://github.com/software-mansion/scarb[Scarb]: A build toolchain and package manager for Cairo and Starknet ecosystems.

== Starkli Installation

Starkliup is the installer for the Starkli environment, and it can be installed using the command line with curl:

[source,shell]
----
curl https://get.starkli.sh | sh
----

Restart the terminal after executing the command.

Once starkliup has been successfully installed, it can then be used to install Starkli:

[source,shell]
----
starkliup
----

Restart the terminal and run the following command to verify the installation:

[source,shell]
----
starkli --version
----

To upgrade to the latest version of Starkli simply follow these steps again.

=== Starkli environment variables

For the majority of flags available on Starkli you can define environment variables to make the commands shorter and easier to manage.

There are two primary environment variables that are vital for effective usage of Starkli's CLI.

These are:

* The location of the keystore file for the xref:set_up_an_account.adoc#creating_a_signer[Signer].
* The location of the xref:set_up_an_account.adoc#creating_an_account_descriptor[Account Descriptor] file.

Environment variables for these can be set as follows:

[source,bash]
----
export STARKNET_ACCOUNT=~/.starkli-wallets/deployer/account.json
export STARKNET_KEYSTORE=~/.starkli-wallets/deployer/keystore.json
----

Setting environment variables for Starkli significantly simplifies command execution and management, thereby enhancing efficiency, readability, and control in your Starkli-related development activities.

Your environment is now ready to begin developing on Starknet.


== Scarb installation

Scarb is compatible with macOS, Linux, and Windows operating systems.


=== MacOS and Linux installation
For macOS and Linux users, open your terminal and execute the following command:

[source, bash]
----
curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----

Restart the terminal and run the following command to verify the installation:

[source, bash]
----
scarb --version
----

You can run the same command to upgrade Scarb.

=== Windows installation
Scarb's installation on Windows requires manual setup. Follow the steps in the link:https://docs.swmansion.com/scarb/download#install-via-installation-script[Scarb documentation] to install it.

Restart the terminal and run the following command to verify the installation:

[source, bash]
----
scarb --version
----

You can run the same command to upgrade Scarb:

[source, bash]
----
curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----