[#setup]

= Setting up your environment

You need to install several tools that allow you to interact with Starknet and compile Cairo code.

The following tools are suggested:

https://github.com/xJonathanLEI/starkli[Starkli]: A command-line interface that allows you to interact with Starknet.

https://github.com/software-mansion/scarb[Scarb]: A package manager for Cairo. Among other things, it allows you to compile Cairo code to Sierra, the intermediate language between high-level Cairo and the low-level Cairo Assembly (CASM).

== Starkli Installation

`Starkliup` is the installer for the Starkli environment, and it can be installed using the command line with curl:

[source,shell]
----
curl https://get.starkli.sh | sh
----

Restart the terminal after executing the command. Once `starkliup` has been successfully installed, it can then be used to install Starkli:

[source,shell]
----
starkliup
----

Restart the terminal and run the following command to verify the installation:

[source,shell]
----
starkli --version
----

To upgrade to the latest version of Starkli simply follow these steps again.

== The Scarb package manager installation

Scarb is compatible with macOS, Linux, and Windows operating systems.


=== MacOS and Linux installation
For macOS and Linux users, open your terminal and execute the following command:

[source, bash]
----
curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----

You can run the same command to upgrade it.

=== Windows installation
Scarb's installation on Windows requires manual setup. Follow the steps in the link:https://docs.swmansion.com/scarb/download#install-via-installation-script[Scarb documentation] to install it.

Restart the terminal and run the following command to verify the installation:

[source, bash]
----
$ scarb --version
----

You can run the same command to upgrade it:

[source, bash]
----
curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----

Your environment is now ready to begin developing on Starknet.