= Interacting with a smart contract with Remix

We shall utilize the Starknet Remix Plugin for the compilation, deployment, and interaction with our smart contract. This tool proves invaluable for initiating Starknet development, obviating the necessity of any local installations on your machine.

== Introduction

. Access the https://remix.ethereum.org/#activate=Starknet&lang=en&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.24+commit.e11b9ed9.js)[Remix IDE] website with the Starknet plugin activated.
. Navigate to the `settings` option and opt for the Cairo version, as depicted in the accompanying image. The latest iteration available in Remix is `v2.5.4`.
. Proceed to the `file explorer` tab to review the particulars of the sample project. Within the `Scarb.toml` file, the version of this sample project is delineated.

Given our intent to utilize `version 2.5.4` for this project, it is imperative to ensure its alignment within our `Scarb.toml`. Any disparities should be rectified accordingly, setting `starknet = "2.5.4"`.

== Customizing for Ownable Contract

[NOTE]
====
A sample project is provided by default, but for the purposes of this tutorial we will be demonstrate the Ownable contract example. To achieve this, certain files and directories will need to be modified or removed.
====

. Rename the root directory as `ownable`. Within your `Scarb.toml`, under the [package] section, designate the name as `ownable`.
. Eliminate the `balance.cairo` and `forty_two.cairo` files, if extant.
. Access `lib.cairo` and expunge all contents therein, rendering it devoid of any material.

== Introduction to Starknet Smart Contracts

The following exposition unveils a fundamental `Ownable` contract pattern crafted in Cairo for Starknet. It encapsulates:

* A sophisticated ownership framework.
* A mechanism for seamless ownership transfer.
* A facility for querying the incumbent owner.
* An intricately designed event notification system facilitating the tracking of ownership alterations.

=== Cairo Example Contract

[source,cairo]
----
use starknet::ContractAddress;

#[starknet::interface]
trait OwnableTrait<T> {
    fn transfer_ownership(ref self: T, new_owner: ContractAddress);
    fn get_owner(self: @T) -> ContractAddress;
}

#[starknet::contract]
mod Ownable {
    use super::ContractAddress;
    use starknet::get_caller_address;

    #[event]
    #[derive(Drop, starknet::Event)]
    enum Event {
      OwnershipTransferred: OwnershipTransferred,
    }

    #[derive(Drop, starknet::Event)]
    struct OwnershipTransferred {
        #[key]
        prev_owner: ContractAddress,
        #[key]
        new_owner: ContractAddress,
    }

    #[storage]
    struct Storage {
        owner: ContractAddress,
    }

    #[constructor]
    fn constructor(ref self: ContractState, init_owner: ContractAddress) {
        self.owner.write(init_owner);
    }

    #[abi(embed_v0)]
    impl OwnableImpl of super::OwnableTrait<ContractState> {
        fn transfer_ownership(ref self: ContractState, new_owner: ContractAddress) {
            self.only_owner();
            let prev_owner = self.owner.read();
            self.owner.write(new_owner);
            self.emit(Event::OwnershipTransferred(OwnershipTransferred {
                prev_owner: prev_owner,
                new_owner: new_owner,
            }));
        }

        fn get_owner(self: @ContractState) -> ContractAddress {
            self.owner.read()
        }
    }

    #[generate_trait]
    impl PrivateMethods of PrivateMethodsTrait {
        fn only_owner(self: @ContractState) {
            let caller = get_caller_address();
            assert(caller == self.owner.read(), 'Caller is not the owner');
        }
    }
}
----

=== Components Breakdown

The ensuing discourse offers a succinct elucidation of the constituent elements within the contract. For those uninitiated in smart contract development, this section may be bypassed temporarily, with deeper exploration deferred until a later juncture.

. Dependencies and Interface:
* `starknet::ContractAddress`: Serves as a representation of a Starknet contract address.
* `OwnableTrait`: Defines essential functions pertaining to ownership transfer and retrieval.

. Events:
* `OwnershipTransferred`: Signifies alterations in ownership, conveying pertinent details regarding the former and new owners.

. Storage:
* Acts as the repository for the contract's state, encapsulating the address of the current owner.

. Constructor:
* Initializes the contract, assigning an initial owner.

. External Functions:
* Comprises functions facilitating ownership transfer and furnishing details regarding the incumbent owner.

. Private Methods:
* `only_owner`: Serves to validate whether the caller holds the status of the current owner.

== Compilation Process

To compile using Remix:

.File Creation

* Proceed to the "File Explorer" tab within Remix's interface.
* Locate the file titled `lib.cairo`, and proceed to insert the preceding code into it.

.Compilation

* Navigate to the `Starknet` tab within Remix, then select `Home`.
* Within the `1 Compile` section, opt for `compile a single file`.
* Upon prompt, grant the necessary permissions. Opt for `Remember my choice` to streamline this process in subsequent instances.
* Initiate the compilation process by selecting `Compile lib.cairo`.
* Following compilation, an "artifacts" directory materializes, housing the compiled contract in two distinctive formats: Sierra (JSON file) and CASM. For Starknet deployment purposes, Remix will utilize the Sierra file. 
Rest assured, detailed elaboration on this process will ensue in subsequent chapters. At present, Remix is adeptly handling both compilation and deployment on our behalf.

== Deployment on the Development Network

Initiating the operational phase of your smart contract necessitates the establishment of an initial owner, a prerequisite addressed by the Constructor function.

Outlined below is a methodical approach to deploying your smart contract on the development network:

.Select the Appropriate Network

* Within the Starknet tab, navigate to the uppermost button labeled `Remote Devnet`.

.Choose a Devnet Account

* In the section titled "Devnet account selection" a roster of accounts specific to the designated devnet is presented.
* Select an account from the list and record its address for subsequent use.

.Declare

* Execute a click on "Declare lib.cairo".
* Following declaration, Remix's terminal will disseminate various logs furnishing crucial details such as:
* `transaction_hash`: This unique hash denotes the transaction and can be utilized for tracking its status.
* `class_hash`: Analogous to an identifier, the class hash encapsulates the definition of the smart contract.

[source,bash]
----
------------------------ Declaring contract: ownable_Ownable ------------------------
{
  "transaction_hash": "0x36dabf43f4962c97cf67ba132fb520091f268e7e33477d77d01747eeb0d7b43",
  "class_hash": "0x540779cd109ad20f46cb36d8de1ce30c75469862b4dc75f2f29d1b4d1454f60"
}
---------------------- End Declaring contract: ownable_Ownable ----------------------
----

.Initiating Deployment
* Input the copied address into the `init_owner` variable.
* Click on **"Deploy"**.
Post-deployment, Remix's terminal will send various logs. These logs provide crucial details, including:
* `transaction_hash`: The unique hash of the transaction. This hash can be used to track the transaction's status.
* `contract_address`: The address of the deployed contract. Use this address to interact with your contract.
* `data`: Contains the `init_owner` address fed to the constructor.

[source,bash]
----
{
  "transaction_hash": "0x624f5b9f57e53f6b5b62e588f0f949442172b3ad5d04f0827928b4d12c2fa58",
  "contract_address": [
    "0x699952dc736661d0ed573cd2b0956c80a1602169e034fdaa3515bfbc36d6410"
  ]
    ...
  "data": [
        "0x6b0ee6f418e47408cf56c6f98261c1c5693276943be12db9597b933d363df",
         ...
      ]
    ...
}
----

By adhering to the aforementioned procedure, you will effectively deploy your smart contract on the development network.

== Interaction with the Contract

Now that the contract is operational on the development network, engaging with it becomes feasible. Presented below is a comprehensive guide on effectively interacting with your contract on Starknet:

.Initiating Interaction

* Access the "Starknet" plugin tab within your interface.
* Opt for the "Interact" option to commence interaction.

.Calling the `get_owner` Function

* Select the `get_owner` function. Given its lack of arguments, the calldata field remains unpopulated. (Since this function pertains to reading data, its invocation is characterized as a "call").
* Execute the "Call" operation. The terminal will promptly furnish the outcome, divulging the address of the owner as supplied during the contract's deployment within the calldata for the constructor:

[source,json]
----
{
  "resp": {
    "result": [
      "0x6b0ee6f418e47408cf56c6f98261c1c5693276943be12db9597b933d363df"
    ]
  },
  "contract": "lib.cairo",
  "function": "get_owner"
}
----

This call does not consume gas as the function does not modify the contract's state.

.Invoking the `transfer_ownership` Function

* Opt for the "Write" option within the interaction area, where functions altering the contract's state are listed.
* Select the `transfer_ownership` function, necessitating the provision of the `new owner` address as input.
* Populate the `new_owner` field with the pertinent address. (Select any address from the "Devnet account selection" listed within the Environment tab for this purpose.)
* Activate the "Call" button. Subsequently, the terminal will present the transaction hash indicative of the alteration in the contract's state. Given that we are effectuating a modification in the contract's state, this form of interaction is termed an "invoke" and mandates signature by the account executing the function.
* For such transactions, the terminal logs will incorporate a "status" parameter, delineating the transaction's outcome. A status of "ACCEPTED_ON_L2" denotes acknowledgment by the Sequencer, the entity responsible for receiving and processing transactions, signifying inclusion in an imminent block. Conversely, a "REJECTED" status signifies disapproval by the Sequencer, precluding inclusion in the forthcoming block. Typically, transactions of this nature are approved, culminating in a modification of the contract's state.

[source,json]
----
{
  "resp": {
    "result": [
      "0x5495d56633745aa3b97bdb89c255d522e98fd2cb481974efe898560839aa472"
    ]
  },
  "contract": "lib.cairo",
  "function": "get_owner"
}
----

== Deployment on Starknet Testnet

Following the testing of your smart contract on a development network, the next step is deploying it onto the Starknet Testnet. The Starknet Testnet serves as a public platform accessible to all, offering an ideal environment for testing smart contracts and fostering collaboration among developers.

Before proceeding, it is imperative to establish a Starknet account.

=== Smart Wallet Configuration

Prior to deploying your smart contract on Starknet, addressing the transaction costs is paramount. While deploying on the Starknet Goerli Testnet incurs no charges, an operational smart wallet account is indispensable. You can set up a smart wallet through either of the following platforms:

* https://www.argent.xyz/argent-x/[Argent]
* https://braavos.app/[Braavos]

Both options provide robust Starknet wallets equipped with advanced security measures and enhanced accessibility features enabled by the capabilities of the Cairo VM, including Account Abstraction (further insights on this subject will be provided in subsequent sections of this guide).

. Install the recommended Chrome/Brave extension corresponding to your chosen wallet.
. Follow the instructions provided by your wallet provider to deploy your account.
. Utilize the https://faucet.goerli.starknet.io/[Starknet Faucet] to fund your account.
. Execute the deployment of your account onto the network, typically accomplished within approximately 10 seconds.

Once the setup is complete, you are primed to deploy your smart contracts onto the Starknet Testnet.

=== Deployment and Interaction

. Proceed as per the aforementioned deployment steps.
. Within the 'Environment selection' tab, opt for 'Wallet'.
. Select your Starknet account and proceed with the deployment and interaction processes for your contract.

Monitoring transaction hashes and addresses can be facilitated through various Starknet block explorers such as:

* https://testnet.starkscan.co/[Starkscan]
* https://goerli.voyager.online/[Voyager]
* https://viewblock.io/starknet[ViewBlock]
* https://www.oklink.com/starknet[Oklink]

These utilities offer a graphical depiction of transactions and modifications to the contract state. Noteworthy is the visibility provided when altering contract ownership through the `transfer_ownership` function, as the emitted event by the contract becomes observable within the block explorer. This mechanism serves as a potent means to monitor contractual events.
