[id="setting_up_environment"]
= Setting up your environment
:icons:
:toc: macro
:toc-title:
:toclevels: 1
:linkattrs:
:description: How to set up your environment to contribute

toc::[]

== Create a GitHub account
Before you can contribute to Starknet documentation, you must
https://www.github.com/join[sign up for a GitHub account].

== Set up authentication
When you have your account set up, follow the instructions to
https://help.github.com/articles/generating-ssh-keys/[generate and set up SSH
keys on GitHub] for proper authentication between your workstation and GitHub.

Confirm authentication is working correctly with the following command:

----
$ ssh -T git@github.com
----

== Fork and clone the Starknet documentation repository

For significant contributions, set up the Starknet documentation repository on your
workstation so that you can create PRs and contribute.
You only have to perform these steps during the initial setup.

=== Procedure

. Fork the https://github.com/starknet-io/starknet-docs repository to your
GitHub account from the GitHub UI. You can do this by clicking on *Fork* in the
upper right-hand corner.

. In the terminal on your workstation, change into the directory where you want
to clone the forked repository.

.  Clone the forked repository onto your workstation with the following
command, replacing _<user_name>_ with your actual GitHub username.
+
----
$ git clone git@github.com:<user_name>/starknet-docs.git
----

. Change into the directory for the local repository you just cloned.
+
----
$ cd starknet-docs
----

. Add an upstream pointer back to Starknet's remote repository, in this
case _starknet-docs_.
+
----
$ git remote add upstream git@github.com:starknet-io/starknet-docs.git
----

This ensures that you are tracking the remote repository so you can keep your local
repository synchronized.

[#previewing_the_website_on_your_local_machine]
== Previewing the website on your local machine

You don't need to install Antora to preview the website. This repo includes an embedded Antora installation, which is referred to in the Antora documentation as a _local installation_.

=== Prerequisites

You must have an active Node.js LTS release on your machine. See the _Antora documentation_ for your OS:

* https://docs.antora.org/antora/latest/install/linux-requirements/#node[Linux]
* https://docs.antora.org/antora/latest/install/windows-requirements/#node[Windows]
* https://docs.antora.org/antora/latest/install/macos-requirements/#node[macOS]

[id="http_server"]
[TIP]
====
Install the optional link:https://docs.antora.org/antora/latest/preview-site/#run-a-local-server-optional[http server Antora provides] so you can view the output in a local web server
====

[#git_related_info]
== Git-related info


* When naming a branch, if you do not use a fork, use the following format: `<name>/<short_description>`
* When creating a new PR, tag one or more of the following as reviewers: `stoobie`, `JameStark`
* When creating a new PR, you need to merge to the `dev` branch.

