= Troubleshooting the StarkGate bridge guide 

== Migrating from DAI v0 to DAI

Following https://twitter.com/MakerDAO/status/1746977683190251591?s=20[Maker DAO's announcement^], StarkWare launched a new set of DAI bridge and token contracts under StarkGate. This new DAI token retains the same contract 'symbol' and 'name' as the existing one, and to differentiate between the two, the old DAI is referred to as “DAI v0” while the new DAI is simply referred to as “DAI”.

Withdrawal of DAI v0 tokens is still possible with no limitations, but depositing DAI v0 using the DAI v0 bridge is disabled. Users are *strongly* encouraged to migrate to the new DAI token, as it cannot support StarkGate's latest features (such as Smart Deposits and Withdrawal Limits) and will stop being compatible with Starknet altogether over time.

To migrate from DAI v0 to DAI, either swap your DAI v0 for DAI using one of Starknet's https://www.starknet.io/dapps/?type=live&tags=216[swap apps and aggregators^] or withdraw your current DAI v0 tokens to L1 using and re-deposit them using StarkGate (which automatically issues the new DAI).










