pipeline {
    agent { label "gcp-hodor-slave-generic"}
    options {
       // Add timestamps to output.
       timestamps()
       timeout(time: 45, unit: 'MINUTES')
    }
    environment {
        TEST = "test"
        PR_ID = "pr-${env.CHANGE_ID}"
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:16.20.2'
                    reuseNode true
                }
            }
            environment {
                ANTORA_CACHE_DIR="${WORKSPACE}/.cache"
            }
            steps {
                script {
                    sh label:"Listing current directory", script:
                    """
                        ls -la
                    """
                    sh label:"Install node modules", script:
                    """
                        yarn
                    """
                    sh label:"Generate site", script:
                    """
                        yarn generate
                    """
                    sh label:"Copy artifacts", script:
                    """
                        mkdir ${PR_ID}
                        cp -r ./public_html/* ${PR_ID}
                    """
                    stash includes: "${PR_ID}/**/*", name: 'artifact'
                }
            }
        }
        stage('Publish') {
            steps {
                script {
                    def prId = env.CHANGE_ID
                    println "Pull Request ID: ${PR_ID}"
                    sh label:"Checkout gh-pages", script:
                    """
                        git fetch origin gh-pages:gh-pages
                        git checkout gh-pages
                    """
                    sh label:"Remove PR folder if exist", script:
                    """
                        if [ -d $PR_ID ]
                        then
                            rm -rf $PR_ID
                        fi
                    """
                    unstash 'artifact'
                    sh label:"Push to branch gh-pages", script:
                    """
                        git status
                        git config user.name "Jenkins Automation"
                        git config user.email "noreply@github.com"
                        git add .

                        if ! git diff-index --quiet HEAD --; then
                            # Debug information
                            echo "Changes detected. Committing and pushing changes."

                            commit_message="Adding or updating preview build for PR ${PR_ID}"
                        
                            # Debug message
                            echo "Commit message: $commit_message"
                        
                            # Commit changes
                            git commit -m "$commit_message"

                            # Check if commit was successful
                            if [ $? -eq 0 ]; then
                            # Debug information
                            echo "Commit successful. Pushing changes."
                        
                            # Push changes
                            git push
                        
                            # Check if push was successful
                            if [ $? -eq 0 ]; then
                                # Debug information
                                echo "Push successful."
                            else
                                # Debug information
                                echo "Error: Push failed."
                            fi
                            else
                            # Debug information
                            echo "Error: Commit failed."
                            fi
                        else
                            # Debug information
                            echo "No changes found."
                        fi
                    """
                }
            }
        }
    }
    post {
        cleanup {
            deleteDir()
        }
    }
}
