[id="chain-info"]

= Chain information

[TIP]
====
You can get the latest updates delivered to your inbox by subscribing to the link:https://www.starknet.io/starknet-devs-newsletter/[Starknet Devs Newsletter].
====

[id="important_addresses"]
== Important addresses

[discrete]
=== Core contract

[horizontal, labelwidth="15"]
Mainnet:: 0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4
Sepolia:: 0xE2Bb56ee936fd6433DC0F6e7e3b8365C906AA057

[discrete]
===  SHARP Verifier

[horizontal, labelwidth="15"]
Mainnet:: 0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60
Sepolia:: 0x07ec0D28e50322Eb0C159B9090ecF3aeA8346DFe

[discrete]
=== Fee tokens

[horizontal, labelwidth="15"]
STRK:: 0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d
ETH:: 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7

[discrete]
=== Voting token

[NOTE]
====
For information on The Starknet voting token, see link:https://governance.starknet.io/learn/vstrk_overview[_vSTRK overview_] on the Starknet Governance Hub.
====

[horizontal, labelwidth="15"]
Mainnet:: 0x0782f0ddca11d9950bc3220e35ac82cf868778edb67a5e58b39838544bc4cd0f
Sepolia:: 0x035c332b8de00874e702b4831c84b22281fb3246f714475496d74e644f35d492

[discrete]
=== Sequencer base URL
[horizontal, labelwidth="15"]
Mainnet:: \https://alpha-mainnet.starknet.io
Sepolia:: \https://alpha-sepolia.starknet.io

== Current versions

[%autowidth.stretch]
|===
|Environment |Starknet version|Sierra version|Cairo version

|Mainnet|0.13.3|1.6.0|2.0.0 - 2.8.2
|Sepolia Testnet|0.13.3|1.6.0|2.0.0 - 2.8.2
|===

== Current limits

[IMPORTANT]
====
The following limits are subject to revisions and change on a regular basis
====

[NOTE]
====
Starting from v0.13.0, blockifier-related constants and limits are defined for each Starknet version in a JSON file called `versioned_constants` in the link:https://github.com/starkware-libs/sequencer/tree/main/crates/blockifier/resources[blockifier's resources directory^].
====

[%autowidth.stretch]
|===
| Entity | Description | Sepolia | Mainnet

| Block time
| The maximum amount of time within which a pending block is closed, if no other limit is met.
| 30 seconds
| 30 seconds

| Block limit (Cairo steps)
| The maximum number of Cairo steps that can be completed
within each block to ensure block production times remain consistent and predictable.
| 40,000,000
| 40,000,000

| Block limit (gas)
| Certain Starknet operations, such as sending messages between L1 and L2, consume Ethereum gas. The current L1 state update
mechanism involves an Ethereum transaction for each Starknet block.

The gas limit for Starknet blocks is therefore inherited from the gas limit for Ethereum blocks.
| 5,000,000
| 5,000,000

| Max transaction size (Cairo steps)
| The maximum number of computational steps, measured in Cairo steps, that a transaction can contain when processed on the Starknet network.
This limit is important for ensuring the efficient execution of transactions and preventing potential congestion.
| 10,000,000
| 10,000,000

| Max state updates per transaction
| The maximum number of storage updates that a single transaction can generate. This limit helps maintain network stability and predictable performance.
| 2,000
| 2,000

| Max number of events per transaction
| The maximum number of events that a transaction can emit during its execution.
| 1,000
|  1,000

| Max number of data felts per event
| The maximum number of felts that an event can contain in its `data` array.
| 300
|  300

| Max number of key felts per event
| The maximum number of felts that an event can contain in its `keys` array.
| 50
| 50

| Max Cairo steps for `validate`
| The maximum number of computational steps, measured in Cairo steps, for a `validate` function.
| 1,000,000
| 1,000,000

| Max contract bytecode size
| The maximum size of the bytecode or program that a smart contract can have on Starknet.

Bytecode is the low-level code that comprises smart contracts. Limiting this size helps manage the complexity of contracts and the overall efficiency of the network.
| 81,290
|  81,290
| Max contract class size
| The maximum size for a contract class within Starknet.

Contract classes are a fundamental building block for smart contracts, and limiting their size can have implications for the network's scalability and security.
| 4,089,446 bytes
| 4,089,446 bytes

| IP address limits
| In order to reduce network spam, Starknet limits the amount of contract reads and writes that a single IP
address can make.
| 200 per min per IP address
| 200 per min per IP address

| Signature length (felts)
| The maximum length of a signature
| 4,000 
| 4,000

| Calldata length (felts)
| The maximum length of a transaction calldata
| 5,000
| 5,000
|===


== Deprecated features

[NOTE]
====
A deprecated feature is a feature that is still supported, but support will be removed in a future release of Starknet.
====

[cols="1,3",]
|===
|Name|Description

|Starknet CLI | Support for the Starknet CLI has been removed. Instead use xref:cli:starkli.adoc[Starkli].

Support for Starknet CLI is removed in Starknet v0.13.0.
|Cairo 0 | xref:starknet-versions:version-notes.adoc#version0.11.0[Starknet v0.11.0] introduces Cairo 1.0 smart contracts.
|===

== Unsupported and removed features

[NOTE]
====
An unsupported feature is a feature that is no longer supported.

A removed feature is a feature that has been entirely removed.
====

[cols="1,3"]
|===
|Name|Description

| Goerli testnet
a| Goerli testnet support was removed April 2, 2024. Sepolia testnet replaces Goerli testnet.

Starknet started migrating to Sepolia testnet on November 15th, 2023.  For more information on the Goerli deprecation, see https://ethereum.org/nb/developers/docs/networks/#ethereum-testnets[the deprecation announcement on Ethereum's site].

Full nodes, API services, SDKs, and other Starknet developer tools have migrated to Sepolia as well.

[NOTE]
====
Sepolia's state and history are relatively small. Sepolia xref:starknet-versions:version-notes.adoc[supports declaring classes of CairoZero and Cairo v2.0.0 and higher].
====

| Starknet feeder gateway a| The Starknet feeder gateway, a temporary solution for querying the sequencer’s state, is being replaced by Starknet full nodes (Pathfinder, Juno, Deoxys, Papyrus) and RPC services. For more information, see xref:tools:api-services.adoc[Full nodes and API services].

Support for the feeder gateway queries that are not required for full nodes to synchronize on the state of Starknet will stop according to the following schedule:

[%autowidth.stretch]
!===
!Environment !Date

!Integration
!1 November 2023
!Testnet
!15 November 2023
!Mainnet
!19 December 2023
!===

Queries that are required for full nodes to synchronize on the state of Starknet are still supported.

For more information, see the Community Forum post link:https://community.starknet.io/t/feeder-gateway-deprecation/100233[_Feeder Gateway Deprecation_].
// | Goerli testnet 2 | Goerli testnet 2 is removed. Use Goerli testnet.
|Free L1-> L2 messaging |Previously, sending a message from L1 to L2 had an optional fee associated.

From xref:starknet-versions:version-notes.adoc#version0.11.0[Starknet v0.11.0], the fee mechanism is enforced and the ability to send L1->L2 messages without the corresponding L2 fee has been removed.

See xref:architecture-and-concepts:network-architecture/messaging-mechanism.adoc#l1-l2-message-fees[here] for more details.

|`invoke` transaction v0 |`invoke` transaction v0 has been removed since xref:starknet-versions:version-notes.adoc#version0.11.0[Starknet v0.11.0].
|`declare` transaction v0 |`declare` transaction v0 has been removed since xref:starknet-versions:version-notes.adoc#version0.11.0[Starknet v0.11.0].

|`deploy` transaction|The `deploy` transaction has been removed since xref:starknet-versions:version-notes.adoc#version0.10.3[Starknet v0.10.3].

To deploy new contract instances, you can use the xref:architecture-and-concepts:smart-contracts/system-calls-cairo1.adoc#deploy[`deploy` system call].
|===

