[id="contract_management"]
= Contract Management


[id="governance"]
== Governance

The StarkEx contract is governed by one or more Governors of which the initial one is the deployer of the contract.

A governor has the sole authority to perform the following operations:

. Nominate additional governors (https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/MainGovernance.sol#L53[`mainNominateNewGovernor`])
. Remove other governors (https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/MainGovernance.sol#L57[`mainRemoveGovernor`])
. Add new https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/Verifiers.sol#L45[`Verifiers`] and https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/AvailabilityVerifiers.sol#L48[`AvailabilityVerifiers`]``
. Remove https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/Verifiers.sol#L57[`Verifiers`] and https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/AvailabilityVerifiers.sol#L60[`AvailabilityVerifiers`] after a time-lock allows it
. Nominate Operators (see xref:contract-management.adoc[`Operator`]) and Token Administrators (see xref:contract-management.adoc[`Tokens`])

Adding governors is performed in a two-step procedure:

. First, an existing governor nominates a new governor (https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/MainGovernance.sol#L53[`mainNominateNewGovernor`])
. Then, the new governor must accept governance to become a governor (https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/MainGovernance.sol#L61[`mainAcceptGovernance`])

This two-step procedure ensures that a Governor's public key cannot be nominated unless there is an entity that has the corresponding private key. This is intended to prevent errors in the addition process.

The Governor's private key should typically be held in a secure cold wallet.

[id="operator"]
== Operator

The Operator of the contract is the entity entitled to submit state update requests by calling xref:contract-management.adoc[`updateState`].

An Operator may be instantly appointed or removed by the contract Governor (as explained above).

Typically, the Operator is the hot wallet of the StarkEx service submitting proofs for state updates.

[id="tokens"]
== Tokens

Registration of a new asset entails defining a new asset type within the system and associating it with an `assetInfo` array of bytes and a quantization factor (`quantum`).

To register a new asset, the `tokenAdmin` calls https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/TokenRegister.sol#L80[`registerToken`], providing `assetType` and `assetInfo`. A full explanation of how to compute both can be found  xref:starkex-specific-concepts.adoc#assetinfo-assettype-and-assetid[here].

Once registered, assets cannot be removed from the system, as their IDs may be used by off-chain accounts.

A `tokenAdmin` may be instantly appointed or removed by the contract `Governor` (as explained above). Typically, the `tokenAdmin``'s private key should be kept in a cold wallet.

[id="verifiers"]
== Verifiers

A Verifier contract is an implementation of a STARK verifier that the StarkEx service sends STARK proofs to (see xref:fact-registry.adoc#stark-verifier-for-cairo-programs[STARK Cairo verifier]). In addition, StarkEx contract can call a verifier to check if a valid proof has been accepted for a given state transition (typically described as a hash on the public input of the assumed proof).

The StarkEx contract will normally query only one verifier contract for proof validity checks. However, in the event that the verifier algorithm needs to be updated, additional verifiers may be https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/Verifiers.sol#L45[registered] by the contract Governor. Such new verifiers are then also required to attest to the validity of state transitions and only if all the verifiers attest to the validity the state transition is accepted.
[NOTE]
====
This _*one*_ verifier is our  xref:fact-registry.adoc#stark-verifier-for-cairo-programs[Universal Cairo verifier], _*capable of verifying any Cairo program.*_

In order to validate that the Cairo verifier has verified the correct off-chain Cairo program, StarkEx smart contract compares the hash of the off-chain program with the hash of the program that the Cairo Verifier verified. This hash is given as an input to the Cairo verifier along with the proof.
====

Removal of verifiers is also the responsibility of the  xref:contract-management.adoc#governance[Governor]. The removal process is more sensitive than verifier registration as it may affect the soundness of the system. Hence, this is performed in two steps:

. The xref:contract-management.adoc#governance[Governor] first announces the intent to remove a verifier by calling https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/Verifiers.sol#L51[`announceVerifierRemovalIntent`].
. After the expiration of a https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/libraries/LibConstants.sol#L26[VERIFIER_REMOVAL_DELAY] time-lock, actual removal may be performed by calling https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/Verifiers.sol#L57[`removeVerifier`].

The removal delay ensures that a user concerned about the soundness of the system has ample time to leave the exchange.

[id="availability_verifiers"]
== Availability Verifiers

A Committee contract is a contract that the exchange service sends committee member signatures to attest that they have a copy of the data over which a new Merkle root is to be accepted as the new state root (See  xref:fact-registry.adoc#committee-signature-verifier[here]). In addition, the exchange contract can call an availability verifier to check if such signatures were indeed provided by a sufficient number of committee members as defined in the Committee contract for a given state transition (as reflected by the old and new vault and order roots).
[NOTE]
====
The committee mechanism is required only when StarkEx works with xref:data-availability-modes.adoc#validium[Validium]. When StarkEx works with xref:data-availability-modes.adoc#zkrollup[ZK-Rollups], all the relevant data appears on-chain as part of the proof output - so there is no need for a committee.
====

The exchange contract will normally query only one Committee contract for data availability checks. However, in the event that the Committee needs to be updated, additional verifiers may be https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/AvailabilityVerifiers.sol#L48[registered] by the contract  xref:contract-management.adoc#governance[Governor]. Such new availability verifiers are then also required to attest to the availability of the for state transitions and only if all the availability verifiers attest to it, the state transition is accepted.

Removal of availability verifiers is also the responsibility of the Governor. The removal process is more sensitive than availability verifier registration as it may affect the soundness of the system. Hence, this is performed in two steps:

. The  Governor first announces the intent to remove an availability verifier by calling https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/AvailabilityVerifiers.sol#L54[`announceAvailabilityVerifierRemovalIntent`].
. After the expiration of a https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/libraries/LibConstants.sol#L26[VERIFIER_REMOVAL_DELAY] time-lock, actual removal may be performed by calling https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/components/AvailabilityVerifiers.sol#L60[`removeAvailabilityVerifier`].

The removal delay ensures that a user concerned about the soundness of the system has ample time to leave the exchange.

[id="state_update"]
== State Update

The StarkEx contract tracks the state of the off-chain exchange service by storing Merkle roots of the vault state (off-chain account state) and the order state (including orders and transfers).

The xref:contract-management.adoc#operator[`Operator`] is the only entity entitled to submit state updates by calling https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/starkex/interactions/UpdateState.sol#L113[`updateState`] and this is only allowed if the contract is not in the frozen state (see xref:contract-management.adoc[`FullWithdrawals`]). The call includes the `publicInput` of a STARK proof, and additional data (`applicationData`) that includes information not attested to by the proof.

The `publicInput` includes the current (initial) and next (final) Merkle roots as mentioned above, the heights of the Merkle trees, a list of vault operations and a list of conditional transfers.

[id="vault_operations"]
=== Vault Operations

A vault operation can be a ramping operation (deposit/withdrawal) or an indication to clear a forced operation request. Each vault operation is encoded in 3 words as follows:

. Word 0: Stark Key of the vault owner (or the requestor Stark Key for false full withdrawal).
. Word 1: Asset ID of the vault representing either the currency (for fungible tokens) or a unique token ID and its on-chain contract association (for non-fungible tokens).
. Word 2:
 .. ID of the vault (off-chain account)
 .. Vault balance change in biased representation (excess-2**63). A negative balance change implies a withdrawal while a positive amount implies a deposit. A zero balance change may be used for operations implying neither (e.g. a false xref:spot-trading-full-withdrawals.adoc[full withdrawal]request).
 .. A bit indicating whether the operation requires clearing a full withdrawal request.

The above information is used by the exchange contract in order to update the pending accounts used for xref:deposits.adoc[deposits] and xref:README-withdrawal.adoc[withdrawals].

The next section in the `publicInput` is a list of encoded conditions corresponding to the conditional transfers in the batch.

The `applicationData` holds the following information:

. The ID of the current batch for which the operator is submitting the update.
. The expected ID of the last batch accepted on chain. This allows the operator submitting state updates to ensure the same batch order is accepted on-chain as was intended by the operator in the event that more than one valid update may have been generated based on different previous batches - an unlikely but possible event.
. For each conditional transfer in the batch two words are provided:
 .. Word 0: The address of a xref:fact-registry.adoc[fact registry contract].
 .. Word 1: A fact to be verified on the above contract attesting that the condition has been met on-chain.

The STARK proof attesting to the validity of the state update is submitted separately by the exchange service to (one or more) STARK integrity verifier contract(s). Likewise, the signatures of committee members attesting to the availability of the vault and order data is submitted separately by the exchange service to (one or more) availability verifier contract(s).

The state update is only accepted by StarkEx contract if the integrity verifier and availability verifier contracts have indeed received such proof of soundness and data availability.

Upon a successful state update, the event https://github.com/starkware-libs/starkex-contracts/blob/e42fedeb2d6a262edc7ed5086e4cecddc2df087e/scalable-dex/contracts/src/starkex/interactions/UpdateState.sol#L93[LogRootUpdate] is emitted.
