[id="perpetual_trading"]
= Perpetual trading


[id="vault_structure"]
== Vault Structure

The vault contains the following fields:

* `starkKey` - the public key of the vault's owner.  Transfers and trades that refer to this vault must be signed with this key.
* `collateralAmount` - the amount of collateral in the vault.
* A list of synthetic `assetId`. For each `assetId` we have:
 ** `assetId`&#x20;
 ** `amount` (xref:starkex-specific-concepts.adoc[resolutionised])
 ** xref:funding-tick-1.adoc[`cachedFundingIndex`]

[id="additional_elements_in_the_state"]
== Additional Elements in the State

[id="global_funding_indices"]
=== Global funding indices

The most recent global funding index according to the lastxref:funding-tick-1.adoc[funding tick]. Used to update the position's balance before every transaction execution according to the funding logic.

[id="current_system_time"]
=== Current system time

The current time of the system advances whenever a Funding tick or an Oracle price tick arrives. When closing a batch for submission, the system time must be a date within the last week.

[id="current_prices"]
=== Current prices

The current prices of all the assets in the system, as received from different xref:oracle-price-tick.adoc[Oracle Price Tick] transactions.
