[id="overview"]
= Overview

Starknet is a permissionless decentralized Zero Knowledge Rollup (also known as a “Validity-Rollup”). It
operates as an L2 network over Ethereum, enabling any dApp to achieve unlimited scale for its computation – without compromising Ethereum’s composability and security, thanks to Starknet’s reliance on the safest and most scalable cryptographic proof system – STARK.

Starknet Contracts and the Starknet OS are written in Cairo – supporting the deployment and scaling of any use case, whatever the business logic.


[.block-container]
====
Starknet Smart contracts

Learn how to write and deploy smart contracts for Starknet.

>Read more
====

[.block-container]
====
The Starknet book

Learn Cairo programming language and Starknet smart contract development step by step.

>Read more
====

[.block-container]
====
Cairo 1.0 documentation

Explore the Cairo 1.0 documentation.

>Read more
====

[.block-container]
====
The Cairo book

Learn Cairo with the community Cairo book.

>Read more
====



== Explore

[.block-container]
====
Starknet versions

Find the latest information on Starknet versions and features.

>Read more
====

[.block-container]
====
Architecture and concepts

Learn about the core concepts of Starknet.

>Read more
====

[.block-container]
====
Developer tools and resources

Explore our developer tools and resources

>Read more
====

[.block-container]
====
Quick start

Get started with Starknet

>Read more
====