[id="overview"]
= Overview

Starknet is a permissionless decentralized Validity-Rollup (also known as a “ZK-Rollup”). It operates as an L2 network over Ethereum, enabling any dApp to achieve unlimited scale for its computation – without compromising Ethereum’s composability and security, thanks to Starknet’s reliance on the safest and most scalable cryptographic proof system – STARK.

Starknet Contracts and the Starknet OS are written in Cairo – supporting the deployment and scaling of any use case, whatever the business logic.


[.block-container]
====
.Starknet Smart contracts
Learn how to write and deploy smart contracts for Starknet.
>Read more
====

[.block-container]
====
.The Starknet book
Learn Cairo programming language and Starknet smart contract development step by step.
>Read more
====

[.block-container]
====
.Cairo 1.0 documentation
Explore the Cairo 1.0 documentation.
>Read more
====

[.block-container]
====
.The Cairo book
Learn Cairo with the community Cairo book.
>Read more
====

== Explore
