[id="overview"]
= Overview

Starknet is a permissionless decentralized Validity-Rollup (also known as a “ZK-Rollup”). It operates as an L2 network over Ethereum, enabling any dApp to achieve unlimited scale for its computation – without compromising Ethereum’s composability and security, thanks to Starknet’s reliance on the safest and most scalable cryptographic proof system – STARK.

Starknet Contracts and the Starknet OS are written in Cairo – supporting the deployment and scaling of any use case, whatever the business logic.


<div class="doc">
<div class="ctablock">
    <div class="block-container">Deep dive into Starknet</div>
    <div class="block-container">Learn Cairo programming language and Starknet smart contract development step by step.</div>
    <div class="block-container">Explore the Cairo 1.0 documentation.</div>
    <div class="block-container">Learn Cairo with the community Cairo book.</div>
</div>
</div>

== Explore

<div class="doc">
<div class="ctablock">
<div class="block-container">Smart contract syntax.</div>
<div class="block-container">Developer tools and resources.</div>
<div class="block-container">Contribute to Starknet.</div>
<div class="block-container">Starknet roadmap and upcoming versions.</div>
</div>
</div>
