[id="overview"]
= Overview

== What is Starknet?

**Starknet is a Validity-Rollup (aka ZK-Rollup) Layer 2 network that operates on top of Ethereum, enabling dApps to massively scale Ethereum without compromising on security.**

Blockchains aim to achieve three core attributes: security, decentralization, and scalability. In the blockchain world, a well-known trilemma is that it’s possible to achieve only two of these concurrently in a given system, inevitably requiring a compromise on the third. Ethereum places a higher emphasis on security and decentralization, impacting its scalability. Growth in the number of Ethereum users leads to slow transaction speeds and high gas prices, hindering Ethereum’s widespread adoption.

How can we make Ethereum scalable without undermining its security and decentralization? This is where the Starknet Validity Rollup comes in. Combining Ethereum and Starknet achieves massive scalability.

Starknet achieves scale by shifting transaction processing off the Ethereum Mainnet (what we call off-chain) while retaining a summary of the transactions onchain. Transactions are grouped in batches into blocks, processed off-chain, and then summarized into a single onchain transaction. Since transactions occur off-chain, it’s vital to ensure the integrity of the transactions and their execution without having to re-execute them. Starknet addresses this by employing STARK (Scalable, Transparent ARgument of Knowledge) proofs for verifiable computation. Starknet then transmits only essential information about the block and the proof to Ethereum, where it is verified with minimal computational effort.


**These are some key features of Starknet:**

- **Speed and Efficiency:** Starknet averaged 127 transactions per second (TPS) on October 29 2024, breaking the Layer-2 record for sustained TPS over 24 hours. A peak of 857 TPS has been reached. Transactions on Starknet are super fast, with an average confirmation time of under 2 seconds. Upcoming releases aim to make transactions even faster.

- **Low Costs:** Transactions on Starknet cost less than on Ethereum. Network fees are ultra-low, averaging at $0.002 per transaction. Future updates will make it even cheaper.

- **State of the art blockchain technology:** Account abstraction / Volition / Paymaster are new technologies that are already implemented in Starknet, allowing a great User Experience (UX), that are not able to propose older blockchains.

- **Developer-Friendly:** Starknet lets developers easily build decentralized apps using its native language, Cairo.

- **CVM:** Thanks to Cairo, Starknet runs on it's own Virtual Machine, called Cairo VM (CVM), that allow to innovate beyond the Ethereum Virtual Machine (EVM) and create a new paradigm for decentralized applications.

== CairoVM

Creating Validity Proofs for general computational programs requires a deep grasp of the complex mathematical principles that underlie STARKs. The Cairo VM is intentionally tailored for Validity Proof systems and is not constrained by the limitations imposed by the EVM (Ethereum virtual machine).

|===
| | **CairoVM** | **EVM**  

| **Purpose**  | Proof Optimised VM | Blockchain 
| **Computational model** | Von Neumann architecture | Stack-based machine 
| **Memory model** | Nondeterministic read-only memory (key in optimizing the proof for memory accesses) | Read write memory requires more computation to generate a proof.   
|===

== Cairo Language

The goal of StarkNet is to exponentially scale Ethereum using the mathematical integrity of STARKs, and the goal of Cairo is to make this exponential scale accessible to developers. Accessibility means a programming language that is efficient, easy to read and write, and safe to use.
Cairo is a Turing-complete programming language for efficiently writing STARK-provable programs. It's a Rust-like high-level language. Like Rust, it is intended to allow developers to easily write code that is efficient and safe.

== Explore Starknet

[pass]
++++
<div class="home-cta-container">
  <a href="https://docs.starknet.io/documentation/quick_start/environment_setup/" class="home-cta home-cta-first" id="cta1">
    <div class="image-container">
      <img src="_images/developers.svg" style="filter: none; border-radius: 0px;" class="cta-image" id="img_1">
    </div>
    <h2>Quick start</h2>
    <p class="chakra-card__body css-jintet" id="text1">Set up your environment and get started with Starknet.</p>
    <p class="chakra-card__body css-jintet" id="text2"><b>Explore ></b></p>
  </a>

  <a href="https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/header/" class="home-cta" id="cta2">
    <div class="image-container">
      <img src="_images/how_SN_works.svg" style="filter: none; border-radius: 0px;" class="cta-image" id="img_2">
    </div>
    <h2>Architecture</h2>
    <p class="chakra-card__body css-jintet" id="text3">Learn about Starknet's architecture including contracts and accounts.</p>
    <p class="chakra-card__body css-jintet" id="text4"><b>Explore ></b></p>
  </a>

  <a href="https://docs.starknet.io/documentation/starknet_versions/version_notes/" class="home-cta" id="cta3">
    <div class="image-container">
      <img src="_images/roadmap.svg" style="filter: none; border-radius: 0px;" class="cta-image" id="img_3">
    </div>
    <h2>Releases</h2>
    <p class="chakra-card__body css-jintet" id="text5">Learn more about the current version of Starknet.</p>
    <p class="chakra-card__body css-jintet" id="text6"><b>Explore ></b></p>
  </a>
</div>
++++

== Contribute to the Starknet docs

Want to contribute to Starknet documentation? Get started here:

* See the link:https://github.com/starknet-io/starknet-docs/blob/dev/README.adoc#different_ways_to_contribute[different ways to contribute].
* Review these link:https://github.com/starknet-io/starknet-docs/blob/dev/contributing_to_docs/doc_guidelines.adoc[basic writing guidelines] to help you write better and be a more valuable contributor.
* Use the link:https://github.com/starknet-io/starknet-docs/blob/dev/contributing_to_docs/starknet_docs_style_guide.adoc[Starknet documentation supplementary style guide] to help you write with the Starknet voice.

[pass]
++++
<html>
<head>
<style>
*::before, ::after {
  border-color: var(--chakra-colors-gray-200);
}

:where(*, *::before, *::after) {
  border-width: 0;
  border-style: solid;
  box-sizing: border-box;
  word-wrap: break-word;
}

@media (max-width: 768px) {
  .home-cta-container {
    flex-direction: column; /* Switch back to a column layout for mobile */
  }

  .home-cta-container .home-cta {
    margin: 8px 8px 0 8px; /* Reset margin for mobile */
    width: 100%; /* Make each box take up the full width of the screen */
  }
}

.home-cta-container {
  display: flex;
}

.cta-image-container {
  background-image: url('_images/developers.svg');
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
  width: 100%;
  height: 100%;
}

.image-container {
  display: flex;
  flex-direction: column;
  justify-content: center; s
  align-items: center;
  height: 8em;
  margin-bottom: 10px;
  margin: 8px;
  border-radius: 20px 20px 0 0;
  position: relative;
  background-image: linear-gradient(180.15deg, var(--chakra-colors-chakra-body-text) 0.2%, var(--chakra-colors-chakra-body-bg) 105.43%);
  overflow: hidden;
}

.image-container img {
  z-index: -1;
}

.cta-image {
  max-width: 464px;
  max-height: 100%;
}

.home-cta {
  flex: 1;
  margin: 8px 8px 0 8px;
  padding: 20px;
  background-color: var(--chakra-colors-chakra-body-bg);
  border: 1px solid rgb(226, 232, 240);
  border-bottom: 1px solid rgb(226, 232, 240);
  border-radius: 20px;
  color: var(--chakra-colors-card-link-fg);
  font-size: 18px;
  font-weight: var(--chakra-fontWeights-medium);
  text-decoration: none;
  transition: background-color 0.15s, border-color 0.15s, color 0.15s;
  box-sizing: border-box;
  position: relative;
  background-image: linear-gradient(180.15deg, var(--chakra-colors-gradient-blue-default-a) 0.2%, var(--chakra-colors-gradient-blue-default-b) 105.43%);
  overflow: hidden;
  transition-property: var(--chakra-transition-property-common);
  transition-duration: var(--chakra-transition-duration-fast);
  transition-timing-function: var(--chakra-transition-easing-ease-out);
  cursor: pointer;
  -webkit-text-decoration: none;

  outline: 2px solid transparent;
  outline-offset: 2px;
}

.home-cta-first {
  margin-left: 0;
}

.chakra-card__body.css-jintet {
  font-size: 15px;
  color: #363636;
}

.column-container {
  display: flex;
}

.column {
  flex: 1;
  padding: 10px;
  margin: 5px;
  border-radius: 5px;
}

.home-cta-container .home-cta:hover {
  text-decoration: none;
  color: #363636;
  border-color: #C506E4;
}

.home-cta a {
  text-decoration: none;
  color: #363636;
}
</style>

<script>

document.addEventListener('DOMContentLoaded', function() {
  const themeSwitch = document.querySelector('[data-theme="dark"]');
  if (!themeSwitch) {
    console.error('Theme switch element not found');
    return;
  }

  const image1 = document.getElementById('img_1');
  const image2 = document.getElementById('img_2');
  const image3 = document.getElementById('img_3');

  const text1 = document.getElementById('text1');
  const text2 = document.getElementById('text2');
  const text3 = document.getElementById('text3');
  const text4 = document.getElementById('text4');
  const text5 = document.getElementById('text5');
  const text6 = document.getElementById('text6');

  let initialThemeSet = false; // To track if the initial theme has been set

  themeSwitch.addEventListener('click', () => {
    const currentTheme = themeSwitch.getAttribute('data-theme');
    // Toggle the theme
    themeSwitch.setAttribute('data-theme', currentTheme === 'dark' ? 'light' : 'dark');
    // Toggle the theme
    toggleTheme(currentTheme);
  });

  function toggleTheme(currentTheme) {
    // Handle theme switching and image/text updates
    if (currentTheme === 'dark' || !initialThemeSet) {
      image1.src = '_images/developers_dark.svg';
      image2.src = '_images/how_SN_works_dark.svg';
      image3.src = '_images/roadmap_dark.svg';
      text1.style.color = 'white';
      text2.style.color = 'white';
      text3.style.color = 'white';
      text4.style.color = 'white';
      text5.style.color = 'white';
      text6.style.color = 'white';
    } else {
      image1.src = '_images/developers.svg';
      image2.src = '_images/how_SN_works.svg';
      image3.src = '_images/roadmap.svg';
      text1.style.color = '';
      text2.style.color = '';
      text3.style.color = '';
      text4.style.color = '';
      text5.style.color = '';
      text6.style.color = '';
    }

    if (!initialThemeSet) {
      initialThemeSet = true;
    }
  }

  // Set the initial state based on the themeSwitch value
  toggleTheme(themeSwitch.getAttribute('data-theme'));
});


</script>
</head>
</html>

++++
