[id="overview"]
= Overview

Starknet is a permissionless decentralized Zero Knowledge Rollup (also known as a “Validity-Rollup”). It
operates as an L2 network over Ethereum, enabling any dApp to achieve unlimited scale for its computation – without compromising Ethereum’s composability and security, thanks to Starknet’s reliance on the safest and most scalable cryptographic proof system – STARK.

Starknet Contracts and the Starknet OS are written in Cairo – supporting the deployment and scaling of any use case, whatever the business logic.


[.block-container]
====
*Starknet Architecture and concepts*

Get familiar with Starknet and how it works.

xref:architecture_and_concepts:index.adoc[Read more >]
====

[.block-container]
====
*The Starknet book*

Learn Starknet smart contract development step by step.

link:book.starknet.io[Read more >]
====

[.block-container]
====
*Cairo 1.0 documentation*

Explore the Cairo 1.0 documentation.

link:https://www.cairo-lang.org/docs/v1.0/[Read more >]
====

[.block-container]
====
*The Cairo book*

Learn Cairo with the community Cairo book.

link:https://cairo-book.github.io/[Read more >]
====


== Explore the Starknet documentation

[.block-container]
====
*Starknet versions*

Find the latest information on Starknet versions and features.

xref:starknet_versions:version_notes.adoc[Read more >]
====

[.block-container]
====
*Starknet API reference*

Learn how to interact with Starknet's node API.

xref:api:api-reference.adoc[Read more >]
====

[.block-container]
====
*Developer tools and resources*

Explore our developer tools and resources

xref:tools:[Read more >]
====

[.block-container]
====
*Quick start*

Get started with Starknet

xref:quick_start:[Read more >]
====