[id="overview"]
= Overview

Starknet is a permissionless decentralized Zero Knowledge Rollup (also known as a “Validity-Rollup”). It
operates as an L2 network over Ethereum, enabling any dApp to achieve unlimited scale for its computation – without compromising Ethereum’s composability and security, thanks to Starknet’s reliance on the safest and most scalable cryptographic proof system – STARK.

Starknet Contracts and the Starknet OS are written in Cairo – supporting the deployment and scaling of any use case, whatever the business logic.


[.block-container]
====
*Starknet Architecture and concepts*

Get familiar with Starknet and how it works.

Read more >
====

[.block-container]
====
*The Starknet book*

Learn Starknet smart contract development step by step.

Read more >
====

[.block-container]
====
*Cairo 1.0 documentation*

Explore the Cairo 1.0 documentation.

Read more >
====

[.block-container]
====
*The Cairo book*

Learn Cairo with the community Cairo book.

Read more >
====


== Explore the Starknet documentation

[.block-container]
====
*Starknet versions*

Find the latest information on Starknet versions and features.

Read more >
====

[.block-container]
====
*Starknet API reference*

Learn how to interact with Starknet's node API.

Read more >
====

[.block-container]
====
*Developer tools and resources*

Explore our developer tools and resources

Read more >
====

[.block-container]
====
*Quick start*

Get started with Starknet

Read more >
====