[id="overview"]
= Overview
Starknet is a permissionless, decentralized zero-knowledge rollup (ZK rollup) for Ethereum. It operates as a Layer 2 (L2) network, enabling any dApp to achieve unlimited scale for its computation without compromising on Ethereum’s composability
and security.

Starknet acheives low cost transactions and high performance by using its own cryptographic proof system called STARK. Starknet contracts and the Starknet OS are written in link:https://github.com/starkware-libs/cairo[Cairo], a custom-built,
low level programming language.

The Starknet stack is fully open source allowing developers to choose exactly how they interact with Starknet.

== Explore Starknet

[pass]
++++
<div class="home-cta-container">
  <a href="https://docs.starknet.io/documentation/quick_start/environment_setup/" class="home-cta home-cta-first" id="cta1">
    <div class="image-container">
      <img src="_images/developers.svg" style="filter: none; border-radius: 0px;" class="cta-image">
    </div>
    <h2>Quick start</h2>
    <p class="chakra-card__body css-jintet">Set up your environment and get started with Starknet.</p>
    <p class="chakra-card__body css-jintet">Explore ></p>
  </a>

  <a href="https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/header/" class="home-cta" id="cta2">
    <div class="image-container">
      <img src="_images/how_SN_works.svg" style="filter: none; border-radius: 0px;" class="cta-image">
    </div>
    <h2>Architecture</h2>
    <p class="chakra-card__body css-jintet">Learn about Starknet's architecture including contracts and accounts.</p>
    <p class="chakra-card__body css-jintet">Explore ></p>
  </a>

  <a href="https://docs.starknet.io/documentation/starknet_versions/version_notes/" class="home-cta" id="cta3">
    <div class="image-container">
      <img src="_images/roadmap.svg" style="filter: none; border-radius: 0px;" class="cta-image">
    </div>
    <h2>Releases</h2>
    <p class="chakra-card__body css-jintet">Learn more about the current version of Starknet.</p>
    <p class="chakra-card__body css-jintet">Explore ></p>
  </a>
</div>
++++

== Developer tools and resources

[pass]
++++
<div class="no-background no-border">
  <div class="column-container">
    <div class="column">
      <p><a href="https://book.starknet.io/">The Starknet Book</a></p>
      <p><a href="https://docs.cairo-lang.org/">The Cairo docs</a></p>
      <p><a href="https://docs.starknet.io/documentation/tools/devtools/">Starknet development tools</a></p>
      <p><a href="https://docs.starknet.io/documentation/tools/api-services/">Full nodes and API services</a></p>
    </div>
    <div class="column">
      <p><a href="https://docs.starknet.io/documentation/tools/limits_and_triggers/">Limits and triggers</a></p>
      <p><a href="">Cairo 0 tools</a></p>
      <p><a href="https://docs.starknet.io/documentation/tools/ref_block_explorers/">Block explorers</a></p>
      <p><a href="https://docs.starknet.io/documentation/tools/audit/">Audit providers</a></p>
    </div>
  </div>
</div>
++++

== Contribute to these docs

If you are interested in contributing to Starknet technical documentation, the following table provides quick links to help you get started.

|===
|*Question* |*Resource*
|I'm interested, how do I contribute?
|For information on how you can contribute, see link:https://github.com/starknet-io/starknet-docs/blob/dev/README.adoc#different_ways_to_contribute[Different ways to contribute].
|Are there any basic guidelines to help me?
| For basic guidelines to help us keep our content consistent, see link:https://github.com/starknet-io/starknet-docs/blob/dev/contributing_to_docs/doc_guidelines.adoc[Documentation guidelines].
| Is there a style guide and writing guide I should use?
| See the link:https://github.com/starknet-io/starknet-docs/blob/dev/contributing_to_docs/starknet_docs_style_guide.adoc[Starknet documentation supplementary style guide].
|===
