= The Starknet Stack

== What is the Starknet Stack?

The Starknet Stack is a set of components required to create a Starknet instance. 

== Variations of the Starknet Stack

Alongside https://www.starknet.io/blog/staking-phase-1/[Starknet becoming the most decentralized L2], the Starknet Stack has also achieved organic decentralization, with multiple teams producing different versions of its core components. This decentralization makes the Starknet Stack more secure, transparent and customizable, with no single point of failure and plenty of room for innovation.

There are currently three teams offering their stacks for creating Starknet instances:

* StarkWare: The StarkWare stack is the Starknet Stack that has been used by StarkWare to successfully power Starknet for over 4 years, and is now available to builders as a hosted service by StarkWare.

* Madara: The Madara stack is a Starknet Stack focused on modularity and customizability, aiming to give builders the flexibility to tailor their Starknet instance according to their application's specific needs. To learn more about the Madara stack, visit https://www.dojoengine.org/[Madara's official website].

* Dojo: The Dojo stack is a Starknet Stack primarily – though not exclusively – used for onchain gaming, utilizing the Dojo toolchain to enable spinning up an L3 Katana-powered fork of Starknet for individual user sessions (e.g. dungen runs), proving the validity of their execution, and settling their state diffs back on Starknet. To learn more about the Dojo stack, visit https://www.dojoengine.org/[Dojo's official website].

== Additional resources

* https://www.starknet.io/blog/the-starknet-stacks-growth-spurt/["The Starknet Stack’s Growth Spurt" blog post]

