= The Starknet Stack

== What is the Starknet Stack?

The Starknet Stack is the technological stack that powers Starknet. At its core, the stack includes the following components:

. Starknet sequencer: An offchain service capable of producing Starknet blocks. Implementations include StarkWare's current closed-source and next-gen open-source sequencers, as well as Madara Alliance's Madara sequencer and Dojo's Katana sequencer.
. STARK prover: An offchain service capable of generating STARK proofs of the execution of Cairo programs. Implementations include StarkWare's current and next-gen open-source provers, Stone (STark ONE) and Stwo (Stark Two) provers, and closed-source proof aggregatation service, SHARP.
. STARK verifier: A set of smart contracts capable of verifying proofs generated by one of the aforementioned STARK provers. Implementations include StarkWare's Solidity verifier, already deployed on Ethereum, and Herodtus's Cairo verifier (named "Integrity"), already deployed on Starknet.
. Onchain Starknet core contract: A set of smart contracts that store the state of the network onchain. Implementations include StarkWare's Solidity core contract, already deployed on Ethereum, and Dojo's Cairo core contract (named "Piltover").