[id="starkgate_token_bridge"]
= The StarkGate bridge guide overview

[IMPORTANT]
====
This guide is a hands-on tutorial for using StarkGate. To learn about the different components of StarkGate, go to xref:architecture.adoc[_Architecture_].
====

https://starkgate.starknet.io[StarkGate^], developed by StarkWare, bridges ETH and ERC-20 tokens between Ethereum and Starknet. StarkGate supports many tokens, each by its own L1 and L2 contracts. For a comprehensive list of tokens that StarkGate supports, including their L1 and L2 addresses, see the JSON files shown in the following table:

[#table_StarkGate_token_addresses]
[%autowidth]
|===
| Network | JSON file

| Mainnet | link:https://starkgate.starknet.io/static/tokens.json[tokens.json]
| Sepolia | link:https://sepolia.starkgate.starknet.io/static/tokens.json[tokens.json]
|===

[TIP]
====
You can also check if a token is supported using the `getBridge` function.

For full details about this and all other functions and events, see the xref:function-reference.adoc[function and events reference].
====

This guide will walk you through the various procedures enabled by StarkGate, including:

* https://docs.starknet.io/starkgate/depositing/[Depositing funds]: Depositing ETH and ERC-20 tokens from your L1 wallet on Ethereum to your L2 wallet on Starknet, using a lock-and-mint mechanism.

* https://docs.starknet.io/starkgate/automated-actions-with-bridging/[Performing a Smart Deposit]:  Depositing ETH and ERC-20 tokens from your L1 wallet on Ethereum to your L2 wallet on Starknet, with an option to add subsequent actions (e.g., depositing funds and transferring those funds to another recipient within the same transaction).

* https://docs.starknet.io/starkgate/cancelling-a-deposit/[Canceling a deposit]: Canceling a previous deposit or deposit with message, if you don't see your deposited funds appear on L2 within a reasonable amount of time.

* https://docs.starknet.io/starkgate/withdrawing/[Withdrawaling funds]: Withdrawing ETH and ERC-20 tokens from your L2 wallet on Starknet to your L1 wallet on Ethereum, using a burn-and-unlock mechanism.

* https://research.lazer1.xyz/blog/making-sense-of-starknet-architecture-and-l1-l2-messaging/#enroll-a-token-bridge[Adding a token^]: Permissionlessly enrolling a token bridge on StarkGate.

[NOTE]
====
StarkGate enforces xref:architecture-and-concepts:network-architecture/messaging-mechanism.adoc#l1-l2-message-fees[fees] for all procedures to account for L1->L2 message costs.

Fees for depositing funds or enrolling a token bridge on StarkGate, can be estimated using the `estimateDepositFeeWei` or `estimateEnrollmentFeeWei` function.
====
