[id="starkgate_token_bridge"]
= The StarkGate bridge guide overview

[IMPORTANT]
====
This guide is a hands-on tutorial for using StarkGate. To learn about the different components of StarkGate, go to xref:architecture.adoc[_Architecture_].
====

https://starkgate.starknet.io[StarkGate^], developed by StarkWare, bridges ETH and ERC-20 tokens between Ethereum and Starknet. StarkGate supports many tokens, each by its own L1 and L2 contracts. For a comprehensive list of tokens that StarkGate supports, including their L1 and L2 addresses, see the JSON files shown in the following table:

[#table_StarkGate_token_addresses]
[%autowidth]
|===
| Network | JSON file

| Mainnet | link:https://starkgate.starknet.io/static/tokens.json[tokens.json]
| Sepolia | link:https://sepolia.starkgate.starknet.io/static/tokens.json[tokens.json]
|===

[NOTE]
====
You can also check if a token is currently supported using the xref:function-reference.adoc#getBridge[`getBridge` function].

To permissionlessly enroll more ERC-20 tokens, check out https://research.lazer1.xyz/blog/making-sense-of-starknet-architecture-and-l1-l2-messaging/#enroll-a-token-bridge[Lazer 1 Research's community guide] (use the xref:function-reference.adoc#estimateEnrollmentFeeWei[`estimateEnrollmentFeeWei` function] to estimate the fee for an enrollment).
====

This guide will walk you through the various procedures enabled by StarkGate, including:

* https://docs.starknet.io/starkgate/depositing/[Depositing funds]: Depositing ETH and ERC-20 tokens from your L1 wallet on Ethereum to your L2 wallet on Starknet, using a lock-and-mint mechanism.

* https://docs.starknet.io/starkgate/automated-actions-with-bridging/[Performing a Smart Deposit]:  Depositing ETH and ERC-20 tokens from your L1 wallet on Ethereum to your L2 wallet on Starknet, with an option to add subsequent actions (e.g., depositing funds and transferring those funds to another recipient within the same transaction).

* https://docs.starknet.io/starkgate/cancelling-a-deposit/[Canceling a deposit]: Canceling a previous deposit or deposit with message, if you don't see your deposited funds appear on L2 within a reasonable amount of time.

* https://docs.starknet.io/starkgate/withdrawing/[Withdrawaling funds]: Withdrawing ETH and ERC-20 tokens from your L2 wallet on Starknet to your L1 wallet on Ethereum, using a burn-and-unlock mechanism.

[NOTE]
====
StarkGate enforces a minimum fee for all transactions to account for the L1->L2 message costs.

For more information, see xref:architecture-and-concepts:network-architecture/messaging-mechanism.adoc#l1-l2-message-fees[L1->L2 message fees].

To estimate the fee for a `deposit` transaction, use the xref:function-reference.adoc#estimateDepositFeeWei[`estimateDepositFeeWei`] function.
====
