[id="starkgate_token_bridge"]
= StarkGate bridge overview

StarkGate, developed by StarkWare, bridges ETH and ERC-20 tokens between Ethereum and Starknet. Each supported token is associated with a pair of L1 and L2 bridge contracts that communicates via Starknet's messaging mechanism.

For some tokens, a pair of bridges consist of a single StarkGate instance on L1 and a single StarkGate instance on L2. For most tokens, the pair of bridges is a multi-bridge, which has an instance on L1 and an instance on L2, serving multiple tokens.

To use the StarkGate web app, go to https://starkgate.starknet.io.

[#starkgate_transactions]
== StarkGate transactions

The StarkGate bridge enables the following transactions:

* *Deposit*: Deposit ETH and ERC-20 tokens from your L1 wallet on Ethereum to your L2 wallet on Starknet. This procedure is done through a Lock and Mint mechanism. For more information go to the https://docs.starknet.io/starkgate/depositing/[Deposit] flow.

* *Deposit with a message*:  A deposit that has an option to add subsequent actions, such as, deposit funds and transfer those funds to another recipient within the same transaction. For more information go to the https://docs.starknet.io/starkgate/automated-actions-with-bridging/[Deposit with message] flow.

* *Withdrawal*: Withdraw ETH and ERC-20 tokens from your L2 wallet on Starknet to your L1 wallet on Ethereum. This procedure is done through a Burn and Unlock mechanism. For more information go to the https://docs.starknet.io/starkgate/withdrawing/[Withdrawal] flow.

* *Cancel deposit*: To ensure self-custody, StarkGate enables you to cancel a Deposit and a Deposit with message if, after depositing funds, you don’t see your funds appear on L2 within a reasonable amount of time. For more information go to the https://docs.starknet.io/starkgate/cancelling-a-deposit/[Cancel deposit] flow.

include::partial$snippet_backwards_compatibility_note.adoc[]


[#starkgate_addresses]
== StarkGate addresses

L1 and L2 addresses for StarkGate bridges and supported tokens are listed in the JSON files shown in the table xref:#table_StarkGate_token_addresses[].

[#table_StarkGate_token_addresses]
.StarkGate bridged tokens and their addresses
|===
| Network | StarkGate bridged tokens JSON file

| Mainnet | link:https://starkgate.starknet.io/static/tokens.json[tokens.json]
| Sepolia | link:https://sepolia.starkgate.starknet.io/static/tokens.json[tokens.json]
|===


[#starkgate_supported_tokens]
== Supported tokens in StarkGate

StarkGate supports many tokens, including ETH, WBTC, USDC, DAI, and many more.

For a comprehensive list of tokens that StarkGate supports, including their L1 and L2 addresses, see the JSON files shown in the table xref:#table_StarkGate_token_addresses[].

You can check if a token is currently supported with the L1 function `getBridge`.

You can permissionlessly add support for ERC-20 tokens via the multi-bridge using the `enrollTokenBridge` function. For more information go to https://docs.starknet.io/starkgate/adding-a-token/[Adding a token].

[NOTE]
====
Previously, StarkGate placed limitations for each supported token on the amount that could be deposited and the total value locked in the L1 bridge contract on Mainnet. These limits have been removed as of December 2023.
====

== Additional resources

* https://docs.starknet.io/architecture-and-concepts/network-architecture/messaging-mechanism/[L1-L2 messaging]
