[id="gas-and-transaction-fees"]
= Gas and transaction fees
:--auto-ids:
:stem: latexmath

In this section, we will review Starknet Alpha fee mechanism. If you want to skip the motivation and deep dive into the mechanism, you can skip directly to the final xref:overall_fee[formula].

This section focuses on fees paid by an account on L2. For information about messaging fees that are paid on L1, see xref:Network_Architecture/messaging-mechanism.adoc#l1-l2-message-fees[L1 → L2 message fees].

== Introduction

Users can specify the maximum fee that they are willing to pay for a transaction.

include::partial$snippet_v3_max_price_sidebar.adoc[]

For transaction versions before v3 transactions, the `max_fee` field specifies the maximum fee.

The only limitation on the sequencer, which is enforced by the Starknet OS, is that the actual fee charged is bounded by `max_fee`, but for now, StarkWare's sequencer only charges the fee required to cover the proof cost, which is potentially less than the maximum fee.

Presently, the sequencer only takes into account L1 costs involving proof submission. There are two components affecting the L1 footprint of a transaction:

* xref:computation[Computational complexity]: the heavier the transaction, the larger its portion in the proof verification cost.
* xref:_on_chain_data[Onchain data]: L1 calldata cost originating from xref:Network_Architecture/on-chain-data.adoc[data availability] and L2→L1 messages.

== Fee units

The fee is denominated in ETH (this might change in future versions). Each transaction is associated with an estimate of the amount of gas used. Combining this estimate with the price of gas yields the estimated fee.

== How much fee is charged? High-level overview

[id="computation"]
=== Computation

Let's analyze the correct metric for measuring transaction complexity. For simplicity, we will ignore Cairo's builtins for the sake of the explanation, and later see how to address them.

==== Without builtins

Recall that a Cairo program execution yields an execution trace. When proving a Starknet block, we aggregate all the transactions appearing in that block to the execution trace.

Starknet's prover generates proofs for execution traces, up to some maximal length stem:[$L$] (Derived from the specs of the proving machine and the desired proof latency).

Tracking the execution trace length associated with each transaction is simple.
Each assertion over field elements (such as verifying addition/multiplication over the field) requires the same, constant number of trace cells (this is where our "`no-builtins`" assumption kicks in! Obviously Pedersen occupies more trace cells than addition). Therefore, in a world without builtins, the fee of the transaction stem:[$tx$] is correlated with stem:[$\text{TraceCells}[tx\]/L$].

==== Adding builtins

The Cairo execution trace is separated -- and each builtin has its own slot. We have to mind this slot allocation when determining the fee.

Let's go over a concrete example first. For example, imagine the following trace that the prover will occupy:

[%autowidth]
|===
| (up to) 500,000,000 Cairo Steps | (up to) 20,000,000 Pedersen hashes | (up to) 4,000,000 signature verifications | (up to) 10,000,000 range checks

|===

The proof is closed and sent to L1 when any of these components becomes full.

Suppose, for example, that a transaction uses 10,000 Cairo steps and 500 Pedersen hashes. We can squeeze at most 40,000 such transactions into our hypothetical trace (20,000,000/500). Therefore, its gas price will be correlated with 1/40,000 of the cost of submitting proof.

Notice we completely ignored the number of Cairo steps in this transaction performance estimation, as it is not the limiting factor (since 500,000,000/10,000 > 20,000,000/500). With this example in mind, we can now formulate the exact fee associated with L2 computation.

[IMPORTANT]
====
The allocation of resources among built-in operations must be predetermined; it's not possible to decide post-execution to include only 20,000,001 Pedersen hashes without additional components.

This safeguards fairness and prevents manipulation, ensuring integrity in proof generation and fee determination.
====

==== General case

For each transaction, the sequencer calculates a vector `CairoResourceUsage` holding:

* Number of Cairo steps
* Number of applications of each Cairo builtin (e.g., five range checks and two Pedersen hashes)

The sequencer crosses this information with the `CairoResourceFeeWeights` vector. For each resource type (step or a specific builtin application), `CairoResourceFeeWeights` has an entry that specifies the relative gas cost of that component in the proof.

Going back to the above example, if the cost of submitting a proof with 20,000,000 Pedersen hashes is roughly 5m gas, then the weight of the Pedersen builtin is 0.25 gas per application (5,000,000/20,000,000). The sequencer has a pre-defined weights vector, in accordance with the proof parameters.

The sequencer will charge only according to the limiting factor! Therefore the fee is correlated with:

[stem]
++++
\max_k[\text{CairoResourceUsage}_k \cdot \text{CairoResourceFeeWeights}_k]
++++

Where stem:[$k$] here enumerates the Cairo resource components, i.e. the number of steps and builtins used.

The weights are listed in the table xref:#gas_cost_per_cairo_step_or_builtin_step[].

#Review#
[#gas_cost_per_cairo_step_or_builtin_step]
.Amount of gas used per Cairo step or per each time a Cairo builtin is applied
[%autowidth,cols="2,2",options="header",stripes=even]
|===
| Step | Gas cost

| Cairo step | 0.005 gas/step
| Pedersen | 0.16 gas/application
| Poseidon | 0.16 gas/application
| Range check | 0.08 gas/application
| ECDSA | 10.24 gas/application
| Keccak | 10.24 gas/application
| Bitwise | 0.32 gas/application
| EC_OP | 5.12 gas/application
|===


[id="_on_chain_data"]
=== Onchain data

The onchain data associated with a transaction is composed of three parts

* Storage updates
* L2→L1 messages
* Deployed contracts

==== Storage updates

Whenever a transaction updates a key #Does _updates a key_ mean that the address changes?# at the storage #_at the storage_ I don't understand what _at_ means here. Should it be _updates the storage address of some contract_?# of some contract, the following data elements reach L1 within a word:

* contract address
* number of updated keys #In Data availability, this is referred to as number of storage updates, not number of updated keys. Why the discrepancy?# in that contract and the new nonce
* key to update
* new value

For more information on the construction of this word, see xref:architecture_and_concepts:Network_Architecture/on-chain-data.adoc#v0.11.0_format[Data availability]

[NOTE]
====
Only the most recent value reaches L1. So the transaction's fee only depends on the number of _unique_ storage updates. If the same storage cell is updated multiple times within the transaction, the fee remains that of a single update.
====

#START REVIEW#
Consequently, the following formula describes the storage update fee for a transaction, where:

* stem:[$n$] is the number of unique contracts
* stem:[$m$] is the number of unique keys
* stem:[$\text{calldata_cost}$] is the calldata cost, in gas, per 32-byte word.
* stem:[$200$] The cost of the onchain storage update, in gas. This value accounts for bytes whose value is 0. Assumes three non-zero bytes for the nonce, two non-zero bytes for storage updates, and one non-zero byte for the deployment flag.
// * stem:[$c_w'$] accounts for bytes whose value is 0. Assumes three non-zero bytes for the nonce, two non-zero bytes for storage updates, and one non-zero byte for the deployment flag.
* stem:[$\text{account_balance_update_cost}$] is a constant whose value is 272, which assumes a balance of at most 12 non-zero bytes, which is 1.2 billion ETH or STRK, where the cost of a non-zero byte is 16 gas, and the cost of a byte of zeros is 4 gas. 12 * 16 + 20* 4 = 272

#Why did you choose c~w~ and c'~w~? What does `c` stand for? What does `w` stand for?#


// [stem]
// ++++
// \underbrace{\text{gas_price}(c_w \cdot n + c_w' \cdot n)}_{\text{contract addresses +  new nonce and number of storage updates
// }} \\
//
// + \\
//
// \underbrace{\text{gas_price} \cdot c_w(2(m-1)+\text{account_balance_update_cost})}_{\text{storage updates}}
// ++++

[stem]
++++
\underbrace{\textit{gas_price}(\text{calldata_cost} \cdot n + 200 \cdot n)}_{\text{contract addresses +  new nonce and number of storage updates
}} \\

+ \\

\underbrace{\textit{gas_price} \cdot \textit{calldata_cost}(2(m-1)+\text{account_balance_update_cost})}_{\text{storage updates}}
++++

#Does `gas_price` mean _the cost of gas in ETH/wei/gwei_, or does it mean the _amount of gas_?#



#What actually does c'~w~ stand for, if c~w~ is calldata?#

[NOTE]
====
Improvements to the above pessimistic estimation might be gradually implemented in future versions of Starknet.

For example, if different transactions within the same block update the same storage cell, there is no need to charge for both transactions, because only the last value reaches L1. In the future, Starknet might include a refund mechanism for such cases.
====


==== L2→L1 messages

When a transaction that raises the `send_message_to_l1` syscall is included in a state update, the following data reaches L1:

* L2 sender address
* L1 destination address
* Payload size
* Payload (list of field elements)

Consequently, the fee associated with a single L2→L1 message is:

[stem]
++++
\text{gas_price}\cdot c_w\cdot(3+\text{payload_size})
++++

where stem:[$c_w$] is the calldata cost, in gas, per 32-byte word.

==== Deployed contracts

When a transaction that raises the `deploy` syscall is included in a state update, the following data reaches L1:

* contract address
* number of storage updates and the new nonce
* class hash

Consequently, the fee associated with a single deployment is:

[stem]
++++
\text{gas_price}\cdot 3 c_w
++++

where stem:[$c_w$] is the calldata cost, in gas, per 32-byte word.

For more information on data saved on L1, see xref:architecture_and_concepts:Network_Architecture/on-chain-data.adoc[Data availability].

== Overall fee

The fee for a transaction with:

* Cairo usage represented by the vector stem:[$v$] (the entries of stem:[$v$] correspond to the number of steps and number of applications per builtin)
* stem:[$n$] unique contract updates
* stem:[$m$] unique key updates
* stem:[$t$] messages with payload sizes stem:[$q_1,...,q_t$]
* stem:[$\ell$] contract deployments

is given by:

[stem]
++++
F = 0.9 \cdot \text{gas_price}\cdot\left(\max_k v_k w_k + c_w\left(2(n+m) + 3t + \sum\limits_{i=1}^t q_i +3\ell\right)\right)
++++

where:

* stem:[$0.9$] is a 10% cost reduction
* stem:[$w$] is the xref:general_case[`CairoResourceFeeWeights`] vector discussed above
* stem:[$c_w$] is the calldata cost, in gas, per 32-byte word

== When is the fee charged?

The fee is charged atomically with the transaction execution on L2. The Starknet OS injects a transfer of the fee-related ERC-20, with an amount equal to the fee paid, the sender equal to the transaction submitter, and the sequencer as a receiver.

