[id="gas-and-transaction-fees"]
= Gas and transaction fees (Starting in Starknet 0.13.0)
:--auto-ids:

[IMPORTANT]
====
For information on v0.12.3 and earlier, see xref:architecture_and_concepts:Network_Architecture/fee-mechanism-pre-v0.13.0.adoc[].
====

This section describes fees that are paid on L2. For information about messaging fees that are paid on L1, see xref:Network_Architecture/messaging-mechanism.adoc#l1-l2-message-fees[L1 → L2 message fees].

[#overall_fee]
== Overall transaction fee

This section shows the formula for determining a transaction's fee. The following sections describe how this formula was derived.

The following formula describes the overall fee for a transaction:

// OLD
// [stem]
// ++++
// F = \text{gas_price}\cdot\left(\max_k v_k w_k + 0.9\cdot\text{calldata_cost}\cdot\left(2(n+m) + 3t + \sum\limits_{i=1}^t q_i +3\ell\right)\right)
// ++++

[stem]
++++
F = \text{gas_price}\cdot\left(\max_k v_k w_k + 0.9\cdot\text{calldata_cost}\cdot\left((n+2m-1) + 3t + \sum\limits_{i=1}^t q_i +3\ell\right)+ t\cdot\text{storage_write_cost} + n \cdot 200 + 272\right)
++++

where:

* stem:[$v$] is a vector that represents resource usage, where each of its entries, stem:[$v_k$], correspond to different resource types: Cairo steps and number of applications of each builtin.
+
For more information see xref:#calculation_of_computation_costs[Calculation of computation costs].
* stem:[$n$] is xref:#storage_updates[the number of unique contracts updated].
* stem:[$m$] is the number of values updated, not counting multiple updates for the same key.
* stem:[$t$] is the number of L2->L1 messages sent, where the corresponding payload sizes are denoted by stem:[$q_1,...,q_t$].
* stem:[$\ell$] is the number of contract deployments.
* stem:[$0.9$] is a 10% cost reduction that considers that the sequencer does not incur additional costs for repeated updates to the same storage slot within a single block.
* stem:[$w$] is the xref:#calculation_of_computation_costs[`CairoResourceFeeWeights`] vector.
* stem:[$\text{calldata_cost}$] is 612 gas per 32-byte word (~100 gas is charged for on-chain hashing the happens for every sent word).
* stem:[$\text{storage_write_cost}$] is the 20,000 gas, the cost associated with allocating a new storage cell on Ethereum.
* stem:[200] and stem:[272] are gas costs associated with storage updates. For more information, see xref:#storage_updates[].

== When is the fee charged?

The fee is charged atomically with the transaction execution on L2. The Starknet OS injects a transfer of the fee-related ERC-20, with an amount equal to the fee paid, the sender equal to the transaction submitter, and the sequencer as a receiver.

[#fee_limitations]
== Fee limitations

Users can specify the maximum fee that they are willing to pay for a transaction.

include::partial$snippet_v3_max_price_sidebar.adoc[]

For transaction versions before v3 transactions, the `max_fee` field specifies the maximum fee.

The only limitation on the sequencer, which is enforced by the Starknet OS, is that the actual fee charged is bounded by `max_fee`, but for now, StarkWare's sequencer only charges the fee required to cover the proof cost, which is potentially less than the maximum fee.

Currently, the sequencer only takes into account L1 costs involving proof submission. The following two components affect the L1 footprint of a transaction:

* xref:#computation_without_builtins[Computational complexity]: A transaction's portion of the proof verification cost is proportional to its complexity.
* xref:#onchain_data_components[Onchain data]: L1 calldata cost originating from xref:Network_Architecture/on-chain-data.adoc[data availability] and L2→L1 messages.

== Fee units

Each transaction is associated with an estimate of the amount of gas used. Combining this estimate with the price of gas yields the estimated fee.

For transactions prior to v3, the fee is denominated in WEI. For transactions v3 and later, the fee is denominated in STRK.

[#fee_calculation]
== Fee calculation

[#computation_without_builtins]
=== Computation without builtins

Let's analyze the correct metric for measuring transaction complexity. For simplicity, we will ignore Cairo's builtins, and address them later.

A Cairo program execution yields an execution trace. When proving a Starknet block, we aggregate all the transactions appearing in that block to the execution trace.

Starknet's prover generates proofs for execution traces, up to some maximal length stem:[$L$], derived from the specs of the proving machine and the desired proof latency.

Tracking the execution trace length associated with each transaction is simple.
Each assertion over field elements, such as verifying addition/multiplication over the field, requires the same, constant number of trace cells, which is where our "no-builtins" assumption kicks in: Pedersen occupies more trace cells than addition. Therefore, in a world without builtins, the fee of the transaction stem:[$tx$] is correlated with stem:[$\text{TraceCells}[tx\]/L$].

[#computation_with_builtins]
=== Computation with builtins

In the Cairo execution trace each builtin has its own slot, which is important to consider when determining the fee.

For example, consider that the prover can process a trace with the following limits:

[%autowidth]
|===
| up to 500,000,000 Cairo Steps | up to 20,000,000 Pedersen hashes | up to 4,000,000 signature verifications | up to 10,000,000 range checks

|===

The proof is closed and sent to L1 when any of these slots is filled.

Suppose that a transaction uses 10,000 Cairo steps and 500 Pedersen hashes. At most 40,000 such transactions can fit into the hypothetical trace (20,000,000/500). Therefore, its gas price correlates with 1/40,000 of the cost of submitting proof.

Notice that this estimate ignores the number of Cairo steps, as it is not the limiting factor, since 500,000,000/10,000 > 20,000,000/500.

With this example in mind, it is possible to formulate the exact fee associated with L2 computation.

[IMPORTANT]
====
The allocation of resources among builtin operations must be predetermined; it is not possible to decide, post-execution, to include only 20,000,001 Pedersen hashes without additional components.

This safeguards fairness and prevents manipulation, ensuring integrity in proof generation and fee determination.
====

[#calculation_of_computation_costs]
=== Calculation of computation costs

For each transaction, the sequencer calculates a vector, `CairoResourceUsage`, that contains the following:

* The number of Cairo steps.
* The number of applications of each Cairo builtin. For example, five range checks and two Pedersen hashes.

The sequencer crosses this information with the `CairoResourceFeeWeights` vector. For each resource type, either a Cairo step or a specific builtin application, `CairoResourceFeeWeights` has an entry that specifies the relative gas cost of that component in the proof.

Going back to the above example, if the cost of submitting a proof with 20,000,000 Pedersen hashes is roughly 5m gas, then the weight of the Pedersen builtin is 0.25 gas per application (5,000,000/20,000,000). The sequencer has a predefined weights vector, in accordance with the proof parameters.

The sequencer charges only according to the limiting factor. Therefore the fee is correlated with:

[stem]
++++
\max_k[\text{CairoResourceUsage}_k \cdot \text{CairoResourceFeeWeights}_k]
++++

where stem:[$k$] enumerates the Cairo resource components, that is the number of Cairo steps and builtins used.

The weights are listed in the table xref:#gas_cost_per_cairo_step_or_builtin_step[].

[#gas_cost_per_cairo_step_or_builtin_step]
.Amount of gas used per Cairo step or per each time a Cairo builtin is applied
[width=80%,cols="1,2",options="header",stripes=even]
|===
| Step or builtin | Gas cost

| Cairo step | 0.005 gas/step
| Pedersen | 0.16 gas/application
| Poseidon | 0.16 gas/application
| Range check | 0.08 gas/application
| ECDSA | 10.24 gas/application
| Keccak | 10.24 gas/application
| Bitwise | 0.32 gas/application
| EC_OP | 5.12 gas/application
|===


[id="onchain_data_components"]
=== Onchain data components

The onchain data associated with a transaction is composed of three parts

* Storage updates
* L2→L1 messages
* Deployed contracts

[#storage_updates]
=== Onchain data: Storage updates

Whenever a transaction updates some value in the storage of some contract, the following data is sent to L1:

* two 32-byte words per contract
* two 32-byte words for every updated storage value

For information on the exact data and its construction, see xref:architecture_and_concepts:Network_Architecture/on-chain-data.adoc#v0.11.0_format[Data availability].

[NOTE]
====
Only the most recent value reaches L1. So the transaction's fee only depends on the number of _unique_ storage updates. If the same storage cell is updated multiple times within the transaction, the fee remains that of a single update.
====

The following formula describes the storage update fee for a transaction:

[stem]
++++
\underbrace{\textit{gas_price}(\text{calldata_cost} \cdot n + 200 \cdot n)}_{\text{contract addresses +  new nonce and number of storage updates
}} \\

+ \\

\underbrace{\textit{gas_price} \cdot (\text{calldata_cost}(2m-1)+272)}_{\text{storage updates}}
++++

where:

* stem:[$n$] is the number of unique contracts updated.
* stem:[$m$] is the number of unique values updated. Be aware that the account balance is always updated, because the account needs to pay a fee. A discount is applied to the account balance update to consider that the value of the account balance most likely does not use the full 32 bytes allotted to it.
* stem:[$\text{calldata_cost}$] is 512 gas per 32-byte word.
* stem:[$200$] is the cost of the onchain storage update's meta information and nonce, in gas. This value accounts for the fact that out of 32 bytes in the meta information, only the following six bytes are non-zero:
+
--
** three bytes for the nonce
** two bytes for storage updates
** one byte for the class information flag
--
+
The cost of a non-zero byte is 16 gas, and the cost of a byte of zeros is 4 gas. So 6 non-zero bytes @ 16 gas per byte + 26 bytes of zeros @ 4 gas per byte results in 200 gas.

* stem:[$\text{272}$] is the cost of updating the balance, in gas. This value assumes a balance of at most 12 non-zero bytes, which is enough for 1.2 billion ETH or STRK.
+
The cost of a non-zero byte is 16 gas, and the cost of a byte of zeros is 4 gas. So 12 non-zero bytes @ 16 gas per byte + 20 bytes of zeros @ 4 gas per byte results in 272 gas.



[NOTE]
====
Improvements to the above pessimistic estimation might be gradually implemented in future versions of Starknet.

For example, if different transactions within the same block update the same storage cell, there is no need to charge for both transactions, because only the last value reaches L1. In the future, Starknet might include a refund mechanism for such cases.
====

[#l_2→l_1_messages]
=== Onchain data: L2->L1 messages

When a transaction that raises the `send_message_to_l1` syscall is included in a state update, the following data reaches L1:

* L2 sender address
* L1 destination address
* Payload size
* Payload (list of field elements)

Consequently, the fee associated with a single L2→L1 message is:

[stem]
++++
\textit{gas_price}\cdot \text{calldata_cost}\cdot(3+\text{payload_size})
++++

where stem:[$\text{calldata_cost}$] is 512 gas per 32-byte word.

[#deployed_contracts]
=== Onchain data: Deployed contracts

When a transaction that raises the `deploy` syscall is included in a state update, the following data reaches L1:

* contract address
* number of storage updates and the new nonce
* class hash

The following formula describes the fee for a single deployment:

[stem]
++++
\textit{gas_price}\cdot 3 \cdot \text{calldata_cost}
++++

where stem:[$\text{calldata_cost}$] is 512 gas per 32-byte word.

For more information on data saved on L1, see xref:architecture_and_concepts:Network_Architecture/on-chain-data.adoc[Data availability].


