[id="messaging_reference"]
= Messaging reference
:description: Comprehensive function and event reference for Starknet messaging.

The Starknet messaging smart contracts include functions and events that you use to implement various flows in a dApp.

For information on the messaging mechanism, see xref:architecture_and_concepts:Network_Architecture/messaging-mechanism.adoc[Messaging mechanism].

The L1 functions, where available, are defined in the following smart contract:

[cols=",,",]
|===
|Contract |Description |Functions

|https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol[`StarknetMessaging.sol`] |
The StarknetMessaging contract that implementing messaging functions.

Interfaces are available through https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessaging.sol[`IStarknetMessaging.sol`]. a|
* xref:#cancelL1ToL2Message[`cancelL1ToL2Message`]
* xref:#consumeMessageFromL2[`consumeMessageFromL2`]
* xref:#getMaxL1MsgFee[`getMaxL1MsgFee`]
* xref:#l1ToL2Messages[`l1ToL2Messages`]
* xref:#sendMessageToL2[`sendMessageToL2`]
* xref:#startL1ToL2MessageCancellation[`startL1ToL2MessageCancellation`]

|===

The L1 events, where available, are defined in the following smart contract:

[cols=",,",]
|===
|Contract |Description |Events

|https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol[`IStarknetMessagingEvents.sol`] |
The contract that defines messaging events. a|
* xref:#ConsumedMessageToL1[`ConsumedMessageToL1`]
* xref:#ConsumedMessageToL2[`ConsumedMessageToL2`]
* xref:#LogMessageToL1[`LogMessageToL1`]
* xref:#LogMessageToL2[`LogMessageToL2`]
* xref:#MessageToL2Canceled[`MessageToL2Canceled`]
* xref:#MessageToL2CancellationStarted[`MessageToL2CancellationStarted`]

|===

'''

== L1 function reference

Functions are listed in alphabetical order.

'''

[#cancelL1ToL2Message]
=== `cancelL1ToL2Message`

[discrete]
==== Description

Cancels an L1 to L2 message. This function should be called at least messageCancellationDelay() seconds after the call to startL1ToL2MessageCancellation().

A message may only be canceled by its sender.

If the message is missing, the call will revert.

Note that the message fee is not refunded.

[discrete]
==== State Mutability

None.

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`uint256 _toAddress_`:: The address of the L2 contract.
`uint256 _selector_`:: The selector of the message.
`uint256[] calldata _payload_`:: The payload of the message.
`uint256 _nonce_`:: The nonce of the message.

[discrete]
==== Returns

[horizontal,labelwidth="30",role=stripes-odd]
`bytes32 _msgHash_`:: The hash of the canceled message.

[discrete]
==== Function definition

Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol[`StarknetMessaging.sol`]

* Function: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol#L161[`cancelL1ToL2Message`]

'''

[#consumeMessageFromL2]
=== `consumeMessageFromL2`

[discrete]
==== Description

Consumes a message that was sent from an L2 contract.

Returns the hash of the message.

[discrete]
==== State Mutability

None.

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`uint256 _fromAddress_`:: The address of the L2 contract.
`uint256[] calldata _payload_`:: The payload of the message.

[discrete]
==== Returns

[horizontal,labelwidth="30",role=stripes-odd]
`bytes32 _msgHash_`:: The hash of the consumed message.

[discrete]
==== Function definition

Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol[`StarknetMessaging.sol`]

* Function: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol#L132[`consumeMessageFromL2`]

'''

[#getMaxL1MsgFee]
=== `getMaxL1MsgFee`

[discrete]
==== Description

Returns the maximum fee, in Wei, that Starknet accepts per single message.

[discrete]
==== State Mutability

`pure`

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="30",role=stripes-odd]
`uint256 _maxFee_`:: The maximum fee, in Wei, that Starknet accepts per single message.

[discrete]
==== Function definition

Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol[`StarknetMessaging.sol`]

* Function: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol#L31[`getMaxL1MsgFee`]

'''

[#l1ToL2Messages]
=== `l1ToL2Messages`

[discrete]
==== Description

[horizontal,labelwidth="30",role=stripes-odd]
`msg_fee + 1`:: A pending message is associated with the given message hash.
`0`:: No pending message is associated with the given message hash.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`bytes32 _msgHash_`:: The hash of the message.

[discrete]
==== Returns

[horizontal,labelwidth="30",role=stripes-odd]
`uint256 _result_`:: `msg_fee + 1` if there is a pending message, otherwise 0.

[discrete]
==== Function definition

Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol[`StarknetMessaging.sol`]

* Function: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol#L39[`l1ToL2Messages`]

'''

[#sendMessageToL2]
=== `sendMessageToL2`

[discrete]
==== Description

Sends a message to an L2 contract.

This function is payable, the paid amount is the message fee.

Returns the hash of the message and the nonce of the message.

[discrete]
==== State Mutability

`payable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`uint256 _toAddress_`:: The address of the L2 contract.
`uint256 _selector_`:: The selector of the message.
`uint256[] calldata _payload_`:: The payload of the message.

[discrete]
==== Returns

[horizontal,labelwidth="30",role=stripes-odd]
`bytes32 _msgHash_`:: The hash of the message.
`uint256 _nonce_`:: The nonce of the message.

[discrete]
==== Function definition

Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol[`StarknetMessaging.sol`]

* Function: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol#L110[`sendMessageToL2`]

'''

[#startL1ToL2MessageCancellation]
=== `startL1ToL2MessageCancellation`

[discrete]
==== Description

Starts the cancellation of an L1 to L2 message.

A message can be canceled messageCancellationDelay() seconds after this function is called.

Note: This function may only be called for a message that is currently pending, and the caller must be the sender of that message.

[discrete]
==== State Mutability

None.

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`uint256 _toAddress_`:: The address of the L2 contract.
`uint256 _selector_`:: The selector of the message.
`uint256[] calldata _payload_`:: The payload of the message.
`uint256 _nonce_`:: The nonce of the message.

[discrete]
==== Returns

[horizontal,labelwidth="30",role=stripes-odd]
`bytes32 _msgHash_`:: The hash of the cancellation message.

[discrete]
==== Function definition

Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol[`StarknetMessaging.sol`]

* Function: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol#L147[`startL1ToL2MessageCancellation`]

== L1 event reference

Events are listed in alphabetical order.

* Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol[`IStarknetMessagingEvents`]

'''

[#ConsumedMessageToL1]
=== `ConsumedMessageToL1`

[discrete]
==== Description

This event is emitted when a message from L2 to L1 is consumed.

[discrete]
==== Event attributes

[horizontal,role=stripes-odd]
`uint256 indexed _fromAddress_`:: The address of the sender on L2.
`address indexed _toAddress_`:: The address of the receiver on L1.
`uint256[] _payload_`:: The payload of the consumed message.

[discrete]
==== Event definition

* Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol[`IStarknetMessagingEvents`]

* Event: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol#L19[`ConsumedMessageToL1`]

'''

[#ConsumedMessageToL2]
=== `ConsumedMessageToL2`

[discrete]
==== Description

This event is emitted when a message from L1 to L2 is consumed.

[discrete]
==== Event attributes

[horizontal,role=stripes-odd]
`address indexed _fromAddress_`:: The address of the sender on L1.
`uint256 indexed _toAddress_`:: The address of the receiver on L2.
`uint256 indexed _selector_`:: The selector of the consumed message.
`uint256[] _payload_`:: The payload of the consumed message.
`uint256 _nonce_`:: The nonce of the consumed message.

[discrete]
==== Event definition

* Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol[`IStarknetMessagingEvents`]

* Event: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol#L26[`ConsumedMessageToL2`]

'''

[#LogMessageToL1]
=== `LogMessageToL1`

[discrete]
==== Description

This event is emitted when a message is sent from L2 to L1.

[discrete]
==== Event attributes

[horizontal,role=stripes-odd]
`uint256 indexed _fromAddress_`:: The address of the sender on L2.
`address indexed _toAddress_`:: The address of the receiver on L1.
`uint256[] _payload_`:: The payload of the message.

[discrete]
==== Event definition

* Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol[`IStarknetMessagingEvents`]

* Event: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol#L6[`LogMessageToL1`]

'''

[#LogMessageToL2]
=== `LogMessageToL2`

[discrete]
==== Description

This event is emitted when a message is sent from L1 to L2.

[discrete]
==== Event attributes

[horizontal,role=stripes-odd]
`address indexed _fromAddress_`:: The address of the sender on L1.
`uint256 indexed _toAddress_`:: The address of the receiver on L2.
`uint256 indexed _selector_`:: The selector of the message.
`uint256[] _payload_`:: The payload of the message.
`uint256 _nonce_`:: The nonce of the message.
`uint256 _fee_`:: The fee associated with the message.

[discrete]
==== Event definition

* Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol[`IStarknetMessagingEvents`]

* Event: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol#L9[`LogMessageToL2`]

'''

[#MessageToL2Canceled]
=== `MessageToL2Canceled`

[discrete]
==== Description

This event is emitted when an L1 to L2 message is canceled.

[discrete]
==== Event attributes

[horizontal,role=stripes-odd]
`address indexed _fromAddress_`:: The address of the sender on L1.
`uint256 indexed _toAddress_`:: The address of the receiver on L2.
`uint256 indexed _selector_`:: The selector of the canceled message.
`uint256[] _payload_`:: The payload of the canceled message.
`uint256 _nonce_`:: The nonce of the canceled message.

[discrete]
==== Event definition

* Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol[`IStarknetMessagingEvents`]

* Event: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol#L44[`MessageToL2Canceled`]

'''

[#MessageToL2CancellationStarted]
=== `MessageToL2CancellationStarted`

[discrete]
==== Description

This event is emitted when the cancellation of an L1 to L2 message is started.

[discrete]
==== Event attributes

[horizontal,role=stripes-odd]
`address indexed _fromAddress_`:: The address of the sender on L1.
`uint256 indexed _toAddress_`:: The address of the receiver on L2.
`uint256 indexed _selector_`:: The selector of the message to be canceled.
`uint256[] _payload_`:: The payload of the message to be canceled.
`uint256 _nonce_`:: The nonce of the message to be canceled.

[discrete]
==== Event definition

* Contract: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol[`IStarknetMessagingEvents`]

* Event: link:https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol#L35[`MessageToL2CancellationStarted`]

