[id="transaction_structure"]
= Transaction types

Starknet supports the following types of transactions:

* _invoke_ transaction
* _declare_ transaction
* _deploy_account_ transaction

This topic describes the available fields for these transaction types and how each transaction hash is calculated.

[id="transaction_versioning"]
== Transaction versioning

Starknet supports the transaction versions described here.

When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.

[IMPORTANT]
====
Do not submit a transaction that uses an unsupported transaction type, because it cannot be included in a proof, and so cannot become part of a Starknet block.
====

[id="deploy_transaction"]

=== Deploy transaction hash calculation

In order to calculate the transaction hash, we first need to obtain the deployed contract address. The Deploy transaction's hash is calculated as follows:

[source,cairo]
----
deploy_tx_hash = ℎ(
    "deploy",
    version,
    contract_address,
    sn_keccak("constructor"),
    ℎ(constructor_calldata),
    0,
    chain_id
)
----

Where:

* The placeholder zero is used to align the hash computation for the different types of transactions.
* “deploy” and “constructor” are constant strings encoded in ASCII.
* stem:[$h$] is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash and
stem:[$sn\_keccak$] is xref:../Cryptography/hash-functions.adoc#starknet_keccak[Starknet Keccak].
* `chain_id` is a constant value that specifies the network to which this transaction is sent. See xref:#chain-id[Chain-Id].
* `contract_address` is calculated as described xref:architecture_and_concepts:Smart_Contracts/contract-address.adoc[here].

[id=invoke_transaction]
== Invoke transaction

The invoke transaction is the main transaction type used to invoke contract functions in Starknet.

[IMPORTANT]
====
Invoke transaction version 0 is deprecated and will be removed in a future release of Starknet.
====

=== Invoke v1

.Transaction fields

[%autowidth.stretch]
|===
| Name | Type | Description

| `sender_address` | `FieldElement` | The address of the sender of this transaction.
| `calldata` | `List<FieldElement>` | The arguments that are passed to the `validate` and `execute` functions.
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. The value is 1. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.
|===

=== v1 hash calculation

The `invoke` v1 transaction hash is calculated as a hash over the given transaction elements,
specifically:

[source,cairo]
----
invoke_v1_tx_hash = ℎ(
    "invoke",
    version,
    sender_address,
    0,
    ℎ(calldata),
    max_fee,
    chain_id,
    nonce
)
----

Where:

* stem:[\text{invoke}] is a constant prefix string, encoded in ASCII.
* The placeholder zero is used to align the hash computation for the different types of transactions.
* stem:[\text{chain_id}] is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* stem:[$h$] is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash


=== Deprecated features
==== v0 hash calculation


The hash of a v0 invoke transaction is computed as follows:

[source,cairo]
----
invoke_v0_tx_hash = ℎ(
    "invoke",
    version,
    contract_address,
    entry_point_selector,
    ℎ(calldata),
    max_fee,
    chain_id
)
----

Where:

* stem:[\text{invoke}] is a constant prefix string, encoded in (ASCII).
* stem:[\text{chain_id}] is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* stem:[$h$] is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash

[id="declare-transaction"]
== Declare transaction

The declare transaction is used to introduce new classes into the state of Starknet, enabling other contracts to deploy instances of those classes or use them in a library call. For more information, see xref:architecture_and_concepts:Smart_Contracts/contract-classes.adoc[contract classes].

[IMPORTANT]
====
New Cairo 1.0 classes can only be declared via the declare v2 transaction.

v1 used to declare Cairo 0 classes are deprecated and will be removed in a future Starknet version.

v0 is no longer supported.
====

[id="declare_v2"]
=== Declare v2

// todo add flow for invoke /deploy transaction flows examples, from upcoming versions / account
// abstraction./ Link to flow in AA section.

.Transaction fields

[%autowidth.stretch]
|===
| Name | Type | Description

| `chain_id` | `FieldElement`  | The id of the chain to which the transaction is sent.
| `contract_class` | `ContractClass` | The (Cairo 1.0) xref:Smart_Contracts/class-hash.adoc#definition_of_a_cairo_1_class[class].
| `compiled_class_hash` | `FieldElement` | The hash of the compiled class (see xref:documentation:starknet_versions:upcoming_versions.adoc#what_to_expect[here] for more information)
| `sender_address` | `FieldElement` | The address of the account initiating the transaction.
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction.
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. The value is 2. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases. Transaction version 0 is deprecated and will be removed in a future version of Starknet.
|===

=== v2 hash calculation

The hash of a v2 declare transaction is computed as follows:

[source,cairo]
----
declare_v2_tx_hash = ℎ(
    "declare",
    version,
    sender_address,
    0,
    h(class_hash),
    max_fee,
    chain_id,
    nonce,
    compiled_class_hash
)
----

Where:

* stem:[$h$] is the xref:Cryptography/hash-functions.adoc#poseidon_hash[Poseidon hash function]
* `class_hash` is the hash of the contract class. See xref:Smart_Contracts/class-hash.adoc#computing_the_cairo_1_class_hash[Class Hash]
for details about how the
hash is computed
* `compiled_class_hash` is the hash of the xref:starknet_versions:upcoming_versions.adoc#what_to_expect[compiled class]
generated by the Sierra->Casm compiler which is currently used in Starknet

=== Deprecated features

[IMPORTANT]
====
These old versions used to declare Cairo 0 classes are deprecated and will be removed in a future Starknet version.
====

==== Declare v1

.Transaction fields

[%autowidth.stretch]
|===
| Name | Type | Description

| `contract_class` | `ContractClass` | The class object.
| `sender_address` | `FieldElement` | The address of the account initiating the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction.
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. Possible values are 1 or 0. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases. Transaction version 0 is deprecated and will be removed in a future version of Starknet.
|===


==== v1 hash calculation

The hash of a v1 declare transaction is computed as follows:


[source,cairo]
----
declare_v1_tx_hash = ℎ(
    "declare",
    version,
    sender_address,
    0,
    h(class_hash),
    max_fee,
    chain_id,
    nonce
)
----

Where:

* stem:[\text{declare}] is a constant prefix string, encoded in ASCII.
* stem:[\text{class_hash}] is the hash of the xref:architecture_and_concepts:Smart_Contracts/contract-classes.adoc[contract class]. See xref:architecture_and_concepts:Smart_Contracts/class-hash.adoc[Class Hash] for details about how the hash is
computed.
* The placeholder zero is used to align the hash computation for the different types of transactions.
* stem:[\text{chain_id}] is a constant value that specifies the network to which this transaction is sent. See xref:#chain-id[Chain-Id].
* stem:[$h$] is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash


==== v0 hash calculation

The hash of a v0 declare transaction is computed as follows:

[source,cairo]
----
declare_v0_tx_hash = ℎ(
    "declare",
    version,
    sender_address,
    0,
    h(),
    max_fee,
    chain_id,
    class_hash
)
----

Where:

* stem:[\text{declare}] is a constant prefix string, encoded in ASCII.
* The placeholder zeros are used to align the hash computation for the different types of transactions.
* stem:[\text{class_hash}] is the hash of the xref:architecture_and_concepts:Smart_Contracts/contract-classes.adoc[contract
class]. See xref:architecture_and_concepts:Smart_Contracts/class-hash.adoc[Class Hash] for details about how the hash is
computed.
* stem:[\text{chain_id}] is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* stem:[$h$] is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash


[id=deploy_account_transaction]
## Deploy account transaction

Since xref:starknet_versions:version_notes.adoc#version0.10.1[StarkNet v0.10.1] the `deploy_account`
transaction replaces the `deploy` transaction
for deploying account contracts.

To use it, you should first pre-fund your would-be account address so that you could pay the
transaction fee (see xref:Accounts/deploying_new_accounts.adoc[here] for more details)
. You can then send the `deploy_account`
transaction.

A `deploy_account` transaction has the following fields:

.Deploy account fields

[%autowidth]
|===
| Name | Type | Description

| `class_hash` | `FieldElement` | The hash of the desired account class.
| `constructor_calldata` | `List<FieldElement>` | The arguments to the account constructor.
| `contract_address_salt` | `FieldElement` | A random salt that determines the xref:Smart_Contracts/contract-address.adoc[account address].
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. The value is 1. +

|===

=== Deploy account hash calculation

The hash of a `deploy_account` transaction is computed as follows:

[source,cairo]
----
deploy_account_tx_hash = ℎ(
    "deploy_account",
    version,
    contract_address,
    0,
    ℎ(class_hash, contract_address_salt, constructor_calldata),
    max_fee,
    chain_id,
    nonce
)
----

[id="signature"]
== Signature

While Starknet does not have a specific signature scheme built into the protocol, the Cairo language, in which smart contracts are written, does have an efficient implementation for ECDSA signature with respect to a xref:../Cryptography/hash-functions.adoc#stark_curve[STARK-friendly curve].

The generator used in the ECDSA algorithm is stem:[G=\left(g_x, g_y\right)] where:

stem:[g_x=874739451078007766457464989774322083649278607533249481151382481072868806602] stem:[g_y=152666792071518830868575557812948353041420400780739481342941381225525861407]

[id="chain-id"]
== Chain-Id

Starknet currently supports three chain IDs. Chain IDs are given as numbers, representing the ASCII encoding of specific constant strings, as illustrated by the following Python snippet:

[source,python]
----
chain_id = int.from_bytes(value, byteorder="big", signed=False)
----
The following constants are currently used:

* `SN_MAIN` for Starknet's main network.
* `SN_GOERLI` for Starknet's public testnet.

include::ROOT:partial$snippet_important_goerli2_removed.adoc[]
