[id="transaction_structure"]
= Transaction types

Starknet supports the following types of transactions:

[horizontal,labelwidth="20"]
_Declare_:: Declares new contract classes, enabling new contract instances.
_Invoke_:: Invokes an existing function in a contract.
_Deploy account_:: Deploys new account contracts in smart wallets.

This topic describes the available fields for these transaction types and how each transaction's hash is calculated.

[id="transaction_versioning"]
== Transaction versions

When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.

[IMPORTANT]
====
Do not submit a transaction that uses an unsupported transaction type, because it cannot be included in a proof, and so cannot become part of a Starknet block.
====

.Supported versions of Starknet transaction types
[cols=",,",]
|===
|Transaction name |Current version |Deprecated version

|*Invoke* | v3 |v1, v0
|*Declare* |v3 |v2, v1, v0
|*Deploy account* | v3 | v0
|===

[NOTE]
====
The *Deploy* transaction type is unsupported. The last supported version was v0.
====

[id=invoke_transaction]
== *Invoke* transaction

[IMPORTANT]
====
Invoke transaction version 0 is deprecated and will be removed in a future release of Starknet.
====

The Invoke transaction type invokes an existing function in a Starknet smart contract, or a contract instance.

Invoke transactions don't add new functions.

Every Invoke transaction in Starknet undergoes `+__validate__+` and `+__execute__+` stages. The `+__validate__+` step checks the transaction's correctness, similar to a syntax or logic check. After validation, the `+__execute__+` phase processes the transaction.


=== v1 transaction fields

.*Invoke* transaction fields

[%autowidth.stretch]
|===
| Name | Type | Description

| `sender_address` | `FieldElement` | The address of the sender of this transaction.
| `calldata` | `List<FieldElement>` | The arguments that are passed to the `validate` and `execute` functions.
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. The value is 1. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.
|===

=== v1 hash calculation

The *Invoke* v1 transaction hash is calculated as a hash over the given transaction elements,
specifically:

[,subs="quotes"]
----
invoke_v1_tx_hash = _h_(
    "invoke",
    version,
    sender_address,
    0,
    _h_(calldata),
    max_fee,
    chain_id,
    nonce
)
----

Where:

* `invoke` is a constant prefix string, encoded in ASCII.
* The placeholder zero is used to align the hash computation for the different types of transactions.
* `chain_id` is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* `_h_` is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash


=== v0 (deprecated) hash calculation


The hash of a v0 invoke transaction is computed as follows:

[,subs="quotes"]
----
invoke_v0_tx_hash = _h_(
    "invoke",
    version,
    contract_address,
    entry_point_selector,
    _h_(calldata),
    max_fee,
    chain_id
)
----

Where:

* `invoke` is a constant prefix string, encoded in (ASCII).
* `chain_id` is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* `_h_` is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash

[id="declare-transaction"]
== *Declare* transaction

The *Declare* transaction introduces new contract classes into the state of Starknet, enabling other contracts to deploy instances of those classes or use them in a library call. For more information, see xref:architecture_and_concepts:Smart_Contracts/contract-classes.adoc[contract classes].

[IMPORTANT]
====
You can only declare Cairo 1.0 classes with the *Declare* v2 transaction type.

v1, which declares Cairo 0 classes, is deprecated and will be removed in a future Starknet version.

v0 is no longer supported.
====

[id="declare_v2"]
=== v2 transaction fields

// todo add flow for invoke /deploy transaction flows examples, from upcoming versions / account
// abstraction./ Link to flow in AA section.

.*Declare* v2 transaction fields

[%autowidth.stretch]
|===
| Name | Type | Description

| `chain_id` | `FieldElement`  | The id of the chain to which the transaction is sent.
| `contract_class` | `ContractClass` | The (Cairo 1.0) xref:Smart_Contracts/class-hash.adoc#definition_of_a_cairo_1_class[class].
| `compiled_class_hash` | `FieldElement` | The hash of the compiled class (see xref:documentation:starknet_versions:upcoming_versions.adoc#what_to_expect[here] for more information)
| `sender_address` | `FieldElement` | The address of the account initiating the transaction.
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction.
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. The value is 2. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.
|===

=== v2 hash calculation

The hash of a v2 *Declare* transaction is computed as follows:

[,subs="quotes"]
----
declare_v2_tx_hash = __h__(
    "declare",
    version,
    sender_address,
    0,
    _h_(class_hash),
    max_fee,
    chain_id,
    nonce,
    compiled_class_hash
)
----

Where:

* `_h_` is the xref:Cryptography/hash-functions.adoc#poseidon_hash[Poseidon hash function]
* `class_hash` is the hash of the contract class. See xref:Smart_Contracts/class-hash.adoc#computing_the_cairo_1_class_hash[Class Hash]
for details about how the
hash is computed
* `compiled_class_hash` is the hash of the xref:starknet_versions:upcoming_versions.adoc#what_to_expect[compiled class]
generated by the Sierra->Casm compiler that is used in Starknet


=== v1 transaction fields

include::partial$snippet_transaction_admonition.adoc[]

This transaction version was used to declare Cairo 0 classes.

.*Declare* v1 transaction fields
[%autowidth.stretch]
|===
| Name | Type | Description

| `contract_class` | `ContractClass` | The class object.
| `sender_address` | `FieldElement` | The address of the account initiating the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction.
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. Possible values are 1 or 0. +
When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases.
|===


=== v1 hash calculation

The hash of a v1 declare transaction is computed as follows:


[,subs="quotes"]
----
declare_v1_tx_hash = _h_(
    "declare",
    version,
    sender_address,
    0,
    _h_(class_hash),
    max_fee,
    chain_id,
    nonce
)
----

Where:

* `declare` is a constant prefix string, encoded in ASCII.
* `class_hash` is the hash of the xref:architecture_and_concepts:Smart_Contracts/contract-classes.adoc[contract class]. See xref:architecture_and_concepts:Smart_Contracts/class-hash.adoc[Class Hash] for details about how the hash is
computed.
* The placeholder zero is used to align the hash computation for the different types of transactions.
* `chain_id` is a constant value that specifies the network to which this transaction is sent. See xref:#chain-id[Chain-Id].
* `_h_` is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash


=== v0 hash calculation

include::partial$snippet_transaction_admonition.adoc[]

This transaction version was used to declare Cairo 0 classes.

The hash of a v0 declare transaction is computed as follows:

[,subs="quotes"]
----
declare_v0_tx_hash = _h_(
    "declare",
    version,
    sender_address,
    0,
    _h_(),
    max_fee,
    chain_id,
    class_hash
)
----

Where:

* `declare` is a constant prefix string, encoded in ASCII.
* The placeholder zeros are used to align the hash computation for the different types of transactions.
* `_h_` is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash
* `chain_id` is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* `class_hash` is the hash of the xref:architecture_and_concepts:Smart_Contracts/contract-classes.adoc[contract class]. See xref:architecture_and_concepts:Smart_Contracts/class-hash.adoc[Class Hash] for details about how the hash is computed.


[id=deploy_account_transaction]
== *Deploy account* transaction

Since xref:starknet_versions:version_notes.adoc#version0.10.1[StarkNet v0.10.1] the *Deploy account*
transaction replaces the *Deploy* transaction
for deploying account contracts.

To use it, you should first pre-fund your would-be account address so that you could pay the
transaction fee (see xref:Accounts/deploying_new_accounts.adoc[here] for more details)
. You can then send the *Deploy account*
transaction.

A *Deploy account* transaction has the following fields:

=== v1 transaction fields

.*Deploy account* transaction fields

[%autowidth]
|===
| Name | Type | Description

| `class_hash` | `FieldElement` | The hash of the desired account class.
| `constructor_calldata` | `List<FieldElement>` | The arguments to the account constructor.
| `contract_address_salt` | `FieldElement` | A random salt that determines the xref:Smart_Contracts/contract-address.adoc[account address].
| `signature` | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.
| `max_fee` | `FieldElement` | The maximum fee that the sender is willing to pay for the transaction
| `nonce` | `FieldElement` | The transaction nonce.
| `version` | `FieldElement` | The transaction's version. The value is 1. +

|===

=== v1 hash calculation

The hash of a *Deploy account* transaction is computed as follows:

[,subs="quotes"]
----
deploy_account_tx_hash = _h_(
    "deploy_account",
    version,
    contract_address,
    1,
    _h_(class_hash, contract_address_salt, constructor_calldata),
    max_fee,
    chain_id,
    nonce
)
----

Where:

* `deploy_account` is a constant prefix string, encoded in ASCII.
* The placeholder zero is used to align the hash computation for the different types of transactions.
* `_h_` is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash
* `chain_id` is a constant value that specifies the network to which this transaction is sent. See xref:chain-id[Chain-Id].
* `class_hash` is the hash of the xref:architecture_and_concepts:Smart_Contracts/contract-classes.adoc[contract class]. See xref:architecture_and_concepts:Smart_Contracts/class-hash.adoc[Class Hash] for details about how the hash is computed.



[id="deploy_transaction"]

If you need to retrieve the hash of an existing *Deploy* transaction, you can use this information to calculate the hash of the transaction.

== *Deploy* transaction hash calculation

Before you can calculate the transaction hash, get the deployed contract address. The *Deploy* transaction's hash is calculated as shown in the following pseudo code:

[,subs="quotes"]
----
deploy_tx_hash = _h_(
    "deploy",
    version,
    contract_address,
    sn_keccak("constructor"),
    _h_ constructor_calldata),
    0,
    chain_id
)
----

Where:

* The placeholder zero is used to align the hash computation for the different types of transactions.
* `deploy` and `constructor` are constant strings encoded in ASCII.
* `_h_` is the xref:../Cryptography/hash-functions.adoc#pedersen_hash[Pedersen] hash and
`sn_keccak` is xref:../Cryptography/hash-functions.adoc#starknet_keccak[Starknet Keccak].
* `chain_id` is a constant value that specifies the network to which this transaction is sent. See xref:#chain-id[Chain-Id].
* `contract_address` is calculated as described xref:architecture_and_concepts:Smart_Contracts/contract-address.adoc[here].

[id="signature"]
== Signature

While Starknet does not have a specific signature scheme built into the protocol, the Cairo language, in which smart contracts are written, does have an efficient implementation for ECDSA signature with respect to a xref:../Cryptography/stark-curve.adoc[STARK-friendly curve].

The generator used in the ECDSA algorithm is stem:[G=\left(g_x, g_y\right)] where:

stem:[g_x=874739451078007766457464989774322083649278607533249481151382481072868806602] stem:[g_y=152666792071518830868575557812948353041420400780739481342941381225525861407]

[id="chain-id"]
== Chain ID

Chain IDs are given as numbers, representing the ASCII encoding of specific constant strings, as illustrated by the following Python snippet:

[source,python]
----
chain_id = int.from_bytes(value, byteorder="big", signed=False)
----

The following constants are currently used. They correspond to the chain IDs that Starknet currently supports:

* `SN_MAIN` for Starknet's main network.
* `SN_GOERLI` for Starknet's public testnet.

include::ROOT:partial$snippet_important_goerli2_removed.adoc[]
