= API services

[TIP]
====
For complete information on Starknet's JSON-RPC API, see https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json[`starknet_api_openrpc.json`^].
====

== API providers

[discrete]
=== Alchemy
http://www.alchemy.com/starknet[Alchemy^] is a blockchain platform layer, providing developers with the fundamental building blocks they need to create the future of technology.

[NOTE]
====
Information about multiple versions support is available at https://docs.alchemy.com/reference/starknet-api-faq#what-versions-of-starknet-api-are-supported[docs.alchemy.com/reference/starknet-api-faq#what-versions-of-starknet-api-are-supported^].
====

[discrete]
=== All That Node
https://www.allthatnode.com/starknet.dsrv[All That Node^] is a multi-chain node and data service offered by DSRV. 


[discrete]
=== Blast
http://blastapi.io/public-api/starknet[Blast^] is a premium blockchain API platform providing top-of-industry performance and reliability.

[discrete]
=== BlockPI
http://blockpi.io/starknet[BlockPI^] is a professional infrastructure platform driving industry growth and catering to both the diverse needs of developers and the inclusive requirements of regular users.#


[discrete]
=== Chainbase
https://platform.chainbase.com/chainNetwork/Starknet[Chainbase^] is an open Web3 data infrastructure for accessing, organizing, and analyzing on-chain data at scale.

[discrete]
=== Chainstack
https://chainstack.com/build-better-with-starknet/[Chainstack^] makes sure you get access to robust and scalable infrastructure, ready for your Starknet journey, in a matter of minutes.

[NOTE]
====
Information about multiple versions support is available at https://docs.chainstack.com/reference/getting-started-starknet#starknet-json-rpc-version-endpoints[docs.chainstack.com/reference/getting-started-starknet#starknet-json-rpc-version-endpoints^].
====

[discrete]
=== dRPC
https://drpc.org/chainlist/starknet[dRPC^] is a decentralized network of RPC endpoints with unlimited scalability supporting 29+ chains.

[NOTE]
====
Multiple versions are supported by using the `/rpc/vX_Y suffix`, as explained in https://github.com/eqlabs/pathfinder?tab=readme-ov-file#json-rpc-api[Pathfinder's README].
====

[discrete]
=== Dwellir
https://www.dwellir.com/networks/starknet[Dwellir^] offers scalable RPC nodes that power Web3 developers with high-speed, affordable infrastructure.

[discrete]
=== GetBlock
https://getblock.io/nodes/strk/[GetBlock^] provides access to blockchain RPC nodes, supporting over 50 blockchain protocols, including Starknet.

[discrete]
=== Infura
https://www.infura.io/networks/ethereum/starknet[Infura^] offers a powerful suite of high availability blockchain APIs and developer tools


[discrete]
=== Lava
https://www.lavanet.xyz/get-started/starknet[Lava^] is an open-source protocol for reliable access to RPC data.

[NOTE]
====
Multiple versions are supported by using the `/rpc/vX_Y suffix`, as explained in https://github.com/eqlabs/pathfinder?tab=readme-ov-file#json-rpc-api[Pathfinder's README].
====

[discrete]
=== Nethermind
https://data.voyager.online/[Nethermind^] provides fast and reliable Starknet RPC service built for developers.

[NOTE]
====
Information about multiple versions support is available at https://docs.data.voyager.online/spec[docs.data.voyager.online/spec^].
====

[discrete]
=== NOWNodes
https://nownodes.io/starknet[NOWNodes^] is a Starknet RPC Full Node API with zero RPS limits.

[discrete]
=== OMNIA
https://omniatech.io/[OMNIA^] is a specialized RPC provider for DeFi traders, developed by cybersecurity, privacy and trading experts.

[discrete]
=== QuickNode
https://www.quicknode.com/chains/strk[QuickNode^] offers everything you need for accessing the Starknet blockchain, from elastic APIs to powerful tools and analytics.

[NOTE]
====
Information about multiple versions support is available at https://quicknode.com/docs/starknet#supporting-multiple-versions[quicknode.com/docs/starknet#supporting-multiple-versions^].
====

[discrete]
=== Reddio
https://www.reddio.com/node[Reddio^] provide fast connection to Starknet/Ethereum across the global, with faster response times, quick secure connection handshakes, and impressive server responsiveness.

[discrete]
=== ZAN
https://zan.top/home/node-service[ZAN^] provides comprehensive technologies, products and solutions for Web3 ecosystem, including node service dedicated to securing and optimizing Web3 applications, platforms and businesses.

[NOTE]
====
Multiple versions are supported by using the `/rpc/vX_Y suffix`, as explained in https://github.com/eqlabs/pathfinder?tab=readme-ov-file#json-rpc-api[Pathfinder's README].
====

== Open API endpoints

[%autowidth.stretch,cols=",,",options="header"]
|===
| Provider
| Mainnet
| Sepolia

| xref:#blast[Blast]
| \https://starknet-mainnet.public.blastapi.io
| \https://starknet-sepolia.public.blastapi.io

| xref:#drpc[dRPC]
| \https://starknet.drpc.org
| \https://starknet-sepolia.drpc.org

| xref:#lava[Lava]
| \https://rpc.starknet.lava.build:443[]
| \https://rpc.starknet-testnet.lava.build:443

| xref:nethermind[Nethermind]
| \https://free-rpc.nethermind.io/mainnet-juno
| \https://free-rpc.nethermind.io/sepolia-juno

| xref:#zan[Zan]
| \https://api.zan.top/public/starknet-mainnet
| N/A
|===

// .Node providers
// [cols="1,2,1",stripes=even]
// [%header,cols="2,2,1"]
// |===
// | Provider name | Description | More information 
// |Madara|Madara is a powerful Starknet client written in Rust. |link:https://github.com/madara-alliance/madara[github.com/madara-alliance/madara] 
// |Juno|A Starknet full-node written in go-lang by Nethermind.

// You can use the link:https://aws-samples.github.io/aws-blockchain-node-runners/docs/Blueprints/Starknet[Juno Node runner on AWS].
// |link:https://github.com/NethermindEth/juno[github.com/NethermindEth/juno] 

// |Papyrus|A Starknet full-node written in Rust by StarkWare | link:https://github.com/starkware-libs/papyrus[github.com/starkware-libs/papyrus] 
// |Pathfinder|A Starknet full-node written in Rust by Equilibrium |link:https://github.com/eqlabs/pathfinder[github.com/eqlabs/pathfinder] 
// |===
