[id="audit_providers"]
= Auditors and security platforms

== ABDK

https://www.abdk.consulting/[ABDK^] is as a top service provider in the design and security of Web 3.0, that have conducted over 100 audit project and consulted dozens of clients.

== Beosin

https://beosin.com/[Beosin^] provides one-stop blockchain security solutions for projects on Starknet including security audit, on-chain risk monitoring and alert.

== Beyond

https://beyondaudit.github.io/[Beyond^] is a dedicated blockchain security team aiming to erase unseen threats, one line of code at the time. Our auditors combine technical insight with experience to protect protocols as they evolve, delivering excellence in smart contract security.

== Cairo Security Clan

https://cairosecurityclan.com/[Cairo Security Clan^] is a team of highly talented Starknet auditors united to secure the Starknet ecosystem.

== ChainSecurity

https://chainsecurity.com/[Chain Security^] is ChainSecurity is a flat and self-owned organization, that focus on providing the best security to the best innovators.


== CODESPECT

https://codespect.xyz/[CODESPECT^] is a security company specializing in Starknet and Ethereum audits, offering a tailored approach to each protocol’s unique security challenges.

== ConsenSys

http://consensys.net/diligence[ConsenSys^] is a leading smart contract auditing and blockchain security tooling for smart contract developers, auditors and web3 protocols.

== Extropy

https://www.extropy.io/[Extropy^] provides auditing, training and development services for Web3 / ZKP companies.

== FuzzingLabs

https://fuzzinglabs.com/[FuzzingLabs^] is a blockchain security company specializing in vulnerability research and fuzzing, providing audit, training, and custom development services for Web3 and ZKP companies.

== Ginger Security

https://gingersec.xyz/[Ginger Security^] offer security advisory, End-to-end penetration testing, Smart contract audits, Zero-knowledge, automations, & MEV bot development.

== Hashlock

https://hashlock.com/[Hashlock^] is the industry-leading blockchain cybersecurity and web3 security auditing firm.

== Hypernative

https://www.hypernative.io/[Hypernative^] is a real time security and risk prevention platform that helps protocols, chains and asset managers detect hacks/exploits or other custom risk before they happen.

== Nethermind Security

https://www.nethermind.io/smart-contract-audits[Nethermind Security^] is the security arm of Nethermind, providing services related to Smart Contract Audits, Formal Verification, and Real-Time Monitoring.

== Open Zeppelin

https://www.openzeppelin.com/[Open Zeppelin^] is an elite team that brings together unparalleled expertise in PhD-level mathematics, cryptography, low-level EVM operations, and finance.

== OtterSec

https://osec.io/[OtterSec^] is a blockchain security company with a holistic and collaborative approach to identifying and patching critical exploits for clients before they go to market.

== PeckShield

https://peckshield.com/[PeckShield^] is a blockchain security company that provides comprehensive security audits, threat monitoring and prevention, penetration testing and emergency response, and more.

== Softstack

https://softstack.io/[softstack^] is a leading Web3 cybersecurity and software development firm since 2017, providing smart contract audits, regulatory compliance solutions, and enterprise-grade penetration testing.

== Trail of Bits

http://www.trailofbits.com/[Trail of Bits^] has helped secure some of the world’s most targeted organizations and products, combining high-end security research, with a real-world attacker mentality to reduce risk and fortify code.

== Zellic

https://www.zellic.io/[Zellic^] is a security research firm with deep expertise in blockchain security and cryptography, led by the best hackers in the world.
