= Tools for building Starknet dApps

== Scaffold-Stark
https://scaffoldstark.com/[Scaffold-Stark^] is built using NextJS, Starknet.js, Scarb, Starknet-React, Starknet Foundry and Typescript, and designed to make it easier for developers to create, deploy and interact with smart contracts.

== Starknet Scaffold
https://www.starknetscaffold.xyz/[Starknet-Scaffold^] is an open-source, up-to-date toolkit for building decentralized applications on Starknet, that help you move from prototyping to production-grade apps seamlessly.

Decentralized applications are at the heart of Starknet. These libraries help developers build Dapps on Starknet and connect to prominent Starknet wallets.

== Starknet React
https://github.com/apibara/starknet-react[Starknet React^], developed by Apibara using starknet.js, is a wagmi-inspired collection of React hooks for Starknet.

== Get Starknet
https://github.com/starknet-io/get-starknet[Get Starknet^] is a Starknet wallet<>dApp connection bridge, that enables easy discovery and UI for Starknet wallets, including ArgentX, Braavos, Metamask Snaps, and OKx.

== Starknetkit
https://www.starknetkit.com/[Starknetkit] is a Starknet wallet connection kit, built by Argent using Starknet.js and starknet-react.

== Invisible SDK
https://docs.argent.xyz/tools/invisible-sdk[Invisible SDK^] enables users to interact with dApps using just their email address, eliminating the need for seed phrases or private keys.

== Dojo
https://www.dojoengine.org/[Dojo^] is a developer friendly framework for building provable Games, Autonomous Worlds and other Applications that are natively composable, extensible, permissionless and persistent.

== Starkweb
https://www.starkweb.xyz/[Starkweb^] is TypeScript toolkit for Starknet development focused on developer experience, performance, comprehensive feature support, and stability, enabling developers to concentrate on building high-quality applications without the usual friction.

== Chipi SDK
https://sdk.chipipay.com/introduction[Chipi SDK^] is an SDK that enables invisible wallet creation on StarkNet with social login and Avnu's paymaster, streamlining dApp development on StarkNet. Users can log in with familiar accounts (Google, X, Meta) and a wallet is automatically generated, eliminating the need for manual key management.
