= Tools for coding in Cairo

[#usc]
== Universal-Sierra-Compiler
https://github.com/software-mansion/universal-sierra-compiler[Universal-Sierra-Compiler^] is a utility tool for compiling single Sierra files (unlike Scarb, which compiles full projects) from any Sierra version into CASM.

[NOTE]
====
Universal-Sierra-Compiler comes bundled with Starknet Foundry and does not need to be installed separately if Starknet Foundry is installed.
====

[#cairo-profiler]
== cairo-profiler
https://github.com/software-mansion/cairo-profiler[cairo-profiler^] is a utility tool that can be used to create profiles of Cairo executions from execution traces, which can be analyzed and used to show flame graphs and other useful information.

[NOTE]
====
cairo-profiler comes bundled with Starknet Foundry and does not need to be installed separately if Starknet Foundry is installed.
====

[#cairo-playground]
== Cairo Playground

https://www.cairo-lang.org/cairovm/[Cairo Playground^] an online tool that can be used to both experiment with Cairo without deploying a smart contract on Starknet, as well as dive deep into the Cairo virtual machine.

[#sierra-analyzer] 
== Sierra Analyzer

https://github.com/FuzzingLabs/sierra-analyzer[Sierra Analyzer^], developed by https://x.com/fuzzinglabs[FuzzingLabs^] is a security toolkit for analyzing Sierra files, including decompiling a Sierra file, printing the contract's control flow graph, and running static analysis detectors.

== Cairo lint

https://github.com/software-mansion/cairo-lint[Cairo lint^] is a collection of lints that can either be used as either a library or as a standalone binary to help both detect and fix common mistakes and improve your Cairo code.

== Stark-utils

https://www.stark-utils.xyz/converter[Stark-utils^] is a simple web application that aims to be a toolbox for Cairo developers, allowing you to convert any input to a felt, string, hexadecimal value, and more.


