= Starknet Compatibility Tables

== Overview

The Starknet development ecosystem consists of tools built to work and support the latest version of Starknet. As Starknet evolves, these tools are updated to support its latest features.

Each version of Starknet is usually coupled with an update of all or some of:

* Starknet API
* Cairo
* Sierra

The following compatibility matrices provide an overview of the compatibility between Starknet updates and the tools in the ecosystem.


[NOTE]
====
Currently this page is being manually updated. Contributions with more up-to-date information are more than welcome. 
====

== Starknet versions

The following tables specifies the latest version of Starknet API, Cairo and Sierra supported by each Starknet version. The Pathfinder and Juno versions represent the recommended versions for running a full node with the relevant Starknet version.

[%header, cols="~,^~,^~,^~"]
|===
| | Starknet 0.13.2 | Starknet 0.13.1 | Starknet 0.13.0 
| RPC Version | 0.7 | 0.7 | 0.6
| Cairo Version | 2.8.0 | 2.6.0 | 2.4.0
| Sierra Version | 1.6.0 | 1.5.0 | 1.4.0
| Pathfinder | 0.14.1 | 0.11.0 | 0.10.0
| Juno | 0.12.0 | 0.11.0 | 0.8
|===

== Starknet API

The following table specifies:

* For the latest API version: the recommended version for working with the respective API version. If a newer version exist, the newest version should be used instead.
* For older API versions: the last recommended version of the tool that worked with the respective API version.

[%header, cols="~,^~,^~"]
|===
| | RPC 0.7 | RPC 0.6
| starknet.js | ≥ 6.11.0 | 5.14.0
| starknet.py | ≥ 0.21.0 | 0.20.0
| starknet-rs | ≥ 0.11.0 | 0.10.0
| starknet.go | ≥ 0.7.0 | 0.6.1
| starknet-jvm | ≥ 0.11.0 | 0.10.0
| starknet.swift | ≥ 0.9.0 | 0.8.0
| Starkli | ≥ 0.3.0 | 0.2.0
| Pathfinder | ≥ 0.11.0 | 0.10.2
| Juno | ≥ 0.11.0 | 0.8.0
| Starknet Foundry | ≥ 0.27.0 | 0.20.0
| Starknet Devnet RS | ≥ 0.1.2 | 0.0.2
|===

== Cairo

The following tables specifies:

* For SDKs: the version that support the respective Cairo version types and can declare and deploy contracts written in that version.
* For Starknet Foundry and Scarb: the version that can compile, declare, and deploy contracts written in the respective Cairo version.
* For Starknet Devnet: the version that contracts written in the respective Cairo version can be declared and deployed on.
* For Starkli: the version that can declare and deploy contracts written in the respective Cairo version.

[%header, , cols="~,^~,^~,^~"]
|===
| | Cairo 2.8.0 | Cairo 2.7.0 | Cairo 2.6.0
| starknet.js | 6.11.0 | - | -
| starknet.py | ≥ 0.24.1 | ≥ 0.24.1 | 0.19.0
| starknet-jvm | ≥ 0.11.1 | ≥ 0.11.1 | ≥ 0.11.1
| starknet.swift | ≥ 0.9.0 | ≥ 0.9.0 | ≥ 0.9.0
| starkli | 0.3.4 | 0.3.4 | 0.3.3
| Scarb | 2.8.1 | 2.7.1 | 2.6.5
| Starknet Foundry | ≥ 0.28.0 | ≥ 0.28.0 | 0.27.0
| Starknet Devnet RS |  0.2.0-rc.3 | 0.2.0-rc.3 | 0.1.2
|===