[id="dai_token_migration"]
= Migrating DAI v0 to DAI
:description: Migrating DAI v0 on Starknet to DAI on Starknet.
:keywords: Starknet DAI, DAI doesn't work on Starknet, New DAI on Starknet, Starknet new DAI

Following link:https://twitter.com/MakerDAO/status/1746977683190251591?s=20[Maker DAO’s announcement on Jan 25th], StarkWare launched a new DAI contract and bridge on Starknet.

The new DAI token and bridge are a part of StarkGate and compatible with StarkGate 2.0 features.

You can withdraw old DAI tokens (DAI v0) without any limitation. Depositing using the DAI v0 bridge are disabled. You are encouraged to migrate to the new DAI token. You can use swap services on Starknet to swap DAI v0 for DAI.

Maker DAO's DAI token on Starknet is written in Cairo0 and is not upgradeable. Without upgradability, it cannot support StarkGate's latest features, such as Smart Deposits and Withdrawal Limits, and over time it will stop being compatible with Starknet altogether (Regenesis). This means that a transition plan is necessary.

On January 25th, StarkWare launched a new set of DAI bridge and token contracts under StarkGate, written in Cairo. This new DAI token will retain the same contract ’symbol’ and ’name’ as the existing one. To differentiate between the two on Apps and other UIs, we refer to the old DAI as “DAI v0” and the new DAI simply as “DAI.”


.Procedure

Use one of the following methods:

* Use StarkGate:
+
. Withdraw your current DAI (DAI v0) to L1 using StarkGate
. Re-deposit your L1 DAI using StarkGate.
+
StarkGate automatically issues the new DAI.

* Swap your DAI v0 for DAI using an L2 swap app or aggregator within the Starknet ecosystem, such as the following:
** link:https://www.layerswap.io/migration/DAI[LayerSwap]
** link:https://app.ekubo.org/?amount=1000&inputCurrency=DAI&outputCurrency=DAIv2[Ekubo]
** link:https://app.avnu.fi/en?tokenFrom=0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7&tokenTo=0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d&amount=0.001[AVNU]
** link:https://app.fibrous.finance/[Fibrous]
** link:https://app.jediswap.xyz/#/swap[JediSwap]
** link:https://app.haiko.xyz/trade/swap[Haiko]
** link:https://app.nostra.finance/[Nostra]
** link:https://app.starkdefi.com/#/swap[StarkDeFi]




