= Indexers

== Apibara

https://www.apibara.com/[Apibara^] is a fast and open-source data platform connecting Starknet to Web2 services.

== Checkpoint

https://checkpoint.fyi/#/[Checkpoint^] is inspired by The Graph and focused on providing similar functionality for Starknet, providing a library for indexing data from Starknet events and making it accessible through a GraphQL API. 

== Token Flow

https://tokenflow.live/[Token Flow^] provides fully decoded and contextualised on-chain data, including storage information and L1 / L2 messaging.

== DipDup

https://dipdup.io/[DipDup^] is an open-source indexing stack, providing GraphQL access to  decoded on-chain data, NFT balances & transfers, and app-specific collections.

== SubQuery

https://subquery.network/[SubQuery^] provides customised blockchain data from hundreds of networks to make your dApp lighting quick.

== Footprint Analytics

https://www.footprint.network/[Footprint Analytics^] is a data platform blending web2 and web3 data with abstractions.