//include::1.0.0@docs-common-content:ROOT:partial$partial_devtools.adoc[]
// Previously, to edit this topic, you needed to go to:
// https://github.com/starknet-io/docs-common-content/edit/main/modules/ROOT/partials/partial_devtools.adoc
// This topic no longer needs to be shared, so the source is now directly coded here.
[id="starknet_development_tools"]
= Starknet developer tools

While Starknet is a blockchain, it is different from blockchains built on the model of the Ethereum virtual machine (EVM), and so it requires many of its own developer tools. The tools discussed here are being developed in coordination with StarkWare and, in some cases, have received grants from StarkWare or the Starknet Foundation to make the development process as friendly as possible, with improvements happening constantly.

While the stack of Starknet development tools was originally based mostly on Python, tool developers are moving towards building with Rust.


[NOTE]
====
This list of tools is dynamic and is being updated as more tools are added. If a tool you are using is missing, please consider editing this page and creating a Pull Request.
====


== Command-line tools

[#starkli]
=== starkli

Starkli is a fast command-line interface for interacting with the Starknet network. It supports fetching data from the Starknet network, deploying accounts, and interacting with contracts. Developed by Jonathan Lei.
Starkli also includes useful utilities for developers, such as:

* Compute class hashes from the Cairo file that defines the class.
* Compute a function’s selector.
* Encode messages.
* Fetching existing accounts
* The ability to make multi-calls.

[discrete]
==== Relevant links

* GitHub: link:https://github.com/xJonathanLEI/starkli/[starkli on GitHub]
* Documentation: link:https://book.starkli.rs/[Starkli Book]

* link:https://medium.com/starknet-edu/starkli-the-new-starknet-cli-86ea914a2933[Starkli: The New Starknet CLI], on Medium, includes information on getting started, including installation instructions.

[#sncast]
=== sncast
Starknet Cast, part of the Starknet Foundry suite, is a command line tool for interacting with the Starknet network, with deep integration with xref:starknet_foundry[Starknet Foundry] projects.

* link:https://foundry-rs.github.io/starknet-foundry/starknet/index.html[Starknet Cast Docs]

[#scarb]

[#sdks]
== Starknet SDKs

A Software Development Kit (SDK) is a library that abstracts the complexities of Starknet when building transactions and interacting with the blockchain, including the following:

* Read the chain state.
* Account creation and management.
* Cryptography: Signature verification and signing, computing hashes used by Starknet.
* Contarct declaration and deployment.
* Contract interactions: ABI import, constructing transactions.

There are SDKs for various languages, so you can choose the SDK according to your needs.

[cols=",,,,,",]
|===
| SDK name | Github | Package | Docs | Support | Maintainer 

|Starknet.js  | link:https://github.com/starknet-io/starknet.js[starknet.js on GitHub] | link:https://www.npmjs.com/package/starknet[starknet.js on NPM] | link:https://www.starknetjs.com/[starknet.js Book] | starknet.js channel on link:https://discord.gg/starknet-community[Starknet Discord] |SpaceShard 
|Starknet.py | link:https://github.com/software-mansion/starknet.py[starknet.js on GitHub] | link:https://pypi.org/project/starknet-py/[starknet.py on PyPi] | link:https://starknetpy.rtfd.io/[starknet.py Docs] | link:https://t.me/starknetpy[starknet.py on Telegram] | Software Mansion 
|Starknet-rs | link:https://github.com/xJonathanLEI/starknet-rs[starknet-rs on GitHub] | link:https://crates.io/crates/starknet[starknet-rs on Crates] | link:https://github.com/xJonathanLEI/starknet-rs[starknet-rs Docs] | link:https://t.me/starknet_rs[starknet-rs on Telegram] | Jonathan Lei 
|Starknet.go | link:https://github.com/NethermindEth/starknet.go[starknet.go on GitHub] | | link:https://pkg.go.dev/github.com/NethermindEth/starknet.go[starknet.go Docs] | link:https://t.me/StarknetGo[starknet.go on Telegram] | Nethermind 
|===

[#Contract-Development]
== Smart Contract Development
Cairo is a turing complete language for writing provable programs. It is also the language used for writing smart contracts for Starknet. Developing Cairo is supported by the following tools.

[#scarb]
=== Scarb: The Cairo package manager

Scarb is a package manager for Cairo, but it is much more than that. It is the easiest and recommended way to build and maintain Cairo code. Think Cargo for Rust.
Scarb is developed by Software Mansion.

Scarb includes the following features:

* Initiating a new Cairo project.
* Compiling Cairo projects.
* Adding and removing Cairo dependencies.
* Generating Cairo documentation.
* Fetching and uploading packages to the Cairo registry
* Integration with the Cairo Language Server
* It integrates with other tools in the Cairo ecosystem, such as Starknet Foundry and the Dojo gaming engine.

[discrete]
==== Relevant links
* GitHub: link:https://github.com/software-mansion/scarb[Scarb on GitHub]
* Documentation: link:https://docs.swmansion.com/scarb/[Scarb Docs]
* Support: link:https://t.me/+1pMLtrNj5NthZWJk[Scarb on Telegram]

---

[#starknet_foundry]
=== Starknet Foundry

Starknet Foundry is the go-to toolchain for developing Starknet smart contracts. Similarly to its EVM counterpart, Starknet Foundry supports a plethora of features focused on testing Cairo smart contracts for Starknet.

Starknet Forge, and `forge_std` allow the use of "cheatcodes" to test various aspects of the contracts.
For example:
* Setting caller address
* Manipulating the timestamp and block number
* Forking the chain at a specific block and testing with that state
* Fuzz testing
* Getting accurate gas and resource reports
* Profiling

Starknet Cast is a command line tool for interacting with the Starknet network, with deep integration with Starknet Foundry projects.
With `sncast` it is possible to:
* Declare and deploy contracts
* Read from Starknet contracts
* Deploy accounts
* Interact with contracts

[discrete]
==== Relevant links
* GitHub: link:https://github.com/foundry-rs/starknet-foundry[starknet-foundry on GitHub]
* Documentation: link:https://foundry-rs.github.io/starknet-foundry/[starknet-foundry Docs]
* Support: link:https://t.me/starknet_foundry_support[Starknet Foundry Support on Telegram]

---

[#starknet_remix_plugin]
=== The Starknet Remix plugin

Remix is a browser-based integrated development environment (IDE) for Ethereum that you can use for learning, experimenting and finding vulnerabilities in smart contracts, without installing anything. The Starknet Remix plugin lets you use Remix for testing Starknet smart contracts, so you can focus on learning Cairo and Starknet in the comfort of your browser.

Remix and the Starknet Remix plugin include the following features:

* Integrated compiling.
* You can deploy contracts to testnet, mainnet and the plugin’s own integrated devnet.
* You can call functions of contracts that you have already deployed, to facilitate testing and interaction.
* The Starknet Remix Plugin is integrated with link:https://starknet-by-example.voyager.online/[Starknet By Example], a rich repository of practical learning content.

[discrete]
==== Relevant links
Remix Project: link:https://remix-project.org[Remix Project site].

* Blogpost: link:https://medium.com/nethermind-eth/unlocking-onboarding-to-starknet-an-overview-of-the-starknet-remix-plugin-6b0658e73521[Unlocking Onboarding to Starknet: An Overview of the Starknet Remix Plugin].
* GitHub link:https://github.com/NethermindEth/starknet-remix-plugin[Starknet Remix on GitHub].

[#vs_code_cairo_extension]
== The Visual Studio Code Cairo extension

An extension for the Microsoft VSCode IDE that provides assistance when writing Cairo smart contracts, by using the Cairo Language Server. It integrates with Scarb, and works best when Scarb is installed via `asdf`.

Features include:

* Live diagnostic highlighting for compile errors
* Quick fixes with suggestions
* Go to definition
* Code formatting
* Code completion for imports

[discrete]
==== Relevant links
* link:https://marketplace.visualstudio.com/items?itemName=starkware.cairo1[Cairo 1.0 - Visual Studio Marketplace]
* link:https://github.com/starkware-libs/cairo/tree/main/vscode-cairo[vscode-cairo on GitHub]


[#devnets]
== Local Development nodes
A Starknet devnet is a local node Starknet node implementations, aimed for testing and development. A devnet behaves just like a real Starknet node, but everything is executed locally. This enables much faster and more private development of Starknet applications.


[#starknet-devnet-rs]
=== starknet-devnet-rs

starknet-devnet-rs can is a Rust implementation of a local Starknet node. Developed by SpaceShard.

With starknet-devnet-rs includes many featured tailored for testing and development, which are not present on testnet/mainnet.
Some of the features include:

* Pre-deployed and pre-funded accounts
* Forking the chain at a specific block.
* Dumping current state (and loading in future runs)
* Impersonating account
* Mock L1<>L2 communication

[discrete]
==== Relevant links

* GitHub: link:https://github.com/0xSpaceShard/starknet-devnet-rs[starknet-devnet-rs on GitHub]
* Crates: link:https://crates.io/crates/starknet-devnet[starknet-devnet-rs on Crates]
* Documentation: link:https://0xspaceshard.github.io/starknet-devnet-rs/[starknet-devnet-rs Docs]
* Support: devnet channel on link:https://discord.gg/starknet-community[Starknet Discord]

---

[#katana]
=== Katana

Katana, developed by the Dojo team, is an extremely fast devnet designed to support local development with Dojo, which is a gaming engine for Starknet. You can use Katana as a general purpose devnet as well.

[discrete]
==== Relevant links

* GitHub: link:https://github.com/dojoengine/dojo[Dojo Engine on GitHub]
* Documentation: link:https://book.dojoengine.org/toolchain/katana[Katana Docs]

[#libs-for-dapps]
== Libraries for Dapps

[#starknet-react]
=== Starknet React
Starknet React is a collection of React hooks for Starknet. It is inspired by wagmi, powered by starknet.js. Developed by Apibara.

[discrete]
==== Relevant links

* GitHub: link:https://github.com/apibara/starknet-react[starknet-react on GitHub]
* Package: link:https://www.npmjs.com/package/@starknet-react/core[starknet-react on NPM]
* Documentation: link:https://starknet-react.com/[Starknet-React Docs]
* Beta Version Documentation: https://v3.starknet-react.com/docs/getting-started[Starknet-React V3 Docs]


[#get-starknet]
=== Get Starknet
Starknet wallet<>Dapp connection bridge.

[discrete]
==== Relevant links

* GitHub: link:https://github.com/starknet-io/get-starknet[get-starknet on GitHub]
* Package: link:https://www.npmjs.com/package/get-starknet[get-starknet on NPM]

[#utilities]
== Utilities

While not under any specific category, these tools can be helpful in various stages of development.

[#usc]
=== Universal Sierra Compiler
While Scarb compiles full projects, and produces both Sierra and CASM files, it is often needed to only compile a single Sierra file to CASM (for example, when getting a class from Starknet mainnet). The Universal Sierra Compiler supports all sierra versions, and can compile the the a CASM file.

[NOTE]
====
The USC comes bundled with Starknet Foundry and does not need to be installed separately if Starknet Foundry is installed.
====

* GitHub: link:https://github.com/software-mansion/universal-sierra-compiler[Universal Sierra Compiler on GitHub]


[#rpc-request-builder]
=== RPC Request Builder
The Starknet RPC Request Builder is a useful tool to generate RPC queries for Starknet, with support for basic example for JavaScript, Go and Rust.

* link:https://rpc-request-builder.voyager.online/[RPC Request Builder]

[# Open Zeppelin Contract Wizrd]
=== Open Zeppelin Contract Wizard

The Open Zeppelin Contract Wizard is a tool that helps you create smart contracts with Open Zeppelin libraries. Easily toggle on and off features for popular smart contract patterns, and the wizard will generate the code for you.

* link: https://wizard.openzeppelin.com/cairo[Open Zeppelin Contract Wizard]

[#cairo-profiler]
=== Cairo Profiler
Cairo-profiler can be used to create profiles of Cairo executions from execution traces.
These can be analyzed and displayed to show Flame Graphs, and other useful information.

[NOTE]
====
Cairo-profiler is currently integrated into Starknet Foundry, but can be used as a standalone tool.
====

* link: https://github.com/software-mansion/cairo-profiler[Cairo Profiler on GitHub]

[#cairo-visualizer]


[#Security]
== Security and Analysis tools

[#sierra-analyzer] 
=== Sierra Analyzer

Sierra-Analyzer is a security toolkit for analyzing Sierra files, developed by FuzzingLabs.

Supported featrued include:
* Decompile a Sierra file
* Print the contracts Control Flow Graph
* Run Static Analysis detectors

* link:https://github.com/FuzzingLabs/sierra-analyzer(sierra-analyzer on GitHub)

[#entro]
=== Entro

Analyze and Decode Starknet Transactions and events.

Features:
* Get contract class history
* Decode contract ABI
* Decode transaction data
* Backfill data for faster analysis

* link: https://github.com/NethermindEth/entro[Entro on GitHub]
