= Full nodes

== Juno

https://github.com/NethermindEth/juno[Juno^] is a Go implementation of a Starknet full-node client created by https://nethermind.io/[Nethermind^] to allow node operators to easily and reliably support the network and advance its decentralisation goals

[TIP]
====
See https://aws-samples.github.io/aws-blockchain-node-runners/docs/Blueprints/Starknet[_Sample AWS Blockchain Node Runner app for Starknet Nodes_^] for deploying Juno nodes on AWS.
====

== Madara

https://github.com/madara-alliance/madara[Madara^] is an open-source framework written that makes it simple for you to deploy your own Cairo-powered chain, including an easy-to-use, blazing-fast and powerful Starknet full node client, written in Rust and powered by Substrate.

== Papyrus

https://github.com/starkware-libs/papyrus[Papyrus^] is StarkWare's own Rust implementation of a Starknet full-node, integrated in https://github.com/starkware-libs/sequencer[StarkWare's next-gen Starknet sequencer^].

== Pathfinder

https://github.com/eqlabs/pathfinder[Pathfinder^] is a Rust implementation of a Starknet full node created by https://equilibrium.co/[Equilibrium^], that provides a secure view into the Starknet blockchain, giving access to Starknet's entire state history and allowing users to query contract code, storage, and transactions.