[id="important_addresses"]
= Important addresses

include::ROOT:partial$snippet_important_goerli2_removed.adoc[]

==  Starknet Alpha on Mainnet

The Starknet core contract:: link:https://etherscan.io/address/0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4[`0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4`^]
Verifier address::  link:https://etherscan.io/address/0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60[`0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60`^]
Sequencer base URL for API routing:: \https://alpha-mainnet.starknet.io

== Starknet Alpha version on Goerli testnet

The Starknet core contract:: link:https://goerli.etherscan.io/address/0xde29d060D45901Fb19ED6C6e959EB22d8626708e[`0xde29d060D45901Fb19ED6C6e959EB22d8626708e`^]
Verifier address::  link:https://goerli.etherscan.io/address/0x8f97970aC5a9aa8D130d35146F5b59c4aef57963[`0x8f97970aC5a9aa8D130d35146F5b59c4aef57963`^]
Sequencer base URL for API routing:: \https://alpha4.starknet.io

== Starknet Alpha version on Sepolia testnet

The Starknet core contract:: link:https://sepolia.etherscan.io/address/0xE2Bb56ee936fd6433DC0F6e7e3b8365C906AA057[`0xE2Bb56ee936fd6433DC0F6e7e3b8365C906AA057`^]

Verifier address::  link:https://sepolia.etherscan.io/address/0x07ec0D28e50322Eb0C159B9090ecF3aeA8346DFe[`0x07ec0D28e50322Eb0C159B9090ecF3aeA8346DFe`^]
Sequencer base URL for API routing:: \https://alpha-sepolia.starknet.io

== Starknet fee token

The Starknet fee token is currently ETH.

This address is the same for testnet and Mainnet.

l2_token_address:: link:https://starkscan.co/contract/0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7[`0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7`]

== Bridged tokens

The tokens that are currently bridged to Starknet are listed in the following `.json` files:

link:https://github.com/starknet-io/starknet-addresses/blob/master/bridged_tokens/goerli.jsonstarknet-addresses/blob/master/bridged_tokens/mainnet.json[`mainnet.json`^]:: The addresses of the tokens currently bridged to Starknet Mainnet.
https://github.com/starknet-io/starknet-addresses/blob/master/bridged_tokens/goerli.json[`goerli.json`^]:: The addresses of the tokens currently bridged to Starknet Goerli testnet.
https://github.com/starknet-io/starknet-addresses/blob/master/bridged_tokens/sepolia.json[`sepolia.json`^]:: The addresses of the tokens currently bridged to Starknet Sepolia testnet.

Each token has the following parameters:

[horizontal, labelwidth="25"]
Name:: Token name.
Symbol:: Token symbol.
Decimals:: Number of decimal places used to get the user representation.
l1_token_address:: Address of the L1 ERC-20 contract.
l2_token_address:: Address of the L2 ERC-20 contract.
l1_bridge_address:: Address of the L1 bridge contract.
l2_bridge_address:: Address of the L2 bridge contract.
