= Tools for interacting with Starknet

== Starkli
https://github.com/xJonathanLEI/starkli/[Starkli^], developed by https://x.com/xjonathanlei[Jonathan Lei^], is a fast command-line interface for interacting with Starknet. It supports fetching data from the Starknet network, deploying accounts, interacting with contracts, and other useful utilities for developers. 

== Entro
https://github.com/NethermindEth/entro[Entro^] helps decoding and analyzing Starknet transactions and events, including decoding contract ABI and transaction data and getting contract class history, 

== Starknet RPC Request Builder
https://rpc-request-builder.voyager.online/[Starknet RPC Request Builder^] is a useful tool for generating RPC queries for Starknet, with support for basic example for JavaScript, Go, and Rust.

== Walnut
https://walnut.dev/[Walnut^] is a transaction debugger and simulator for Starknet that supports Starknet Mainnet, Starknet Sepolia and Starknet Appchains and includes transaction call trace analysis, visual transaction step by step debugger, and transaction simulator.

== Starknet Deploy
https://github.com/olas-protocol/starknet-deploy[Starknet Deploy^] streamlines the deployment and interaction of Starknet contracts by automatically managing deployments, providing simple methods for contract interactions, and enabling network and account configuration.

== Cainome
https://github.com/cartridge-gg/cainome[Cainome^] is a library for generating bindings from Cairo ABI, abstracting away Cairo serialization and deserialization, and providing a flexible way for different languages to interact with Cairo contracts.