= Tools for interacting with Starknet

== Starkli
https://github.com/xJonathanLEI/starkli/[Starkli^], developed by https://x.com/xjonathanlei[Jonathan Lei^], is a fast command-line interface for interacting with Starknet. It supports fetching data from the Starknet network, deploying accounts, interacting with contracts, and other useful utilities for developers. 

== Starknet SDKs
A Software Development Kit (SDK) is a library that abstracts the complexities of Starknet when building transactions and interacting with the blockchain. SDKs implement the Starknet https://github.com/starkware-libs/starknet-specs[JSON RPC specification^], and are updated to support the latest API changes. There are SDKs for various languages, so you can choose the SDK according to your needs.

[%autowidth]
|===
| Language | Maintainer | Code | Package | Docs | Support  

| JavaScript / TypeScript
| https://x.com/0xSpaceShard[SpaceShard^]
| https://github.com/starknet-io/starknet.js[starknet.js on GitHub^]
| https://www.npmjs.com/package/starknet[starknet.js on NPM^]
| https://www.starknetjs.com/[starknet.js Book^]
| https://discord.gg/starknet-community[starknet.js channel on Starknet Discord^]
 
| Python
| https://x.com/swmansionxyz[Software Mansion^]
| https://github.com/software-mansion/starknet.py[starknet.py on GitHub^]
| https://pypi.org/project/starknet-py/[starknet.py on PyPi^]
| https://starknetpy.rtfd.io/[starknet.py Docs^]
| https://t.me/starknetpy[starknet.py on Telegram^]

| Rust
| https://x.com/xjonathanlei[Jonathan Lei^]
| https://github.com/xJonathanLEI/starknet-rs[starknet-rs on GitHub^]
| https://crates.io/crates/starknet[starknet-rs on Crates^]
| https://github.com/xJonathanLEI/starknet-rs[starknet-rs Docs^] | https://t.me/starknet_rs[starknet-rs on Telegram^]

| Go
| https://x.com/NethermindEth[Nethermind^]
| https://github.com/NethermindEth/starknet.go[starknet.go on GitHub^]
| N/A
| https://pkg.go.dev/github.com/NethermindEth/starknet.go[starknet.go Docs^]
| https://t.me/StarknetGo[starknet.go on Telegram^]

| Java
| https://x.com/swmansionxyz[Software Mansion^]
| https://github.com/software-mansion/starknet-jvm[starknet-jvm on GitHub^]
| https://central.sonatype.com/artifact/com.swmansion.starknet/starknet[starknet-jvm on Maven]
| https://docs.swmansion.com/starknet-jvm/[starknet-jvm Docs^]
| N/A

| Swift
| https://x.com/swmansionxyz[Software Mansion]
| https://github.com/software-mansion/starknet.swift[starknet.swift on GitHub^]
| N/A
| https://docs.swmansion.com/starknet.swift/documentation/starknet/[starknet.swift Docs^]
| N/A

| Dart
| https://x.com/focustree_app[Focustree^]
| https://github.com/focustree/starknet.dart[starknet.dart on GitHub^]
| https://pub.dev/packages/starknet[starknet.dart on Pub^]
| https://starknetdart.dev/[starknet.dart Docs^]
| https://t.me/+CWezjfLIRYc0MDY0[starknet.dart on Telegram^]
|===

== Entro
https://github.com/NethermindEth/entro[Entro^] helps decoding and analyzing Starknet transactions and events, including decoding contract ABI and transaction data and getting contract class history, 

== Starknet RPC Request Builder
https://rpc-request-builder.voyager.online/[Starknet RPC Request Builder^] is a useful tool for generating RPC queries for Starknet, with support for basic example for JavaScript, Go, and Rust.

== Walnut
https://walnut.dev/[Walnut^] is a transaction debugger and simulator for Starknet that supports Starknet Mainnet, Starknet Sepolia and Starknet Appchains and includes transaction call trace analysis, visual transaction step by step debugger, and transaction simulator.

== Starknet Deploy
https://github.com/olas-protocol/starknet-deploy[Starknet Deploy^] streamlines the deployment and interaction of Starknet contracts by automatically managing deployments, providing simple methods for contract interactions, and enabling network and account configuration.

== Cainome
https://github.com/cartridge-gg/cainome[Cainome^] is a library for generating bindings from Cairo ABI, abstracting away Cairo serialization and deserialization, and providing a flexible way for different languages to interact with Cairo contracts.