[id="limits_and_triggers"]
= Current limits

Starknet currently has a number of limits and triggers in place in order to keep the network stable and optimized for best performance.

[NOTE]
====
These are subject to revisions and change on a regular basis
====

.Starknet current limits and triggers
[%header, stripes=even]
[%autowidth.stretch]
|===
|Entity | Description | Sepolia | Goerli (deprecated) | Mainnet
|Block time | The average time it takes for a new block to be created on the Starknet blockchain.|3 minutes |3 minutes |3 minutes
|Block limit (Cairo steps)|Starknet enforces a limit on the number of steps that can be completed
within each block to ensure block production times remain consistent and predictable. | 5,000,000 | 5,000,000 | 5,000,000
|Block limit (gas)| Certain Starknet operations, such as sending messages between L1 and L2, consume Ethereum gas. The current L1 state update
mechanism involves an Ethereum transaction for each Starknet block.

The gas limit for Starknet blocks is therefore inherited from the gas limit for Ethereum blocks.
|5,000,000 |5,000,000 |5,000,000

|Max transaction size (Cairo steps)|The maximum number of computational steps, measured in Cairo steps, that a transaction can contain when processed on the Starknet network.
This limit is important for ensuring the efficient execution of transactions and preventing potential congestion.
| 3,000,000 | 3,000,000 | 3,000,000

|Max Cairo steps for `validate`| The maximum number of computational steps, measured in Cairo steps, for a `validate` function. | 1,000,000 | 1,000,000 |1,000,000

|Max contract bytecode size (No of felts in the program)| The maximum size of the bytecode or program that a smart contract can have on Starknet.

Bytecode is the low-level code that comprises smart contracts. Limiting this size helps manage the complexity of contracts and the overall efficiency of the network.
| 61,440 | 61,440 | 61,440
|Max contract class size|The maximum size for a contract class within Starknet.

Contract classes are a fundamental building block for smart contracts, and limiting their size can have implications for the network's scalability and security.
| 20MB | 20MB | 20MB
|IP address limits (read/write)| In order to reduce network spam, Starknet limits the amount of contract reads and writes that a single IP
address can make. | 200 per min per IP address| 200 per min per IP address|200 per min per IP address
|===

