[id="limits_and_triggers"]
= Current limits and triggers

Starknet alpha currently has a number of limits and triggers in place in  order to keep the network stable and optimized for best performance.

[NOTE]
====
These are subject to revisions and change on a regular basis
====

.Starknet current limits and triggers
[%header, stripes=even]
[%autowidth.stretch]
|===
|Entity | Goerli | Mainnet
|Block time |3 minutes |3 minutes
|Block limit (Cairo steps) | 8M | 8M
|Block limit (gas) |3M |3M
|Max transaction size (Cairo steps)|3M |3M
|Max contract bytecode size (No of felts in the program) | 61440 | 61440
|Max contract class size| 20MB | 20MB
|Mempool size limit | No limitation|1000 transactions
|IP address limits (read) | 100 per min|200 per min
|IP address limits (write)|10 per min / per ip address |10 per min / per ip address
|===

## Block time
The average time it takes for a new block to be created on the Starknet blockchain.

## Block limit (Cairo steps)
The execution of each transaction involves a certain number of computational steps.

Starknet enforces a limit on the number of steps that can be completed
within each block to ensure block production times remain consistent and predictable.

## Block limit (gas)
Certain Starknet operations consume Ethereum gas, e.g L1/L2 messages. The current L1 state update
mechanism involves an Ethereum transaction for each Starknet block.

The gas limit for Starknet blocks is therefore inherited from the gas limit for Ethereum blocks.

[NOTE]
====
The gas limit for Starknet blocks is inherited from the gas limit for Ethereum blocks.
====

## Max transaction size (Cairo steps)
The maximum number of computational steps, measured in Cairo steps, that a transaction can contain when processed on the Starknet network.

This limit is important for ensuring the efficient execution of transactions and preventing potential congestion.

## Max contract bytecode size / Number of felts in the program

The maximum size of the bytecode or program that a smart contract can have on Starknet.

Bytecode is the low-level code that smart contracts are composed of. Limiting this size helps manage the complexity of contracts and the overall efficiency of the network.

## Max contract class size
The maximum size for a contract class within Starknet.

Contract classes are a fundamental building block for smart contracts, and limiting their size can have implications for the network's scalability and security.

## Mempool size limit

// The mempool contains transactions that have undergone preliminary verification by the sequencer and are candidates for inclusion into a block

The mempool contains transactions that have undergone a preliminary verification by the sequencer
and are candidates for inclusion into a block.

// local to the sequencer (each has a mempool)


## IP address limits (read)
In order to reduce network spam, Starknet limits the amount of contract reads that a single IP
address can make.

## IP address limits (write)
In order to reduce network spam, Starknet limits the amount of contract writes that a single IP
address can make.
