= Starknet developer tools overview

To support its unique architecture, Starknet boasts its own xref:#list_of_tools[suite of developer tools] (also known as _devtools_) that aim to streamline the development process for Starknet developers. While sometimes developed in coordination with StarkWare, the majority of these tools are community-driven projects, showcasing the collaborative and innovative spirit of the Starknet ecosystem.

Starknet's xref:core-tools.adoc[core devtools] include Scarb, Starknet Foundry, and Starknet Devnet. For ease of navigation, additional tools are categorized by context, including xref:coding-in-cairo.adoc[tools for coding in Cairo], xref:writing-smart-contracts.adoc[tools for writing smart contract], xref:building-dapps.adoc[tools for building dApps], xref:interacting-with-starknet.adoc[tools for interacting with Starknet], and xref:creating-ai-agents.adoc[tools for creating AI agents].

[NOTE]
====
The list of tools in this section is dynamic and continuously updated. If a tool you are using is missing, please consider opening an issue or editing the page by yourself.
====
