= Starknet tooling overview

To support its unique architecture, Starknet boasts its own suite of developer tools (also known as _devtools_) that aim to streamline the development process for Starknet developers. While sometimes developed in coordination with StarkWare, the majority of these tools are community-driven projects, showcasing the collaborative and innovative spirit of the Starknet ecosystem.

Starknet's core tools include its build toolchain and package manager _Scarb_, smart contract development toolchain _Starknet Foundry_, local node implementation _Starknet Devnet_, and various software development kits (also known as _SDKs_). For ease of navigation, additional tools are categorized by context, including xref:coding-in-cairo.adoc[tools for coding in Cairo], xref:writing-smart-contracts.adoc[tools for writing smart contracts], xref:building-dapps.adoc[tools for building dApps], xref:interacting-with-starknet.adoc[tools for interacting with Starknet], xref:creating-ai-agents.adoc[tools for creating AI agents], and xref:running-devnets[tools for working locally].

[NOTE]
====
The list of tools in this section is dynamic and continuously updated. If a tool you are using is missing, please consider opening an issue or editing the page by yourself.
====
