[id="StarkGate_function_reference"]
= StarkGate API reference

The StarkGate smart contracts include functions that you use to implement various flows in a dApp.

The L1 functions are defined in the following smart contracts:

[horizontal,labelwidth="30"]
link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/IStarkgateManager.sol[IStarkgateManager.sol]:: The StarkGate Manager API
link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/IStarkgateRegistry.sol[IStarkgateRegistry.sol]:: The StarkGate Registry API
link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/StarknetTokenBridge.sol[StarkGateTokenBridge.sol]:: The StarkGate bridge API

== The StarkGate Manager and Registry

StarkGate includes support for ETH and ERC-20 tokens. To see if a token is currently supported, use the L1 function `getBridge`.

// Ask Dan if he can add a feature that shows all currently supported ERC-20 tokens.

You can add support for other tokens by adding bridges for those other tokens, either existing bridges or new ones that StarkGate automatically creates when you try to bridge an unsupported ERC-20 token from Ethereum to Starknet.

The StarkGate Manager is responsible for adding and removing bridges.

The StarkGate Registry contains the addresses to all supported bridges.


Some of the functions in these files are for internal administration use only. This function reference does not describe those functions in detail.

== L1 function reference

Functions are listed in alphabetical order.

[#addExistingBridge]
=== `addExistingBridge`

[discrete]
==== Description
Internal use only.

Adds an existing Starknet bridge to the StarkGate registry.

Does not work for any ERC-20 token bridge's contract address that is already in the registry.

[discrete]
==== State Mutability

#???#

[discrete]
==== Parameters

[horizontal,labelwidth=20]
`token`:: The address of an ERC-20 token contract.
`bridge`:: The address of the corresponding existing ERC-20 token bridge contract.

[discrete]
==== Returns

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/7b967dd0db1019e91b1efb5e530fdef9f025e538/src/solidity/IStarkgateManager.sol#L14C14-L14C31[`addExistingBridge`] in `IStarkgateManager.sol`


[#blockToken]
=== `blockToken`

[discrete]
==== Description

Internal use only.

Blocks a specific token from being used in StarkGate. You cannot deploy a blocked token.

[discrete]
==== State Mutability

#???#

[discrete]
==== Parameters

[horizontal,labelwidth=20]
`token`:: The address of the contract for the desired token.

[discrete]
==== Returns

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateManager.sol#L26[`blockToken`] in `IStarkgateManager.sol`




[#deactivateToken]
=== `deactivateToken`

[discrete]
==== Description

Internal use only.

Deactivates bridging of a specific token.

You cannot redeploy or make deposits to a deactivated token bridge.

[discrete]
==== State Mutability

#???#

[discrete]
==== Parameters

[horizontal,labelwidth=20]
`token`:: The address of the contract for the desired token.

[discrete]
==== Returns

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateManager.sol#L20C20-L20C20[`deactivateToken`] in `IStarkgateManager.sol`



[#enrollTokenBridge]
=== `enrollTokenBridge`

[discrete]
==== Description

Creates a Starknet bridge for the specified ERC-20 token contract address and adds it to the StarkGate registry.

Does not work for any ERC-20 token bridge's contract address that is already in the registry.

[discrete]
==== State Mutability

`payable`

The message payload needs to include funds to cover the Starknet (L2) fee for executing this transaction. For the minimum deployment fee, see link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/StarkgateConstants.sol#L22[MIN_DEPLOYMENT_FEE], part of `StarkgateConstants.sol`.

[discrete]
==== Parameters

[horizontal,labelwidth=20]
`token`:: The address of the contract for the desired token.

[discrete]
==== Returns

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateManager.sol#L31C40-L31C45[enrollTokenBridge]

=== `getBridge`

[discrete]
==== Description

Returns the address of the bridge for the specified token, or a value indicating if the bridge does not exist, is blocked, or deactivated.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth=20]
`tokenAddress`:: The address of the contract for the desired token.

[discrete]
==== Returns

[discrete]
==== Function definition

link:[function_name]

`address`:: The address of the bridge for the specified token.
`Address(0)`:: The bridge does not exist.
`Address(1)`:: The bridge is blocked or deactivated.


[#getWithdrawalBridges]
=== `getWithdrawalBridges`

[discrete]
==== Description

Retrieves a list of all bridge addresses that have ever facilitated withdrawals for the specified token.

In a case where an inactive bridge for a specific token might still have funds locked, you can use this function to identify all bridges that ever serviced that token.

If you used a bridge for a given token that subsequently was replaced with a new or updated bridge, but you still have funds locked on the first bridge, you might not know the address of the old bridge. This function returns

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth=20]
`token`:: The address of the contract for the desired token.

[discrete]
==== Returns

`bridges`:: An array of addresses of all bridges that ever serviced `token`.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateRegistry.sol#L31C1-L31C2[`getWithdrawalBridges`] in `IStarkgateRegistry.sol`.


[#getRegistry]
=== `getRegistry`

[discrete]
==== Description

Internal use only.

Returns the address of the StarkGate Registry contract.

Only the Manager uses this function.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

None

[discrete]
==== Returns

The address of the Registry contract.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/7b967dd0db1019e91b1efb5e530fdef9f025e538/src/solidity/IStarkgateManager.sol#L8C14-L8C14[getRegistry]


[#isServicingToken]
=== `isServicingToken`

[discrete]
==== Description

Checks whether the calling contract is currently providing a service for the specified token.

If `true`, or if `isServicingToken` is not implemented, this function fails and the entire transaction is reverted.

You need to include a function in your bridge that implements `isServicingToken` to check if the bridge is currently servicing any transactions.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth=20]
`token`:: The address of the contract for the desired token.

[discrete]
==== Returns

[horizontal,labelwidth=20]
`true`:: The calling contract is currently providing a service for the token.
`false:: The calling contract is not currently providing a service for the token.

[discrete]
==== Example

In this example, the function `onlyServicingToken` implements the `isServicingToken` API to check if the specified token is currently being serviced. If `isServicingToken` returns `false`,  it outputs `TOKEN_NOT_SERVICED`.

[source,solidity]
----
    modifier onlyServicingToken(address token) {
        require(isServicingToken(token), "TOKEN_NOT_SERVICED");
        _;
    }
----

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateService.sol#L9C14-L9C30[isServicingToken] in `IStarkgateService.sol`.



[#selfRemove]
=== `selfRemove`

[discrete]
==== Description

Use this function to remove enlisting of a specific token bridge from the registry.

The bridge must implement the `isServicingToken` function. For more information, see xref:#isServicingToken[`isServicingToken`]).

If you don’t implement `isServicingToken`, or if it returns `true`, this function fails and the entire transaction is reverted.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth=20]
`token`:: The address of the token bridge contract to remove.

[discrete]
==== Returns

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateRegistry.sol#L37[`selfRemove`] in `IStarkgateRegistry.sol`



// //////////////////////////////////////////////////

== L2 function reference




[#get_erc20_class_hash]
=== `get_erc20_class_hash`

[discrete]
==== Description

Returns the class hash of the implementation used by the ERC-20 contract. Use the class hash as the type when deploying the ERC-20 contract on L2.

Creating a new bridge with xref:#enrollTokenBridge[`enrollTokenBridge`] generates this class hash.

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal]
ClassHash:: The class hash of the ERC-20 token contract.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L637C1-L639C10[`get_erc20_class_hash`] in `token_bridge.cairo`.


[#get_identity]
=== `get_identity`

[discrete]
==== Description

Returns a string in a felt252 type with the identity of StarkGate.

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth=20]
`felt252`:: The identity of StarkGate.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L633[`get_identity`] in `token_bridge.cairo`.






[#get_l1_token_address]
=== `get_l1_token_address`

[discrete]
==== Description

Returns the L1 address that corresponds to the matching L2 address of an ERC-20 token contract.

[discrete]
==== Parameters

[horizontal,labelwidth=20]
l2_token_address:: The L2 address of the ERC-20 token contract.

[discrete]
==== Returns

[horizontal,labelwidth=20]
`ContractAddress`:: The L1 address of the ERC-20 token contract.


[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L642C23-L642C23[`get_l1_token_address`] in `token_bridge.cairo`.



[#get_l2_token_address]
=== `get_l2_token_address`

[discrete]
==== Description

Returns the L2 address that corresponds to the matching L1 address of an ERC-20 token contract.

[discrete]
==== Parameters

[horizontal,labelwidth=20]
l1_token_address:: The L1 address of the ERC-20 token contract.

[discrete]
==== Returns

[horizontal,labelwidth=20]
`ContractAddress`:: The L2 address of the ERC-20 token contract.


[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L647C11-L647C11[`get_l2_token_address`] in `token_bridge.cairo`.




[#get_version]
=== `get_version`

[discrete]
==== Description

Returns the current version of StarkGate.

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal]
`felt252`:: The current version of StarkGate.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L629[`get_version`] in `token_bridge.cairo`.

