= About `depositWithMessage`

With the `depositWithMessage` function, a deposit transaction can trigger subsequent actions. For example, you can deposit funds and include a message to transfer those funds to another address. `+depositWithMessage+` lets you execute these two separate transactions with a single user action.

Upon completion, the `depositWithMessage` function triggers a call to the `on_receive` callback function on the receiving L2 contract. The `on_receive` function receives the deposit message as input, and it must return `true` for the deposit to succeed.

The L2 contract that receives the message that is sent with the `depositWithMessage` function must implement a callback function named `on_receive`.

If `on_receive` returns `false`, or if the receiving contract does not implement `on_receive`,
The `depositWithMessage` L1 handler fails, and the user must recover their funds using the xref:#depositWithMessageCancelRequest[`depositWithMessageCancelRequest`] function.

[discrete]
== Additional resources

* xref:starkgate_function_reference.adoc#depositWithMessageCancelRequest[`depositWithMessageCancelRequest`]
* xref:starkgate_function_reference.adoc#depositWithMessage[`depositWithMessage`]
* xref:starkgate_function_reference.adoc#depositWithMessageReclaim[`depositWithMessageReclaim`]