[id="StarkGate_architecture"]
= StarkGate architecture

In StarkGate, the bridge for each supported token is defined in a corresponding pair of L1 and L2 contracts.

StarkGate includes the following types of bridges:

[horizontal, labelwidth=30]
Multi-token bridge:: An instance of an L1 and L2 ERC-20 contract pair that handles multiple tokens.
+
You can permissionlessly add new tokens to this bridge using the `enrollTokenBridge` function.
+
When you enroll a new token to StarkGate, StarkGate adds the bridge functionality to the `StarknetErc20Bridge.sol` contract on L1, and creates a new ERC-20 token contract on L2 based on a standard ERC-20 contract developed by OpenZeppelin.

Single-token bridge:: For ETH and for ERC-20 tokens supported prior to StarkGate v2.0 #Need to verify version number#, each supported token has its own instance of the pair of L1 and L2 bridge contracts.
+
The single-token bridge enables seamless backward compatibility with the previous version of StarkGate.
+
Each of the following tokens are supported with a single-token bridge:

* ETH
* WBTC
* USDC
* USDT
* DAI
* rETH
* wstETH

To check if a token is currently supported, use the L1 function `getBridge`.

Table xref:#bridge_explanation_table[] describes the two bridge types, including the base contracts for each.


[#bridge_explanation_table]
.Comparison of bridge types
[cols="2,4,4",]
|===
| |Single-token bridge (ERC-20, ETH) |Multi-token bridge (ERC-20)

|*Description* |Each supported token has its own instance of the pair of L1 and L2 bridge contracts. |One instance of an L1 and L2 ERC-20 contract pair that handles multiple tokens.
|*L1 contract* a|
ERC-20:

`StarknetERC20Bridge.sol`,

inherits from `StarknetTokenBridge.sol`


ETH:

`StarknetEthBridge.sol`

a|
One instance of `StarknetERC20Bridge.sol`,

inherits from `StarknetTokenBridge.sol`

|*L2 contract* |One instance of OpenZeppelin’s standard ERC-20 contract: `https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/token/erc20/erc20.cairo[erc20.cairo]`. |One instance of OpenZeppelin’s standard ERC-20 contract: `https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/token/erc20/erc20.cairo[erc20.cairo]`.

|*Supported starting with StarkGate version…* |Prior to StarkGate v2.0 |StarkGate v2.0
|===

// Need to add the Ethereum addresses of these contracts


// Ask Dan if he can add a feature that shows all currently supported ERC-20 tokens.

[#StarkGate_manager_and_registry]
== The StarkGate Manager and Registry

StarkGate includes the following administration components:

[horizontal]
The _StarkGate Manager_:: Is responsible for adding and removing bridges.
The _StarkGate Registry_:: Contains the addresses to all supported bridges.

For information on the functions these components expose, see the xref:starkgate_function_reference.adoc[].

== Additional resources

* xref:starkgate_function_reference.adoc#getBridge[`getBridge`] function in the _StarkGate function reference_
* Standard Open Zeppelin L2 contract link:https://github.com/OpenZeppelin/cairo-contracts/blob/cairo-1/src/openzeppelin/token/erc20/erc20.cairo[`erc20.cairo`] on Github
* L1 contract `StarknetErc20Bridge.sol` on Github
* L1 contract `StarknetEthBridge.sol` on Github
