[id="starkgate_token_bridge"]
= StarkGate bridge overview

StarkGate, developed by StarkWare, bridges ETH and ERC-20 tokens between Ethereum and Starknet. Each supported token is associated with an L1 and L2 bridge contract that communicates via Starknet's messaging mechanism.

To use StarkGate, go to https://starkgate.starknet.io.

A bridge enables you to fund your L2 wallet with ETH and ERC-20 tokens that reside on L1.

The terms _deposit_, _transact_, and _transfer_ refer to various operations involving a bridge, even though ETH and ERC-20 tokens never actually leave Ethereum.

include::partial$snippet_backwards_compatibiity_note.adoc[]

[#starkgate_supported_tokens]
== Supported tokens in StarkGate

In order to reduce the risks involved in using an Alpha version, StarkGate Alpha on Mainnet has limitations regarding the deposit amount and total value locked in the L1 bridge contract:

[%autowidth.stretch,stripes=even]
|===
| Token | Max total value locked

| ETH
| 150,000 ETH

| WBTC
| 200 WBTC

| USDC
| 40,000,000 USDC

| USDT
| 20,000,000 USDT

| DAI
| 5,000,000 DAI

| rETH
| 10,000 rETH

| wstETH
| 5,000 wstETH

|===

[NOTE]
====
StarkWare plans to gradually ease these limitations and lift them completely, as confidence grows.

Changes will be updated here.
====

[id="l1l2_transfer_deposit"]
== L1→L2 transfer (deposit)

[id="step_1_call_the_deposit_function_on_l1"]
=== Step 1: Call the deposit function on L1


. A call to the L1 `deposit` function initates a deposit.
. The function does the following:
+
--
* Checks that the funds transferred are within the Alpha xref:starkgate-bridge.adoc#starkgate_alpha_limitations[limitations].
* Transfers the funds from the user's account to the Starknet bridge.
* Emits a `Deposit` event that includes the L1 and L2 addresses of the user, and the amount deposited.
* Sends a message to the corresponding L2 bridge with the amount deposited, and the recipient's address.
--
+
Starknet's sequencer is now aware of the deposit transaction.

. The sequencer waits for enough L1 block confirmations to fill its quota to run before the corresponding deposit transaction is initiated on L2. During this period of time, the status of the L2 deposit transaction is xref:architecture_and_concepts:Network_Architecture/transaction-life-cycle.adoc#not_received[`NOT_RECEIVED`].

[id="step_2_deposit_triggered_on_starknet"]
=== Step 2: Deposit triggered on Starknet

. The sequencers refer to the deposit
request by triggering the L1 handler using the
https://github.com/starkware-libs/starkgate-contracts/blob/28f4032b101003b2c6682d753ea61c86b732012c/src/starkware/starknet/apps/starkgate/cairo/token_bridge.cairo#L135[`handle_deposit`] function on the L2 bridge.

. The `handle_deposit` function verifies that the deposit indeed came from the corresponding L1 bridge. It then calls the relevant token's contract on Starknet and mints the specified amount of the token on L2 for the user.

. The sequencers complete constructing the block.

The status of the deposit request is now xref:architecture_and_concepts:Network_Architecture/transaction-life-cycle.adoc#accepted_on_l2[`ACCEPTED_ON_L2`].

[id="step_3_the_block_that_includes_the_transfer_is_proved"]
=== Step 3: The block that includes the transfer is proved

. Starknet's provers prove the validity of the block and submit a state update to L1.

. The message confirming transfer of the funds is cleared from the Starknet Core Contract, and the fact that the user has transferred their funds is part of the now finalized state of Starknet.

[NOTE]
====
If the message wasn't on L1 to begin with, that is, if the deposit request was fraudulently created on Starknet, the state update would fail.
====

[id="l2l1_transfer_withdraw"]
== L2→L1 transfer (withdrawal)

[id="step_1_call_the_withdraw_function_on_l2"]
=== Step 1: Initiate a withdrawal from L2

. A call to the L2 `initiate_withdraw` function initiates a withdrawal.
. The function does the following:
* Burns the transferred amount of tokens from the balance of the withdrawal's initiator.
* Sends a message to the relevant L1 bridge with the amount to be transferred and the recipient's address.


[#proving_the_block_that_includes_the_withdrawal_transaction]
=== Step 2: Proving the block that includes the withdrawal transaction

// Once the sequencer completes the block construction, Starknet's provers prove the validity of the block and submit a state update to L1. The message from the previous step is then stored in the Starknet Core Contract.

. The sequencer completes the block construction
. Starknet's provers prove the validity of the block and submit a state update to L1.
. The message from the previous step is stored in the Starknet Core Contract.

[id="step_3_transferring_the_funds_on_l1"]
=== Step 3: Transferring the funds on L1

After the withdrawal message has been recorded on the Starknet Core Contract, anyone can finalize the transfer on L1 from the bridge back to the user, by calling the `withdraw` function.

[NOTE]
====
This step is permissionless, anyone can do it. The recipient's address is part of the recorded message on L1, so they receive the funds regardless of who calls the `withdraw` function on L1.
====

== Additional resources

* xref:architecture_and_concepts:Network_Architecture/messaging-mechanism.adoc[L1-L2 messaging]
* The _StarkGate developer's reference_:
** xref:starkgate_function_reference.adoc#deposit[`deposit` function, `Deposit` event]
** xref:starkgate_function_reference.adoc#withdraw[`withdraw`]
** xref:starkgate_function_reference.adoc#initiate_withdraw[`initiate_withdraw`]
* link:https://github.com/starkware-libs/starkgate-contracts/blob/28f4032b101003b2c6682d753ea61c86b732012c/src/starkware/starknet/apps/starkgate/cairo/token_bridge.cairo#L135[`handle_deposit`] function on the L2 bridge
