[id="con_automated_actions_with_bridging"]
= Performing a Smart Deposit
// please move to be under procedures
A single user action can move funds from L1 to L2 and then trigger subsequent actions. For example, a user can deposit funds and transfer those funds to another recipient, such as an exchange.

To enable this feature in your application, you can use the `depositWithMessage` function. `depositWithMessage` is similar to a `deposit` function, with an additional 256-bit message, which can contain instructions for executing additional actions.

Upon completion, the `depositWithMessage` function triggers a call to a callback function, named `on_receive`, on the receiving L2 contract. The `on_receive` function receives the deposit message as input.

`on_receive` must return `true` for the deposit to succeed. If `on_receive` returns `false`, or if the recipient contract does not include the `on_receive` function, the `depositWithMessage` function's L1 handler fails. The user can recover their funds using the `depositWithMessageCancelRequest` function.

[discrete]
== Additional resources

* xref:starkgate_function_reference.adoc#depositWithMessageCancelRequest[`depositWithMessageCancelRequest`]
* xref:starkgate_function_reference.adoc#depositWithMessage[`depositWithMessage`]
* xref:starkgate_function_reference.adoc#depositWithMessageReclaim[`depositWithMessageReclaim`]
* xref:architecture_and_concepts:Network_Architecture/messaging-mechanism.adoc#l1-l2-messages[L1 handler]

