[id="StarkGate_cancelling_a_deposit"]
= Cancelling a deposit

To ensure self-custody, StarkGate enables you to cancel a deposit if, after depositing funds with the `deposit` function on L1, you don't see your funds appear on L2 within a reasonable amount of time.

You can only cancel a deposit that you yourself deposited.

In order to guard against an attack, it takes approximately five days to cancel a deposit. From the moment StarkGate receives the cancellation request, a counter begins. When exactly five days have passed, and the funds still do not appear on L2, you can reclaim the deposit.


// a deposit, and only before depositReclaim was performed.

// If five days pass and the deposit request has still not been serviced, you can reclaim the deposit.

.Procedure

. To cancel a deposit, call the `depositCancelRequest` request function.
+
When StarkGate receives the cancellation request, a counter begins to count five days.

. When exactly five days have passed, and the funds still do not appear on L2, you can reclaim the deposit by calling `depositReclaim`.

[NOTE]
====
As long as the `depositReclaim` was not performed, the deposit may be processed, even if
the cancellation delay time has already passed.

Only the depositor is allowed to cancel
a deposit, and only before depositReclaim was performed.
====

.Additional resources

* xref:starkgate_dev_reference.adoc#depositCancelRequest[`depositCancelRequest`] in the _StarkGate function reference_.
* xref:starkgate_dev_reference.adoc#depositReclaim[`depositReclaim`] in the _StarkGate function reference_.