[id="StarkGate_function_reference"]
= StarkGate function and event reference
:description: Comprehensive function and event reference for StarkGate.

The StarkGate smart contracts include functions that you use to implement various flows in a dApp.

For information on the movement of funds between Ethereum and Starknet, see xref:starkgate-bridge.adoc[StarkGate bridge overview].

include::partial$snippet_backwards_compatibiity_note.adoc[]

The L1 functions and their interfaces, where available, are defined in the following smart contracts:

[cols=",,",]
|===
|Contract |Name |Functions

|https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarkgateManager.sol[`StarkgateManager.sol`] |The StarkGate Manager.

Use the Manager to enroll a new token.

An interface is available through https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/IStarkgateManager.sol[`IStarkgateManager.sol`]. a| * xref:#enrollTokenBridge[`enrollTokenBridge`]
|https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarkgateRegistry.sol[`StarkgateRegistry.sol`] a|The StarkGate Registry.

Use the Registry to view the addresses of existing bridges and to stop servicing a specific token.

An interface is available through https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/IStarkgateRegistry.sol[`IStarkgateRegistry.sol`].
a| * xref:#getBridge[`getBridge`]
* xref:getWithdrawalBridges[`getWithdrawalBridges`]

|https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol[`StarknetTokenBridge.sol`] |The primary StarkGate bridge contract. The functions and events in this reference that provide the main user bridge functionality are defined in this contract. a|
* xref:#deposit[`deposit`]
* xref:#depositCancelRequest[`depositCancelRequest`]
* xref:#depositReclaim[`depositReclaim`]
* xref:#depositWithMessage[`depositWithMessage`]
* xref:#depositWithMessageCancelRequest[`depositWithMessageCancelRequest`]
* xref:#depositWithMessageReclaim[`depositWithMessageReclaim`]
* xref:#getStatus[`getStatus`]
* xref:#withdraw[`withdraw`]

|https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/IStarkgateService.sol[`IStarkgateService.sol`] | An interface to check if a contract is servicing a token. a|
* xref:#isServicingToken[`isServicingToken`]
|===

The L2 functions and their interfaces, where available, are defined in the following smart contracts:

[cols=",,",]
|===
|Contract |Description |Functions

|https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge.cairo[`token_bridge.cairo`] |The StarkGate bridge implementation on L2. This contract includes the standard functions for a token bridge.

An interface is available through https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge_interface.cairo[`token_bridge_interface.cairo`]. a|
* xref:#get_erc20_class_hash[`get_erc20_class_hash`]
* xref:#get_identity[`get_identity`]
* xref:#get_l1_token[`get_l1_token`]
* xref:#get_l2_token[`get_l2_token`]
* xref:#get_remaining_withdrawal_quota[`get_remaining_withdrawal_quota`]
* xref:#get_version[`get_version`]
* xref:#initiate_withdraw[`initiate_withdraw`]
* xref:#on_receive[`on_receive`]

|===


// Need to add Backward compatibility bridge.

== L1 function reference

Functions are listed in alphabetical order.

'''

[#deposit]
=== `deposit`

[discrete]
==== Description

Deposits the specified amount of an ERC-20 token to the L1 StarkGate bridge contract.

The deposit function does the following:

* Transfers the funds from the caller's account to the Starknet bridge contract
* Emits the `Deposit` event with the sender's address on L1, the recipient's address on L2, and the amount


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`payable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`::
// tag::address_token[]
The address of the contract for the desired token.
// end::address_token[]
`uint256 _amount_`::
// tag::uint256_amount_deposit[]
The amount of the deposit.
// end::uint256_amount_deposit[]
`uint256 _l2Recipient_`::
// tag::uint256_l2Recipient[]
The L2 address of the recipient.
// end::uint256_l2Recipient[]

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`Deposit`

.Event attributes
[horizontal,labelwidth="35",role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`::
include::starkgate_function_reference.adoc[tag=address_token]
`uint256 _amount_`::
include::starkgate_function_reference.adoc[tag=uint256_amount_deposit]
`uint256 indexed _l2Recipient_`::
include::starkgate_function_reference.adoc[tag=uint256_l2Recipient]
`uint256 _nonce_`:: The nonce for the L1 transaction.
`uint256 _fee_`:: The Starknet fee sent with the transaction.

[discrete]
==== Function and event definitions

Contract: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol[`StarknetTokenBridge.sol`]

* Function: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L284[`deposit`]
* Event: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L65[`Deposit`]



'''

[#depositCancelRequest]
=== `depositCancelRequest`

[discrete]
==== Description

Sends a request to StarkGate to cancel a deposit.

You can send a cancellation request if the funds you transfer from L1 to L2 do not appear on L2 within a reasonable amount of time.

In order to guard against an attack on Starknet, it takes approximately five days to cancel a deposit. When StarkGate receives the cancellation request, a counter begins. When exactly five days have passed, and the funds still do not appear on L2, you can reclaim the deposit using the xref:#depositReclaim[`depositReclaim`] function.

The `depositReclaim` function can only be used once for any deposit cancellation request.


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`::
// tag::uint256_l2Recipient[]
The L2 address of the recipient.
// end::uint256_l2Recipient[]
`uint256 _nonce_`::
// tag::uint256_nonce[]
The nonce of the deposit.
// end::uint256_nonce[]

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`DepositCancelRequest`

.Event attributes
[horizontal,labelwidth="30",role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`::
include::starkgate_function_reference.adoc[tag=address_token]
`uint256 _amount_`::
include::starkgate_function_reference.adoc[tag=uint256_amount_deposit]
`uint256 indexed _l2Recipient_`::
include::starkgate_function_reference.adoc[tag=uint256_l2Recipient]
`uint256 _nonce_`::
include::starkgate_function_reference.adoc[tag=uint256_nonce]

[discrete]
==== Function and event definitions

Contract: https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol[`StarknetTokenBridge.sol`]

* Function: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L515[`depositCancelRequest`]
* Event: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L73[`DepositCancelRequest`]


'''

[#depositReclaim]
=== `depositReclaim`

[discrete]
==== Description

Reclaims a deposit after a five day period has passed from the time that StarkGate received a deposit cancellation request from the `depositCancelRequest` function.


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256 _nonce_`:: The nonce of the deposit.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`event DepositReclaimed`

.Event attributes
[horizontal,labelwidth="30",role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`::
include::starkgate_function_reference.adoc[tag=address_token]
`uint256 _amount_`::
include::starkgate_function_reference.adoc[tag=uint256_amount_deposit]
`uint256 indexed _l2Recipient_`::
include::starkgate_function_reference.adoc[tag=uint256_l2Recipient]
`uint256 _nonce_`::
include::starkgate_function_reference.adoc[tag=uint256_nonce]

[discrete]
==== Function and event definitions

Contract: `StarknetTokenBridge.sol`

* Function: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L588[`depositReclaim`]
* Event: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L80[`DepositReclaimed`]

[discrete]
==== See also

* xref:#depositCancelRequest[`depositCancelRequest`]

'''

[#depositWithMessage]
=== `depositWithMessage`

[discrete]
==== Description

Similar to xref:#deposit[`deposit`], with a message attached.

With this function, a deposit transaction can trigger subsequent actions. For example, you can deposit funds and include a message to transfer those funds to another address. `depositWithMessage` lets you execute these two separate transactions with a single user action.

After depositing to another recipient, the L1 handler in `token_bridge.cairo` calls the `on_receive` function in the contract of the recipient.

If `on_receive` returns `true`, then the `on_receive` function succeeded. If it returns `false`, or if it doesn't return any value because the `on_receive` function is not implemented in the recipient contract, the operation fails and the transaction is reverted.

//
// ##----
// fn on_receive(
// self: @ContractState,
// token_address: ContractAddress,
// amount: u256,
// depositor: EthAddress,
// message: Span<felt252>
// ) -> bool {
// ----##

[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`payable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256[] calldata _message_`::
// tag::calldata_message[]
The message attached to the deposit.
// end::calldata_message[]

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`DepositWithMessage`

.Event attributes
[horizontal,role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`::
include::starkgate_function_reference.adoc[tag=address_token]
`uint256 _amount_`::
include::starkgate_function_reference.adoc[tag=uint256_amount_deposit]
`uint256 indexed _l2Recipient_`::
include::starkgate_function_reference.adoc[tag=uint256_l2Recipient]
`uint256[] _message_`::
include::starkgate_function_reference.adoc[tag=calldata_message]
`uint256 _nonce_`:: The nonce for the L1 transaction.
`uint256 _fee_`:: The Starknet fee sent with the transaction.

[discrete]
==== Function and event definitions

Contract: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol[StarknetTokenBridge.sol]

* Function: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L255[`depositWithMessage`]
* Event: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L37[`DepositWithMessage`]


'''


[#Continue review with Roee here#]

[#depositWithMessageCancelRequest]
=== `depositWithMessageCancelRequest`

[discrete]
==== Description

Sends a request to StarkGate to cancel a deposit sent with `depositWithMessage`.

Similar to `depositCancelRequest`.


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256[] calldata _message_`:: The message attached to the deposit.
`uint256 _nonce_`:: The nonce of the deposit.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`DepositWithMessageCancelRequest`

.Event attributes
[horizontal,role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`::
include::starkgate_function_reference.adoc[tag=address_token]
`uint256 _amount_`::
include::starkgate_function_reference.adoc[tag=uint256_amount_deposit]
`uint256 indexed _l2Recipient_`::
include::starkgate_function_reference.adoc[tag=uint256_l2Recipient]
`uint256[] _message_`::
include::starkgate_function_reference.adoc[tag=calldata_message]
`uint256 _nonce_`:: The nonce for the L1 transaction.

[discrete]
==== Function and event definitions

Contract: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol[StarknetTokenBridge.sol]

* Function: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L534[`depositWithMessageCancelRequest`]
* Event: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L46[`DepositWithMessageCancelRequest`]

[discrete]
==== See also

* xref:#depositWithMessage[`depositWithMessage`]
* xref:#depositCancelRequest[`depositCancelRequest`]



'''

[#depositWithMessageReclaim]
=== `depositWithMessageReclaim`

[discrete]
==== Description

Sends a request to StarkGate to cancel a deposit sent with `depositWithMessage`.

Similar to `depositCancelRequest`.

Reclaims a deposit sent with a message after a five day period has passed from the time that StarkGate received a deposit cancellation request from the `depositWithMessageCancelRequest` function.


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256 _nonce_`:: The nonce of the deposit.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`DepositWithMessageCancelRequest`

.Event attributes
[horizontal,role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`::
include::starkgate_function_reference.adoc[tag=address_token]
`uint256 _amount_`::
include::starkgate_function_reference.adoc[tag=uint256_amount_deposit]
`uint256 indexed _l2Recipient_`::
include::starkgate_function_reference.adoc[tag=uint256_l2Recipient]
`uint256[] _message_`::
include::starkgate_function_reference.adoc[tag=calldata_message]
`uint256 _nonce_`:: The nonce for the L1 transaction.

[discrete]
==== Function and event definitions

Contract: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol[StarknetTokenBridge.sol]

* Function: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L564[`depositWithMessageReclaim`]
* Event: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L54[`DepositWithMessageReclaimed`]

[discrete]
==== See also

* xref:#depositCancelRequest[`depositCancelRequest`]
* xref:#depositReclaim[`depositReclaim`]
* xref:depositWithMessageCancelRequest[`depositWithMessageCancelRequest`]


'''

[#enrollTokenBridge]
=== `enrollTokenBridge`

[discrete]
==== Description

Creates a Starknet bridge for the specified ERC-20 token contract address in the multi-token bridge contracts and adds the token to the StarkGate Registry.

Does not work for any ERC-20 token bridge's contract address that is already in the registry.

Enrolling a new bridge creates a new ERC-20 contract on L2. You can see the class hash for this contract using xref:#get_erc20_class_hash[`get_erc20_class_hash`].

include::partial$snippet_enrollTokenBridge_note.adoc[]


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`payable`

The message payload needs to include funds to cover the Starknet (L2) fee for executing this transaction. You can include this payload using a standard wrapper such as web3.js.

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired ERC-20 token.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`TokenEnrollmentInitiated`

[discrete]
==== Function and event definition

* Function: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarkgateManager.sol#L132[`enrollTokenBridge`] in `StarkgateManager.sol`
* Event: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L34[`TokenEnrollmentInitiated`] in `StarknetTokenBridge.sol`


'''


[#estimateDepositFeeWei]
=== `estimateDepositFeeWei`

[discrete]
==== Description

Returns an estimate of the fee, in Wei, for depositing funds to the L1 StarkGate bridge contract.

[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`uint256`:: An estimate of the fee, in Wei, for depositing funds to the L1 StarkGate bridge contract.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L142C28-L142C28[`estimateDepositFeeWei`] in `StarknetTokenBridge.sol`

[discrete]
==== Additional resources

* xref:#deposit[`deposit`]
* xref:#depositWithMessage[`depositWithMessage`]

'''

[#estimateEnrollmentFeeWei]
=== `estimateEnrollmentFeeWei`

[discrete]
==== Description

Returns an estimate of the fee, in Wei, for creating and registering a new bridge using the `enrollTokenBridge` function.

[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`uint256`:: An estimate of the fee, in Wei, for creating and registering a new bridge.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L146[`estimateEnrollmentFeeWei`] in `StarknetTokenBridge.sol`

[discrete]
==== Additional resource

* xref:#enrollTokenBridge[`enrollTokenBridge`]

'''

[#getBridge]
=== `getBridge`

[discrete]
==== Description

Returns the address of the bridge for the specified token, or a value indicating if the bridge does not exist, is blocked, or is deactivated.


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired ERC-20 token.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`address _address_`:: The address of the bridge for the specified token.
`Address(0)`:: The bridge does not exist.
`Address(1)`:: The bridge is blocked or deactivated.

[discrete]
==== Emitted event

None.
[discrete]
==== Function definition


link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/IStarkgateRegistry.sol#L8[`getBridge`] in `IStarkgateRegistry.sol`


'''

[#getRegistry]
=== `getRegistry`

[discrete]
==== Description

Returns the address of the StarkGate Registry contract.

Only the Manager uses this function.


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

None

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`address`:: The address of the Registry contract.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarkgateManager.sol#L24[`getRegistry`] in `StarkgateManager.sol`



'''

[#getStatus]
=== `getStatus`

[discrete]
==== Description

Returns the status of a token in StarkGate.

`deploy` transaction triggered by the `enrollTokenBridge` API.


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired ERC-20 token.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`TokenStatus`:: One of the following values:
+
[horizontal]
0::: Unknown. The bridge does not recognize the token.
1::: Pending. The token has been enrolled to StarkGate, but the `deploy` transaction has not yet successfully completed. You can deposit funds.
2::: Active. The `deploy` transaction for this token has completed successfully and StarkGate recognizes the token.
3::: Deactivated. The token has been removed from StarkGate. You cannot deposit funds.

[discrete]
==== Emitted event

None.


[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L198C23-L198C23[`getStatus`] in `StarknetTokenBridge.sol`



'''

[#getWithdrawalBridges]
=== `getWithdrawalBridges`

[discrete]
==== Description

Retrieves a list of all bridge addresses that have ever facilitated withdrawals for the specified token.

In a case where an inactive bridge for a specific token might still have funds locked, you can use this function to identify all bridges that ever serviced that token.

If you used a bridge for a given token that subsequently was replaced with a new or updated bridge, but you still have funds locked on the first bridge, you might not know the address of the old bridge. This function returns


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.

[discrete]
==== Returns

[horizontal,labelwidth="30",role=stripes-odd]
`address[] memory _bridges_`:: An array of addresses of all bridges that ever serviced `token`.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarkgateRegistry.sol#L110[`getWithdrawalBridges`] in `StarkgateRegistry.sol`.



'''
[#identify]
=== `identify`

[discrete]
==== Description

Returns the name and version of the `StarknetTokenBridge.sol` contract.


[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`pure`

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`string _memory_`:: The name and version of the `StarknetTokenBridge.sol` contract.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition
link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L92[`identify`] in `StarknetTokenBridge.sol`

'''

[#isServicingToken]
=== `isServicingToken`

[discrete]
==== Description

Checks whether the calling contract is currently providing a service for the specified token.

[discrete]
==== Visibility

`external`

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`true`:: The calling contract is currently providing a service for the token.
`false`:: The calling contract is not currently providing a service for the token.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/IStarkgateService.sol#L9C14-L9C30[`isServicingToken`] in `IStarkgateService.sol`.

'''

[#withdraw]
=== `withdraw`

[discrete]
==== Description

Transfers the specified amount of the specified token to the address of the recipient specified in the `l1_recipient` parameter of the `initiate_token_withdraw` function on L2.

Anyone can call this function, but only after the withdraw message has been recorded on the Starknet Core Contract.

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`::
// tag::uint256_amount_withdrawal[]
The amount of the withdrawal.
// end::uint256_amount_withdrawal[]
`address _recipient_`::
(Optional)
// tag::address_recipient[]
The recipient.
// end::address_recipient[]
If you don't specify this parameter, the withdraw function uses the sender's address.

[discrete]
==== State mutability

`nonpayable`

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`Withdrawal`

.Event attributes
[horizontal,role=stripes-odd]
`address indexed _recipient_`::
include::starkgate_function_reference.adoc[tag=address_recipient]
`address indexed _token_`::
include::starkgate_function_reference.adoc[tag=address_token]
`uint256 _amount_`::
include::starkgate_function_reference.adoc[tag=uint256_amount_withdrawal]

[discrete]
==== Function and event definition

Contract: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol[`StarknetTokenBridge.sol`]

* Function: link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L481[`withdraw`]
* Event: https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/solidity/StarknetTokenBridge.sol#L62[`Withdrawal`]

== L2 function reference

Functions are listed in alphabetical order.

'''
[#get_erc20_class_hash]
=== `get_erc20_class_hash`

[discrete]
==== Description

Returns the current class hash of the implementation used by the ERC-20 contract. Use the class hash as the type when deploying the ERC-20 contract on L2.

[IMPORTANT]
====
If StarkWare changes the class hash such that it is no longer the class hash that you used when deploying your bridge contract, this function returns the new class hash. If you want to refer to the class hash that you used when deploying your contract, see your deployed contract on Starknet.
====

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`ClassHash`:: The class hash of the ERC-20 token contract.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge.cairo#L376-L378[`get_erc20_class_hash`] in `token_bridge.cairo`.

'''

[#get_identity]
=== `get_identity`

[discrete]
==== Description

Returns a string in a felt252 type with the identity of StarkGate.

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`felt252`:: The identity of StarkGate.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge_interface.cairo#L8[`get_identity`] in `token_bridge_interface.cairo`.




'''

[#get_l1_token]
=== `get_l1_token`

[discrete]
==== Description

Returns the L1 address that corresponds to the matching L2 address of an ERC-20 token contract.

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`_l2_token_address_: ContractAddress`:: The L2 address of the ERC-20 token contract.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`EthAddress`:: The L1 address of the ERC-20 token contract.
`EthAddressZeroable::zero()`:: The token is not found in the bridge.


[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge_interface.cairo#L9[`get_l1_token`] in `token_bridge_interface.cairo`.



'''
[#get_l2_token]
=== `get_l2_token`

[discrete]
==== Description

Returns the L2 address that corresponds to the matching L1 address of an ERC-20 token contract.

If the token is not found in the bridge, this function returns `0`.

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`l1_token_address`:: The L1 address of the ERC-20 token contract.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`ContractAddress _address_`:: The L2 address of the ERC-20 token contract.
`ContractAddressZeroable::zero()`:: The token is not found in the bridge.



[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge_interface.cairo#L10[`get_l2_token`] in `token_bridge_interface.cairo`.


'''

[#get_remaining_withdrawal_quota]
=== `get_remaining_withdrawal_quota`

[discrete]
==== Description

Returns the amount that the user can withdraw within the current 24-hour time period. The time period begins at 00:00 UTC.

[discrete]
==== Parameters

[horizontal,labelwidth="25",role=stripes-odd]
`l1_token_address`:: The L1 address of the ERC-20 token contract.

[discrete]
==== Returns

[horizontal,labelwidth="25",role=stripes-odd]
`u256`:: The amount that can currently be withdrawn from the bridge, in units defined by the ERC-20 token contract.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge_interface.cairo#L11[`get_remaining_withdrawal_quota`] in `token_bridge_interface.cairo`




'''

[#get_version]
=== `get_version`

[discrete]
==== Description

Returns the current version of StarkGate.

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="25",role=stripes-odd]
`felt252`:: The current version of StarkGate.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge_interface.cairo#L7[`get_version`] in `token_bridge_interface.cairo`.


'''

[#initiate_withdraw]
=== `initiate_withdraw`

[discrete]
==== Description

Initiates a withdrawal from L2. After initiating the withdrawal, the function does the following:

. Burns the transferred amount of tokens from the balance of the withdrawal’s initiator.
. Sends a message to the relevant L1 bridge with the amount to be transferred, and the recipient's address.

[discrete]
==== Parameters

[horizontal,labelwidth="25",role=stripes-odd]
`l1_recipient`:: The L1 address of the recipient.
`EthAddress _token_`:: The L1 address of the ERC-20 token contract.
`uint256 _amount_`:: The amount to transfer.

[discrete]
==== Returns

None.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/token_bridge_interface.cairo#L12[`initiate_withdraw`] in `token_bridge_interface.cairo`.



'''

[#on_receive]
=== `on_receive`

[discrete]
==== Description

An interface to an implementation of the `on_receive` function that you must provide in your L2 contract in order to enable the `depositWithMessage` function to succeed.

// When calling the `depositWithMessage` function, the resulting transaction triggers an `on_receive` function that you need to implement in your application.
//
The L2 contract that receives the message that is sent with the `depositWithMessage` function must implement a callback function named `on_receive`.

Upon completion, the `depositWithMessage` function triggers a call to the `on_receive` callback function on the receiving L2 contract. The `on_receive` function receives the deposit message as input, and it must return `true` for the deposit to succeed.

If `on_receive` returns `false`, or if the receiving contract does not implement `on_receive`, the `depositWithMessage` L1 handler fails, and the user can only recover their funds using the xref:#depositWithMessageCancelRequest[`depositWithMessageCancelRequest`] function.

[discrete]
==== Parameters

[horizontal,labelwidth="35",role=stripes-odd]
`_l2_token_: ContractAddress`:: The L2 address of the ERC-20 token contract.
`_amount_: uint256`:: The amount deposited.
`_depositor_`: EthAddress:: L1 address of the deposit sender.
`_message_: Span<felt252>`:: The message that was sent with the `depositWithMessage` function.

[discrete]
==== Returns

[horizontal,labelwidth="25",role=stripes-odd]
`true`:: The `on_receive` function completed successfully.
`false`:: The `on_receive` function did not complete successfully. The transaction is reverted.
// The recipient L2 contract of the `depositWithMessage` function does not accept the funds on L2.
No value:: If the recipients's smart contract does not implement the `on_receive` function, the call fails to execute, and the transaction is reverted.

[discrete]
==== Function definition

link:https://github.com/starknet-io/starkgate-contracts/tree/v2.0.1/src/cairo/receiver_interface.cairo#L6[`on_receive`] in `receiver_interface.cairo`.
