[id="withdrawing-funds-with-starkgate"]
= Withdrawing funds with StarkGate

:description: How to use StarkGate to withdraw funds from Starknet using a function in a block explorer, and what happens when you use StarkGate to withdraw funds.

Using StarkGate to withdraw funds from Starknet requires StarkGate's `initiate_token_withdraw` function to initiate a withdrawal. The function does the following:

* Burns the transferred amount of tokens from the L2 balance of the withdrawal's initiator.
* Sends a message to the relevant L1 bridge with the amount to be transferred and the recipient's Ethereum address.

Subsequently, the funds should be transferred to the recipent's Ethereum address.

For more information on what happens during the transfer process, see xref:starkgate-bridge.adoc#l2l1_transfer_withdraw[L2->L1 transfer (withdrawal)].

.Prerequisites

* A Starknet block explorer. For a list of Starknet block explorers, see link:https://www.starknet.io/en/ecosystem/block-explorers-indexers-and-enhanced-api[Block explorers, indexers & Enhanced API] on the Starknet site.
* Funds to transfer from L2 to L1, including enough to pay the fees required for the transfer.
* The L2 address of the StarkGate bridge for the token you want to withdraw. To view the token addresses for tokens on Mainnet or Sepolia testnet, see xref:tools:bridged_tokens.adoc[].

.Procedure

. Using a Starknet block explorer, go to the StarkGate contract for the token you want to withdraw. For example, to withdraw USDC:
+
* If using Voyager, go to the link:https://voyager.online/contract/0x05cd48fccbfd8aa2773fe22c217e808319ffcc1c5a6a463f7d8fa2da48218196[USDC StarkGate bridge] and click *Write Contract*.
* If using StarkScan, go to the link:https://starkscan.co/contract/0x05cd48fccbfd8aa2773fe22c217e808319ffcc1c5a6a463f7d8fa2da48218196[USDC StarkGate bridge] and click menu:Read/Write Contract[Write].
. Click the `initiate_token_withdraw` function and enter the following:
+
* In *l1_token*, enter the L1 address of the ERC-20 contract for the token you want to withdraw, in this case, USDC.
* In *`l1_recipient`*, enter the L1 address of the recipient.
* In *`amount`*, enter the amount to transfer.
. Click *Transact* for Voyager, or *Write* for StarkScan. The function initiates a withdrawal.

#How long should it take until you see the funds in your L1 account?#
