[id="StarkGate_architecture"]
= StarkGate architecture

While StarkGate is referred to as _a bridge_, technically, each supported token has its own bridge, each of which is defined in a corresponding pair of L1 and L2 contracts, as described in xref:#bridge_explanation_table[].

.Components of a bridge for an individual token
[#bridge_explanation_table]
[cols='1,8']
|===
| *L1*
a|
* ERC-20 contract that defines the token on Ethereum. This contract must exist before you can bridge it.
* Bridge functionality for ERC-20 tokens is supported in `StarknetTokenBridge.sol`.
| *L2*
a|
* StarkGate Cairo bridge contract instance of the `token_bridge.cairo`contract class.
* ERC-20 Cairo token contract instance of a standard ERC-20 Cairo token contract class. Each new contract uses the hash of this class to define its inheritance. StarkGate creates this contract automatically when creating the bridge in StarkGate.
|===

// Need to add the Ethereum addresses of these contracts
StarkGate provides a contract that enables seamless backward compatibility with the previous version of StarkGate.

You can check if a token is currently supported with the L1 function `getBridge`.

// Ask Dan if he can add a feature that shows all currently supported ERC-20 tokens.

You can permissionlessly add support for ERC-20 tokens to the multi-token bridge using the `enrollTokenBridge` function.

When you enroll a new ERC-20 token, StarkGate does the following:

. Adds bridge functionality for that token on L1 using the `StarknetTokenBridge.sol` contract.
. Adds bridge functionality for that token on L2 using the `token_bridge.cairo` class.
. Creates a new ERC-20 token contract on L2 based on a standard ERC-20 contract class. Each new contract uses the class hash of this contract class to identify its inheritance.
+
[NOTE]
====
When the code of `token_bridge.cairo` is updated, its class hash changes. However,any existing contract continues to refer to the previous class hash. Any new contracts use the new class hash.
====

[#StarkGate_manager_and_registry]
== The StarkGate Manager and Registry

StarkGate includes the following administration components:

// [horizontal]
The _StarkGate Manager_:: is responsible for adding bridges
The _StarkGate Registry_::
* contains the addresses to all supported bridges
* enables a bridge developer to stop servicing an existing bridge


== Additional resources

The xref:starkgate_function_reference.adoc[_StarkGate function reference_]. Lists functions exposed by the Registry, Manager, and the bridge itself, including:

* xref:starkgate_function_reference.adoc#getBridge[`getBridge`]
* xref:starkgate_function_reference.adoc#enrollTokenBridge[`enrollTokenBridge`]
* L1 contracts on Github
* L2 contracts on Github