[id="StarkGate_architecture"]
= StarkGate architecture

StarkGate includes the following types of bridges:

[horizontal, labelwidth=30]
Multi-token bridge:: An instance of an L1 and L2 ERC-20 contract pair that handles multiple tokens.
Single bridge:: Each single bridge is an instance of an L1 and L2 ERC-20 contract pair that handles a single token. Each token that was supported prior to the latest release uses a single bridge. Each of the following tokens are supported with a single bridge:
+
* ETH
* WBTC
* USDC
* USDT
* DAI
* rETH
* wstETH

[#multi_token_bridge]
== Multi-token bridge (ERC-20 only)

The multi-token bridge is a pair of L1 and L2 contracts. This bridge type handles multiple ERC-20 tokens.

[discrete]
=== L1 base token contract

`StarknetErc20Bridge.sol`, which inherits from `StarknetTokenBridge.sol`.

[discrete]
=== L2 base token contract

The standard Open Zeppelin L2 contract link:https://github.com/OpenZeppelin/cairo-contracts/blob/cairo-1/src/openzeppelin/token/erc20/erc20.cairo[`erc20.cairo`]

== Single

This bridge is an instance of the L1 contract `StarknetErc20Bridge.sol`, together with an instance of the standard Open Zeppelin L2 contract link:https://github.com/OpenZeppelin/cairo-contracts/blob/cairo-1/src/openzeppelin/token/erc20/erc20.cairo[`erc20.cairo`].
StarkGate uses the L1 bridge contract `StarknetErc20Bridge.sol`, as the contract upon which it bases both the multi-token bridge and all ERC-20 single bridges, and `StarknetEthBridge.sol` for the ETH single bridge. Each single bridge has a separate instantiation of the base contract. The multi-token bridge is a single instantiation of this contract, with support for multiple tokens.


Users can permissionlessly add new tokens to this bridge using the `enrollTokenBridge` function. For more information, see xref:starkgate_function_reference.adoc#enrollTokenBridge[`enrollTokenBridge`].

== Single-bridge

The implementation is similar to that of the multi-token bridge, but each instance of the bridge contract supports only one token. This type of bridge enables seamless backward compatibility with the previous version of StarkGate.

StarkGate uses the L1 bridge contract `StarknetErc20Bridge.sol`, as the contract upon which it bases both the multi-token bridge and all ERC-20 single bridges, and `StarknetEthBridge.sol` for the ETH single bridge. Each single bridge has a separate instantiation of the base contract. The multi-token bridge is a single instantiation of this contract, with support for multiple tokens.

When you enroll a new token to StarkGate, StarkGate adds the bridge functionality to the `StarknetErc20Bridge.sol` contract on L1, and creates a new ERC-20 token contract on L2 based on a standard ERC-20 contract developed by OpenZeppelin.

StarkGate uses the L1 bridge contract `StarknetEthBridge.sol` for ETH.

// Need to add the Ethereum addresses of these contracts


StarknetErc20Bridge.sol is the class, and that the multi-token bridge and all the single ERC-20 bridges are instantiations of this class. StarknetTokenBridge.sol is not the multi-token bridge, but rather the original contract from which StarknetErc20Bridge.sol inherits.

All existing token bridges that StarkGate currently supports continue to be supported each in its own pair of contracts.

StarkGate includes support for ETH and ERC-20 tokens. To see if a token is currently supported, use the L1 function xref:#getBridge[`getBridge`].

// Ask Dan if he can add a feature that shows all currently supported ERC-20 tokens.

You can add support for other tokens by adding bridges for those other tokens, either existing bridges or new ones that StarkGate automatically creates when you try to bridge an unsupported ERC-20 token from Ethereum to Starknet.


== The StarkGate Manager and Registry

StarkGate includes the following administration components:

[horizontal]
The _StarkGate Manager_:: Is responsible for adding and removing bridges.
The _StarkGate Registry_:: Contains the addresses to all supported bridges.

For information on the functions these components expose, see the xref:starkgate_function_reference.adoc[].

== Single bridges

The following tokens are supported using a single bridge:

* ETH
* WBTC
* USDC
* USDT
* DAI
* rETH
* wstETH
