[id="starknet_book"]
= About the Starknet Book

The link:https://book.starknet.io[Starknet Book] serves as a comprehensive guide to understanding Starknet, Cairo, and introduces you to the Starknet ecosystem.

The Starknet Book caters to various objectives and interests. Mix and match these chapters to customize your learning experience based on your unique interests and requirements. Whether you're exploring smart contract development, frontend integration, or learning about the core architecture, The Starknet Book is your trusted companion on the journey of deepening your understanding of Starknet.

== Table of Contents

[cols="1,3"]
|===
| Chapter | Description 

| Chapter 1 
|*Introduction to Starknet and Cairo*

How to quickly get started with Starknet and Cairo development.
| Chapter 2 
|*Starknet tooling*

An overview of the available tooling for Starknet.
| Chapter 3 
|*Starknet architecture*

Learn how Starknet works under the hood. Learn how sequencer, prover and nodes interact.

| chapter 4 
| *Account abstraction*

Account abstraction is one of the main usability features of Starknet. Learn how this works and how you can utilize it.


|===
