[id="StarkGate_architecture"]
= StarkGate architecture

While StarkGate is referred to as _a bridge_, technically, each supported token has its own bridge, each of which is defined in a corresponding pair of L1 and L2 contracts, as described in xref:#bridge_explanation_table[].

.Components of a bridge for an individual token
[#bridge_explanation_table]
[cols='1,8']
|===
| *L1*
a|
* ERC-20 contract that defines the token on Ethereum. This contract must exist before you can bridge it.
* Bridge functionality for ERC-20 tokens is supported in `StarknetTokenBridge.sol`.
| *L2*
a|
* StarkGate Cairo bridge contract instance of the `token_bridge.cairo` contract class.
* ERC-20 Cairo token contract instance of a standard ERC-20 Cairo token contract class. Each new contract uses the hash of this class to define its inheritance. StarkGate creates this contract automatically when creating the bridge in StarkGate.
|===

// Need to add the Ethereum addresses of these contracts

include::partial$snippet_backwards_compatibiity_note.adoc[]

You can check if a token is currently supported with the L1 function `getBridge`.

// Ask Dan if he can add a feature that shows all currently supported ERC-20 tokens.

You can permissionlessly add support for ERC-20 tokens to the multi-token bridge using the `enrollTokenBridge` function.

[#StarkGate_manager_and_registry]
== The StarkGate Manager and Registry

StarkGate includes the following administration components:

// [horizontal]
The _StarkGate Manager_:: is responsible for adding bridges
The _StarkGate Registry_::
* contains the addresses to all supported bridges
* enables a bridge developer to stop servicing an existing bridge

[#legacy_bridge]
== Legacy bridges

All token bridges that existed prior to StarkGate 2.0 (Mainnet: January 2024) besides supporting all StarkGate 2.0 functionality, are backwards-compatible. For tokens bridged prior to StarkGate 2.0, each token was bridged with a unique pair of L1 and L2 bridge contracts. The L1 bridge is an instance of LegacyBridge.sol, and the L2 bridge is an instance of legacy_bridge_eic.cairo. For example, USDT...
Go to StarkGate USDC on Etherscan: https://etherscan.io/address/0xf6080d9fbeebcd44d89affbfd42f098cbff92816#writeProxyContract

Notice that there are two Deposit functions. This shows that the bridge includes support for the legacy functionality as well as the modern functionality.  The one that says *Support Legacy ABI* does not have the `token (address)` parameter. Because the contract that contains this function only supports USDC, having the address of the token is superfluous. On the other hand, the StarkGate 2.0 version puts that token together with all other tokens, so it's necessary to state the address of the token in the deposit function.

Legacy tokens:




#Add a l=#ist of all legacy bridges


[#stark_gate_withdrawal_limit]
== Withdrawal limit

By default, StarkGate imposes no limit on withdrawals. However, in order to mitigate risks associated with critical vulnerabilities that could result in the loss of user funds, StarkGate can enable a withdrawal limit.

If a serious security issue arises, the security agent in the StarkGate contract can limit withdrawals to 5% of the Total Value Locked (TVL) per day for any affected token by calling the `setWithdrawLimitPCT()` function in the `WithdrawalLimit.sol` contract. A dedicated team can then investigate and resolve the issue.

Only a security admin quorum can disable the withdrawal limit. The quorum will consist of Starknet Foundation members, Starknet ecosystem contributors, and StarkWare representatives. This diverse group will ensure that decisions reflect the Starknet community's broad interests.

This approach, blending manual oversight with automated detection, aims to minimize potential losses.


== Additional resources

* xref:starkgate-adding_a_token.adoc[]

* The xref:starkgate_function_reference.adoc[_StarkGate function reference_]. Lists functions exposed by the Registry, Manager, and the bridge itself, including:
** xref:starkgate_function_reference.adoc#getBridge[`getBridge`]
** xref:starkgate_function_reference.adoc#enrollTokenBridge[`enrollTokenBridge`]
** L1 contracts on GitHub
** L2 contracts on GitHub
// Awaiting final URL.
// * link:https://github.com/starknet-io/starkgate-contracts/blob/d62a255307d2f3de65665f18316766a2c69ead78/src/solidity/WithdrawalLimit.sol#L20[`setWithdrawLimitPCT`] in `WithdrawalLimit.sol`
