[id="StarkGate_function_reference"]
= StarkGate API reference

The StarkGate smart contracts include functions that you use to implement various flows in a dApp.

The L1 functions and their interfaces, where available, are defined in the following smart contracts:

[horizontal,labelwidth="30"]
link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/IStarkgateManager.sol[`IStarkgateManager.sol`]:: The StarkGate Manager API
link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/StarkgateManager.sol[`StarkgateManager.sol`]:: The StarkGate Manager implementation
link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/IStarkgateRegistry.sol[`IStarkgateRegistry.sol`]:: The StarkGate Registry API
link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/StarkgateRegistry.sol[`StarkgateRegistry.sol`]:: The StarkGate Registry implementation
link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/StarknetTokenBridge.sol[`StarknetTokenBridge.sol`]:: The StarkGate multi-token bridge implementation. You can use the functions in this contract to implement all currently supported single bridges, such ETH and USDC.

// Need to add Backward compatibility bridge.

The L2 functions and their interfaces, where available, are defined in the following smart contracts:

[horizontal,labelwidth="30"]
link:https://github.com/starkware-libs/starkgate/blob/dev/src/cairo/token_bridge.cairo[`token_bridge.cairo`]:: The StarkGate multi-token bridge implementation on L2.
link:https://github.com/starkware-libs/starkgate/blob/dev/src/cairo/token_bridge_interface.cairo[`token_bridge_interface.cairo`]:: The StarkGate multi-token bridge interface on L2.


== The StarkGate Manager and Registry

StarkGate includes support for ETH and ERC-20 tokens. To see if a token is currently supported, use the L1 function xref:#getBridge[`getBridge`].

// Ask Dan if he can add a feature that shows all currently supported ERC-20 tokens.

You can add support for other tokens by adding bridges for those other tokens, either existing bridges or new ones that StarkGate automatically creates when you try to bridge an unsupported ERC-20 token from Ethereum to Starknet.

The _StarkGate Manager_ is responsible for adding and removing bridges.

The _StarkGate Registry_ contains the addresses to all supported bridges.

StarkGate includes the following types of bridges, where each type has a corresponding smart contract:

[horizontal,labelwidth=30]
Multi-token bridge:: The multi-token bridge contract handles multiple tokens. Users can permissionlessly add new tokens to StarkGate using the `enrollTokenBridge` API. For more information, see xref:#enrollTokenBridge[`enrollTokenBridge`] below.
Single-bridge:: The implementation is similar to that of the multi-token bridge, but each bridge contract implements only one token. This type of bridge enables seamless backward compatibility with the previous version of StarkGate.
Custom bridge:: A bridge provider can write their own custom bridge and contact StarkWare to add it to StarkGate. This type of bridge can enable functionality beyond what the `enrollTokenBridge` API provides.

Some of the functions in these files are for internal administration use only. This function reference does not describe those functions in detail.

== L1 function reference

Functions are listed in alphabetical order.

'''
[#addExistingBridge]
=== `addExistingBridge`

[discrete]
==== Description
_Internal use only._

Adds an existing Starknet bridge to the StarkGate registry.

Does not work for any ERC-20 token bridge's contract address that is already in the registry.

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of an ERC-20 token contract.
`address _bridge_`:: The address of the corresponding existing ERC-20 token bridge contract.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/7b967dd0db1019e91b1efb5e530fdef9f025e538/src/solidity/IStarkgateManager.sol#L14C14-L14C31[`addExistingBridge`] in `IStarkgateManager.sol`



'''

[#blockToken]
=== `blockToken`

[discrete]
==== Description

_Internal use only._

Blocks a specific token from being used in StarkGate. You cannot deploy a blocked token.

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateManager.sol#L26[`blockToken`] in `IStarkgateManager.sol`


'''

[#deactivateToken]
=== `deactivateToken`

[discrete]
==== Description

_Internal use only._

Deactivates bridging of a specific token.

You cannot redeploy or make deposits to a deactivated token bridge.

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateManager.sol#L20C20-L20C20[`deactivateToken`] in `IStarkgateManager.sol`



'''

[#deposit]
=== `deposit`

[discrete]
==== Description

Deposits the specified amount of an ERC-20 token to the L1 StarkGate bridge contract.

The deposit function does the following:

* Checks that the funds transferred are within the xref:starkgate-bridge.adoc#starkgate_alpha_limitations[Starknet Alpha limitations]
* Transfers the funds from the caller's account to the Starknet bridge contract
* Emits the `Deposit` event with the sender's address on L1, the recipient's address on L2, and the amount

[discrete]
==== State Mutability

`payable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`Deposit`

.Event attributes
[horizontal,role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`:: Same as the `address _token_` parameter.
`uint256 _amount_`:: Same as the `uint256 _amount_` parameter.
`uint256 indexed _l2Recipient_`:: Same as the `uint256 _l2Recipient_` parameter.
`uint256 _nonce_`:: The nonce for the L1 transaction.
`uint256 _fee_`:: The Starknet fee sent with the transaction.

[discrete]
==== Function and event definitions

Contract: link:https://github.com/starkware-libs/starkgate/blob/2f96bca50cc6203645b419a890b4a066d617a1cd/src/solidity/StarknetTokenBridge.sol[`StarknetTokenBridge.sol`]

* Function: link:https://github.com/starkware-libs/starkgate/blob/2f96bca50cc6203645b419a890b4a066d617a1cd/src/solidity/StarknetTokenBridge.sol#L290[`deposit`]
* Event: link:[`Deposit`]



'''

[#depositCancelRequest]
=== `depositCancelRequest`

[discrete]
==== Description

Sends a request to StarkGate to cancel a deposit.

You can send a cancellation request if the funds you transfer from L1 to L2 do not appear on L2 within a reasonable amount of time.

In order to guard against an attack on Starknet, it takes approximately five days to cancel a deposit. When StarkGate receives the cancellation request, a counter begins. When exactly five days have passed, and the funds still do not appear on L2, you can reclaim the deposit using the xref:#depositReclaim[`depositReclaim`] function.

The `depositReclaim` function can only be used once for any deposit cancellation request.

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256 _nonce_`:: The nonce of the deposit.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`DepositCancelRequest`

.Event attributes
[horizontal,labelwidth="30",role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`:: Same as the `address _token_` parameter.
`uint256 _amount_`:: Same as the `uint256 _amount_` parameter.
`uint256 indexed _l2Recipient_`:: Same as the `uint256 _l2Recipient_` parameter.
`uint256 _nonce_`:: Same as the `uint256 _nonce_` parameter.

[discrete]
==== Function and event definitions

Contract: https://github.com/starkware-libs/starkgate/blob/2f96bca50cc6203645b419a890b4a066d617a1cd/src/solidity/StarknetTokenBridge.sol[`StarknetTokenBridge.sol`]

* Function: link:https://github.com/starkware-libs/starkgate/blob/2f96bca50cc6203645b419a890b4a066d617a1cd/src/solidity/StarknetTokenBridge.sol#L531[`depositCancelRequest`]
* link:https://github.com/starkware-libs/starkgate/blob/94056402acf7eb97458fac2d6e33372ce193c3f0/src/solidity/StarknetTokenBridge.sol#L74[`DepositCancelRequest`]


'''

[#depositReclaim]
=== `depositReclaim`

[discrete]
==== Description

Reclaims a deposit after a five day period has passed from the time that StarkGate received a deposit cancellation request from the `depositCancelRequest` function.

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256 _nonce_`:: The nonce of the deposit.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`event DepositReclaimed`

.Event attributes
[horizontal,labelwidth="30",role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`:: Same as the `address _token_` parameter.
`uint256 _amount_`:: Same as the `uint256 _amount_` parameter.
`uint256 indexed _l2Recipient_`:: Same as the `uint256 _l2Recipient_` parameter.
`uint256 _nonce_`:: Same as the `uint256 _nonce_` parameter.

[discrete]
==== Function and event definitions

Contract: `StarknetTokenBridge.sol`

* Function: link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L604[`depositReclaim`]
* Event: link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L81C11-L81C27[`DepositReclaimed`]

[discrete]
==== See also

* xref:#depositCancelRequest[`depositCancelRequest`]

'''

[#depositWithMessage]
=== `depositWithMessage`

[discrete]
==== Description

Similar to xref:#deposit[`deposit`], with a message attached.

With this function, a deposit transaction can trigger subsequent actions. For example, you can deposit funds and include a message to transfer those funds to another address. `depositWithMessage` lets you execute these two separate transactions with a single user action.

After I deposit to another recipient, the L1 handler calls the `on_receive` function in the contract of the recipient.

#What is _the_ L1 handler? Is there only one? I don't see anything about `on_receive` in the docs, so I don't really understand fully.#

#If `on_receive` returns `true`, then all is well. If it returns `false`, the transaction is reverted.#

##----
fn on_receive(
self: @ContractState,
token_address: ContractAddress,
amount: u256,
depositor: EthAddress,
message: Span<felt252>
) -> bool {
----##

#Which contract has this function?#
[discrete]
==== State Mutability

`payable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256[] calldata _message_`:: The message attached to the deposit.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`DepositWithMessage`

.Event attributes
[horizontal,role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`:: Same as the `address _token_` parameter.
`uint256 _amount_`:: Same as the `uint256 _amount_` parameter.
`uint256 indexed _l2Recipient_`:: Same as the `uint256 _l2Recipient_` parameter.
`uint256[] _message_`:: Same as the `uint256[] calldata _message_` parameter.
`uint256 _nonce_`:: The nonce for the L1 transaction.
`uint256 _fee_`:: The Starknet fee sent with the transaction.

[discrete]
==== Function and event definitions

Contract: link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/StarknetTokenBridge.sol[StarknetTokenBridge.sol]

* Function: link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L261[`depositWithMessage`]
* Event: link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L37[`DepositWithMessage`]


'''

'''
'''
'''

[#Continue review with Roee here#]

[#depositWithMessageCancelRequest]
=== depositWithMessageCancelRequest

[discrete]
==== Description

Sends a request to StarkGate to cancel a deposit sent with `depositWithMessage`.

Similar to `depositCancelRequest`.

[discrete]
==== State mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256[] calldata _message_`:: The message attached to the deposit.
`uint256 _nonce_`:: The nonce of the deposit.

[discrete]
==== Returns

None.

[discrete]
==== Event emitted

`DepositWithMessageCancelRequest`

.Event attributes
[horizontal,role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`:: Same as the `address _token_` parameter.
`uint256 _amount_`:: Same as the `uint256 _amount_` parameter.
`uint256 indexed _l2Recipient_`:: Same as the `uint256 _l2Recipient_` parameter.
`uint256[] _message_`:: Same as the `uint256[] calldata _message_` parameter.
`uint256 _nonce_`:: The nonce for the L1 transaction.

[discrete]
==== Function and event definitions

Contract: link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/StarknetTokenBridge.sol[StarknetTokenBridge.sol]

* Function: link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L550[`depositWithMessageCancelRequest`]
* Event: link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L550[`DepositWithMessageCancelRequest`]

[discrete]
==== See also

* xref:#depositWithMessage[`depositWithMessage`]
* xref:#depositCancelRequest[`depositCancelRequest`]



'''

[#depositWithMessageReclaim]
=== depositWithMessageReclaim

[discrete]
==== Description

Sends a request to StarkGate to cancel a deposit sent with `depositWithMessage`.

Similar to `depositCancelRequest`.

Reclaims a deposit sent with a message after a five day period has passed from the time that StarkGate received a deposit cancellation request from the `depositWithMessageCancelRequest` function.

[discrete]
==== State Mutability

`nonpayable`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.
`uint256 _amount_`:: The amount of the deposit.
`uint256 _l2Recipient_`:: The L2 address of the recipient.
`uint256 _nonce_`:: The nonce of the deposit.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`DepositWithMessageCancelRequest`

.Event attributes
[horizontal,role=stripes-odd]
`address indexed _sender_`:: The L1 address of the account that sent the deposit.
`address indexed _token_`:: Same as the `address _token_` parameter.
`uint256 _amount_`:: Same as the `uint256 _amount_` parameter.
`uint256 indexed _l2Recipient_`:: Same as the `uint256 _l2Recipient_` parameter.
`uint256[] _message_`:: Same as the `uint256[] calldata _message_` parameter.
`uint256 _nonce_`:: The nonce for the L1 transaction.

[discrete]
==== Function and event definitions

Contract: link:https://github.com/starkware-libs/starkgate/blob/dev/src/solidity/StarknetTokenBridge.sol[StarknetTokenBridge.sol]
Function: link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L580[`depositWithMessageReclaim`]
Event: link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L54[`DepositWithMessageReclaimed`]

[discrete]
==== See also

* xref:#depositCancelRequest[`depositCancelRequest`]
* xref:#depositReclaim[`depositReclaim`]
* xref:depositWithMessageCancelRequest[`depositWithMessageCancelRequest`]


'''

[#enrollTokenBridge]
=== `enrollTokenBridge`

[discrete]
==== Description

Creates a Starknet bridge for the specified ERC-20 token contract address in the multi-token bridge contracts and adds the token to the StarkGate registry.

Does not work for any ERC-20 token bridge's contract address that is already in the registry.

Enrolling a new bridge creates a class hash. You can see the value of this hash using xref:#get_erc20_class_hash[`get_erc20_class_hash`].

include::partial$snippet_enrollTokenBridge_note.adoc[]

[discrete]
==== State Mutability

`payable`

The message payload needs to include funds to cover the Starknet (L2) fee for executing this transaction. You can include this payload using a standard wrapper such as web3.js.

For the minimum deployment fee, see link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/StarkgateConstants.sol#L22[`MIN_DEPLOYMENT_FEE`] in `StarkgateConstants.sol`.

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired ERC-20 token.

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

`TokenEnrollmentInitiated`

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateManager.sol#L31C40-L31C45[`enrollTokenBridge`] in `IStarkgateManager.sol`


'''

[#getBridge]
=== `getBridge`

[discrete]
==== Description

Returns the address of the bridge for the specified token, or a value indicating if the bridge does not exist, is blocked, or deactivated.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _tokenAddress_`:: The address of the contract for the desired ERC-20 token.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`address _address_`:: The address of the bridge for the specified token.
`Address(0)`:: The bridge does not exist.
`Address(1)`:: The bridge is blocked or deactivated.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/ce53961e124c3f8a5e73e9ec2a7f4dcbc1ab6ab9/src/solidity/IStarkgateRegistry.sol#L8[`getBridge`] in `IStarkgateRegistry.sol`


'''

[#getRegistry]
=== `getRegistry`

[discrete]
==== Description

_Internal use only._

Returns the address of the StarkGate Registry contract.

Only the Manager uses this function.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

None

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`address`:: The address of the Registry contract.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/7b967dd0db1019e91b1efb5e530fdef9f025e538/src/solidity/IStarkgateManager.sol#L8C14-L8C14[`getRegistry`] in `IStarkgateManager.sol`



'''

[#getStatus]
=== `getStatus`

[discrete]
==== Description

Returns the status of the `deploy` transaction triggered by the `enrollTokenBridge` API.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired ERC-20 token.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`TokenStatus`:: One of the following values: +
* `Unknown`
* `Pending`
* `Active`
* `Deactivated`


[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/757a461fd998f7e2909e8e71031b419d257da3ed/src/solidity/StarknetTokenBridge.sol#L203C23-L203C23[`getStatus`] in `StarknetTokenBridge.sol`



'''

[#getWithdrawalBridges]
=== `getWithdrawalBridges`

[discrete]
==== Description

Retrieves a list of all bridge addresses that have ever facilitated withdrawals for the specified token.

In a case where an inactive bridge for a specific token might still have funds locked, you can use this function to identify all bridges that ever serviced that token.

If you used a bridge for a given token that subsequently was replaced with a new or updated bridge, but you still have funds locked on the first bridge, you might not know the address of the old bridge. This function returns

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`address[] memory _bridges_`:: An array of addresses of all bridges that ever serviced `token`.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateRegistry.sol#L31C1-L31C2[`getWithdrawalBridges`] in `IStarkgateRegistry.sol`.



'''
[#identify]

[discrete]
==== Description

Returns the name and version of the `StarknetTokenBridge.sol` contract.

[discrete]
==== State Mutability

`pure`

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`string _memory_`:: The name and version of the `StarknetTokenBridge.sol` contract.

[discrete]
==== Function definition
link:https://github.com/starkware-libs/starkgate/blob/2f96bca50cc6203645b419a890b4a066d617a1cd/src/solidity/StarknetTokenBridge.sol#L89[`identify`] in `StarknetTokenBridge.sol`



'''

[#isServicingToken]
=== `isServicingToken`

[discrete]
==== Description

Checks whether the calling contract is currently providing a service for the specified token.

If `true`, or if `isServicingToken` is not implemented, this function fails and the entire transaction is reverted.

You need to include a function in your bridge that implements `isServicingToken` to check if the bridge is currently servicing any transactions.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the contract for the desired token.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`true`:: The calling contract is currently providing a service for the token.
`false`:: The calling contract is not currently providing a service for the token.

[discrete]
==== Example

In this example, the function `onlyServicingToken` implements the `isServicingToken` API to check if the specified token is currently being serviced. If `isServicingToken` returns `false`,  it outputs `TOKEN_NOT_SERVICED`.

[source,solidity]
----
    modifier onlyServicingToken(address token) {
        require(isServicingToken(token), "TOKEN_NOT_SERVICED");
        _;
    }
----

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateService.sol#L9C14-L9C30[`isServicingToken`] in `IStarkgateService.sol`.

'''

[#selfRemove]
=== `selfRemove`

[discrete]
==== Description

Use this function to remove enlisting of a specific token bridge from the registry.

The bridge must implement the `isServicingToken` function. For more information, see xref:#isServicingToken[`isServicingToken`]).

If you don’t implement `isServicingToken`, or if it returns `true`, this function fails and the entire transaction is reverted.

[discrete]
==== State Mutability

`view`

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`:: The address of the token bridge contract to remove.

[discrete]
==== Returns

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/solidity/IStarkgateRegistry.sol#L37[`selfRemove`] in `IStarkgateRegistry.sol`



'''

[#withdraw]
=== `withdraw`

[discrete]
==== Description

Transfers the specified amount of the specified token to the address of the recipient specified in the `l1_recipient` parameter of the `initiate_token_withdraw` function on L2.

Anyone can call this function, but only after the withdraw message has been recorded on the Starknet core contract.

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`address _token_`::
`uint256 _amount_`::

[discrete]
==== State mutability

`nonpayable`

[discrete]
==== Returns

None.

[discrete]
==== Emitted event

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/44c63434782e45d476622924ec004526f6fe64a0/src/solidity/StarknetTokenBridge.sol#L517C11-L517C11[`withdraw`] in `StarknetTokenBridge.sol`


== L2 function reference

Functions are listed in alphabetical order.

'''
[#get_erc20_class_hash]
=== `get_erc20_class_hash`

[discrete]
==== Description

Returns the class hash of the implementation used by the ERC-20 contract. Use the class hash as the type when deploying the ERC-20 contract on L2.

Creating a new bridge with xref:#enrollTokenBridge[`enrollTokenBridge`] generates this class hash.

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`ClassHash`:: The class hash of the ERC-20 token contract.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L637C1-L639C10[`get_erc20_class_hash`] in `token_bridge.cairo`.

'''

[#get_identity]
=== `get_identity`

[discrete]
==== Description

Returns a string in a felt252 type with the identity of StarkGate.

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`felt252`:: The identity of StarkGate.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L633[`get_identity`] in `token_bridge.cairo`.




'''

[#get_l1_token_address]
=== `get_l1_token_address`

[discrete]
==== Description

Returns the L1 address that corresponds to the matching L2 address of an ERC-20 token contract.

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`_l2_token_address_: ContractAddress`:: The L2 address of the ERC-20 token contract.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`ContractAddress`:: The L1 address of the ERC-20 token contract.


[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L642C23-L642C23[`get_l1_token_address`] in `token_bridge.cairo`.



'''
[#get_l2_token_address]
=== `get_l2_token_address`

[discrete]
==== Description

Returns the L2 address that corresponds to the matching L1 address of an ERC-20 token contract.

[discrete]
==== Parameters

[horizontal,labelwidth="20",role=stripes-odd]
`l1_token_address`:: The L1 address of the ERC-20 token contract.

[discrete]
==== Returns

[horizontal,labelwidth="20",role=stripes-odd]
`ContractAddress`:: The L2 address of the ERC-20 token contract.


[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L647C11-L647C11[`get_l2_token_address`] in `token_bridge.cairo`.




'''

[#get_remaining_withdrawal_quota]
=== `get_remaining_withdrawal_quota`

[discrete]
==== Description

Returns the amount that the user can withdraw within the current 24 hour time period. The time period begins at 00:00 UTC.

[discrete]
==== Parameters

[horizontal,labelwidth="25",role=stripes-odd]
`l1_token_address`:: The L1 address of the ERC-20 token contract.

[discrete]
==== Returns

[horizontal,labelwidth="25",role=stripes-odd]
`u256`:: The amount that can currently be withdrawn from the bridge, in units defined by the ERC-20 token contract.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/894d822a33fd5aa2b8469606d2d6e363ff06bb2c/src/cairo/token_bridge_interface.cairo#L14C15-L14C15[`get_remaining_withdrawal_quota`] in `token_bridge_interface.cairo`




'''

[#get_version]
=== `get_version`

[discrete]
==== Description

Returns the current version of StarkGate.

[discrete]
==== Parameters

None.

[discrete]
==== Returns

[horizontal,labelwidth="25",role=stripes-odd]
`felt252`:: The current version of StarkGate.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/f060fd5d1ca49a0014dbcb0777a0c084c12f41d2/src/cairo/token_bridge.cairo#L629[`get_version`] in `token_bridge.cairo`. #Should this be token_bridge_interface.cairo?#


'''

[#initiate_withdraw]
=== `initiate_withdraw`

[discrete]
==== Description

Initiates a withdrawal from L2. After initiating the withdrawal, the function does the following:

. Burns the transferred amount of tokens from the balance of the withdrawal’s initiator.
. Sends a message to the relevant L1 bridge with the amount to be transferred, and the recipient's address.

[discrete]
==== Parameters

[horizontal,labelwidth="25",role=stripes-odd]
`l1_recipient`:: The L1 address of the recipient.
`token`:: The L1 address of the ERC-20 token contract.
`amount`:: The amount to transfer. +
#Would it be helpful to add the type here (not just here, but in all parameters and return values)? Or it enough to supply to link to the function in the contract?#

[discrete]
==== Returns

None.

[discrete]
==== Function definition

link:https://github.com/starkware-libs/starkgate/blob/894d822a33fd5aa2b8469606d2d6e363ff06bb2c/src/cairo/token_bridge_interface.cairo#L18[`initiate_withdraw`] in `token_bridge_interface.cairo`.
