= Tools for writing Starknet smart contracts

[#starknet-foundry]
== Starknet Foundry

https://github.com/foundry-rs/starknet-foundry[Starknet Foundry^] is the go-to toolchain for developing Starknet smart contracts, which includes:

* `snforge`, a command line interface that enables using of various "cheatcodes" for testing various aspects of the contracts, such as setting caller address, manipulating the timestamp and block number, forking the chain at a specific block, getting accurate gas and resource reports, profiling and more.

* `sncast`, a command line interface with Starknet Foundry projects that enable to interact with Starknet with deep integration, including declaring, deploying, and interacting with contracts, deploying accounts, and more.

[#starknet-remix-plugin]
== Starknet Remix plugin

https://remix-project.org[Remix^] is a browser-based integrated development environment (IDE) for Ethereum that you can use for learning, experimenting and finding vulnerabilities in smart contracts, without installing anything. https://github.com/NethermindEth/starknet-remix-plugin[Starknet Remix plugin^] lets you use Remix for testing Starknet smart contracts, so you can focus on learning Cairo and Starknet in the comfort of your browser. The plugin is also integrated with https://starknet-by-example.voyager.online/[Starknet By Example^], a rich repository of practical learning content.

[#open-zeppelin-contract-wizard]
== Open Zeppelin Contract Wizard

https://wizard.openzeppelin.com/cairo[Open Zeppelin Contract Wizard^] is a tool that helps you create smart contracts with Open Zeppelin libraries by easily toggling on and off features for popular smart contract patterns.