[id="deploying_new_accounts"]
= Deploying a new account

The `DEPLOY_ACCOUNT` transaction deploys new accounts to the network.

Upon receiving a `DEPLOY_ACCOUNT` transaction, the sequencer performs the following steps:

. Verifies that the address has funds to pay for the deployment.
. Executes the constructor with the given arguments.
. Executes the `+__validate_deploy__+` entry point. For more information, see xref:#validate_deploy[].
. Charges fees from the new account address.
. Sets the account's nonce to `1`.

*To create and deploy a new account*, you can use Starkli's `starkli account` command.

For more information, see link:https://book.starkli.rs/accounts[Accounts] in the Starkli Book.
For information on how to starkli to create and deploy a new account.

// After the deployment has completed successfully, it is recommended to validate the account deployment using .

[#DEPLOY_ACCOUNT_restrictions]
== `DEPLOY_ACCOUNT` constructor restrictions

The constructor of the `DEPLOY_ACCOUNT` transaction has the following limitations:

* Restricted access to `sequencer_address` in the `get_execution_info` syscall. The syscall returns zero values for `sequencer_address`
* Restricted access to the following syscalls:
** `get_block_hash` for Cairo contracts
** `get_sequencer_address` for Cairo 0 contracts

[#validate_deploy]
== Validation of a `DEPLOY_ACCOUNT` transaction

A `DEPLOY_ACCOUNT` transaction automatically tells the sequencer to call the `+__validate_deploy__+` function, which validates the transaction.

[NOTE]
====
When creating a new account without the `DEPLOY_ACCOUNT` transaction, such as by invoking the Universal Deployer Contract (UDC) with an `INVOKE` transaction, the sequencer calls the `+__validate__+` function, which validates the `INVOKE` transaction.
====

== Limitations of validation

The limitations listed here apply to:

* `+__validate__+`
* `+__validate_deploy__+`
* `+__validate_declare__+`
* A constructor, when run in a `DEPLOY_ACCOUNT` transaction. That is, if an account is deployed from an existing class via the `deploy` syscall, the constructor can run differently.

The sequencer automatically calls:

* `+__validate_deploy__+` when executing a `DEPLOY_ACCOUNT` transaction
* `+__validate__+` when executing an `INVOKE` transaction
* `+__validate_declare__+` when executing a `DECLARE` transaction

The requirement to pass validate_deploy after the constructor execution as a prerequisite for charging fees solves 1, and the limitations on validate execution [link to the new limitation section I suggested above] solves 2.


By automatically calling these validation functions, the sequencer avoids the following potential issues:

* Sequencers can charge arbitrarily high fees, potentially draining user funds from a pre-funded account.
* A bad actor can carry out a Denial of Service (DoS) attack on the sequencer by sending multiple, invalid `DEPLOY_ACCOUNT` transactions, which would result in the sequencer not being compensated for work completed.

//  the constructor and `+__validate_deploy__+` executions



The following limitations on validation prevent the potential issues above:

* Limited number of Cairo steps.
* Limited number of times a builtin can be applied.
* External contract calls are not allowed. Library calls and self-calls are allowed.

// Include the `+__validate_deploy__+` entrypoint in any accounts or contracts that can enable deploying a new account.

== `+__validate_deploy__+`

Validates a `DEPLOY_ACCOUNT` transaction.

[discrete]
=== Parameters

[horizontal,labelwidth="35",role="stripes-odd"]
`class_hash: _felt_`:: The class hash.
`contract_address_salt: _felt_`:: The contract address salt.
`<__constructor_arguments__>`:: The arguments expected by the contract’s constructor. The compiler enforces this constructor.

[NOTE]
====
In determining the contract address, the deployer address `0x0` is used.
====

[discrete]
=== Example
Consider an account with the following constructor signature:

The signature of `+__validate_deploy__+` must be:

[#call_validate_deploy]
[source,cairo,sub="quotes"]
----
  fn __validate_deploy__(
      self: @ComponentState<TContractState>,
      class_hash: felt252,
      contract_address_salt: felt252,
      public_key: felt252
  ) -> felt252

#[constructor]
fn constructor(ref self: ContractState, public_key: felt252)
----

[NOTE]
====
You can access the transaction hash and value for `max_fee` with the `get_tx_info` system call.
====
