[id="deploying_new_accounts"]
= Deploying a new account

You can deploy a new account in the following ways:

* Send a `DEPLOY_ACCOUNT` transaction. This method does not require a preexisting account.
* Include the `deploy` syscall in the account contract, such as by invoking the Universal Deployer Contract (UDC) with an `INVOKE` transaction. This method requires an existing account to send the `INVOKE` transaction.

Upon receiving one of these transactions, the sequencer performs the following steps:

. Verifies that the address has funds to pay for the deployment.
. Executes the constructor with the given arguments.
. Runs the respective validation function in the contract, as follows:
** When deploying with the `DEPLOY_ACCOUNT` transaction type, the sequencer executes the `+__validate_deploy__+` function in the contract.
** When deploying with the `INVOKE` transaction type and a contract that includes the `deploy` syscall, such as the UDC, the sequencer executes the `+__validate__+` function in the contract.
. Charges fees from the new account address.
. Sets the account's nonce to `1`.

== Deploying an account

Starkli simplifies account creation.

.Prerequisites

* Starkli is installed.
* The deployed contract must include a `+__validate_deploy__+` entrypoint.

.Procedure

To create and deploy a new account, use Starkli's `starkli account` command.

For more information on creating a new account as a Starknet wallet account with a `DEPLOY_ACCOUNT` transaction, or by using the UDC with an `INVOKE` transaction , see link:https://book.starkli.rs/accounts[Accounts] in the Starkli Book.

[#DEPLOY_ACCOUNT_restrictions]
== `DEPLOY_ACCOUNT` constructor restrictions

The constructor of the `DEPLOY_ACCOUNT` transaction has the following limitations:

* Restricted access to `sequencer_address` in the `get_execution_info` syscall. The syscall returns zero values for `sequencer_address`
* Restricted access to the following syscalls:
** `get_block_hash` for Cairo contracts
** `get_sequencer_address` for Cairo 0 contracts