= Devtools for building Starknet dApps

[#scaffold-stark]
== Scaffold-Stark
https://scaffoldstark.com/[Scaffold-Stark^] is built using NextJS, Starknet.js, Scarb, Starknet-React, Starknet Foundry and Typescript, and designed to make it easier for developers to create, deploy and interact with smart contracts.

[#starknet-scaffold]
== Starknet Scaffold
https://www.starknetscaffold.xyz/[Starknet-Scaffold^] is an open-source, up-to-date toolkit for building decentralized applications on Starknet, that help you move from prototyping to production-grade apps seamlessly.

// [#libs-for-dapps]
// === dApps Libraries

Decentralized applications are at the heart of Starknet. These libraries help developers build Dapps on Starknet and connect to prominent Starknet wallets.

[#starknet-react]
== Starknet React
https://github.com/apibara/starknet-react[Starknet React^], developed by Apibara using starknet.js, is a wagmi-inspired collection of React hooks for Starknet.

[#get-starknet]
== Get Starknet
https://github.com/starknet-io/get-starknet[Get Starknet^] is a Starknet wallet<>dApp connection bridge, that enables easy discovery and UI for Starknet wallets, including ArgentX, Braavos, Metamask Snaps, and OKx.

[#starknetkit]
== Starknetkit
https://www.starknetkit.com/[Starknetkit] is a Starknet wallet connection kit, built by Argent using Starknet.js and starknet-react.