= Command-line tools

[#starkli]
== starkli

Starkli is a fast command-line interface for interacting with the Starknet network. It supports fetching data from the Starknet network, deploying accounts, and interacting with contracts. Developed by https://x.com/xjonathanlei[Jonathan Lei].
Starkli also includes useful utilities for developers, such as:

* Compute class hashes from the Cairo file that defines the class.
* Compute a function’s selector.
* Encode messages.
* Deploying new accounts or fetching existing accounts
* Submitting multi-calls to your account

[discrete]
=== Relevant links

* GitHub: link:https://github.com/xJonathanLEI/starkli/[starkli on GitHub]
* Documentation: link:https://book.starkli.rs/[Starkli Book]

* link:https://medium.com/starknet-edu/starkli-the-new-starknet-cli-86ea914a2933[Starkli: The New Starknet CLI], on Medium, includes information on getting started, including installation instructions.

[#sncast]
== sncast
Starknet Cast, part of the Starknet Foundry suite, is a command line tool for interacting with the Starknet network, with deep integration with xref:tools:devtools/smart-contract-tools.adoc#starknet_foundry[Starknet Foundry] projects.

* link:https://foundry-rs.github.io/starknet-foundry/starknet/index.html[Starknet Cast Docs]
