= Devtools for coding in Cairo

[#scarb]
== Scarb

https://github.com/software-mansion/scarb[Scarb^] is much more than a package manager for Cairo: It is the easiest and most recommended way to build and maintain Cairo code. Developed by Software Mansion and inspired by Cargo for Rust, Scarb includes:

* Initiating a new Cairo project.
* Compiling Cairo projects.
* Adding and removing Cairo dependencies.
* Generating Cairo documentation.
* Fetching and uploading packages link:https://scarbs.xyz/[Scarbs.xyz], the Cairo Registry.
* Integrating with the Cairo language server, as well as other tools in the Cairo ecosystem, such as Starknet Foundry and the Dojo gaming engine.

[#vs-code-cairo-extension]
== VS Code Cairo extension

https://marketplace.visualstudio.com/items?itemName=starkware.cairo1[VS Code Cairo extension^] is an extension for the Microsoft Visual Studio (VS) Code IDE that provides assistance when writing Cairo smart contracts, including live diagnostic highlighting for compile errors, quick fixes with suggestions, code formatting and completion, and more. It integrates with Scarb, and works best when Scarb is installed via `asdf`.

[#usc]
== Universal-Sierra-Compiler
https://github.com/software-mansion/universal-sierra-compiler[Universal-Sierra-Compiler^] is a utility tool for compiling single Sierra files (unlike Scarb, which compiles full projects) from any Sierra version into CASM.

[NOTE]
====
Universal-Sierra-Compiler comes bundled with Starknet Foundry and does not need to be installed separately if Starknet Foundry is installed.
====

[#cairo-profiler]
== cairo-profiler
https://github.com/software-mansion/cairo-profiler[cairo-profiler^] is a utility tool that can be used to create profiles of Cairo executions from execution traces, which can be analyzed and used to show flame graphs and other useful information.

[NOTE]
====
cairo-profiler comes bundled with Starknet Foundry and does not need to be installed separately if Starknet Foundry is installed.
====

[#cairo-playground]
== Cairo Playground

https://www.cairo-lang.org/cairovm/[Cairo Playground^] an online tool that can be used to both experiment with Cairo without deploying a smart contract on Starknet, as well as dive deep into the Cairo virtual machine.

[#sierra-analyzer] 
== Sierra Analyzer

https://github.com/FuzzingLabs/sierra-analyzer[Sierra Analyzer^], developed by https://x.com/fuzzinglabs[FuzzingLabs^] is a security toolkit for analyzing Sierra files, including decompiling a Sierra file, printing the contract's control flow graph, and running static analysis detectors.

== Cairo lint

https://github.com/software-mansion/cairo-lint[Cairo lint^] is a collection of lints that can either be used as either a library or as a standalone binary to help both detect and fix common mistakes and improve your Cairo code.

