[#devnets]
= Local Development nodes

A Starknet devnet is a local Starknet node implementations, aimed for testing and development. A devnet behaves just like a real Starknet node, but everything is executed locally. This enables much faster and more private development of Starknet applications.


[#starknet-devnet-rs]
== starknet-devnet-rs

starknet-devnet-rs can is a Rust implementation of a local Starknet node. Developed by SpaceShard.

With starknet-devnet-rs includes many featured tailored for testing and development, which are not present on testnet/mainnet.
Some of the features include:

* Pre-deployed and pre-funded accounts
* Forking the chain at a specific block.
* Dumping current state (and loading in future runs)
* Impersonating account
* Mock L1<>L2 communication

[discrete]
=== Relevant links

* GitHub: link:https://github.com/0xSpaceShard/starknet-devnet-rs[starknet-devnet-rs on GitHub]
* Crates: link:https://crates.io/crates/starknet-devnet[starknet-devnet-rs on Crates]
* Documentation: link:https://0xspaceshard.github.io/starknet-devnet-rs/[starknet-devnet-rs Docs]
* Support: devnet channel on link:https://discord.gg/starknet-community[Starknet Discord]

[#katana]
== Katana

Katana, developed by the link:https://x.com/cartridge_gg[Dojo team], is an extremely fast devnet designed to support local development with Dojo, which is a gaming engine for Starknet. You can use Katana as a general purpose devnet as well.

[discrete]
=== Relevant links

* GitHub: link:https://github.com/dojoengine/dojo[Dojo Engine on GitHub]
* Documentation: link:https://book.dojoengine.org/toolchain/katana[Katana Docs]
