[id="starknet_development_tools"]
= Starknet devtools reference

Cairo is a turing complete language for writing provable programs. It is also the language used for writing smart contracts for Starknet. Starknet uses a different model than the Ethereum Virtual Machine (EVM), and as such, requires specialized tools for development.

This list of tools is dynamic and is being updated as more tools are added. If a tool you are using is missing, please consider editing this page and creating a Pull Request.

[#interacting-with-starknet]
== Interacting with Starknet

[#starkli]
=== Starkli

https://github.com/xJonathanLEI/starkli/[Starkli^], developed by https://x.com/xjonathanlei[Jonathan Lei^], is a fast command-line interface for interacting with Starknet. It supports fetching data from the Starknet network, deploying accounts, interacting with contracts, and other useful utilities for developers. 

[#sncast]
=== sncast
Part of the Starknet Foundry suite, https://foundry-rs.github.io/starknet-foundry/starknet/sncast-overview.html[`sncast`^] is a command line interface for interacting with Starknet, which includes deep integration with Starknet Foundry projects.

[#sdks]
=== Starknet SDKs

A Software Development Kit (SDK) is a library that abstracts the complexities of Starknet when building transactions and interacting with the blockchain. SDKs implement the Starknet https://github.com/starkware-libs/starknet-specs[JSON RPC specification^], and are updated to support the latest API changes. There are SDKs for various languages, so you can choose the SDK according to your needs.

[#entro]
=== Entro

https://github.com/NethermindEth/entro[Entro^] helps decoding and analyzing Starknet transactions and events, including decoding contract ABI and transaction data and getting contract class history, 


[cols=",,,,,",]
|===
| SDK name | Maintainer | Code | Package | Docs | Support  

| Starknet.js
| https://x.com/0xSpaceShard[SpaceShard^]
| https://github.com/starknet-io/starknet.js[starknet.js on GitHub^]
| https://www.npmjs.com/package/starknet[starknet.js on NPM^]
| https://www.starknetjs.com/[starknet.js Book^]
| https://discord.gg/starknet-community[starknet.js channel on Starknet Discord^]
 
| Starknet.py
| https://x.com/swmansionxyz[Software Mansion^]
| https://github.com/software-mansion/starknet.py[starknet.py on GitHub^]
| https://pypi.org/project/starknet-py/[starknet.py on PyPi^]
| https://starknetpy.rtfd.io/[starknet.py Docs^]
| https://t.me/starknetpy[starknet.py on Telegram^]

| Starknet-rs
| https://x.com/xjonathanlei[Jonathan Lei^]
| https://github.com/xJonathanLEI/starknet-rs[starknet-rs on GitHub^]
| https://crates.io/crates/starknet[starknet-rs on Crates^]
| https://github.com/xJonathanLEI/starknet-rs[starknet-rs Docs^] | https://t.me/starknet_rs[starknet-rs on Telegram^]

| Starknet.go
| https://x.com/NethermindEth[Nethermind^]
| https://github.com/NethermindEth/starknet.go[starknet.go on GitHub^]
| 
| https://pkg.go.dev/github.com/NethermindEth/starknet.go[starknet.go Docs^]
| https://t.me/StarknetGo[starknet.go on Telegram^]

| starknet-jvm
| https://x.com/swmansionxyz[Software Mansion^]
| https://github.com/software-mansion/starknet-jvm[starknet-jvm on GitHub^]
| https://central.sonatype.com/artifact/com.swmansion.starknet/starknet[starknet-jvm on Maven]
| https://docs.swmansion.com/starknet-jvm/[starknet-jvm Docs^]
|

| starknet.swift
| https://x.com/swmansionxyz[Software Mansion]
| https://github.com/software-mansion/starknet.swift[starknet.swift on GitHub^]
|
| https://docs.swmansion.com/starknet.swift/documentation/starknet/[starknet.swift Docs^]
|

| starknet.dart
| https://x.com/focustree_app[Focustree^]
| https://github.com/focustree/starknet.dart[starknet.dart on GitHub^]
| https://pub.dev/packages/starknet[starknet.dart on Pub^]
| https://starknetdart.dev/[starknet.dart Docs^]
| https://t.me/+CWezjfLIRYc0MDY0[starknet.dart on Telegram^]
|===

== Building dApps

// [#dapp-frameworks]
// === dApp Frameworks

[#scaffold-stark]
=== Scaffold-Stark
https://scaffoldstark.com/[Scaffold-Stark^] is built using NextJS, Starknet.js, Scarb, Starknet-React, Starknet Foundry and Typescript, and designed to make it easier for developers to create, deploy and interact with smart contracts.

[#starknet-scaffold]
=== Starknet Scaffold
https://www.starknetscaffold.xyz/[Starknet-Scaffold^] is an open-source, up-to-date toolkit for building decentralized applications on Starknet, that help you move from prototyping to production-grade apps seamlessly.

// [#libs-for-dapps]
// === dApps Libraries

Decentralized applications are at the heart of Starknet. These libraries help developers build Dapps on Starknet and connect to prominent Starknet wallets.

[#starknet-react]
=== Starknet React
https://github.com/apibara/starknet-react[Starknet React^], developed by Apibara using starknet.js, is a wagmi-inspired collection of React hooks for Starknet.

[#get-starknet]
=== Get Starknet
https://github.com/starknet-io/get-starknet[Get Starknet^] is a Starknet wallet<>dApp connection bridge, that enables easy discovery and UI for Starknet wallets, including ArgentX, Braavos, Metamask Snaps, and OKx.

[#starknetkit]
=== Starknetkit
https://www.starknetkit.com/[Starknetkit] is a Starknet wallet connection kit, built by Argent using Starknet.js and starknet-react.

[#devnets]
== Developing locally

// A Starknet devnet is a local Starknet node implementations, aimed for testing and development. A devnet behaves just like a real Starknet node, but everything is executed locally. This enables much faster and more private development of Starknet applications.


[#starknet-devnet-rs]
=== Starknet Devnet RS

https://github.com/0xSpaceShard/starknet-devnet-rs[Starknet Devnet RS
^], developed by SpaceShard, is a Rust implementation of a local Starknet node that includes many featured tailored for testing and development, which are not present on testnet or mainnet,including
* Pre-deployed and pre-funded accounts
* Forking the chain at a specific block.
* Dumping current state (and loading in future runs)
* Impersonating account
* Mock L1<>L2 communication

[#starknet-devnet-js]
=== Starknet Devnet JS
https://github.com/0xSpaceShard/starknet-devnet-js[Starknet Devnet JS^] is a JavaScript package that abstracts the Starknet Devnet API, making it easier to interact with it and write end-to-end tests for L1<>L2 communications.

[#katana]
=== Katana

https://book.dojoengine.org/toolchain/katana[Katana], developed by https://cartridge.gg/[Cartridge^], is an extremely fast devnet designed to support local development with the https://github.com/dojoengine/dojo[Dojo Starknet gaming engine] but can be used as a general purpose devnet as well.

== Writing smart contracts

[#scarb]
=== Scarb

https://github.com/software-mansion/scarb[Scarb^] much more than a package manager for Cairo: It is the easiest and most recommended way to build and maintain Cairo code. Developed by Software Mansion and inspired by Cargo for Rust, Scarb includes
* Initiating a new Cairo project.
* Compiling Cairo projects.
* Adding and removing Cairo dependencies.
* Generating Cairo documentation.
* Fetching and uploading packages link:https://scarbs.xyz/[Scarbs.xyz], the Cairo Registry.
* Integration with the Cairo Language Server
* It integrates with other tools in the Cairo ecosystem, such as Starknet Foundry and the Dojo gaming engine.

[#starknet_foundry]
== Starknet Foundry

Starknet Foundry is the go-to toolchain for developing Starknet smart contracts. Similarly to its EVM counterpart, Starknet Foundry supports a plethora of features focused on testing Cairo smart contracts for Starknet, including

* Setting caller address
* Manipulating the timestamp and block number
* Forking the chain at a specific block and testing with that state
* Fuzz testing
* Getting accurate gas and resource reports
* Profiling

Starknet Cast is a command line tool for interacting with the Starknet network, with deep integration with Starknet Foundry projects.
With `sncast` it is possible to:

* Declare and deploy contracts
* Read from Starknet contracts
* Deploy accounts
* Interact with contracts

[discrete]
=== Relevant links
* GitHub: link:https://github.com/foundry-rs/starknet-foundry[starknet-foundry on GitHub]
* Documentation: link:https://foundry-rs.github.io/starknet-foundry/[starknet-foundry Docs]
* Support: link:https://t.me/starknet_foundry_support[Starknet Foundry Support on Telegram]


[#starknet_remix_plugin]
== The Starknet Remix plugin

Remix is a browser-based integrated development environment (IDE) for Ethereum that you can use for learning, experimenting and finding vulnerabilities in smart contracts, without installing anything. The Starknet Remix plugin lets you use Remix for testing Starknet smart contracts, so you can focus on learning Cairo and Starknet in the comfort of your browser.

Remix and the Starknet Remix plugin include the following features:

* Integrated compiling.
* You can deploy contracts to testnet, mainnet and the plugin’s own integrated devnet.
* You can call functions of contracts that you have already deployed, to facilitate testing and interaction.
* The Starknet Remix Plugin is integrated with link:https://starknet-by-example.voyager.online/[Starknet By Example], a rich repository of practical learning content.

[discrete]
=== Relevant links
Remix Project: link:https://remix-project.org[Remix Project site].

* Blogpost: link:https://medium.com/nethermind-eth/unlocking-onboarding-to-starknet-an-overview-of-the-starknet-remix-plugin-6b0658e73521[Unlocking Onboarding to Starknet: An Overview of the Starknet Remix Plugin].
* GitHub link:https://github.com/NethermindEth/starknet-remix-plugin[Starknet Remix on GitHub].

