[id="starknet_development_tools"]
= Starknet devtools reference

Cairo is a turing complete language for writing provable programs. It is also the language used for writing smart contracts for Starknet. Starknet uses a different model than the Ethereum Virtual Machine (EVM), and as such, requires specialized developer tools (devtools).

The following list of devtools is dynamic and continously updated. If a tool you are using is missing, please consider openning an issue or editing the page by yourself.

== Coding in Cairo

The following tools the recommended tools for writing Cairo in general, but can also be helpful for developing on Starknet.

[#vs_code_cairo_extension]
=== VS Code Cairo extension

https://marketplace.visualstudio.com/items?itemName=starkware.cairo1[VS Code Cairo extension^] is an extension for the Microsoft Visual Studio (VS) Code IDE that provides assistance when writing Cairo smart contracts, including live diagnostic highlighting for compile errors, quick fixes with suggestions, code formatting and completion, and more. It integrates with Scarb, and works best when Scarb is installed via `asdf`.

[#usc]
=== Universal-Sierra-Compiler
https://github.com/software-mansion/universal-sierra-compiler[Universal-Sierra-Compiler^] is a utility tool for compiling single Sierra files (unlike Scarb, which compiles full projects) from any Sierra version into CASM.

[NOTE]
====
Universal-Sierra-Compiler comes bundled with Starknet Foundry and does not need to be installed separately if Starknet Foundry is installed.
====

[#cairo-profiler]
=== cairo-profiler
https://github.com/software-mansion/cairo-profiler[cairo-profiler^] is a utility tool that can be used to create profiles of Cairo executions from execution traces, which can be analyzed and used to show flame graphs and other useful information.

[NOTE]
====
cairo-profiler comes bundled with Starknet Foundry and does not need to be installed separately if Starknet Foundry is installed.
====

[#cairo-playground]
=== Cairo Playground

https://www.cairo-lang.org/cairovm/[Cairo Playground^] an online tool that can be used to both experiment with Cairo without deploying a smart contract on Starknet, as well as dive deep into the Cairo virtual machine.

[#sierra-analyzer] 
=== Sierra Analyzer

https://github.com/FuzzingLabs/sierra-analyzer[Sierra Analyzer^], developed by https://x.com/fuzzinglabs[FuzzingLabs^] is a security toolkit for analyzing Sierra files, including decompiling a Sierra file, printing the contract's control flow graph, and running static analysis detectors.

== Writing smart contracts

The following tools are the recommended tools for developing Starknet smart contracts, covering compilation, package management, testing, and deployment.

[#scarb]
=== Scarb

https://github.com/software-mansion/scarb[Scarb^] is much more than a package manager for Cairo: It is the easiest and most recommended way to build and maintain Cairo code. Developed by Software Mansion and inspired by Cargo for Rust, Scarb includes:

* Initiating a new Cairo project.
* Compiling Cairo projects.
* Adding and removing Cairo dependencies.
* Generating Cairo documentation.
* Fetching and uploading packages link:https://scarbs.xyz/[Scarbs.xyz], the Cairo Registry.
* Integrating with the Cairo language server, as well as other tools in the Cairo ecosystem, such as Starknet Foundry and the Dojo gaming engine.

[#starknet_foundry]
=== Starknet Foundry

https://github.com/foundry-rs/starknet-foundry[Starknet Foundry^] is the go-to toolchain for developing Starknet smart contracts, which includes:

* `snforge`, a command line interface that enables using of various "cheatcodes" for testing various aspects of the contracts, such as setting caller address, manipulating the timestamp and block number, forking the chain at a specific block, getting accurate gas and resource reports, profiling and more.

* `sncast`, a command line interface with Starknet Foundry projects that enable to interact with Starknet with deep integration, including declaring, deploying, and interacting with contracts, deploying accounts, and more.

[#starknet_remix_plugin]
=== Starknet Remix plugin

https://remix-project.org[Remix^] is a browser-based integrated development environment (IDE) for Ethereum that you can use for learning, experimenting and finding vulnerabilities in smart contracts, without installing anything. https://github.com/NethermindEth/starknet-remix-plugin[Starknet Remix plugin^] lets you use Remix for testing Starknet smart contracts, so you can focus on learning Cairo and Starknet in the comfort of your browser. The plugin is also integrated with https://starknet-by-example.voyager.online/[Starknet By Example^], a rich repository of practical learning content.

[#open-zeppelin-contract-wizard]
=== Open Zeppelin Contract Wizard

https://wizard.openzeppelin.com/cairo[Open Zeppelin Contract Wizard^] is a tool that helps you create smart contracts with Open Zeppelin libraries by easily toggling on and off features for popular smart contract patterns.

== Building dApps

The following tools are the recommended tools for building the heart of Starknet – decentralized applications (dApps).

[#scaffold-stark]
=== Scaffold-Stark
https://scaffoldstark.com/[Scaffold-Stark^] is built using NextJS, Starknet.js, Scarb, Starknet-React, Starknet Foundry and Typescript, and designed to make it easier for developers to create, deploy and interact with smart contracts.

[#starknet-scaffold]
=== Starknet Scaffold
https://www.starknetscaffold.xyz/[Starknet-Scaffold^] is an open-source, up-to-date toolkit for building decentralized applications on Starknet, that help you move from prototyping to production-grade apps seamlessly.

// [#libs-for-dapps]
// === dApps Libraries

Decentralized applications are at the heart of Starknet. These libraries help developers build Dapps on Starknet and connect to prominent Starknet wallets.

[#starknet-react]
=== Starknet React
https://github.com/apibara/starknet-react[Starknet React^], developed by Apibara using starknet.js, is a wagmi-inspired collection of React hooks for Starknet.

[#get-starknet]
=== Get Starknet
https://github.com/starknet-io/get-starknet[Get Starknet^] is a Starknet wallet<>dApp connection bridge, that enables easy discovery and UI for Starknet wallets, including ArgentX, Braavos, Metamask Snaps, and OKx.

[#starknetkit]
=== Starknetkit
https://www.starknetkit.com/[Starknetkit] is a Starknet wallet connection kit, built by Argent using Starknet.js and starknet-react.

[#interacting-with-starknet]
== Interacting with Starknet

The following tools are the recommended tools for interacting with Starknet, including fetching and analyzing the network's data, declaring, deploying and interacting with smart contracts, generating RPC queries, and more.

[#starkli]
=== Starkli

https://github.com/xJonathanLEI/starkli/[Starkli^], developed by https://x.com/xjonathanlei[Jonathan Lei^], is a fast command-line interface for interacting with Starknet. It supports fetching data from the Starknet network, deploying accounts, interacting with contracts, and other useful utilities for developers. 

[#sncast]
=== sncast
Part of the Starknet Foundry suite, https://foundry-rs.github.io/starknet-foundry/starknet/sncast-overview.html[`sncast`^] is a command line interface for interacting with Starknet, which includes deep integration with Starknet Foundry projects.

[#sdks]
=== Starknet SDKs

A Software Development Kit (SDK) is a library that abstracts the complexities of Starknet when building transactions and interacting with the blockchain. SDKs implement the Starknet https://github.com/starkware-libs/starknet-specs[JSON RPC specification^], and are updated to support the latest API changes. There are SDKs for various languages, so you can choose the SDK according to your needs.


[cols=",,,,,",]
|===
| SDK name | Maintainer | Code | Package | Docs | Support  

| Starknet.js
| https://x.com/0xSpaceShard[SpaceShard^]
| https://github.com/starknet-io/starknet.js[starknet.js on GitHub^]
| https://www.npmjs.com/package/starknet[starknet.js on NPM^]
| https://www.starknetjs.com/[starknet.js Book^]
| https://discord.gg/starknet-community[starknet.js channel on Starknet Discord^]
 
| Starknet.py
| https://x.com/swmansionxyz[Software Mansion^]
| https://github.com/software-mansion/starknet.py[starknet.py on GitHub^]
| https://pypi.org/project/starknet-py/[starknet.py on PyPi^]
| https://starknetpy.rtfd.io/[starknet.py Docs^]
| https://t.me/starknetpy[starknet.py on Telegram^]

| Starknet-rs
| https://x.com/xjonathanlei[Jonathan Lei^]
| https://github.com/xJonathanLEI/starknet-rs[starknet-rs on GitHub^]
| https://crates.io/crates/starknet[starknet-rs on Crates^]
| https://github.com/xJonathanLEI/starknet-rs[starknet-rs Docs^] | https://t.me/starknet_rs[starknet-rs on Telegram^]

| Starknet.go
| https://x.com/NethermindEth[Nethermind^]
| https://github.com/NethermindEth/starknet.go[starknet.go on GitHub^]
| 
| https://pkg.go.dev/github.com/NethermindEth/starknet.go[starknet.go Docs^]
| https://t.me/StarknetGo[starknet.go on Telegram^]

| starknet-jvm
| https://x.com/swmansionxyz[Software Mansion^]
| https://github.com/software-mansion/starknet-jvm[starknet-jvm on GitHub^]
| https://central.sonatype.com/artifact/com.swmansion.starknet/starknet[starknet-jvm on Maven]
| https://docs.swmansion.com/starknet-jvm/[starknet-jvm Docs^]
|

| starknet.swift
| https://x.com/swmansionxyz[Software Mansion]
| https://github.com/software-mansion/starknet.swift[starknet.swift on GitHub^]
|
| https://docs.swmansion.com/starknet.swift/documentation/starknet/[starknet.swift Docs^]
|

| starknet.dart
| https://x.com/focustree_app[Focustree^]
| https://github.com/focustree/starknet.dart[starknet.dart on GitHub^]
| https://pub.dev/packages/starknet[starknet.dart on Pub^]
| https://starknetdart.dev/[starknet.dart Docs^]
| https://t.me/+CWezjfLIRYc0MDY0[starknet.dart on Telegram^]
|===

[#entro]
=== Entro

https://github.com/NethermindEth/entro[Entro^] helps decoding and analyzing Starknet transactions and events, including decoding contract ABI and transaction data and getting contract class history, 

[#rpc-request-builder]
=== Starknet RPC Request Builder
https://rpc-request-builder.voyager.online/[Starknet RPC Request Builder^] is a useful tool for generating RPC queries for Starknet, with support for basic example for JavaScript, Go, and Rust.

[#devnets]
== Running a development network

The following tools are the recommened tools for running a local Starknet development network (devnet), enabling faster and more private development process.

[#starknet-devnet-rs]
=== Starknet Devnet RS

https://github.com/0xSpaceShard/starknet-devnet-rs[Starknet Devnet RS
^], developed by SpaceShard, is a Rust implementation of a local Starknet node that includes many featured tailored for testing and development, which are not present on testnet or mainnet,including
* Pre-deployed and pre-funded accounts
* Forking the chain at a specific block.
* Dumping current state (and loading in future runs)
* Impersonating account
* Mock L1<>L2 communication

[#starknet-devnet-js]
=== Starknet Devnet JS
https://github.com/0xSpaceShard/starknet-devnet-js[Starknet Devnet JS^] is a JavaScript package that abstracts the Starknet Devnet API, making it easier to interact with it and write end-to-end tests for L1<>L2 communications.

[#katana]
=== Katana

https://book.dojoengine.org/toolchain/katana[Katana], developed by https://cartridge.gg/[Cartridge^], is an extremely fast devnet designed to support local development with the https://github.com/dojoengine/dojo[Dojo Starknet gaming engine] but can be used as a general purpose devnet as well.

