= Devtools for running a local Starknet devnet

[#starknet-devnet-rs]
== Starknet Devnet RS

https://github.com/0xSpaceShard/starknet-devnet-rs[Starknet Devnet RS
^], developed by SpaceShard, is a Rust implementation of a local Starknet node that includes many featured tailored for testing and development, which are not present on testnet or mainnet,including
* Pre-deployed and pre-funded accounts
* Forking the chain at a specific block.
* Dumping current state (and loading in future runs)
* Impersonating account
* Mock L1<>L2 communication

[#starknet-devnet-js]
== Starknet Devnet JS
https://github.com/0xSpaceShard/starknet-devnet-js[Starknet Devnet JS^] is a JavaScript package that abstracts the Starknet Devnet API, making it easier to interact with it and write end-to-end tests for L1<>L2 communications.

[#katana]
== Katana

https://book.dojoengine.org/toolchain/katana[Katana], developed by https://cartridge.gg/[Cartridge^], is an extremely fast devnet designed to support local development with the https://github.com/dojoengine/dojo[Dojo Starknet gaming engine] but can be used as a general purpose devnet as well.

