[#Contract-Development]
= Smart Contract Development

The following tools are the recommended tools for developing Starknet smart contracts. These cover compilation, package management, testing and deployment.



[#scarb]
== Scarb: The Cairo package manager

Scarb is a package manager for Cairo, but it is much more than that. It is the easiest and recommended way to build and maintain Cairo code. Think Cargo for Rust.
Scarb is developed by Software Mansion.

Scarb includes the following features:

* Initiating a new Cairo project.
* Compiling Cairo projects.
* Adding and removing Cairo dependencies.
* Generating Cairo documentation.
* Fetching and uploading packages link:https://scarbs.xyz/[Scarbs.xyz], the Cairo Registry.
* Integration with the Cairo Language Server
* It integrates with other tools in the Cairo ecosystem, such as Starknet Foundry and the Dojo gaming engine.

[discrete]
=== Relevant links
* GitHub: link:https://github.com/software-mansion/scarb[Scarb on GitHub]
* Documentation: link:https://docs.swmansion.com/scarb/[Scarb Docs]
* Support: link:https://t.me/+1pMLtrNj5NthZWJk[Scarb on Telegram]
* Cairo Registry: link:https://scarbs.xyz/[scarbs.xyz]


[#starknet_foundry]
== Starknet Foundry

Starknet Foundry is the go-to toolchain for developing Starknet smart contracts. Similarly to its EVM counterpart, Starknet Foundry supports a plethora of features focused on testing Cairo smart contracts for Starknet.

Starknet Forge, and `snforge_std` allow the use of "cheatcodes" to test various aspects of the contracts.

For example:

* Setting caller address
* Manipulating the timestamp and block number
* Forking the chain at a specific block and testing with that state
* Fuzz testing
* Getting accurate gas and resource reports
* Profiling

Starknet Cast is a command line tool for interacting with the Starknet network, with deep integration with Starknet Foundry projects.
With `sncast` it is possible to:

* Declare and deploy contracts
* Read from Starknet contracts
* Deploy accounts
* Interact with contracts

[discrete]
=== Relevant links
* GitHub: link:https://github.com/foundry-rs/starknet-foundry[starknet-foundry on GitHub]
* Documentation: link:https://foundry-rs.github.io/starknet-foundry/[starknet-foundry Docs]
* Support: link:https://t.me/starknet_foundry_support[Starknet Foundry Support on Telegram]


[#starknet_remix_plugin]
== The Starknet Remix plugin

Remix is a browser-based integrated development environment (IDE) for Ethereum that you can use for learning, experimenting and finding vulnerabilities in smart contracts, without installing anything. The Starknet Remix plugin lets you use Remix for testing Starknet smart contracts, so you can focus on learning Cairo and Starknet in the comfort of your browser.

Remix and the Starknet Remix plugin include the following features:

* Integrated compiling.
* You can deploy contracts to testnet, mainnet and the plugin’s own integrated devnet.
* You can call functions of contracts that you have already deployed, to facilitate testing and interaction.
* The Starknet Remix Plugin is integrated with link:https://starknet-by-example.voyager.online/[Starknet By Example], a rich repository of practical learning content.

[discrete]
=== Relevant links
Remix Project: link:https://remix-project.org[Remix Project site].

* Blogpost: link:https://medium.com/nethermind-eth/unlocking-onboarding-to-starknet-an-overview-of-the-starknet-remix-plugin-6b0658e73521[Unlocking Onboarding to Starknet: An Overview of the Starknet Remix Plugin].
* GitHub link:https://github.com/NethermindEth/starknet-remix-plugin[Starknet Remix on GitHub].
