[#utilities]
= Utilities

While not under any specific category, these tools can be helpful in various stages of development.

[#usc]
== Universal Sierra Compiler
While Scarb compiles full projects, and produces both Sierra and CASM files, it is often needed to only compile a single Sierra file to CASM (for example, when getting a class from Starknet mainnet). The Universal Sierra Compiler supports all sierra versions, and can compile the the a CASM file.

[NOTE]
====
The USC comes bundled with Starknet Foundry and does not need to be installed separately if Starknet Foundry is installed.
====

[discrete]
=== Relevant links

* link:https://github.com/software-mansion/universal-sierra-compiler[Universal Sierra Compiler on GitHub]


[#rpc-request-builder]
== RPC Request Builder
The Starknet RPC Request Builder is a useful tool to generate RPC queries for Starknet, with support for basic example for JavaScript, Go and Rust.

[discrete]
=== Relevant links

* link:https://rpc-request-builder.voyager.online/[RPC Request Builder]

[#open-zeppelin-contract-wizard]
== Open Zeppelin Contract Wizard

The Open Zeppelin Contract Wizard is a tool that helps you create smart contracts with Open Zeppelin libraries. Easily toggle on and off features for popular smart contract patterns, and the wizard will generate the code for you.

[discrete]
=== Relevant links

* link:https://wizard.openzeppelin.com/cairo[Open Zeppelin Contract Wizard]

[#cairo-profiler]
== Cairo Profiler
Cairo-profiler can be used to create profiles of Cairo executions from execution traces.
These can be analyzed and displayed to show Flame Graphs, and other useful information.

[NOTE]
====
Cairo-profiler is currently integrated into Starknet Foundry, but can be used as a standalone tool.
====

[discrete]
=== Relevant links

* link:https://github.com/software-mansion/cairo-profiler[Cairo Profiler on GitHub]

[#cairo-playground]
== Cairo Playground

If want to dive deep into the Cairo VM, and experiment writing Cairo online, and don't want to deploy a smart contract on Starknet, the Cairo Playground is a great way to do so.

[discrete]
=== Relevant links

* link:https://www.cairo-lang.org/cairovm/[Cairo Playground]


[#starknet-devnet-js]
== Starknet Devnet JS
A JavaScript package, abstracting the Starknet Devnet API, making it easier to interact with starknet-devnet-rs.
This simplifies writing end-to-end tests using Devnet, including tests for L1<>L2 communications.

Notable features:

* Spawn a new Devnet instance without installing it
* Wrapping RPC calls to Devnet
* Abstracting complex L1<>L2 communication setup with a local L1 node (e.g. Anvil)

[discrete]
=== Relevant links

* link:https://github.com/0xSpaceShard/starknet-devnet-js[starknet-devnet-js on GitHub]

[#starknet-types-converter]
== Starknet Types Converter
Tool to convert different Starknet types.

[discrete]
=== Relevant links

* link:https://www.stark-utils.xyz/converter[Starknet Types Converter]
