name: Upload Data to Algolia Index

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.0.0'
  push:
    branches:
      - dev
jobs:
  upload_data:
    runs-on: ubuntu-latest
    steps:
      - run: |
          VERSION=${{ github.event.inputs.version }}
          echo ::set-output name=build_args::VERSION=${VERSION}
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Node.js 16.15.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.x'   
      - name: Upload data to Algolia Index
        working-directory: ./js # equivalent of 'cd js'
        run: |
          yarn install
          node algolia-index.js
