name: PR workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install lunr
      run: npm i antora-lunr
      
    - name: "Generate site using antora site action"
      uses: kameshsampath/antora-site-action@master
      with:
       antora_playbook: playbook.yml

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.USER_TOKEN }}
        publish_dir: build/pr-${{ github.ref }}
