name: Pull request workflow

on:
  pull_request:
    branches:
      - '*'

#  push:
#    branches:
#      - main

#permissions:
#  contents: write


jobs:

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master

  test-deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: 16

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install node_modules
        run: yarn

      - name: Generate Site
        run: yarn generate

      - name: "Upload generated content"
        uses: actions/upload-artifact@v2
        with:
          name: starknet-site
          if-no-files-found: error
          path:
            public_html

  publish:
    name: deploy-review
    runs-on: ubuntu-latest
    needs:
      - test-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: 16
          ref: gh-pages
          #USER_TOKEN: ${{ secrets.USER_TOKEN }}

      - name: Extract PR details
        id: pr
        run: |
          PR_ID=pr-${{ github.event.pull_request.number }}
          PREVIEW_PATH=previews/${PR_ID}
          echo "::set-output name=PR_ID::${PR_ID}"

      - name: "Remove preview build directory"
        run: rm -rf ${{ steps.pr.outputs.PR_ID }}
      - name: "Create preview build directory"
        run: mkdir -p ${{ steps.pr.outputs.PR_ID }}
      - name: "Download generated content"
        uses: actions/download-artifact@v2
        with:
          name: starknet-site
          path: ${{ steps.pr.outputs.PR_ID }}

      - name: PR preview details
        run:
          echo "you can preview the PR at https://starknet-io.github.io/starknet-docs/${{ steps.pr.outputs.PR_ID }}/documentation/"

      - name: "Commit changes"
        run: |
          set -euo pipefail

          # Debug information
          echo "Current directory: $(pwd)"
          echo "Contents of the repository:"
          ls -al
          echo "Git status:"
          git status
          git config -l
          
          git add .
          
          
          if ! git diff-index --quiet HEAD --; then
            # Debug information
            echo "Changes detected. Committing and pushing changes."

            commit_message="Adding or updating preview build for PR ${{ steps.pr.outputs.PR_ID }}"
          
            # Debug message
            echo "Commit message: $commit_message"
          
            # Commit changes
            git commit -m "$commit_message"
          
            # Check if commit was successful
            if [ $? -eq 0 ]; then
              # Debug information
              echo "Commit successful. Pushing changes."
          
              # Push changes
              git push --set-upstream origin gh-pages
          
              # Check if push was successful
              if [ $? -eq 0 ]; then
                # Debug information
                echo "Push successful."
              else
                # Debug information
                echo "Error: Push failed."
              fi
            else
              # Debug information
              echo "Error: Commit failed."
            fi
          else
            # Debug information
            echo "No changes found."
          fi
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Send comment to PR"
        continue-on-error: true
        run: |
          set -euo pipefail
          echo "Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-io.github.io/starknet-docs/${{ steps.pr.outputs.PR_ID }}/documentation/ ." >/tmp/comment
          gh pr comment ${{ github.event.pull_request.number }} -F /tmp/comment
        env:
          # USER_TOKEN: "${{ secrets.USER_TOKEN }}"
          GH_TOKEN: "${{ github.token }}"
